### ISSUE TITLE
Keybinding Conflict 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Direwolf20-MC/BuildingGadgets#1]
The keybinding for Mode Swith is set to F, vanilla Minecraft already uses that keybinding for swamping items to your off hand. So when you press F instead of it chaining modes it  just swaps the items hand

Minecraft Version: 1.12
Mod Version: 1.1.2
Forge Version: 14.23.4.2725

Ps. Starting these bug reports out right

**Comment by Direwolf20-MC** [comment]
Fixed :).  https://github.com/Direwolf20-MC/BuildingGadgets/commit/e67bf9e14853819534e19569292aa80cc6ee062a

**Comment by UnRealDinnerbone** [comment]
Just a reminder to update the curseforge page to say that the default hotkey is G not F
