### ISSUE TITLE
Feature Request: Copy/paste Construction Paste Improvement

### ISSUE THREAD

**Issue by neclimdul** [Direwolf20-MC/BuildingGadgets#100]
Watching your spotlight I was initially confused by the missing block UI for the Copy-Paste Gadget when placing using Construction Paste. Your explanation made it clear but the UI itself was confusing as the red numbers look like you're missing resources (same as when you don't have paste) when it can perform the "paste."

My suggestion would be to make the numbers Yellow as a "warning" that these blocks are missing but can be pasted and they will use the construction paste as a replacement for the actual block. That way at a glance its much clearer you can actually paste but maybe not the blocks you want.

**Comment by Direwolf20-MC** [comment]
Hrm, I like the idea, but due to the nature of the way it calculates that might be tricky. Let me see what I can do :).

**Comment by Direwolf20-MC** [comment]
I've gone ahead and decided not to do this.  Its a little tricky to figure out which blocks get pasted and which don't when you don't have enough paste
