### ISSUE TITLE
Feature Request: Template Manager

### ISSUE THREAD

**Issue by GGearZZ** [Direwolf20-MC/BuildingGadgets#101]
Good Day! Just caught your updated spotlight. Tis truly awesome sir :) A feature request. Could you make it to where the template manager can read adjacent inventories, complete with a UI (like a tinker's workbench), for storing/swapping out templates and paper without having to hop UI's. Regarding the "Copy to clipboard" function. A confirmation message appearing in chat would be useful. Thank you for the great mod and your time.

**Comment by Direwolf20-MC** [comment]
I don't think I want to add an adjacent inventory hook, but I did add messages to the player when the copy/paste are successful. Thanks! :)

https://github.com/Direwolf20-MC/BuildingGadgets/commit/aa806a9fbf6e9fa41ec68132ad98e6006c3be124

**Comment by GGearZZ** [comment]
Hello. Apologies for the late reply and thank you for your considerations. Just curious. would the block itself having a retainable inventory be a possibility?

**Comment by MajorTuvok** [comment]
Why should it need one?
