### ISSUE TITLE
Building Gadget's "Vertical Column" mode "attempts" to build below bedrock and consumes items.

### ISSUE THREAD

**Issue by Tkap1** [Direwolf20-MC/BuildingGadgets#102]
How to replicate: 
- Place a block one level above bedrock
- Set the range to the max
- Target the block you just placed and use it

It will consume the items but not place anything. You can repeat this as much as you want and it will keep consuming them.

Version: 2.3.5

**Comment by Direwolf20-MC** [comment]
This has been resolved, thanks! :)
