### ISSUE TITLE
Extreme Reactor blocks unable to be used

### ISSUE THREAD

**Issue by Jdreioe** [Direwolf20-MC/BuildingGadgets#104]
I found a bug, Extreme Reactor's blocks are unable to be used with any of Building Gadgets gadgets. My blacklist config:
![image](https://user-images.githubusercontent.com/43964170/46618522-00f13580-cb20-11e8-9cc8-8b44624735eb.png)
It's all ER blocks:

![image](https://user-images.githubusercontent.com/43964170/46625630-0311bf00-cb35-11e8-8f51-ff2500eaeffb.png)

![image](https://user-images.githubusercontent.com/43964170/46625710-4d933b80-cb35-11e8-911c-c51f27fce078.png)

I'm using the latest Building Gadgets and the Exteme Reactor mod version found in StoneBlock.

Is this a known issue?

**Comment by Phylogeny** [comment]
This is not a bug. Those blocks have tile entities, and are thus invalid. When it says "invalid block", it really is invalid.

**Comment by Jdreioe** [comment]
> This is not a bug. Those blocks have tile entities, and are thus invalid. When it says "invalid block", it really is invalid.

Oh. Didn't know that ER had tile entities. Thanks

**Comment by Direwolf20-MC** [comment]
Yup tile entities sorry! :)
