### ISSUE TITLE
[Feature request] Auto conversion for chisel types.

### ISSUE THREAD

**Issue by Electrofried** [Direwolf20-MC/BuildingGadgets#109]
The building gadgets are fantastic, but when building with different chiseled types of materials, swapping types can be frustrating.  It would be great if building gadgets had some sort of chisel support whereby if you had a chiseled block selected and the base block (or another chiseled type of the same block) in your inventory it auto converted to the type selected by the gadget.

**Comment by MajorTuvok** [comment]
Problem is, that this would bypass normal usage of the chisel, as you would no longer use up it's durability. 
Though in case of a chisel this is not much of a loss - cause of the used materials one has practically endless chisels...

**Comment by Electrofried** [comment]
That was my thinking, there could be an option for a chisel to be in the inventory and have it lose durability, or even increased energy cost when converting chiseled blocks, it just seems like a really cool feature to have though, and one none of the other building tools really offer.

**Comment by drunkripper** [comment]
Theoretically, it wouldn't be hard to implement with chisel's api would it?

**Comment by Direwolf20-MC** [comment]
Decided against implementing this :)
