### ISSUE TITLE
[Bug] Off Hand Usage 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Direwolf20-MC/BuildingGadgets#11]
Off Hand usage of the gadgets does not work at all. It does not render the blocks it supposed to be able to place. After looking at the code you call getHeldItemMainhand() so everything assumes that your using the main hand. This also causes a bug where the building gadget disappears when right clicked on air. I Suggest to fix this is to first check the main hand for a gadget, and if there is not one there check the off hand

[Video](http://ss.unrealdinnerbone.x10.bz/2018-07-15_14-45-30.mp4)

**Comment by Direwolf20-MC** [comment]
Fixed, thank you!
https://github.com/Direwolf20-MC/BuildingGadgets/commit/594504cd1c9e91fa505f5b8e5bd26d5ac2703ae1
