### ISSUE TITLE
[Feature Request] ArchitectureCraft support?

### ISSUE THREAD

**Issue by NerdimusPrime** [Direwolf20-MC/BuildingGadgets#110]
When trying to select blocks made using the ArchitectureCraft sawmill, I get the "invalid block type" message, and I'm curious as to why. Are they tile entities (although that seems unlikely)? Is it because of their non-standard shapes, or how they can be rotated? Is it something you could, or would, add support for?

Thanks!

**Comment by Phylogeny** [comment]
@NerdimusPrime Unlikely? The fact that the Sawbench from AC has a GUI with menu items that save their position should make it unsurprising that it has a TE. Most blocks with GUIs have TEs, so when you see one, you should realize that it is likely to have a TE -- not unlikely. And the additional fact that the Sawbench has an inventory guarantees that it has a TE.

Aside from being in the user-specified blacklist, the only thing that makes a block invalid is that it has a TE.

**Comment by NerdimusPrime** [comment]
OK, thanks for clearing that up. I thought it unlikely because AC blocks don't _do_ anything once you make and place them; they just sit there. Turns out I just had a fundamental misunderstanding of what TEs actually are.

**Comment by Phylogeny** [comment]
A block's TE just stores additional data not stored in its state. In this case, [BlockSawbench](https://github.com/elytra/ArchitectureCraft/blob/1.12/src/main/java/com/elytradev/architecture/common/block/BlockSawbench.java) has [TileSawbench](https://github.com/elytra/ArchitectureCraft/blob/1.12/src/main/java/com/elytradev/architecture/common/tile/TileSawbench.java), which extends [TileArchitectureInventory](https://github.com/elytra/ArchitectureCraft/blob/1.12/src/main/java/com/elytradev/architecture/common/tile/TileArchitectureInventory.java). See those classes for the kind of extra data held.
