### ISSUE TITLE
[Bug 2.3.6] Build preview and actual build location out of sync when using Vivecraft

### ISSUE THREAD

**Issue by Alleluid** [Direwolf20-MC/BuildingGadgets#111]
Vivecraft is a mod that allows Minecraft to be played in VR. Almost every mod works fine and this is mostly just a visual bug, but it seems like the preview for where blocks will be placed is based on the look vector of the player's camera, whereas the actual blocks are built using the cross hair. In the vast majority of cases these are the same, but in VR you aim the cross hair with your hand.

I can get an image if you'd like, but the issue seems pretty straight forward.

**Comment by Direwolf20-MC** [comment]
Perhaps, but I have no idea how to fix that :(. Unless I convert a lot of the place block stuff to just use look vectors?

**Comment by Alleluid** [comment]
I don't know how the two are different internally, maybe you could change the preview to use the position of the cross hair instead of look vector? The look direction for rotation is fine, but the position is off.

It might be a lot of work, it's not a big deal if you don't want to put in the time for such a niche issue. I just wanted to report it so you're aware and just in case it's a simple fix.

**Comment by Direwolf20-MC** [comment]
I checked it out, and as far as I know i'm doing everything right. I also wouldn't be able to test a solution I come up with, so I think I'll close this for now unless someone else can chime in and let me know whats up:)
