### ISSUE TITLE
Copy and Pasting issue

### ISSUE THREAD

**Issue by creepers152** [Direwolf20-MC/BuildingGadgets#114]
Hey if anyone or Direwolf20 reads this i am having an issue with the copy and paste tool, when i go and copy one of my buildings its copies everything perfectly except for double slab blocks. I can easily change the blocks but i thought it would be a good idea to report the issue just in case.

Specifically i am trying to copy and paste a double slab block of dark oak wood plank and when pasting it places birch planks slabs instead.

**Comment by Direwolf20-MC** [comment]
This has been resolved, thanks :)

**Comment by creepers152** [comment]
your welcome
