### ISSUE TITLE
Request - Destruction tool be used only as admin

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Direwolf20-MC/BuildingGadgets#116]
I can see many griefing possibilities if this mod cannot be an admin only or creative menu only tool. Please make a setting that allows this to be uncraftable.

**Comment by Direwolf20-MC** [comment]
Sure I can do that.

**Comment by P3rf3ctXZer0** [comment]
Thank you <3

**Comment by Direwolf20-MC** [comment]
Implemented, and deployed in v2.4.1

https://github.com/Direwolf20-MC/BuildingGadgets/commit/f8ccc8ae2d81c69e8c9a5407f3a960e1109b2098
