### ISSUE TITLE
Incorrect Construction Powder Falling Animation

### ISSUE THREAD

**Issue by ConnorMiner** [Direwolf20-MC/BuildingGadgets#117]
Whenever Construction Powder falls, it appears to turn into Lime Glazed Terracotta until it lands.

Video: https://drive.google.com/file/d/1u_1sEbaq6F1acQTtv2wIrgx_-j3mUiOK/view?usp=sharing

**Comment by Direwolf20-MC** [comment]
I tested this in my dev instance and it seems fine to me. Perhaps its a mod conflict? I'm gonna close for now, as I don't *think* its on my end, but if someone knows better feel free to say as much!

https://youtu.be/xTTpaYhNKH8
