### ISSUE TITLE
[Feature Request] List of items to be removed by destruction planner

### ISSUE THREAD

**Issue by drunkripper** [Direwolf20-MC/BuildingGadgets#120]
Could it be possible to have a gui just show somewhere on screen showing the item model of the block and a number when hovering over a block with the destruction gadget? (Also maybe add a implementation to the if statement that says if the difference between x1 and x2 is over a certain number don't calculate it)

**Comment by Direwolf20-MC** [comment]
It’s possible yes, but it complicates the tool a bit. I’ll check into this but I’m not sure what the use case is? So you can see what blocks you’re voiding before you do? I guess this also lets you find diamonds though :).

**Comment by drunkripper** [comment]
that's true. i was just thinking so i can know if i'm about to wake out a wall of another room in my underground bases.

**Comment by Phylogeny** [comment]
If you're removing blocks in an area you know that this may be an issue in, just use a depth of 1, so you can see all the soon-to-be removed blocks.

**Comment by MichaelHillcox** [comment]
I had a play with this concept whilst working on cleaning the mod up... I found that there is no simple & effective way to achive this with some of the limitations with doing something every frame. 

I think I'll agree with @Direwolf20-MC and @Phylogeny that you can use the undo button if needed and you can set a less agressive range if you're working in a specifcally valuable area. Plus, it could totally be used for finding ores 😛 

I'd suggest closing this
