### ISSUE TITLE
Crash when using exchanger on XNet cables

### ISSUE THREAD

**Issue by MarkCW** [Direwolf20-MC/BuildingGadgets#121]
Was prettying up my base and accidentally replaced an XNet cable and game crashed.
Repeated 2 more times and crashed each time.

Crash Report: [https://pastebin.com/eifxJ2rf](https://pastebin.com/eifxJ2rf)

P.S. Great mod, don't know how I managed before without it.

**Comment by Direwolf20-MC** [comment]
I added a try/catch for this, and also in the builder/exchanger render, which you would have gotten if you were trying to build with those blocks.  Thanks for the report! :)
