### ISSUE TITLE
[Feature Request] Conduit Goggles

### ISSUE THREAD

**Issue by gameacid13** [Direwolf20-MC/BuildingGadgets#122]
This is a request for a new item, Conduit Goggles. Wearing or using the goggles will allow you to see any major mod's "wiring" or "conduits" through a semi-transparent xray or maybe the vanilla "glowing" effect. This will help with building massively. No more searching and making tunnels trying to find your fluxduct/liquiduct/ME Cable/etc underground or in a wall.

**Comment by Direwolf20-MC** [comment]
While this is a neat idea I don’t know that it fits in the concept of the mod.
