### ISSUE TITLE
[Probably Duplicate][Bug]Crash when holding building gadget

### ISSUE THREAD

**Issue by Flamebom** [Direwolf20-MC/BuildingGadgets#127]
https://pastebin.com/dJqDv2fi
Crash Report^
Pack: Direwolf20 2.3.0

**Comment by Direwolf20-MC** [comment]
Update the mod :) fixed in 2.0 and forward

**Comment by Flamebom** [comment]
Ha! I would if your 1.12 Direwolf20 pack was updated to 2.0 or higher. Can't manually do it because I'm playing on a server.
