### ISSUE TITLE
[Crash] Template manager

### ISSUE THREAD

**Issue by xt9** [Direwolf20-MC/BuildingGadgets#128]
Template manager crashes when trying to 'Load' from an empty template grabbed from JEI, now this is obviously something the end user shouldnt do (I didn't watch the v2 spotlight beforehand) but some extra validation could probably be in order. 

https://pastebin.com/0jVZESrv

Love the mod, really impressed by your work, about time we had a next level building mod :+1:

**Version:** 2.3.6
**Forge:** 14.23.5.2770

**Comment by Phylogeny** [comment]
This was fixed in v2.3.7 (3f488b00cfc15439022df78a4b513f736b290f27). The current version is v2.4.4.
