### ISSUE TITLE
[Feature Request] Option to change paste's reference point

### ISSUE THREAD

**Issue by ChaoticNonsense** [Direwolf20-MC/BuildingGadgets#132]
It would be nice to be able to change paste's reference point, relative to a copied structure. 

Example: I am in a skyblock map, and am using octagonal platforms. Naturally, I used the copy GUI to copy the structure, as it has no blocks in the corners. However, when trying to paste a platform, the paste function still uses the empty corner as its reference point of the copied structure, making it impossible to properly place the structure without building temporary pathways to the appropriate anchor point. 

From a user standpoint, the ideal behavior would allow you to choose the paste point while copying, and save that data to the blueprint. A less elegant but easier to code approach would be to add a gui to the paste mode that can move a pre-selected anchor.  As in:
1) Use hotkey to place anchor
2) Open gui to move anchor (relative/absolute options work well here)
3) paste structure.

EDIT: On reflection, the anchor moving solution would be much more versatile.

**Comment by Direwolf20-MC** [comment]
Oh yea, you know I was trying to think of a good way to do this, but I do like your idea for the GUI to move the anchor. The different start point is a challenge for sure.

**Comment by Direwolf20-MC** [comment]
Done :D
