### ISSUE TITLE
[Feature Request] Explicit Whitelist, or TE config option

### ISSUE THREAD

**Issue by Beannsss** [Direwolf20-MC/BuildingGadgets#133]
Hey, as you may know, there are many blocks that are useful for building, but are still "invalid" by building gadget's standard. A great example of this is painted cobblestone from Ender IO.  

Possible implementation could include a dangerous/experimental (with apt warning) config option to disable TE checking (unless it just throws an error without fail), or a config option for an explicit whitelist and something like 

if (WhitelistBlocks.checkWhitelist(state.getBlock())) {
            validBlock = true;
        }

in SelectBlock() in tools/GadgetUtils.java after the TE check.

Thank you so much for this awesome mod.

**Comment by Direwolf20-MC** [comment]
No Tile Entity support planned at this time. Even basic TE's break. Badly.

**Comment by Beannsss** [comment]
Gotcha, thanks for reaching out.
