### ISSUE TITLE
[Feature Request] Placing blocks which require other solid blocks

### ISSUE THREAD

**Issue by matix931** [Direwolf20-MC/BuildingGadgets#136]
Copy/Paste tool is placing blocks which require other blocks to be placed.
For example:
If you copy block with torch on it, then holding only torch you paste it somewhere not on the ground, the torch will pop up in the air.

I think, for blocks like torch we should check that there is required block to place it on.
Also it would be great if pasting could be "lazy loaded", not placing all blocks at once, but placing for example 10 blocks per tick or something.

Anyway great mod!

**Comment by Direwolf20-MC** [comment]
Thanks but that would be way too tricky to calculate based on the way the blocks are stored and placed.
