### ISSUE TITLE
Building gadgets - Destruction gadget Crashes the game if...

### ISSUE THREAD

**Issue by Bhaaltazar23** [Direwolf20-MC/BuildingGadgets#138]
When I deleted all the values in the gadget, no value in the coordinate boxes, I just pressed backspace, so there was no value not even 0 and than pressed OK to close the interface, game crashes. 

<It would be nice to add a button that sets all values to 0, for safety in case of accidentally clicking on the wrong block after finished excavation. I know about undo but dont know if you void something vital like machines and alike.>

Playing the latest version of Stoneblock 1.0.28

But otherwise awesome mod! Love it.

**Comment by MichaelHillcox** [comment]
Haha so it does, @Direwolf20-MC I've push a PR to address this as well as cleaning the code base up a bit 👍

**Comment by OnyxBerryBagel** [comment]
Just had this issue. Possible to make it where if field is "" that it sets it to "0"? to avoid crash?

**Comment by MichaelHillcox** [comment]
Hi @OnyxBerryBagel it has been addressed :) @Direwolf20-MC maybe mark this issue with a label `pending release` It'll be fixed soon 👍
