### ISSUE TITLE
Destruction gadget self destructed on "1" in numeric field.

### ISSUE THREAD

**Issue by 5trang30n3** [Direwolf20-MC/BuildingGadgets#140]
I'm playing Stoneblock 1.0.28.

After entering what appeared to be reasonable values for the destruction gadget the game crashed, because apparently there was an invisible character in an input field. Go figure.

Oldest QA trick in the book -- invalid input! Not that I was trying to test the mod... I've been too busy enjoying the pack.

[crash-2018-11-20_22.27.00-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/2603010/crash-2018-11-20_22.27.00-client.txt)

**Comment by MajorTuvok** [comment]
@Direwolf20 just add a try catch of NumberFormatException and display some kind of error message in DestructionGui#actionPerformed

**Comment by MichaelHillcox** [comment]
I've done some work to this already in a non PR'd branch over on my end. If @MajorTuvok wants to take a look at it and see it address this then I'll finish it up and get it PR'd https://github.com/MichaelHillcox/BuildingGadgets/blob/gui-cleanup/src/main/java/com/direwolf20/buildinggadgets/client/gui/DestructionGUI.java

**Comment by MichaelHillcox** [comment]
Effectively the Same bug as #138 or at least the same affecting methods.

**Comment by Direwolf20-MC** [comment]
Should be fixed, thanks @MichaelHillcox
