### ISSUE TITLE
[Feature Request] Center Placement for Copy/Paste?

### ISSUE THREAD

**Issue by HeavyDeception** [Direwolf20-MC/BuildingGadgets#142]
Would I be possible for the Copy/Paste tool to paste something from the middle block and to change it to paste one down, up, or forward? If is is possible now I'm sorry but I cant seem to get it to do so.

I have and image to help explain what i'm trying to say. [Click Here For Image](https://i.imgur.com/LyixW4q.png) Will not open new window.
Really its just there because I like doing them but its there. <a href="https://imgur.com/LyixW4q"><img src="https://i.imgur.com/LyixW4q.png" title="source: imgur.com" /></a>

**Comment by Direwolf20-MC** [comment]
Shift right click while in paste mode (latest version of the mod) :)

**Comment by Phylogeny** [comment]
Duplicate of #132
