### ISSUE TITLE
Add a way to build shapes of shape cards from RFTools

### ISSUE THREAD

**Issue by Flamebom** [Direwolf20-MC/BuildingGadgets#143]
Makes it easier for me to do a lot of my smaller builds. 😄

**Comment by MichaelHillcox** [comment]
To add more info to this https://ftb.gamepedia.com/Shape_Card

I actually think this is a great idea, although actually implementing it could be a pain due to the mode system the building tool already uses.

**Comment by MajorTuvok** [comment]
It might actually be easier to make the template manager accept shape cards and then make him convert them into templates...

**Comment by MajorTuvok** [comment]
Or propably better idea:
A converter block, which accepts shape cards and then writes templates of these shapes (maybe it even has it's own way of defining shapes?) with a given type of blocks...
Later on this could be extended to allow for certain kinds of 'patterns' to be used for defining multiple block types in the same template-pattern (mimicing the builders behaviour when given different block-types whilst building)
