### ISSUE TITLE
gadgets not charging in energy infuser from draconic

### ISSUE THREAD

**Issue by KevinVM1996** [Direwolf20-MC/BuildingGadgets#144]
Hi all,

i am currently playing stoneblock modpack version 1.0.30
And i can't put any of the gadgets inside the energy infuser from draconic evolution for charging,
I can charge them in the energetic infuser from thermal expansion.
I am not completly sure if this is a building gadget problem or a draconic problem so i posted it here.

building gadget version: 2.4.6
draconic evolution version: 1.12.2-2.3.17.321 universal

**Comment by MajorTuvok** [comment]
@Direwolf20-MC what might be producing Problems is that you're returning [a new Capabiliy Instance everytime getCapability is called](https://github.com/Direwolf20-MC/BuildingGadgets/blob/4a838e78b746fc81d5220215d1221a188876bbb2/src/main/java/com/direwolf20/buildinggadgets/items/ItemCaps/CapabilityProviderEnergy.java#L30). 
You're ItemEnergyForge always writes NBT to the ItemStack, but onl< goes the other way around (reading the current Energy as NBT from the Stack) when newly creating resulting in multiple Instances reporting different amounts of energy stored (and when Energy is extracted/inserted these multiple instances override the value stored in the ItemStack...). Just give your [CapabilityProvider one single ItemForgeEnergy instance](https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/#exposing-a-capability) and let him cast that all the time...

Even though the above is definitly not expected by behaviour by your mod, I don't get how Draconic evolution depending on this would result in the described bug, as I cannot think of why Draconic Evolution would cache your Cap-Instances, as this is usually heavily discourged (another reason not to create Objects in getCap - it has to be as fast as possible).

**Comment by MichaelHillcox** [comment]
@MajorTuvok correct me if I'm wrong but...
It would appear that the energy infuser uses the cofh RF api to handle the items charging https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/blocks/tileentity/TileEnergyInfuser.java#L3 where as our tools use ForgeEnergy from what I understand. Would that cause the issue in question? Personally I don't know much about the different energy API's, it's the next thing for me to look into.

**Comment by McJty** [comment]
If the energy infuser only uses the cofh RF api then that's actually a problem on their side IMHO. It would be better for that device to support Forge Energy API. If you really want to solve this in this mod then the only way is to also support the cofh RF api but personally I'm not sure I would do that

**Comment by MichaelHillcox** [comment]
I think if that is the true issue then this should be closed and an issue opened up in the Draconic Issues.

**Comment by MajorTuvok** [comment]
@MichaelHillcox if that is the case, then I agree with you guys...
Though returning a new ItemForgeEnergy instance everytime getCapability is called is still not the right way to go...
