### ISSUE TITLE
Copy-Paste Tool: Different keybindings for GUI and block selection

### ISSUE THREAD

**Issue by TuxMan20** [Direwolf20-MC/BuildingGadgets#145]
Playing StoneBlock, I found it really hard to find an empty space to shift+right click to open up the GUI. What happened is that I selected a far away block. 

I suggest having a customizable keybinding to open the GUI for the tools (Like the radial menu does).

Can be applied to the destruction tool also.

**Comment by MichaelHillcox** [comment]
I feel like this would just add to the "OMG why is every key got a key binding!" problem of mod packs haha but it's definitely a thing that could be done :P

**Comment by MichaelHillcox** [comment]
So as a compromise I have added a button to the Radial Menu of the copy and paste gadget so you can click the button to bring up the gui that shift right click would normally bring up. I hope this resolves your issue 👍
