### ISSUE TITLE
[Bug] Saving an empty input when changing the range crashes the game.

### ISSUE THREAD

**Issue by Tazgirl18992** [Direwolf20-MC/BuildingGadgets#152]
#### Issue description
When setting the range to nothing (delete the numbers in the range boxes) and clicking to save the settings the game crashes. It should probably have some sort of catch to auto set empty inputs to 0.
Edit: I'm playing the latest Stoneblock pack. 

#### Steps to reproduce the issue

1. Get a gadget. (I was using the destruction one)
2. Open the settings to change the range. (up, down, depth, etc)
3. Delete the numbers in the range boxes. Leave them empty.
4. Click 'OK' button 

#### What's the expected result?

It should auto-reset to 0, or give user an 'Invalid input' message.

#### What's the actual result?

Causes game to crash due to a parsing error. (Can't parse an empty input)

**Comment by MichaelHillcox** [comment]
Well maybe you shouldn't input nothing... Duh! Joking, yeah we know about this :) It should be sorted in the next release. @Direwolf20-MC should likely mark this as awaiting release.

**Comment by Direwolf20-MC** [comment]
Yup awaiting release. :)

**Comment by MichaelHillcox** [comment]
( Dire make labels plz 👍 or you know, let me help you out 😁 )
