### ISSUE TITLE
Create repository for copied builds

### ISSUE THREAD

**Issue by krystof1119** [Direwolf20-MC/BuildingGadgets#153]
As it is right now, anyone willing to get a build to paste in their own world must search the internet to find one.

A better approach would be to create a (moderated) branch or repository of builds, with folders organising the builds. New ones could be added with PRs.

This would much improve the usability of the Copy-Paste gadget, as Pastebin is often not searchable.

**Comment by MichaelHillcox** [comment]
I've actually start work on this or at least I've got a domain for it any how. https://diresbg.com feel free to suggest a better name. Still working on the backend system...

**Comment by MajorTuvok** [comment]
If you are already working on a seperate website for this, we might reconsider an special integration for this...?
I know that it might not really be a small thing to implement client side, but if you're already creating a server it should not be difficult to make it send a specific Database entry (or more specifically a file pointed to by the Database)

**Comment by MajorTuvok** [comment]
Btw. can we help you somehow @MichaelHillcox?
I sadly don't have mucht time to offer, but...
(Also this client-side implementation is something I'd immediatly start creating PR for, if I'd have the time for that)

**Comment by MichaelHillcox** [comment]
Logically I'll be exposing an api to clients although I was planning on doing that after the fact instead of along side the development. I've got a design and a bad domain name. You're welcome to suggest changes to both. Heres the design thus far:

![dire-draft](https://user-images.githubusercontent.com/12798904/50378584-8075a780-062d-11e9-8f41-e29d2a76de0d.png)

Ignore crap water mark, internet reasons :P Let me know ❤️

**Comment by MajorTuvok** [comment]
Looks nice to me...
:) 
Looking forward to seeing it online... XD

I hope you're Ok with the creation of the website @Direwolf20...

**Comment by Direwolf20-MC** [comment]
If you guys build and maintain the repo I’ll consider it official and look into integrating it into the mod (or more likely: accept a pr from one of you to do it). :)

**Comment by MichaelHillcox** [comment]
Sounds like a 👍 to me. I'll keep you all posted.

**Comment by krystof1119** [comment]
@MichaelHillcox @MajorTuvok It would be nice to create a separate repository to work on this if going the website route, so that everyone can contribute (potentially make it public, if a private one is needed I can do that) and that the site has a separate issue tracker (which may be important later on). Want me to do that?

**Comment by MichaelHillcox** [comment]
I've got a private repo at the moment that I'll open up if I see fit. I tend to keep website backends closed source to reduce security problems. I'll happily integrate an issue & suggestion system though :)

**Comment by MichaelHillcox** [comment]
@Direwolf20-MC Don't know if you'd like a chat regarding this "issue" but I've added you on Discord, my name is `MiKeY#3704`. I'd love to have a chat about this and a few other things regarding the mod :D

**Comment by InsanityAtHeart** [comment]
Soooo is this still a thing? I'd love to see what people have come up with! 😁

**Comment by loordgek** [comment]
https://www.curseforge.com/minecraft/customization/scripts/building-gadgets
