### ISSUE TITLE
All Immersive Engineering slabs will not paste.

### ISSUE THREAD

**Issue by Azutte** [Direwolf20-MC/BuildingGadgets#155]
Or possibly copy. Seems very silly. Vanilla slabs, BOP slabs, related IE blocks all work fine in comparison.

@BluSunrize have any ideas on this one?

![2018-12-25_15 36 59](https://user-images.githubusercontent.com/6581284/50427373-3bcf5380-085b-11e9-8d68-c9912aa0a77e.png)
![2018-12-25_15 37 14](https://user-images.githubusercontent.com/6581284/50427374-3bcf5380-085b-11e9-8a98-a66aa4aaa32a.png)
![2018-12-25_15 37 19](https://user-images.githubusercontent.com/6581284/50427375-3bcf5380-085b-11e9-956a-bc49fdd83879.png)
![2018-12-25_15 26 59](https://user-images.githubusercontent.com/6581284/50427384-9c5e9080-085b-11e9-9c51-8d0634b5d33d.png)

**Comment by MichaelHillcox** [comment]
It's a tileEntity... Not looked into why yet and I want to start putting work into make use things like that are supported but as you can see here 

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/BlockIESlab.java#L57 

there is a tile entity referenced for the slabs. Might be some logic going on but not sure.

**Comment by Direwolf20-MC** [comment]
I'll add a note indicating as such.

**Comment by Direwolf20-MC** [comment]
Fixed: https://github.com/Direwolf20-MC/BuildingGadgets/commit/f4cfc29fe76d1876602896be936e240cbe8ba764

**Comment by Azutte** [comment]
![2018-12-29_21 08 37](https://user-images.githubusercontent.com/6581284/50544555-13728c80-0bae-11e9-9af8-cdd7e2220443.png)
weird!

**Comment by Direwolf20-MC** [comment]
I should note you can’t copy tile entities. I only added a message.

**Comment by MichaelHillcox** [comment]
@Azutte To confirm, it is weird that they have made half slabs tile entities, I'm sure there is a great reason to it. Unfortunately this mod does not support tile entities in any form so this isn't considered an issue on our end :) Sorry about that. Pretty sure the too many wands mod and extra utilities support these items :)
