### ISSUE TITLE
[Feature Request] Exchanger classic visibility mode

### ISSUE THREAD

**Issue by uecasm** [Direwolf20-MC/BuildingGadgets#156]
Most other mods' exchangers will only exchange blocks that are adjacent to air or transparent blocks (ie. not exchange blocks that are hidden by other blocks).

Currently the Wall mode for the exchanger will allow hidden blocks to be exchanged if the range is set high enough to include them.

Sometimes this is what you want, but sometimes it isn't.  (When you're doing a cosmetic build with expensive blocks, maybe you don't want to "waste" them under the floor or above the ceiling, or in the invisible corners.)

It'd be nice if a new mode "Visible Wall" (or similar) could be added which acts like Wall but will not exchange blocks that are out of sight.  (The two column modes don't need extra modes because it's reasonable to assume you want to affect the entire range.)

(You can somewhat work around this by using Wall mode with Fuzzy true and a limited range, but it'd be more convenient to have the option of using it like the classic exchangers.)

**Comment by MajorTuvok** [comment]
If your arguments apply to the wall mode, then they logically apply to the other modes to (checkerboard f. e.)...

**Comment by Direwolf20-MC** [comment]
Gonna pass on this, i agree that setting the size appropriately should be the correct solution, even if the size turns out to be 1x1x1
