### ISSUE TITLE
Mekanism Blocks Cause Invisible Blocks

### ISSUE THREAD

**Issue by idnthvn** [Direwolf20-MC/BuildingGadgets#159]
When using Mekanism Blocks, Osmium Blocks are the ones i tested with. Using the Building Gadget, i place blocks. If i mess up and use the UNDO key. The blocks are returned to my inventory, but there is still a ghost block that i cannot place or break. 
Minecraft 1.12.2 and is using the latest version as of 12-30-2018

**Comment by idnthvn** [comment]
It is a multiplayer server.  Had this issue on my server with a plugin that when removed, placed a binding block and only did this with mekanism mechanics.  However, i am on someone elses server and help him when i can.            You cannot place on the block, but can place next to it.    I have not tried to move it with a piston but would assume I would not be able to move it.   Ill try and let u know in a few moments

**Comment by idnthvn** [comment]
Oh. Rebooting of the server does not correct the issue

**Comment by MichaelHillcox** [comment]
Do you have the plugin lagbegone or something alone those lines?

**Comment by idnthvn** [comment]
I'll get ahold of the server owner and have him get on

**Comment by tenten8401** [comment]
We have no special lag plugins or measures in place. I don't think it's specifically with mekanism blocks as I've seen it happen with blocks from other mods. Relogging does not fix the issue, they're serverside blocks and I have to worldedit them out whenever I see them. It doesn't seem to be specific to the undo function either.

**Comment by MajorTuvok** [comment]
I think I found their registration again:
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/block/states/BlockStateBasic.java

So OsmiumBlocks don't seem to be Tiles as they are pssing null for TileEntity class in this weird Enum

**Comment by MajorTuvok** [comment]
And the invisible Blocks you are entcountering are Blocks, and not entities (more specifically the Animation Entities used to render the fancy building effects)

**Comment by MajorTuvok** [comment]
Just saw a funny thing in BasicBlock.java:
OsmiumBlock's are neither opaque nor full cubes!

**Comment by Direwolf20-MC** [comment]
Can you tell me what the blocks are?  Like if you look at them with waila or something.

**Comment by idnthvn** [comment]
WAILA shows it as nothing. Just invisible    i can do it 100% replicate with mekanism osmium block and the building gadget. in Single Player i cannot replicate. Instead the blocks simply get voided when hitting the "undo" key

**Comment by idnthvn** [comment]
Noticed something. When doing the UNDO commadn in the server.  the block goes away, but does not return into my hand.  i CAN however break the invisible block(after a few seconds with an atomic disassembler) but it goes away after this. The block is still never returned into inventory and simply disappeared

**Comment by MichaelHillcox** [comment]
Time to disabled Mekanism support haha. It seems to be a source of a lot of issues :P. Hmm, I wonder why it's only happening on a server. By any chance if you where to host the server (I'll assume it's a public mod pack) locally and to try this then could you confirm if it still happens?

**Comment by Direwolf20-MC** [comment]
I'm gonna call this one "Something funky with Mekanism" but if someone figures out whats up and how to resolve, feel free to let me know!
