### ISSUE TITLE
Copy/Paste Gadget wont copy an area with fire in it

### ISSUE THREAD

**Issue by TwiZtedXero** [Direwolf20-MC/BuildingGadgets#160]
Copy/Paste Gadget wont copy an area that has fire in it.

**Comment by MajorTuvok** [comment]
What does it do when tasked with fire?
(though I don't get, why it should copy fire...)

**Comment by TwiZtedXero** [comment]
I said it was not copying anything if the area you are trying to copy has fire in it.

**Comment by Direwolf20-MC** [comment]
Did you try the latest version (2.5.0)?  A similar bug should be fixed in that version.

**Comment by TwiZtedXero** [comment]
Yes its fixed, The issue was with the version on Enigmatica 2 1.46. Thank you
