### ISSUE TITLE
[Suggestion] Checkerboard/Grid modes

### ISSUE THREAD

**Issue by perlguy** [Direwolf20-MC/BuildingGadgets#163]
Change "Checkerboard" to "Grid", and add a true Checkerboard mode...

Was just re-watching your v2 mod-spotlight and had the idea to do a true checkerboard mode.

**Comment by MichaelHillcox** [comment]
Hmm, could you expand on what you mean?

**Comment by Direwolf20-MC** [comment]
You can get this effect by using the tool twice :).
