### ISSUE TITLE
[Bug] Trapdoor State Is Not Copied

### ISSUE THREAD

**Issue by xob** [Direwolf20-MC/BuildingGadgets#164]
While creating a (terrible) street lamp design, I found out that the state of trapdoors is not getting copied by the Copy-Paste Gadget.

In the following screenshot, to the left is the original (terrible) design, and to the right is the pasted result.

![image](https://user-images.githubusercontent.com/4996802/50567302-69ac1080-0d11-11e9-8d80-12c160838b52.png)

This might be related to #28, being that maybe trapdoors need to be added to the blacklist.

**Comment by MichaelHillcox** [comment]
@MajorTuvok is there a specific reason we avoid copying the state of trap doors? I've not got a good understanding of what is a tile entity and what isn't. I'd assume it's just that they're tile entities?

**Comment by MajorTuvok** [comment]
To my knowledge they are not, though I intended to debug this through this afternoon...
There just weren't any other suggestions, so I just did this and waited for some to come up with a better idea

**Comment by MajorTuvok** [comment]
I just saw something: UniqueItem overrides Equals but not hashcode and is used as a Map Key!!! I'm not sure, whether that causes Problems, but it definitly violates the contract of these 2 Methods!!!

**Comment by MichaelHillcox** [comment]
Code snippets plz :D

**Comment by MajorTuvok** [comment]
[UniqueItem](https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/common/tools/UniqueItem.java) is used as a key [here](https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java#L429)...

**Comment by MajorTuvok** [comment]
I'm testing whether allowing copying of the Trapdoor open Property has any side effects... (Currently it wasn't in the safe to copy blacklist...)

**Comment by MichaelHillcox** [comment]
Why is that even a hash map?

**Comment by MajorTuvok** [comment]
Well that makes it work

**Comment by MajorTuvok** [comment]
Don't ask me

**Comment by MajorTuvok** [comment]
I'll just create a new branch to fix this issue here

**Comment by MajorTuvok** [comment]
Sneaky little UniqueItem: it doesn't override equals at all!

**Comment by MajorTuvok** [comment]
Changing all these Maps to Multisets is more than I thought...

**Comment by Phylogeny** [comment]
A change like that should be in a separate PR, yes.

**Comment by MajorTuvok** [comment]
ok
