### ISSUE TITLE
[Bug, 2.5.0] Building Gadget builds twice if in block placing range

### ISSUE THREAD

**Issue by lavraleksej** [Direwolf20-MC/BuildingGadgets#169]
Video demo:
https://cdn-b-east.streamable.com/video/mp4/r6aen.mp4?token=SMJmeYJiLFDh-DpMxnw8kQ&expires=1546569713
Screenshots:
https://i.imgur.com/B7HCXze.png
https://i.imgur.com/xeT8XvE.png

Most noticeable in Checkerboard mode, but can also be reproduced in Vertical Column 
while looking at a block from above
Adding a check in onItemRightClick to only fire if onItemUse has not succeded should fix this

**Comment by MichaelHillcox** [comment]
This isn't unique to this version of the mod but I have also noticed this issue. I'll have a look into how it's being triggered to happen and see if I can figure out how to calm it down :)
