### ISSUE TITLE
Flowers break when swapping grass

### ISSUE THREAD

**Issue by purpleposeidon** [Direwolf20-MC/BuildingGadgets#17]
For example, swapping a grass block that has a dandelion on top with dirt. Or, as a more motivated example, swapping grass with Botania's Vivid Grass.

<blockquote>&lt;mezz> dire's building gadgets is just released and neptunepink already has a handful of concerning sounding but somewhat vague bug reports. welcome to hell dire :D</blockquote>

**Comment by Direwolf20-MC** [comment]
Unavoidable, sorry!
