### ISSUE TITLE
Pastebin / Template Conversion for the CopyPaste Tool

### ISSUE THREAD

**Issue by InsanityAtHeart** [Direwolf20-MC/BuildingGadgets#170]
Hi there, I know this isn't a Bug or anything but I just wanted to ask if anyone on here knows how to convert templates from websites like GrabCraft into Pastebin strings for use with the copy/paste tool?

**Comment by InsanityAtHeart** [comment]
The Readme file simply shows how to convert a Pastebin string into a useable template in-game for the tool, I was wondering if anyone has a method for turning templates from websites into Pastebin strings? Or is this not possible?

**Comment by MajorTuvok** [comment]
You can copy it to your clibboard and paste in?

**Comment by MajorTuvok** [comment]
The line one below what I wrote

**Comment by InsanityAtHeart** [comment]
Nevermind I meant for sites that don't just give you the code string, I was hoping there was a way to convert the blueprints from the GrabCraft website into a code string

**Comment by MajorTuvok** [comment]
Sadly not...
They have to support the Template format in some way.
