### ISSUE TITLE
Introduce a way to show required Items as Strings

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#172]
In [your last video](https://www.youtube.com/watch?v=W5T8BxgOcds) you already said that this would be a good idea, as it is sometimes hard to see from the visuals which blocks are actually required by the Copy-Paste Gadget. (I'm mainly putting this here as a remainder for you @Direwolf20...) 
(For others: the Problem was, that he wanted to paste some mysterious purple blocks in - from the visuals it was almost impossible to tell, what they actually were) 

Also people have been suggesting ideas in the comments on how to show these strings:

- via a crafting recipe, showing the list of items (?) (I guess he/she meant it as a tooltip as soon as its in an InventoryCrafting?) ("put a piece of paper in a crafting grid with the copy paste, and it gives you a list of item names and what mods they belong to")
- via a modifier/key binding when right clickling the copy-paste gadget
- via a right click gui for the template - which then shows a list of items

Personally I like the last version best, as 

1. this doesn't add even more functionality to already very functional-items
2. the template is missing some kind of functionality to show what it is (The gui could maybe expanded to show the same render as the TemplateManager together with the item list?), besides having a name (in my opinion)

#213 Also added some other suggestions/ideas:

- A Template Manager button could be added to show the list (maybe in an upgraded version)
- It would also come in handy if Used mods and the outer dimensions could be displayed
- It also seems handy to have the ability to copy this information to the clibboard, as people could then use it as a reference when sharing their templates

**Comment by MichaelHillcox** [comment]
I'm liking the idea of a scrollable list of item names and images? Along with a count. Not sure how to show it but maybe on the mode selection their could be one to show resources?

**Comment by MajorTuvok** [comment]
I was actually referring to the Copy-Paste Gadget (and it's Templates, which would then show the 'required items gui' when clicked into empty air?) only...

In the case of the building Gadget one almost always knows with which block one is building... 
Though I can't tell if it is useful to know how many blocks one is exactly going to use.

**Comment by MajorTuvok** [comment]
#213 Also added some other suggestions/ideas:

- A Template Manager button could be added to show the list (maybe in an upgraded version)
- It would also come in handy if Used mods and  could be displayed

**Comment by hnOsmium0001** [comment]
Giving a go at this. (might take forever from I start since I'm also doing a refactor)

**Comment by MichaelHillcox** [comment]
This has actually already been implement to 1.13 but I feel we could use this in 1.12 too so I'll sort this out for for 1.12-2.7.0

**Comment by MajorTuvok** [comment]
Closed by #278 and #314. Thanks again @hnOsmium0001.
