### ISSUE TITLE
Config to Disable the angle Gadgets are held with

### ISSUE THREAD

**Issue by NillerMedDild** [Direwolf20-MC/BuildingGadgets#173]
Hello!

I would like to request a config for giving the gadgets normal rotation, if that's possible. This would allow texturepacks to override the Building Gadget textures without the new textures looking odd or crooked.

I hope you'll consider it :)

**Comment by Direwolf20-MC** [comment]
I’m not sure if that’s possible since the rotation is defined in the item model json. 

https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/resources/assets/buildinggadgets/models/item/buildingtool.json

**Comment by Phylogeny** [comment]
@NillerMedDild Texture packs don't exist anymore. They havn't existed for years (since MC 1.6). Only resource packs are supported, which allow much more than textures to be modified (such as models, as Dire mentioned).

**Comment by NillerMedDild** [comment]
I'll have a go at modifying the item model json, thanks :)
