### ISSUE TITLE
[Bug 2.5.0] Tooltip Clash with Thaumcraft

### ISSUE THREAD

**Issue by FenixFyreX** [Direwolf20-MC/BuildingGadgets#177]
Upon holding shift over the Copy Paste Gadget to view what blocks I am missing from a copy / template, the gadget's blocks and aspects are drawn on top of each other, making all icons / text very difficult to read.
![gadget-thaum-bug](https://user-images.githubusercontent.com/1755602/50865582-ec654900-136b-11e9-9f07-de3fe26b25fe.png)
It seems as if enough vertical space is being allocated for both mods' lines, but both are drawing right above the mod name of the gadget (aka the bottom-most line). Modpack is Enigmatica 2: Expert. Thaumcraft version: 6.1.BETA26

**Comment by Direwolf20-MC** [comment]
Yea this is a known issue. Not sure how easy that’ll be to fix.
