### ISSUE TITLE
[Feature Request] Add support for .schematic files

### ISSUE THREAD

**Issue by jmiln** [Direwolf20-MC/BuildingGadgets#180]
Would it be feasible to support using .schematic files in the copy/paste tool (Similar to the Schematica mod) since there are already a ton of those built and out in the wild?

**Comment by MichaelHillcox** [comment]
Are these files build to support "unlimited" sizes of builds? If not then the restrictions of the copy-paste tool would likely cause issues.

**Comment by MajorTuvok** [comment]
We would never be able to fully support it - a quick glance at the [specs](https://minecraft.gamepedia.com/Schematic_file_format) shows me the following Problems:
- infinite sizes are valid
-TileEntities and Entities are valid (though TileEntity Blocks, without their tagCompounds might be considered valid (yes that will make Problems) - Entities are clearly not)
-There are various additional Aspects like "ExtendedMetadata" 

If we can make it clear to users, that we will simply ignore these Properties, I think this might be doable

**Comment by Direwolf20-MC** [comment]
I don't have any plans to support this at this time, but if someone (@MajorTuvok) wants to go for it, be my guest :).
