### ISSUE TITLE
[Feature Request] Fill / Empty Mode

### ISSUE THREAD

**Issue by andr9528** [Direwolf20-MC/BuildingGadgets#181]
Two Modes, One for the Building Gadget and one for the Destruction Gadget

__Fill__
A Mode for the Building Gadget, allowing the player to chose two points in the world much like the Copy-Paste Gadget, and then be filled in with the chosen block.

__Empty__
A Mode for the Destruction Gadget, much like fill, just in revers, allowing two points to be chosen, and anything in this area, will be voided.

**Comment by Direwolf20-MC** [comment]
I kind of feel the gadgets can do this already, it just requires clicking a few more times :).
