### ISSUE TITLE
[bugs] and weird behavior with blocks from the mods Thaumcraft, Immersive Engineering and Tinkers´ Construct  using copy/paste tool 

### ISSUE THREAD

**Issue by MGjokern** [Direwolf20-MC/BuildingGadgets#184]
i really like the mod you have made, and would like to help report some small issues I stumbled upon while using it with other mods

Thaumcraft:
silverwood log can´t be copied at all.
Greatwood logs come out un-rotated when placed with the copy/paste tool .
exchanging gadget can also not orientate the G wood and S wood but can't exchange both, unlike vanilla logs:
![2019-01-09_20 03 26](https://user-images.githubusercontent.com/46539268/50984454-33854280-1502-11e9-983d-6513fc8fbc49.png)
the mod versions: 
1.12.2 Bulding gadgets 2.4.6
1.12.2 Thaumcraft 6.1.BETA26

Immersive engineering: 
all slabs, structural arms, wall mounts, balloon and lantern can´t be copied with copy/paste tool:
![2019-01-09_19 59 31](https://user-images.githubusercontent.com/46539268/50985428-97106f80-1504-11e9-9263-128fbbf4140e.png)
the slabs should be able to de copied like vanilla slabs, but can´t. this would be nice so you would be able to copy an arc furnace and make a blueprint. the wall mounts is a pretty great decoration that looks good on walls with a candle on top, 
the mod versions: 
1.12.2 immersive engineering 0.12-88

Tinkers´ construct
all the blocks under the category of tinkere's smeltery can´t be copied at all 
![2019-01-10_19 46 21](https://user-images.githubusercontent.com/46539268/50989813-a3022e80-1510-11e9-9394-fcb8fa305f0c.png)

i know they can be used to make a smeltery but so can many of the blocks from Immersive engineering.  (note: i know nothing about how to code or how it works) many of the decorations have :(safe for decoration) text in their description.
the mod versions: 
1.12.2 Tinkers´ construct 2.12.0.113 

place don´t take any of the words above as criticism, this is a truly great mod and i don´t know if any of the bugs is fixable on your end :)
the reason i found these "bugs" is that i wanted to submit this structure to Direwolf20's buildings, for his enigmatica 2 series. (note the Greatwood logs have been exchanged to dark oak logs in the pictures)
![2019-01-10_19 58 31 3](https://user-images.githubusercontent.com/46539268/50991882-03479f00-1516-11e9-8fdb-681ff544e49d.png)
![2019-01-10_20 00 58 2](https://user-images.githubusercontent.com/46539268/50991889-05a9f900-1516-11e9-9323-58defea9a846.png)
![2019-01-10_20 00 26 2](https://user-images.githubusercontent.com/46539268/50991993-40ac2c80-1516-11e9-8647-4b4dbc8495ec.png)
this is all from the twitch curse launcher

**Comment by MichaelHillcox** [comment]
Is the mod giving you a reason for it not copying? or does it just not work? most of these Items are likely tile entities and therefor aren't supported.

**Comment by Phylogeny** [comment]
All of the blocks you mentioned have tile entities. And although `BlockLog.LOG_AXIS` (`PropertyEnum.create("axis", BlockLog.EnumAxis.class)`) is a white-listed property, Thaumcraft's `BlockLogsTC.AXIS` (`PropertyEnum.create("axis", EnumFacing.Axis.class)`) isn't.

**Comment by MGjokern** [comment]
ok thank  you both for clarifying, i had a feeling that they might be tile entity blocks, that is too bad.
