### ISSUE TITLE
MC 1.7.10 Support

### ISSUE THREAD

**Issue by Immortalin** [Direwolf20-MC/BuildingGadgets#186]
A lot of older hardware cannot play 1.8+ modpacks smoothly without significant ram upgrades etc. It would be great if this can have 1.7.10 support.

**Comment by MajorTuvok** [comment]
Downgrading to an older MC version would be far too complicated with far too little gain in my opinion...
Also, one doesn't downgrade versions! Especially as BG does use quite a few newer Features of Forge - one would have to rewrite half the mod for this to work!!!

**Comment by Immortalin** [comment]
What do you guys suggest for GC tuning then? On Ubuntu 18.04 with 7th generation i7 + 8 GB of RAM isn't enough to run the DW20 1.12 without significant swapping/paging.

**Comment by MichaelHillcox** [comment]
What gpu @Immortalin

**Comment by Immortalin** [comment]
Nvidia 940MX with 4GB VRAM

**Comment by MichaelHillcox** [comment]
You shouldn't be struggling to run it then :P

**Comment by Immortalin** [comment]
Even with 6GB allocated it has significant lag spikes that makes it unusable

**Comment by MichaelHillcox** [comment]
Hmm, I hate to say it but it's like Linux. Do you have the option of dual booting or have you tried a different graphics driver?

**Comment by Direwolf20-MC** [comment]
Nope. Sorry!
