### ISSUE TITLE
Schematic Rotating

### ISSUE THREAD

**Issue by hotdog95** [Direwolf20-MC/BuildingGadgets#191]
I'm currently playing through the Enigmatica 2: Expert - 1.46 pack and have experienced an bug where some schematics cannot be rotated while the copy-paste gadget is in paste mode. I've rotated and pasted a schematic in the play through however the following factory schematic cannot be rotated: https://drive.google.com/drive/folders/1tyY-wmuGOnLP7Vx8wFsWfk6GB4fnC688

The pack's Building Gadget version is 2.4.6

**Comment by MajorTuvok** [comment]
This should be fixed by the rewrite, if not reopen it after we released rhis

**Comment by MichaelHillcox** [comment]
Should be fixed in 1.14.4 - 3.1.0
