### ISSUE TITLE
[bug?] manager paste failed , invalid jason 

### ISSUE THREAD

**Issue by LordRavenShadow** [Direwolf20-MC/BuildingGadgets#194]
i been trying to use the https://pastebin.com/85pv0AGw   in the manager, it says paste failed , invalid Jason after i hit the paste button.

Enigmatica 2 Expert version: 1.51
BuildingGadgets version: 2.5.0

**Comment by MajorTuvok** [comment]
If I'm not mistaken, then this isn't a valid json...
It looks like the mapIntState Array Bracket is never closed

**Comment by LordRavenShadow** [comment]
that would be great .

**Comment by MajorTuvok** [comment]
Something similiar was already rejected in #94

**Comment by LordRavenShadow** [comment]
@MichaelHillcox , it work thanks i copy the raw data and paste it 

@MajorTuvok , the error was it not reading the raw data , from the paste bin . like dire says in "Enigmatica 2 Ep9 Lovely Home". just copy paste bin. 
how is this the same in #92   ?

**Comment by MajorTuvok** [comment]
I was referring to @NeosGhost's comment...
