### ISSUE TITLE
2.5.0 [Beta] Crashes with Undiscovered pack

### ISSUE THREAD

**Issue by choekstr** [Direwolf20-MC/BuildingGadgets#197]
Running:
- Undiscovered v2.14.1
- Minecraft 1.12.2
- Forge 14.23.3.2655
- Building Gadgets 2.5.0 Beta (Dec 30 2018 build)

Using the latest build of Building Gadgets causes the pack to crash but reverting to 2.4.6 it works.

[Link to crash log](https://pastebin.com/uzRYstKK)

**Comment by Phylogeny** [comment]
The version of Forge used in that pack is even older than the Forge version of BG's initial release. In the recent version of BG, various depreciated methods have been removed. `GameRegistry#registerTileEntity(class, Srting)` is evidently one of them.

**Comment by choekstr** [comment]
yeah, I was afraid it was going to be a forge issue.  I like the cool new features he added in 2.5 but figured upgrading forge would introduce a whole rash of new issues for an older pack like this.

**Comment by Phylogeny** [comment]
Sadly, you're quite right. I'll see that a Forge version dependency is added to make the new restrictions clear.
