### ISSUE TITLE
Building Gadget new mode: Shapes

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [Direwolf20-MC/BuildingGadgets#200]
add another mode for a building gadget to paste in shapes which can be sized via the range buttons. of bettter yet another gadget for pasting in shapes

**Comment by MichaelHillcox** [comment]
Pretty sure this was a rejected request a little while ago although I can't be sure. Most shapes we could preprogram you can achieve manually but I do see the reasoning for wanting them. What shapes?

**Comment by MajorTuvok** [comment]
This seems somewhat related to #143 to me. When I got to RFTools compat, I would have proposed a new page with some simple builder style modes...
Of course that would require rewriting the way modes are handeld, cause with all these hard-coding it seems almost impossible to me, to add new modes.
