### ISSUE TITLE
Copy/Paste under water

### ISSUE THREAD

**Issue by Damit84** [Direwolf20-MC/BuildingGadgets#204]
I really enjoy building bases in the deep blue ocean. Without unlimited breath or other tricks the building is really tedious. My idea was to pre-build everything on dry land and then just paste it underwater with your mod. Sadly the copy/paste tool will not paste because water is seen as a non-air block(duh..).

**Would it be possible to give the copy/paste tool a "Paste/Replace" option that will just replace everything in it's way?** It would even be ok to just destroy those blocks instead of exchanging them. Or if that isn't possible just water blocks?

Anyway, nonetheless thanks for a super awesome mod!!

**Comment by MichaelHillcox** [comment]
Love this idea, I'm sure it wouldn't be too hard to implement 👍
