### ISSUE TITLE
Paste is too large when copied from another world

### ISSUE THREAD

**Issue by pandadox** [Direwolf20-MC/BuildingGadgets#205]
On my creative world it allowed me to copy my house and paste it onto a template, paste it onto pastebin, etc. but when copying the raw data from the pastebin and pasting it on my survival world it tells me the paste is too large. I can copy & paste the house fine on my creative world and preview it in my template manager

**Comment by Phylogeny** [comment]
Please include a link to the paste.

**Comment by MajorTuvok** [comment]
This can happen, as TemplateManagerCommands isn't checking for the templates size before copying it to the clibboard (noticed that yesterday evening)

**Comment by pandadox** [comment]
https://pastebin.com/wtVWh9pV
enigmatica 2 normal pack, if that matters

**Comment by MajorTuvok** [comment]
When looking at it in Pastebin: It definitly seems too large with 228.40KB. The Maximum that can be handeled due to packet limits is 31KB and I don't think that you can get below that limit via compression.

**Comment by MichaelHillcox** [comment]
I mean logically we don't 'have' to send it all through in on packet. We can pretty simply separate it up into max-size parts and send it through with a part & total parts data to allow us to have basically unlimited sizes

**Comment by MajorTuvok** [comment]
That's true...
It will be caught in the world save anyway, so the world save can also put it together once he get's all the packets

**Comment by Direwolf20-MC** [comment]
@majorTuvok I was toying with this when making it (splitting packets). Player was giving me ideas on how if you want them. I’m all for it if you can :)

**Comment by Phylogeny** [comment]
Fixed in v2.6.1
