### ISSUE TITLE
GUI Placement when in alternate GUI Scale...

### ISSUE THREAD

**Issue by RepoDraghon** [Direwolf20-MC/BuildingGadgets#206]
Video Settings... GUI Scale...

![2019-01-24_16 46 42](https://user-images.githubusercontent.com/8423696/51716157-f5efe180-1ff8-11e9-8ec4-8af5fbfd5e9a.png)
![2019-01-24_16 47 31](https://user-images.githubusercontent.com/8423696/51716236-4a935c80-1ff9-11e9-96bc-02886bf9c1d4.png)

**Comment by MajorTuvok** [comment]
(top left I guess...)

**Comment by MichaelHillcox** [comment]
Can not confirm this will scale well for 4k but for normal people with bigger monitors then it's all fixed as of 11f93e8b8d6d51afc35f7fbf20672163ecb9e9b6 we'll also need to give it a facelift at some point but it's been cleaned up and made a lot nicer to use. 

https://i.imgur.com/UnwIEgv.jpg
