### ISSUE TITLE
Compressing the output paste string

### ISSUE THREAD

**Issue by KonKeyHD** [Direwolf20-MC/BuildingGadgets#207]
With bigger pastes the build string gets really long and may even be to big to fit into the clipboard.
what i would suggest doing is:
1. deflate or zlib compress the string
2. base64 encode the string to be copyable

**Comment by hnOsmium0001** [comment]
I think base64 only makes the string larger, not smaller
One option can be using the pastebin/pasteee api, upload them directly like what Multimc does to logs and crash reports

**Comment by MajorTuvok** [comment]
The pastebin api is not going to be implemented in here as has been already discussed.

**Comment by MajorTuvok** [comment]
Also this should no longer be necessary, as of ce3ad2ccc89c72159bf6fc8af976fe44820cdb00 we no longer expose Templates without checking their size and therefore they won't grow indefinitely.

**Comment by MajorTuvok** [comment]
I assigned myself because of the Template Format changes

**Comment by MichaelHillcox** [comment]
( no need to give a reason :P )

**Comment by MajorTuvok** [comment]
Using standard java zip in 1.14
