### ISSUE TITLE
invalid JSON is produced

### ISSUE THREAD

**Issue by blackdrag** [Direwolf20-MC/BuildingGadgets#210]
The json produced by the Copy-Paste-Widget Logic produces quite flawed json. Tags are not put in quotes, nor are many values, stateArray and posIntArray start have I; as first element, which is also not valid.

Basically this is no problem if you just copy the things around or put them directly on pastebin. But I wanted to for example replace materials used in the copy. So first thing I did was put the json in my IDE and autoformat it. That resulted then in a json the Mod rejects with "invalid JSON". And that is for example because of the I; 

Would it be difficult to go with JSON that is considered to be standard? The mod does not even have to produce it, but being able to read it would be nice. That would also allow me for example to write something to translate a 3D from Blender to something the mod can read

**Comment by Shirkit** [comment]
If you make any modifications to the JSON, I strongly suggest to be able to support older templates versions. This mod has the capacity to be the standard for modded survival base sharing, and not supporting older versions would be a first step into making people dropping it.

Just saying, although it's not directly related to the issue, it has some connection.

**Comment by MajorTuvok** [comment]
It will not be possible to convert 1.12 templates to 1.13 because of the flattening. (we simply cannot convert modded 1.12 Blockstates to 1.13 flattended Blocks - Vanilla might be possible (with a **lot** of effort) but definitly not modded ones)

If we backport to 1.12, this will of course include 1.12 conversion utilities @Shirkit (I considered that to be obvious)

**Comment by MajorTuvok** [comment]
I assigned myself because of the Template format changes

**Comment by MajorTuvok** [comment]
1.14 no longer uses json for the actual Template data. And the Template header is going to be created by GSON which does write valid json
