### ISSUE TITLE
Creative Construction Paste container

### ISSUE THREAD

**Issue by Kzorith** [Direwolf20-MC/BuildingGadgets#211]
I would like to offer the thought of a creative construction paste container which is always half full.

This would allow someone to go into creative mode, get only the paste container and then go back into survival to do builds where they don't want to farm the blocks themselves.  By having creative paste, they can paste as large a structure as they want, and not have to worry about anything but power/experience.  And when they break the building, they get paste back which then goes into the container, meaning they get essentially nothing back.

If you wanted to take things a step further, you could keep track of which blocks were "creative paste" and have them break and drop nothing at all, i.e. creative mode block breaking.

**Comment by Phylogeny** [comment]
Fixed in v2.6.2
