### ISSUE TITLE
Name and Author

### ISSUE THREAD

**Issue by generrosity** [Direwolf20-MC/BuildingGadgets#212]
Quick suggestion; currently the JSON copied to the clipboard doesn't contain the template name specified in the Template Manager.

If I could suggest, it would be nice to put this as the 'first' JSON element so anyone looking at several posts can see at a glance.

It might also be useful to include the logged on user name of the template-er. While this could be up for abuse, it could be useful to 'sign' your creation. (You could even encrypt it in to make it non-trivial for someone to put it in, etc etc)

Awesome work!

**Comment by MajorTuvok** [comment]
Added to the TemplateHeader in 1.14
