### ISSUE TITLE
Null Pointer Exception while loading

### ISSUE THREAD

**Issue by utoxin** [Direwolf20-MC/BuildingGadgets#216]
* Forge Version: 14.23.5.2808
* Building Gadgets version: 2.6.0
* Log: https://pastebin.com/Bz76bnE5

This is a non-critical error. The game continues to load, and everything seems to work. But there's a Null Pointer Exception during load that would be nice to have cleaned up.

`[12:59:30] [Client thread/INFO] [buildinggadgets]: Preparing to migrate old config Data to new Format
[12:59:30] [Client thread/ERROR] [buildinggadgets]: Error loading compat-config file! 
java.lang.NullPointerException: null
	at com.direwolf20.buildinggadgets.common.config.CompatConfig.parseCompatConfig(CompatConfig.java:66) ~[CompatConfig.class:?]
...`

**Comment by MajorTuvok** [comment]
wtf?

**Comment by MichaelHillcox** [comment]
@MajorTuvok did you ever implement a way to check for config version number

**Comment by MajorTuvok** [comment]
There wasn't one before...

**Comment by MichaelHillcox** [comment]
Last time I checked you could add a config version number and if it doesn't exist then just check for null. it's a great way to check if there is going to be fatal conversion errors.

**Comment by MajorTuvok** [comment]
Ok

**Comment by MajorTuvok** [comment]
(I tested with a config File from 2.5.0...)

**Comment by utoxin** [comment]
I had two config files somehow... not sure how, since this is a brand new pack I'm working on building, and I haven't messed with Building Gadgets config yet. I installed whatever the version prior to 2.6 was, and then upgraded it the other day when Dire announced he'd released it. Anyway... here's my two config files:

BuildingGadgets.cfg: https://pastebin.com/sgtDJKQp (Jan 27, 2019)
Building Gadgets.cfg: https://pastebin.com/ju9Pm7Sk (Feb 3, 2019)

**Comment by MajorTuvok** [comment]
The older one is the one, that makes Problems according to code

**Comment by MajorTuvok** [comment]
Really?!? I found it: Blacklist is spelled with a capital B not a b - I must have lost it, when I accidentally deleted the CompatConfig whilst merging

**Comment by MajorTuvok** [comment]
After using a captial B everything works fine

**Comment by Phylogeny** [comment]
Fixed in v2.6.1
