### ISSUE TITLE
Lost Config Settings and New Config has a space + Capitals in it.

### ISSUE THREAD

**Issue by KaneHart** [Direwolf20-MC/BuildingGadgets#220]
I know the config was rewritten and that is great. Just a warning it's a bit more annoying now as it shows both configs and did not copy/update it correctly.

On top of that sadly it's very malformed config file name:
"Building Gadgets.cfg" 

Thanks.

**Comment by MajorTuvok** [comment]
Known and fixed issue, which is pending release...

**Comment by MajorTuvok** [comment]
Also, why is that a malformed comfig namr?!? A config name my be any String that's valid on the File System and changing that was intentional, in order to detect the old config. Sadly the Blacklist being capitalized prevents copying over of the old config, which is why you have 2 files now.

**Comment by Phylogeny** [comment]
Fixed in v2.6.1
