### ISSUE TITLE
duplication on undo

### ISSUE THREAD

**Issue by matsaa93** [Direwolf20-MC/BuildingGadgets#225]
----------------------------------------------------------------------------
Forge Version: 1.12.2
Building Gadgets version:  2.5.0
other mods that are involved: Biomes of Plenty
building gadget on undo of blocks 'Urban wood log' it drops the 'Urban Wood log' in world and creates 
'sacred oak log' in inventory. 
may be a oredict conflict or naming of biomes of plenty logs.
it seems to be happening to all Biomes of Plenty logs, any planks does not seem to be effected by this dup bug/replacemet bug. 
additional info:
umbran wood:                                                           
oredict entries: logwood                                            
code name: biomesoplenty:log_0                              
metadata: 6                                                               
meta's unlocalized name: tile.log_0.umbran_log     

sacred oak wood:
oredict entries: none
code name: biomesoplenty:log_0 
metadata: 0
meta's unlocalized name: tile.log_0.sacred_oak_log

**Comment by TomyLobo** [comment]
I also have a dupe problem on 2.6.8:
I built a bunch of slimy grass
then a bunch of stone around it
then fences on top of that
then went out of fences with 30 left to be placed
then set up the remaining fences in anchor mode
then went to get 31 fences
then placed the anchored pattern
then noticed i still had those 31 fences
then tried it a few more times and it still didn't use fences
![image](https://user-images.githubusercontent.com/963797/58044539-4d820200-7b40-11e9-8c41-9920a4c3d1c8.png)

How do I turn it off, help :D

**Comment by TomyLobo** [comment]
This was on FTB Interactions 1.5.0, with 2 satchels in my inventory. I think neither of them was set to auto-vacuum.

**Comment by MichaelHillcox** [comment]
I'm so confused by your comment @TomyLobo the image isn't even Minecraft?

**Comment by MichaelHillcox** [comment]
@matsaa93 that's for the bug report, I'll see if I can reproduce this.

**Comment by TomyLobo** [comment]
the image is just a joke. just ignore it and read the text above it :)

However, I'm not so sure anymore that this duped anything.
I have since found out that the building gadget takes stuff from satchels first.
I wasn't aware of that at the time.

**Comment by MichaelHillcox** [comment]
As this is something we're unsure of can you confirm if this is actually an issue and if it is then reopen the issue? I'm working towards our next release so I'm getting rid of anything that can't be reproduced. If you could get back to me about this that would be great 👍 @TomyLobo

**Comment by TomyLobo** [comment]
It was probably taken from the satchel, which would mean it's not a dupe bug.
