### ISSUE TITLE
CONTRIBUTION.md and Code Style Guide

### ISSUE THREAD

**Issue by hnOsmium0001** [Direwolf20-MC/BuildingGadgets#227]
Currently the project has no official code style and things are all over the place. I suggest to create a `CONTRIBUTION.md` where inside it specify the official code style.  
This way we can avoid many formatting issues when pull requesting and avoid the need of constantly format everything.  

---

Here is some suggestions for formatting:
- 4 space indent everywhere
- no return before open brace (`{`)
- prefix interfaces with `I`, like `ITemplate` but nothing else should have a prefix
- use only 1 return between bodies
- use only 1 return between `package`, `import`'s, and class body
- empty line at start and end of a class definition
  * same for interface, enum, annotation definitions
  * apply for both global and nested definitions
  * does not apply for anonymous bodies
- don't warp the ending brace (`}`) if the method is empty
  * `public static void derp(Episode e) { }`
- always use `@SupressWarnings("...")`
  * **use with caution, avoid when possible**
  * for deprecation warnings, safe unchecked operations (ex. cast to covariants)
  * **always add comment behind the annotation to explain the reason**
  * example: `@SupressWarnings("deprecation") // Minecraft uses deprecation to indicate override-only methods`
  * example: `@SupressWarnings("unchecked") // Safe covariant casting`
- use single-line comment (`//`) only, even if the comment is multiline
- write Javadoc instead of comments when appropriate
- space between `@`'s and descriptions in Javadoc
- capitalize the sentence in comments
- space before and after operators (`+`, `-`, `*`, `/`, `<<`, `&&`, `!`, etc.)
- space after all commas (`,`)
- space after casting type (ex. `(MyBlock) block`)
- no unnecessary else clauses
- no public non-final member fields
- use getters/setters when it doesn't create nonsense situations (ex. don't use getters for config), which should be most of the cases
- use getters and setters for all read-only and write-only properties (not necessarily member fields)

EDIT: added more suggestions
EDIT: include MajorTuvok's opinions

**Comment by MajorTuvok** [comment]
- no public non-final member fields should be obvious to anyone
- why only use single line comments?!? 
- why 4 space indent?

**Comment by hnOsmium0001** [comment]
When a say only use single line comments, I mean
```java
// This is a short comment.

// This is line 1 of a longer comment
// and there's the second line.
// This is a new sentence in line 3 of the longer comment.
```
and don't use
```java
/* This is a short comment. */

/* This is line 1 of a longer comment
 * and there's the second line.
 * This is a new sentence in line 3 of the longer comment.
 */
```

For getters and setters, I don' think it is viable in places with a bunch a fields like config classes, as you added the `SyncedConfig` class and then access them direct.
I don't think getters make a big difference in case of future prove-ness, and most saves wouldn't survive Minecraft version updates anyways.

**Comment by MajorTuvok** [comment]
I know what you mean, but why? 
That might be true, for something like config class, but for almost nothing else it is viable to expose implementation details such as variables. I'm not only talking about an update between mc versions. If you want to update your API at any point, you'll have Problems when exposing things like that. Besides encapsulation should be known as a good practise anyway.

**Comment by MajorTuvok** [comment]
- Space after all commas is too much
-  wrap the empty brace in empty Methods: I never do that, and in my opinion just looks strange
- don't request a space after all single line comments - we aren't doing that at the moment, as far as I've noticed
- @SuppressWarning should be used with caution, and always explain why they are usuable their (see EffectiveJava for reference)
- @SupressWarnings should be used in the smallest poasible scope

**Comment by hnOsmium0001** [comment]
This is just a personal thing, and I don't want to force the collaborators to use some kind of style. From what I see in the project plus some personal bias, I came up with the suggestion so that it is less effort for Dire and Phylogeny or somebody else to add them.

I will include you opinion in the description.

--

I looked at some comments Dire made in his early comments, like `// Used for localization (us_US.lang)` in when calling `setUnlocalizedName`. Maybe I'm wrong: yes I see a lot of comments without space after it, but I don't know if they are made by him.  

For using `@SupressWarnings`, I want to say use them so that you will see no warnings from your IDE, and that's why I included "* single-line comment after annotation that explains the reason"

**Comment by MajorTuvok** [comment]
You don't need to put it into the description... I just wanted to clarify that  one should avoid @SuppressWarnings in general and that's not an good idea to use them just to get warnings away... There's a reason your IDE/the compiler warns you about stuff and one should not just ignore it (). For example if someone marks something with @Depracated he/she usually has a reason for this and marking that with an supression should not be done. (There's one case where one could talk about suppressing deprecations: overriding the depracted methods which are meant to be overridden in 1.13...)

To the comments: I'm pretty sure that they are not from Dire, as for example in the old config there used to be a comment simliarly formatted to what you described "These values you can access elsewhere in your mod". Because of the way it talks to Dire and the fact that code which I know comes from Dire is sadly very, very rarely commented I'm pretty sure that these comments came from the person who explained Forge to Dire.

**Comment by MajorTuvok** [comment]
I will put a conrtibuting.md together after some more discussion...
