### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Modpack-Support** [Direwolf20-MC/BuildingGadgets#233]
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
* Forge Version 14.23.5.2811
* *If updating was not possible*; Building Gadgets version 2.6.2
* *If the issue is a crash*; An external link to the crash report
https://gist.github.com/Modpack-Support/923690d7bf4b7ca1442d18f3e89f8616

**Comment by Phylogeny** [comment]
Fixed in v2.6.3
