### ISSUE TITLE
Server crash (v2.6.2)

### ISSUE THREAD

**Issue by nickjackson-ff** [Direwolf20-MC/BuildingGadgets#234]
* Forge Version: 1.12.2-14.23.5.2811
* Link to crash report: https://pastebin.com/kwWDK8mX

Steps to reproduce:
1. Updated to lastest version of Building Gadgets
2. Start server
3. Server crashes on launch

It seems that the mod is attempting to load the new UI sound on the server-side, which is causing a crash.

**Comment by bigenergy** [comment]
+1

**Comment by nickjackson-ff** [comment]
It seems this is a duplicate of #233, which is already closed and marked as "pending release", so I'm closing this issue.

**Comment by Phylogeny** [comment]
Duplicate of #233
