### ISSUE TITLE
Building Gadgets Causes ghost blocks with GriefPrevention Claims

### ISSUE THREAD

**Issue by MstrTaffy** [Direwolf20-MC/BuildingGadgets#238]
Sponge Forge : 1.12.2-2768-7.1.6-RC3568
BuildingGadgets : 2.4.6
GriefPrevention : 1.12.2-4.3.0.674
Forge : 1.12.2-14.23.5.2768-universal

When placing blocks in a claim using the Build Gadget, Blocks place and when you undo it, it sometimes leaves ghost blocks. These blocks have no ID and can only be broken by creative mode. Reloging, Reloading the chunks and even rebooting the server does not make them go away.
Waila shows nothing is there, except an outline. 

I have reported this to GriefPrevention [here](https://github.com/MinecraftPortCentral/GriefPrevention/issues/833)

They told me some flags to run that may help it, but it has not. They have suggested it may be on your end. `/cf block-break buildinggadgets:lasergunentity any true override`

Any further information I can give, let me know.

**Comment by irritatingness** [comment]
Adding to this, as I've found this bug as well!

It seems the block IDs are #3321, this can be found by selecting with world edit and running `//distr`. World edit also conveniently removes them a lot quicker, by creating a selection and running `//replace 3211 air`

Though would love to see some resolution to this!

**Comment by MajorTuvok** [comment]
as block id's are only valid in a certain instance (your id's would only help someone with the exact same setup...), do you know their registrynames?

**Comment by irritatingness** [comment]
Ah, sorry about that. Still new to the new IDs and forge as a whole.

Anyway, from what I can tell the block is buildinggadgets:effectblock. If that's not what you're looking for I can try some other things, let me know :)

**Comment by MajorTuvok** [comment]
Thanks... Yep, that is what I was looking for

**Comment by Iomega0318** [comment]
This also happens when using the Destruction Gadget.
![image](https://user-images.githubusercontent.com/5641516/53307255-c3354500-3853-11e9-864b-1a0dcdd2b635.png)

**Comment by hnOsmium0001** [comment]
Also I'm confused why does Dire chose to use a bedrock-like block to block access to the position, but using an entity to add fancy effects instead of making a TESR for the effect block.
In most cases entities cause more lag than tile entities.

**Comment by MajorTuvok** [comment]
I have absolutly no clue, though there might even be a reason behind that...

**Comment by D33pfield** [comment]
I am getting the same issues. It's happening with with the exchanging gadget on a area any larger than 1. It will happen quite often. The blocks left behind are breakable, but take a long time. 
![image](https://user-images.githubusercontent.com/14086090/53874265-aa513000-3fc7-11e9-95d7-59b651a3f89b.png)

**Comment by MajorTuvok** [comment]
How is it possible that the exchanging Gadge leaves blocks behind, as you just exchanged blocks with some other Blocks? Or does it fail to exchange the blocks and then leave ghost blocks behind?

**Comment by D33pfield** [comment]
> 
> 
> How is it possible that the exchanging Gadge leaves blocks behind, as you just exchanged blocks with some other Blocks? Or does it fail to exchange blocks and then leave ghost blocks behind?

It seems that in the process of swapping out the block a placeholder is used until the correct block is in place. Im guessing that placeholder is "(Unused) Effect Block" and sometimes it just never finishes the process and leaves this behind.

**Comment by MajorTuvok** [comment]
Yes EffectBlock is used as a placeholder..
So what I was asking was, you tried to exchange things and the exchanger was able to remove the blocks but the effect block, was unable to place the result block, right?

I sadly don't know how to solve that without quite extensive debugging though...

**Comment by MichaelHillcox** [comment]
Closing as caused due to incompatability of unknown origins. A partial solution might be to simply remove the entities through a config to stop this happening but as this is super low priority I'm going to close the issue as it's not become stale.

**Comment by shinyafro** [comment]
Try this command and tell me if it works
/cf block-break buildinggadgets:effectblock true override

it should allow everything to break that block, i tested it and it seems to work on my SF4 server for now.

**Comment by MichaelHillcox** [comment]
Which mod does this solve the issue for? which is /cf for? I'd like to update our readme to help people with this in the future 👍

**Comment by shinyafro** [comment]
Grief prevention, but i'd like to confirm with others if it works or not before claiming it as a fix tbh lol

**Comment by MichaelHillcox** [comment]
Keep us posted 👍 @MstrTaffy @irritatingness @D33pfield if any of you could confirm that this solves this issue that would be great.

**Comment by misako227** [comment]
> Try this command and tell me if it works
> /cf block-break buildinggadgets:effectblock true override
> 
> it should allow everything to break that block, i tested it and it seems to work on my SF4 server for now.
> drop it in the wilderness or they type of claim u want to set it as an override .

The test works, thanks

**Comment by zediious** [comment]
> 
> 
> Try this command and tell me if it works
> /cf block-break buildinggadgets:effectblock true override
> 
> it should allow everything to break that block, i tested it and it seems to work on my SF4 server for now.
> drop it in the wilderness or they type of claim u want to set it as an override .

For anyone coming from google, this flag fixes the problem.
