### ISSUE TITLE
[Feature Request] Building Steps downwards

### ISSUE THREAD

**Issue by WORMSS** [Direwolf20-MC/BuildingGadgets#24]
I was on a high ledge and wanted to go down to the floor.. Sadly the "stairs mode" didn't fulfil this feature.. 

I am not sure if you need a "stairs down" in addition to the existing "stairs up" feature. 

Building Gadgets v1.1.2
Minecraft: 1.12.2
Fordge: 14.23.4.2705

![image](https://user-images.githubusercontent.com/1384537/42843049-e67ea2be-8a06-11e8-91c1-850ba0b50f2e.png)

- Colin

**Comment by MajorTuvok** [comment]
Doesn't it depend on the Block face whether he builds up or down?

**Comment by WORMSS** [comment]
In this position, I cannot build down. Maybe in the screen shot I should have taken a step back, but as you can see, there is a single block in front of me. If I select the top side of this block with the current "stairs" mode, I build upwards. I cannot select the bottom without being below it. 

In the screen shot you can see that I am pointing towards a distant "top facing" block. I would either need this to built towards me, (since it's considerably below my feet), or the top block face on the level I am standing on, to build downwards by `range` distance. I have no idea what building on the "bottom" of the block would do in this separate `down` mode.

**Comment by Direwolf20-MC** [comment]
I need to rethink the stairs mode. They currently build 'down to you' or 'up from you' which is realistically the same thing.

**Comment by Direwolf20-MC** [comment]
Changed stairs mode slightly.

https://github.com/Direwolf20-MC/BuildingGadgets/commit/942734417722532292c42ec2ff501b5feb9cc835
