### ISSUE TITLE
Allow Placing on Liquid's

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#243]
As per rquest of the Discord chat: Allow placing on Liquid's. Aka, allow the Building/Exchanging Gadget to build directly on liquid's like water. Should be toggelable similiar to the connected Surface mode.

3 states were suggested:
- ignored = the current way of doing it
- inLiquid = replace the topmost liquid block 
- onLiquid = treat Liquids as solid blocks, aka place on top of them (building/copy-paste only)

**Comment by MajorTuvok** [comment]
Unassigning me, as @SturdyFool10 is implementing this

**Comment by MajorTuvok** [comment]
This is a pending releasw not?

**Comment by Phylogeny** [comment]
Implemented in v2.6.7
