### ISSUE TITLE
Gadget settings gui

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#244]
With an increasing number of features, it get's less easy to keep track of what the Gadgets are capable of and how to toggle them. The current approach of adding buttons to the RadialMenu, works well, but if we continue adding mode features, then it might get overpopulated. Therefore an extra Settings Gui (toggeled by it's own button) may be useful.

Should we add this only in 1.13?

**Comment by hnOsmium0001** [comment]
Are we talking about per-gadget features or cross-level features?  
I think common features (such as fuzzy, range) should be kept in the radial menu and others like ability to replace fluids, connected surface should be in a separate GUI.

**Comment by Phylogeny** [comment]
I'm leaning towards doing what Algo does in C&B; Putting all non-radial controls in the same screen as the radial wheel by:
1. Only rendering a slice's name string when it's hovered.
2. Making them buttons with icons that also render name strings when hovered.

**Comment by MajorTuvok** [comment]
Could you maybe put an image of how it might look here, as I don't like what I think it looks like, but I also think that I I can't imagine it properly...

**Comment by MajorTuvok** [comment]
Grr, third time I accedently i hit the close and comment instead of comment on my phone! Why are these 2 buttons Next to each other?!?

**Comment by Phylogeny** [comment]
Here's how it looks now:
![](https://i.postimg.cc/1XFJYHSz/radial-menu-old.png)
Here's a rough idea of how it could look:
![](https://i.postimg.cc/FFkWR9SQ/radial-menu-new.png)
Here's how Chiseles & Bits looks:
![](https://i.postimg.cc/G2VXQfZN/radial-menu-c-b.png)

**Comment by MajorTuvok** [comment]
Ahh, okey... And ghen once one mouses over a specific mode it displays the name right?

That sounds nice, we could alao very easily add <- and -> buttons for more pages...

**Comment by Phylogeny** [comment]
Right, they would all have hover text. And there could be buttons to navigate to other pages, if need be, but there should be plenty of room as-is.

**Comment by MichaelHillcox** [comment]
I think we could scale the gadget down a bit in the middle and maybe the whole selector wheel as a whole as it is a bit big :P

**Comment by MajorTuvok** [comment]
We also need to take MC's Scaled Resolution into account... But In my opinion this size looks actually pretty nice - I'm of the opposite opinion, that Chisels one is too small

**Comment by MichaelHillcox** [comment]
I was thinking a middle point between the too :)

**Comment by Phylogeny** [comment]
Yes, if it were slightly smaller, there would be room for controls on the bottom as well as the sides and top. Then it would be very likely that everything would fit on the screen, even if many more controls were added in the future.

**Comment by MajorTuvok** [comment]
Thing is, I'm not so sure whether we truly want all the controls to be on the same screen, as it might get overpopulated and therefore difficult to read...

**Comment by Phylogeny** [comment]
Having everything on the same screen is significantly more convenient. And it helps that the controls are icons, rather than text. In any case, it's always possible to add a config option(s) for whether given controls are in the radial menu, or on a separate page, if things ever get that crowded.

**Comment by Phylogeny** [comment]
Added in 9ea0f4804687f23c00f641a79a133ebc487ae048.

**Comment by Phylogeny** [comment]
Implemented in v2.6.7
