### ISSUE TITLE
Allow Template's to switch Blocks

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#248]
Someone on Discord asked about how to swap Blocks in some Template... I told him that as for now, he needs to modify the Template _'json'_, but I think it would be nice If we added doing that as a feature to the TemplateManager. 
This should wait for the API to be created though (putting this out here, before someone starts implementing this...).

**Comment by MichaelHillcox** [comment]
How do you foresee a feature like this being implemented?

**Comment by MajorTuvok** [comment]
Well I'm propably the main Copy-Paste API designer and what I currently have in mind, would just result in an internal mapping being changed. The most difficult part will propably be the GUI (I guess), as that doesn't really fit into the Template Manager and might need another screen or even an additional block.

**Comment by MichaelHillcox** [comment]
Additional block me thinks :P

**Comment by hnOsmium0001** [comment]
Do we want support different formats? Like vanilla's structure block, Sponge Schemetic format?
Note that the 32*32*32 limit is only for structure blocks, the format itself and related utility class (serializing and deserializing) doesn't have that limit

**Comment by SturdyFool10** [comment]
Another potentially major issue with the copy-paste is that since we’re going to be moving to 1.13 with a lot of things to do with liquids and partial blocks(slabs, stairs, hoppers even, etc) are we going to support the liquid logged blocks(not sure if water is hard coded as the only thing that can do this)

**Comment by MajorTuvok** [comment]
As you might have noticed with the schematic issue, we will be supporting at least the schematic format... Supporting vanilla structure blocks might be nice too (and propably easy to implement, as a vanilla should already have a parser for that - we'd only need a bridge between the 2)
