### ISSUE TITLE
Allow ConstructionPaste to be crafted with less expensive Items+Automation

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#249]
As asked for in [Dire's survey](https://twitter.com/Direwolf20/status/1099463285060063232) people are quite often not using ConstructionPaste as it is to expensive in comparision to crafting the Materials (or cheating them in...). Also the lack of possible automation makes this an even greater disadvantage.

We might therefore consider making ConstructionPaste cheaper and to allow for Automation like it is apparently possible for mc concrete in Thermal (didn't know that was possible until I saw that comment XD). Any thoughts @Phylogeny, @MichaelHillcox (@)Direwolf20-MC ?

**Comment by MichaelHillcox** [comment]
Hmm, maybe a compacting kinda block could be used for automation as well as making the recepie a little cheaper? I don't consider the placing in water to be a bad thing but adding an automatic process would likely be good :)

**Comment by Phylogeny** [comment]
Implemented in v2.6.7
