### ISSUE TITLE
AE2 Remote Inventory Support

### ISSUE THREAD

**Issue by Nerdpie** [Direwolf20-MC/BuildingGadgets#250]
Requested by a viewer in stream: the ability to connect to AE2.  Not sure what functionality is desired, just opening an issue for tracking.  @Phylogeny

![image](https://user-images.githubusercontent.com/11985331/53308702-6183d380-3871-11e9-8fb4-e86559ae3f98.png)

**Comment by MichaelHillcox** [comment]
Well we support Refined storage so we might as well add AE2 👍

**Comment by Nerdpie** [comment]
I had shared this link on the Direcord20, but I'll put it here as well so that it's (theoretically) easier to reference for this enhancement: https://github.com/p455w0rd/AE2WirelessTerminalLibrary

My thought was that p455w0rd's AE2 WT Lib may be a handy reference at the least, since it is usually preferable to avoid adding dependencies where practical.

**Comment by Phylogeny** [comment]
Added in v2.6.6
