### ISSUE TITLE
[Feature Request] Provide pre-made in modpacks

### ISSUE THREAD

**Issue by SeriousCreeper** [Direwolf20-MC/BuildingGadgets#255]
Heya,

as far as i know, right now you have to copy and paste the building string in order to import a building into your world. As a pack maker, it'd be pretty useful to provide pre-made templates, so that the user could craft the template item and load it up directly in game. This would be useful for multiblock structure templates, but also for custom made buildings and such to provide with the pack. 

Would something like this be possible? 

Cheers,
SC

**Comment by MajorTuvok** [comment]
By the way I currently intend to design the Copy-Paste API, Templates would become Data packs in 1.13... So yes...

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
