### ISSUE TITLE
Gadget Does not Correctly Recognize Resources in Player Inventory in Survival Mode

### ISSUE THREAD

**Issue by hnOsmium0001** [Direwolf20-MC/BuildingGadgets#256]
+ Forge: 14.23.5.2768
+ Building Gadgets: master 8cbecd2 (Incoming 2.6.7)

Select a target, and enter a random mode, you will find that the rendering appears to be red and you cannot build with it.

![2019-03-03_22 29 19](https://user-images.githubusercontent.com/36975818/53714722-4e8a7980-3e04-11e9-9522-9c71c9dcc9a3.png)

---

This is tested in the develop environment, I will try to provide example in actual environment later.

**Comment by Phylogeny** [comment]
You can't use gadgets in survival mode when they are set to use energy, and they have no energy. Notice the empty bar.
