### ISSUE TITLE
Horizontal/Vertical Flipping/Mirroring for Copy/Past Gadget

### ISSUE THREAD

**Issue by jtgraphic** [Direwolf20-MC/BuildingGadgets#258]
It would be able to flip/mirror the template in a copy/paste tool for doing symmetrical builds.

**Comment by Phylogeny** [comment]
Pastes can already be mirrored horizontally, as per af204debcd42f25dd250be0fbecc534695388111, but vertical rotation/mirroring should be considered.

**Comment by jtgraphic** [comment]
Oh thanks. Clearly I just need to update my version.

**Comment by Phylogeny** [comment]
That feature is currently unreleased, actually, but it will be soon.

**Comment by Phylogeny** [comment]
Horizontal mirroring added in v2.6.7 (vertical rotation/mirroring has not yet been fully considered)

**Comment by MajorTuvok** [comment]
Duplicate of #305
