### ISSUE TITLE
invalid json failed copy paste

### ISSUE THREAD

**Issue by BlackHoleTON618** [Direwolf20-MC/BuildingGadgets#259]
minecraft 1.12.2
forge 14.23.5.2781
building gadgets ver. 2.6.4
i get error failed paste invalid json when want to paste a pastebin website

**Comment by Phylogeny** [comment]
You have not followed the instructions in the issue template. Please edit your post to do so.

**Comment by BlackHoleTON618** [comment]
also pastebin is banned in my country is that the issue ? i have to use vpn for seeing pastebin website

**Comment by SturdyFool10** [comment]
Not as long as you can use the VPN I guess...

**Comment by Phylogeny** [comment]
Links are not supported. As of v2.6.5, there is a specific message that displays when attempting to use a link, rather than raw text c508807db1b784358c4dd6077bce42d9564f8c5e.

**Comment by BlackHoleTON618** [comment]
So what should i do for having direwolf s house in his enigmatica 2 series

**Comment by Phylogeny** [comment]
Presumably, the link you are trying to use links to a page with data. Use the data.

**Comment by BlackHoleTON618** [comment]
how can i use the data

**Comment by MichaelHillcox** [comment]
Copy it....

**Comment by Phylogeny** [comment]
https://seniorplanet.org/how-do-i-copy-and-paste-on-my-computer/

**Comment by BlackHoleTON618** [comment]
OMG it worked so all i have to do is copying the raw data thank you guys im so happy thanks for help

**Comment by BlackHoleTON618** [comment]
now i cant put house because it says its too big
