### ISSUE TITLE
AREA is too max

### ISSUE THREAD

**Issue by BlackHoleTON618** [Direwolf20-MC/BuildingGadgets#260]
minecraft 1.12.2
forge 14.23.5.2781
building gadgets ver. 2.6.4

i learned how to use copy paste gadget with pastebin but it says area is too big
![2019-03-07_12 41 03](https://user-images.githubusercontent.com/45729798/53947305-30579e80-40ce-11e9-91f3-171f69944033.png)
![2019-03-07_12 41 18](https://user-images.githubusercontent.com/45729798/53947313-33528f00-40ce-11e9-86ea-b39e87bb2fff.png)

**Comment by MajorTuvok** [comment]
This is a user Error: the given message will only occur in Copy Mode. Switch to Paste mode to paste your Building.

Please read the Readme before posting anymore issues as it is obvious you have no idea what your doing.

**Comment by trevorjd** [comment]
With respect, I feel this is a poor UX choice. It would be better if the message was clarified and expanded to:

 "Selected area is too large to Copy (max 125x125x125). Right-click on air to clear selection.
   To paste a blueprint, change Copy/Paste gadget to Paste mode."

**Comment by MichaelHillcox** [comment]
Most of this is part of a my 1.12 re-work branch and most errors, guis and ‘odd’ functionality will be resolve / improved in the next release set. I appreciate what you’re say but I think the underlying issue is deeper down than a single word change.

**Comment by trevorjd** [comment]
Thanks for the quick reply. I have no idea about underlying technical problems as I'm a support tech, not a programmer. I'm simply approaching it from a UX perspective where the underlying rule is "humans are dumb and don't read manuals" :-)  A wording change is a quick band-aid that should be easy to tack onto the next update and may be beneficial for those that lack the inspiration to google the error message!

**Comment by MichaelHillcox** [comment]
I'll add it to my to-do if I need to push an update before the next big version update
