### ISSUE TITLE
Copied structures are too large to paste

### ISSUE THREAD

**Issue by MiningPickaxe** [Direwolf20-MC/BuildingGadgets#261]
Forge 14.23.5.2781
Building Gadgets 2.6.6
I can copy a large portion of my structure just fine, copy it to my clipboard, go to the server I want to place that structure in and it tells me "Paste is too large". I know there is a limit of ~32k Blocks or 125x125x125, you can't copy structures larger than this... but it seems like you also can't import structures that are below 32k and larger than a critical value. 
Here is a link to the part of the basement I wanted to paste: https://gist.githubusercontent.com/MiningPickaxe/eee7e0c9e5d2c6f683b87cd0a1717f7f/raw/853bbaac37239bd8f25bac04d2651f9eccb7c1a2/Basement%2520Part%25201.clipboard 

Apparently this got fixed in 2.6.1, see: https://github.com/Direwolf20-MC/BuildingGadgets/issues/205 
But still happens to me.

**Comment by MajorTuvok** [comment]
(Just to be precise, there's also an limit of 32kB json Tag size, which is what I introduced in #205 for copying to clibboard... I haven't checked, whether other checks are also missing on the copy-side of things.)

**Comment by MajorTuvok** [comment]
Could you send provide us your Log, as there are only 3 ways this Message might appear. 

1. The Template is [too large](https://github.com/Direwolf20-MC/BuildingGadgets/blob/1b2b3e8c012fa50bc23640f62fedba11481508ff/src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerCommands.java#L242) to allow it to be copied to Clibboard
2. [Some kind of Error occured](https://github.com/Direwolf20-MC/BuildingGadgets/blob/1b2b3e8c012fa50bc23640f62fedba11481508ff/src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerCommands.java#L246) when attempting to compress the Template to validate it's size before allowing it o be copied
3. The Paste [stream is too big](https://github.com/Direwolf20-MC/BuildingGadgets/blob/1b2b3e8c012fa50bc23640f62fedba11481508ff/src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerGUI.java#L317) when being pasted in 

In all 3 situations the exact same check is performed and I don't know how it could be possible that suddenly differ... The only way I see you being able to copy something to large out is when you copied it before 2.6.1... 
=> I have no clue why it happens to you after 2.6.1

**Comment by MajorTuvok** [comment]
The only thing I can think of, is that MC for some reason doesn't compress always to the same size...

**Comment by MiningPickaxe** [comment]
The Log of the Client or Server?

**Comment by MajorTuvok** [comment]
If possible both... Cause I really don't know where this might come from

**Comment by MiningPickaxe** [comment]
Client log: `[10:44:37] [Client thread/INFO]: [CHAT] ȣPaste is too large`
No log messages in the server latest.log or even debug.log.

**Comment by MiningPickaxe** [comment]
But you mentioned something about a 32kb compressed size limit... what compression algorithm does it use? Am I hitting that?

**Comment by MajorTuvok** [comment]
Standard mc compression and I don't know what Algorithm MC uses... Usually it hits this limit when the uncompressed json is above 200kB (might also be lower, I only noticed it at some point that 228kB is too much)

**Comment by MajorTuvok** [comment]
(When I meant to send us the Log, I meant putting it in here (for example via an gist) so that we can have a look at it... When you said no messages, I presume that this also means no exception, which implies that you are above the 32kB threshold... You should not have been able to copy it out if you are using 2.6.1 or above though... Which confuses me a lot)

**Comment by Phylogeny** [comment]
See `net.minecraft.nbt.CompressedStreamTools#writeCompressed`, if you're interested.

**Comment by MiningPickaxe** [comment]
The paste is 303kb raw so I guess that is the issue... Since the copy/paste gadget allows for such big structures, it would be nice if support for clipboard-copying/pasting those could be added... Is there a limit to splitting the packets? A higher limit would be very nice, the way it is right now I cannot even copy/paste a part of my base 5 blocks high...

About why I was still able to copy it: I might have updated the pack inbetween creating the copies and trying to paste them.

**Comment by MajorTuvok** [comment]
The latter is the reason for that then...

Sadly supporting that large Templates is not **that** easy, as we need to send it to the Server somehow, and MC imposes us with an 32kB C2S Packet size limit. We'd therefore need to split the Template up...
We are working on a writing a proper Template API for 1.13, which should be able to do this... We'll also try to backport at some point in the future, I don't know when that will be though.

As this was a user error then (too large Template), closing for now.

**Comment by MajorTuvok** [comment]
Sorry that I can't do more at the moment...
