### ISSUE TITLE
Move tutorial to Wiki instead of leaving them in README

### ISSUE THREAD

**Issue by hnOsmium0001** [Direwolf20-MC/BuildingGadgets#265]
Currently all description of sorts exist in `README.md`. They preferably should live in the "Wiki" section provided by Github.

First, Github Wiki allows a better page layout system instead of making people break their middle button every time.
Secondly, it would be people's first reaction to go to the wiki section instead of scroll down to the README.
Lastly, this way we can leave a link to the Wiki in the Curseforge page (and/or update the description please).

We still can leave a note to tell people to look at the Wiki section.

**Comment by Phylogeny** [comment]
There are already plans for better utilizing both the readme and the wiki.

**Comment by MichaelHillcox** [comment]
Done, check out the wiki, it's in it's baby stage but it'll grow with the mod 👍 I'll update the readme now
