### ISSUE TITLE
[suggestion] make building and exchanging gadgets able to use durability

### ISSUE THREAD

**Issue by Trinsdar** [Direwolf20-MC/BuildingGadgets#27]
since you're goig to make them able to require rf, why not also make them able to take damage? it would be an excellent balance in packs that don't have very many options for rf, such as the one I'm making.

**Comment by Direwolf20-MC** [comment]
Will Do, once I add RF functionality. I'll make it some kind of config option.

**Comment by Direwolf20-MC** [comment]
Complete:) v1.6.1
