### ISSUE TITLE
if possible add in a way to copy/paste redstone builds

### ISSUE THREAD

**Issue by CharCharthemonkey** [Direwolf20-MC/BuildingGadgets#271]
* A detailed explanation of the suggestion
as the title says please consider adding in a way to copy/paste redstone builds in survival please? now to clarify i dont mean the really intricate ones (unless its possible) i mean simple redstone builds for simple vanilla buildings of possible please
![2019-03-16_12 25 02](https://user-images.githubusercontent.com/30783285/54710860-9bfe2a80-4b16-11e9-8bf2-402cf5de23ce.png)
this is a simple redstone build and yes i know its not mine i coppied it from avomance on YT but this is just an example of the simple redstone builds i am suggesting please and thank you

**Comment by MajorTuvok** [comment]
If they are not copied then they are either to large to be copied or they are Tile Entities (I see a hopper over there!). Tile's will only be supported in 1.13 and backporting that is still not fully discussed. 

Closing this as it is not going to happen anytime soon.

**Comment by MajorTuvok** [comment]
Just rethinking: Are you saying, that the whole thing doesn't copy at all (Tile's should just be skipped), or as I understood it, that you are complaining about Tile's being skipped and it therefore no longer working after it was pasted...

**Comment by Phylogeny** [comment]
The `rejected` label has been changed to `rejected by Dire`. To be clear, this was not rejected by Dire.

**Comment by MajorTuvok** [comment]
Just to be clear: TileEntities have been rejected because of to much effort required to implement them. We are removing this label because it wasn't Dire who specifically rejected this issue.
=> This might still get an invalid or won't implement label.

**Comment by CharCharthemonkey** [comment]
mainly not complaining at all just asking if its possible cause building gadgets is freaking awesome and the fact that build took me over 5 hours to make and didnt wanna have to rebuild it again if that help

**Comment by MajorTuvok** [comment]
So did you to copy? And what were the errors then?

Could you please describe your issue in addition to what your trying to achieve?

**Comment by CharCharthemonkey** [comment]
basically it just said "unable to copy" and simply trying to scan/copy the building to be able to move it and replace it in another location

**Comment by MajorTuvok** [comment]
This message does not exist: please tell use the precise message.

Also I just verified in code, that the only way a copy is denied is, if it has too many blocks or is too large (which it tells you!). What is your Problem? And also before providing the message please ensure that you are running the latest version (2.6.7) so that I can find out whats your Problem - I'm getting more and more sure that this is an user error.

**Comment by CharCharthemonkey** [comment]
im on the latest version and literally all it said was "unable to copy" so idk honestly wat the error is and ive pretty much given up on making the suggestion since thats originally all it was intended to be so yea

**Comment by MajorTuvok** [comment]
In theory it should be able to do that, as long as you ignore the tiles. My Problem is I see this unable to copy nowhere in code, which confuses me a lot...
