### ISSUE TITLE
thermal expansion recipes not displayed in jei when BG is installed

### ISSUE THREAD

**Issue by Shandoo94** [Direwolf20-MC/BuildingGadgets#272]
* Forge version 
14.23.5.2815

* Building Gadgets version
2.6.7

**Description**
I leave an issue here, because I dont know which mod is responsible for the error.
If I have Building Gadgets installed in my personal modpack, the rechipes for all thermal expansion machines don't get displayed in jei anymore.
For original issue see CoFH/Feedback#1470

* How to reproduce the issue
1. Have TE and building gadgets installed
2. Change BasePower values for pulverizer in cofh/thermalexpansion/common.cfg
3. Recipes from Te should not be displayed in jei anymore

**Comment by MajorTuvok** [comment]
@Phylogeny might this be caused by the strange jei version conclicts with ae2 and mekanism?

**Comment by Saereth** [comment]
I believe this is due to a bad pulverizer recipe being added, see relevant issue here:
https://github.com/CoFH/Feedback/issues/1469

**Comment by Shandoo94** [comment]
Can confirm the issue is just with version 2.6.7 of BG. No error with jei in version 2.6.6 of BG.

**Comment by MajorTuvok** [comment]
Sorry I can't help much as @Phylogeny wrote that and I have no idea how the pulverizer recipes work...

**Comment by Phylogeny** [comment]
The breaking of JEI integration for machines with recipes registered with them that is less than thier base power level was a bug in Thermal Expansion. See the discussion in CoFH/Feedback#1469 for more information.

Raising the energy costs of the recipes to more reasonable values has circumvented the problem.

**Comment by Phylogeny** [comment]
Released in v2.6.8

**Comment by TheMilkman501sr** [comment]
I've ran into the issue of the Numismatic Dynamo from Thermal expansion not in the crafting bar and that prevents me from crafting the tier 5 jet pack from simple jet packs. You can see the item in JEI but you cant click it for crafting.  As far as I can see it's not something that is Augmented to the other dynamos. For 1.12.2

**Comment by MajorTuvok** [comment]
Are you sure that the recipe hasn't just been disabled by the modpack author? Aka can you reproduce this with just bg, thermal/cofh, jei?

And if so, please open a new issue.
