### ISSUE TITLE
Mirror/Rotate shows up for Building/Exchanging Gadget and does nothing

### ISSUE THREAD

**Issue by hnOsmium0001** [Direwolf20-MC/BuildingGadgets#274]
Mirror and Rotate buttons shows up in the radial menu of Building Gadget and Exchanging Gadget. At least this is what I observed, but I could be wrong.

Is this a TODO feature and intended or this is a bug? 

* Forge version: 14.23.5.2768
* Building Gadgets version: `master`, f2d362f

![2019-03-25_18 03 34](https://user-images.githubusercontent.com/36975818/54964125-79aa4980-4f28-11e9-86a8-3c458121120d.png)

**Comment by Phylogeny** [comment]
You didn't read the changelog for the latest (v2.6.8) release: https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/CHANGELOG.md

**Comment by hnOsmium0001** [comment]
Now I understand what they do after I looked it up in the code...
In my opinion, the changelog is not super clear about what it does: my first instinct is that the whole build rotates/mirrors around a center point. However, what they actually do is rotate the block state it self with `IBlockState#withRotation` and `IBlockState#withMirror`.

Consider

> * Building and Exchanging gadgets can now rotate/mirror their *target block state* (using either its new keybind, which is not set by default, or using the radial menu).
>   * For example, click Rotate when some stair is selected, it will change the orientation of the stairs, such as facing north to facing east.

instead of

> * Building and Exchanging gadgets can now rotate/mirror their *set blocks* (using > either its new keybind, which is not set by default, or using the radial menu).
