### ISSUE TITLE
Ability to exchange only blocks that has air on its opposing side

### ISSUE THREAD

**Issue by hnOsmium0001** [Direwolf20-MC/BuildingGadgets#275]
Many dedicated exchangers mod/Draconic Evolution exchanger has a function to only replace if the opposing block on the clicked side is air.
For example, when exchanging the floor of a cave, blocks behind the wall won't be replaced because there are no air block above them.

I suggest this modifier to be called "Visible Only".

**Comment by MajorTuvok** [comment]
This would then also need a mode for following the curves of such a cave - so an additional cave-mode?

(currently this would only be of very limited use, as all the modes are rectangular in some form and would not really be able to fill such a cave wall without quite a few clicks)

**Comment by hnOsmium0001** [comment]
I don't quite agree on the "Cave Mode" thing:
Surface Mode + Fuzzy + + Visible Only on floors, walls, and ceilings should be sufficient for what they need, and it's not that many clicks.

**Comment by MajorTuvok** [comment]
The main advantage would be exchanging surfaces which have uneven surfaces. Say you want to exchange a pyramid - you could just click the top most one and the outer blocks of the pyramid would be exchanged...

I agree that thid already possible though...

**Comment by MichaelHillcox** [comment]
I completely agree that this functionality should be added as some blocks are rare and you'd prefer them not to be under the wall you are trying to place them within.

Sure, you can argue that the range could be taken down but personally I believe this to be a long standing bug in the original functionality of the mod. This really should be an always on thing as I can't think of any instance where this isn't helpful. Its the one reason I tend to keep other building / exchanging tools in my packs. It's bloody annoying to think you've counted the right amount of blocks to have found you've lost 15% of them under walls.

**Comment by MichaelHillcox** [comment]
This is done now so closing (1.12.x and 1.14.x)
