### ISSUE TITLE
Change main branch to 1.13

### ISSUE THREAD

**Issue by hnOsmium0001** [Direwolf20-MC/BuildingGadgets#279]
As discussed before, 1.12 is discontinued and will not receive new features. I think we should consider make `1.13.x` the main branch instead, because there will be fewer and fewer activities on the old 1.12 (`master`) branch.

**Comment by MichaelHillcox** [comment]
This is I'm the plan already but we need to come to an agreement internally on when the final merge of 1.12 into 1.13 will be. Once this is decided will be changing the main branch

**Comment by MichaelHillcox** [comment]
This is in the internal todo, i feel like this doesn't need to be an issue so I'm closing.
