### ISSUE TITLE
[Bug] Weird Behavior With Doors

### ISSUE THREAD

**Issue by UnRealDinnerbone** [Direwolf20-MC/BuildingGadgets#28]
Doors behave weird when trying to build with them....
[Video](http://ss.unrealdinnerbone.x10.bz/2018-07-17_21-04-17.mp4)
 
I Think the best way to fix this would be just to add it to a black list of block that you can not build with

Mod Version: BuildingGadgets-1.1.3.jar

**Comment by Direwolf20-MC** [comment]
You are correct, theres really no (good) way to fix this, I tried. I'll black list them once I implement a blacklist :).

**Comment by Direwolf20-MC** [comment]
Added a blacklist :)
https://github.com/Direwolf20-MC/BuildingGadgets/commit/2281b940efbcf79a70f6756a466bd91e60a643bf
