### ISSUE TITLE
[Future Planning][1.13] Use vanilla structure block format instead of a custom one

### ISSUE THREAD

**Issue by hnOsmium0001** [Direwolf20-MC/BuildingGadgets#283]
I suggest to not use a custom serialization format, but use the existing vanilla Structure Block format, and write them in `<save>/strcutres/` instead of making it a "data pack" (`<save>/data/`).

**Comment by MajorTuvok** [comment]
The reason we are nor doing this, is that the vanilla structure format has some short-comings: most notably it is not under our cpntrol.
If we need to change it for whatever reason we cannot do that. Also it does not provide any abilitiy to give user more information about the Template (header).

Additionally we'd loose a lot of flexibility when saving it as it will always be confined to Vanillas format. Custom implementation (for example a script-Template or an RFTools-Builder-Shape implementation, could save (and more importantly sync over the network!) it very differently)

Your concern about putting it in the structure folder would most likely only make our lives more difficult. Loading from DataPacks would just be a matter of registering another loader - I'm pretty sure MC is a lot more hardcoded in case of vanilla structures (I have to admit I haven't looked at the latter, so correct me if I'm wrong)

**Comment by MajorTuvok** [comment]
Additionally this discussion does not belong in an issue, but either on Discord or if you want it to be public **in the corresponding PR** (#270).
Please don't spam unnecessary issues.
