### ISSUE TITLE
When using various gadgets on a server, fffff is spammed to the log file

### ISSUE THREAD

**Issue by darkphan** [Direwolf20-MC/BuildingGadgets#285]
Forge version: 14.23.5.2831
Building Gadgets version: BuildingGadgets-2.6.8

How to reproduce the issue: Use a gadget on a server and look at the log.

**Comment by MichaelHillcox** [comment]
Interesting, can we have a copy of the log file please? Feel free to remove any private information (IP's Etc) or just send a small section with the 'f' being spammed. If you'd prefer to email it than posting it publicly then you can send it to me@mikey.pro

**Comment by MajorTuvok** [comment]
I cannot reproduce this in dev enviorment: Building Gadget, Exchanging Gadget and Copy-Paste Gadget did not print a line whilst being used. I did test with a dedicated server...

Also I can see that you are running a very new Forge version, whilst we are compiling and testing against the recommended 14.23.5.2768 build.  Does this still exist for you in older Forge versions? Can you send us your log in some way?

**Comment by darkphan** [comment]
Here is a snippet of what happens: https://pste.me/#/x976p

We found this while helping darkosto with the Sky Factory 4 release. I can send a full log as well if needed.

**Comment by MajorTuvok** [comment]
The link results in not found...

**Comment by darkphan** [comment]
Oops, not sure what happened: https://pste.me/#/x976P

**Comment by MajorTuvok** [comment]
> [13:15:47] [Server thread/INFO] [gamestages]: Saved 17 stages for Blargerist.
This is not from Buildinggadgets - I presume it's gamestages who put the following fffff in the log...
Especially as there isn't even a regular logging prefix...

**Comment by MajorTuvok** [comment]
Could you post a bit larger potion if you are sure it is not gamestages? (perhaps the parts between player joined world and saving it)

**Comment by darkphan** [comment]
It seems to log it to the server console but not the log file. The snippet I pasted was from the console not pulled from the log file.

**Comment by MajorTuvok** [comment]
Wtf. - Someone is fiddeling with the logging configurations then and I'm 99,99999....% sure that this isn't BuildingGadgets by mistake.
Could you mabe copy it from the console then?

**Comment by darkphan** [comment]
So if I just load up BG and JEI, it does not happen on the console. I guess we can close this. If I do figure out things and remember I will provide feedback as to what caused it do what it is doing.

**Comment by bk5115545** [comment]
Just a heads up, I also have the `fffff` spam in the console anytime someone uses a building gadget and I found that [this old code](https://github.com/Direwolf20-MC/BuildingGadgets/commit/d9c0314aaeacb948a33f50b8d656b5a491a4766f#diff-c17f82d0fcfda4804198d30ed682d01bL278) is most likely the culprit.

Is there a version of BuildingGadgets with this code published in CurseForge?  
I'm not sure how to check or I would do it myself.
