### ISSUE TITLE
Crash when using building gadget and placing quark candles

### ISSUE THREAD

**Issue by choekstr** [Direwolf20-MC/BuildingGadgets#290]
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
* 2808
* 2.6.8
* java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class vazkii.quark.decoration.block.BlockCandle$Variants, values=[CANDLE_WHITE, CANDLE_ORANGE, CANDLE_MAGENTA, CANDLE_LIGHT_BLUE, CANDLE_YELLOW, CANDLE_LIME, CANDLE_PINK, CANDLE_GRAY, CANDLE_SILVER, CANDLE_CYAN, CANDLE_PURPLE, CANDLE_BLUE, CANDLE_BROWN, CANDLE_GREEN, CANDLE_RED, CANDLE_BLACK]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

* Shift Right click on quark tallow candle with building gadget
* A screenshot: NA

**Comment by MichaelHillcox** [comment]
Please pastebin a full crash log

**Comment by choekstr** [comment]
https://pastebin.com/V45wqC5Y

**Comment by MichaelHillcox** [comment]
This may be on us, I'm working on cleaning up all this code and should hopefully fix it in the mean time.

**Comment by MichaelHillcox** [comment]
I've opened an issue with Quark to try and figure out what's going on here.

**Comment by choekstr** [comment]
one more tidbit of info: when I restarted and switched back to the building gadget with it already programmed to use that block, it crashed the client again, same error.  So just having Shift right click'd and selected crashes.  I threw away the building gadget and made a new one and it was fine.

**Comment by MichaelHillcox** [comment]
Yeah, the render will try and get the block again and will once again crash :(

**Comment by MichaelHillcox** [comment]
As I'm not getting anywhere with our codebase and I'm not having any response on https://github.com/Vazkii/AutoRegLib/issues/30. I'm going to close this issue as it looks like an oversight on Vazkii's side as nothing would / should be causing an issue here.
