### ISSUE TITLE
Crash when equipping Building Gadget with F7 light levels active

### ISSUE THREAD

**Issue by TomArnd** [Direwolf20-MC/BuildingGadgets#291]
My instance of the latest version of Enigmatica 2 (not Expert) crashed when I put my Building Gadget in my hand with the F7 light level visibility active, I think the interaction between the two mods might be at fault. Crash report included.

[crash-2019-04-24_20.19.33-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3123375/crash-2019-04-24_20.19.33-client.txt)

**Comment by MichaelHillcox** [comment]
Do you have a COFH satchel on?

**Comment by MajorTuvok** [comment]
Something destroyed the whole Formatting... :(
I can barely read that crash log

**Comment by MichaelHillcox** [comment]
Stop opening it with notepad then :P Works fine in viscose

**Comment by MajorTuvok** [comment]
-_- - Let's see whether notepad++ likes it

**Comment by MichaelHillcox** [comment]
Whoops

**Comment by MajorTuvok** [comment]
Also I see 2 things in there, which mess with loading (FMLLoadingPlugin and PhosphorLoadingPlugin) as well as a ton of coremods

**Comment by MichaelHillcox** [comment]
Their is also a mod called "Cyclic Extended inv" or an item. Who knows, and it seems to be causing a lot of issue but I still can't be sure. I think my idea of a try catch around out getSlot might be the best fix. Because this is a complete incompatibility issue that I can not track down for the life of me.

**Comment by MajorTuvok** [comment]
I gave it the duplicate label, because it has the same origin the others have - though in a different situation... yet again..

**Comment by TomArnd** [comment]
After further experimentation, this might not be Building Gadget's fault, and it probably has nothing to do with the light level overlay. I had the same crash without light levels on and I also crashed when I put a builders wand in my hand as well. I do have a Thermal satchel but it's just on my hotbar.

**Comment by MajorTuvok** [comment]
... It's kind of not funny how we hear that again and again and still don't know what mod is causing that...

**Comment by TomArnd** [comment]
Have there been a lot of people reporting the same issue? I'm brand new to this GitHub thing, i don't really how this works

**Comment by MajorTuvok** [comment]
Yep: #289 , #280... #287 and #288 have a different reason, but are as mysterious as this one

**Comment by TomArnd** [comment]
Oh I see. Weird stuff, I hope you're able to figure it out. Tell me if I can do something to help.

**Comment by MichaelHillcox** [comment]
We just need to find the mod messing with a native Forge feature / Mc feature

**Comment by MichaelHillcox** [comment]
Please see this comment to understand why this has been closed https://github.com/Direwolf20-MC/BuildingGadgets/issues/289#issuecomment-487381968 

Relates to #289

**Comment by MichaelHillcox** [comment]
Please find attached a link to a possible mod that may have been causing this crash
#280 (comment)
