### ISSUE TITLE
Blacklist is ignored

### ISSUE THREAD

**Issue by pyure** [Direwolf20-MC/BuildingGadgets#292]
* forge-14.23.5.2836
* BuildingGadgets-2.6.8.jar

Grats on the mod Dire. 

I cannot seem to get the configurable blacklist to be respected.  I've tested it with vanilla blocks such as vanilla redstone, and I can still use the Building and Destruction gadgets on those blocks.

```
    "blacklist settings" {
        # All Blocks added to this will be treated similar to TileEntities. Not at all.
        # Notice that you can use Regular Expressions as defined by Java Patterns to express more complex name combinations.
        # Use for example "awfulmod:.*" to blacklist all awfulmod Blocks.
        S:"Blacklisted Blocks" <
            minecraft:redstone_ore
         >
    }
```

Is there an override, config or alternative syntax I'm missing?  

**Disclaimer**: I have nothing against redstone ore.

**Comment by MichaelHillcox** [comment]
Lmao `Disclaimer: I have nothing against redstone ore.` that's just great but that's for the report. I'll see if I can replicate it.

**Comment by MajorTuvok** [comment]
This blacklist was only meant for Building, Exchanging and Copy-Paste Gadgets.

The destruction Gadget does not have such a blacklist to prevent farming blocks...

**Comment by MichaelHillcox** [comment]
( this is why I should keep up to date ) 

Building Gadget should work though @MajorTuvok

**Comment by MajorTuvok** [comment]
It should... What happened there?!? -_-

**Comment by MichaelHillcox** [comment]
Then that's the issue at hand as he's saying that it's not working. I'll look into it :)

**Comment by MichaelHillcox** [comment]
Alright, I've had a look into this and can't seem to reproduce this issue. Make sure you've got the correct block names. If you're still having this issue then please reopen this issue with more details @pyure
