### ISSUE TITLE
[Suggestion] Silk Touch Exchanging Gadget

### ISSUE THREAD

**Issue by Dimentive** [Direwolf20-MC/BuildingGadgets#295]
Could a Silk Touch upgrade to the exchanging gadget or a separate Silk Touch version of the gadget possibly be added? That’d be fantastic! It would be great for when you want to exchange a large area and get the smooth stone and ores rather than cobblestone and ingots.

**Comment by MajorTuvok** [comment]
It should be enchantable with silk touch, if not then that's an oversight...

**Comment by MajorTuvok** [comment]
(Fortune too in my opinion)

**Comment by MichaelHillcox** [comment]
Yeah, this is already implemented :P You can do it with using an anvil with and a silk touch book 👍

**Comment by Dimentive** [comment]
Oh, that’s awesome! Does that work with Fortune, Unbreaking, and Mending too?

**Comment by MichaelHillcox** [comment]
Just silk touch thus far but for tools that aren't using RF / FE it might be an idea to add mending. I'll ask the team.
