### ISSUE TITLE
[Request] Support for Black hole talisman from Botania and the /dank/null 

### ISSUE THREAD

**Issue by Hund** [Direwolf20-MC/BuildingGadgets#30]
It would be neat if there was support for the Black hole talisman from Botania and the /dank/null. :)

**Comment by Direwolf20-MC** [comment]
On the todo list :).

**Comment by Hund** [comment]
I just updated to version 1.3.0. Is there something I need to do to get it to work with the Black hole talisman?

**Comment by Hund** [comment]
It would be nice if this bug could be confirmed so I now that you've aware of it. :)

**Comment by Direwolf20-MC** [comment]
I've added support for forge's built in inventory containers, which a lot of mods use, but some mods do things their own way. Unfortunately I'd have to add each individual mod's support in order for that to work. Sorry!

**Comment by Hund** [comment]
Oh, I see. So it's Vazkii I need to bug this about then? :P
