### ISSUE TITLE
Building with construction paste does not use other blocks afterwards

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#302]
Versions are unknown
A user reported this on Discord, but we should verify this first...

**Comment by hnOsmium0001** [comment]
> I linked my copy paste gadget to an interface of my AE system and it says i have most of the blocks needed, but when i paste it only uses up my construction paste (which is not enough) and then stops. [...]

**Comment by MichaelHillcox** [comment]
So it's not using his AE system?

**Comment by MichaelHillcox** [comment]
Can not reproduce.
