### ISSUE TITLE
Allow configurable behaviour, for paste vs block preference

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#303]
A user on Discord suggested to allow a config option for whether paste or blocks are used first by the copy paste Gadget.

I'm not sure whether we can allow configuring this client side only even it would be best to do that. A user might very well want to change this setting multiple times whilst being in Game.
(I think that the code for finding the Items to use runs Server side, so - _-)

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
