### ISSUE TITLE
Typo when pasting a link

### ISSUE THREAD

**Issue by aaronhowser1** [Direwolf20-MC/BuildingGadgets#304]
* Building Gadgets version
BuildingGadgets-2.6.8
* How to reproduce the issue
Paste a link instead of json data, and it'll say "Please copy the raw json data, instead of an Link"
* A screenshot, if applicable
![image](https://user-images.githubusercontent.com/15698722/57567765-c1374880-73a3-11e9-825f-241fd04df947.png)

**Comment by MajorTuvok** [comment]
Sorry, but whats the Problem here?!?

**Comment by aaronhowser1** [comment]
It should be "a link" instead of "an Link"

**Comment by MajorTuvok** [comment]
Ah, ok.

**Comment by MajorTuvok** [comment]
Thanks for reporting :)
