### ISSUE TITLE
At least 2 rotation axes for all Gadgets

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#305]
I'm pretty sure we currently don't support all rotations, but an user on Discord reminded me that rotating in an arbitary Direction would be really nice to have.

Therefore we should allow rotating along at least 2 axes, so that people can perform any kind of rotation they'd like to perform.

I already checked that 1.13 allows rotation of Blockstates in all Directions and I hope 1.12 would too - it should not be hard to implement.

**Comment by MajorTuvok** [comment]
Also I'd love this to be in 2.7.0

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534

**Comment by Mal0om** [comment]
Any feedback on this suggestion? This mod is lacking in being able to Mirror or Flip on the Gadgets. 

Thanks
