### ISSUE TITLE
Support for Ender Utilities' Handy Bag

### ISSUE THREAD

**Issue by valarnin** [Direwolf20-MC/BuildingGadgets#306]
Ender Utilities has a lovely item called the Handy Bag which acts as a modular extendable bag.

Would it be possible to add support for this bag?

I would assume the following basic logic would work:

- Call [static ItemHandyBag.getOpenableBag](https://github.com/maruohon/enderutilities/blob/master/src/main/java/fi/dy/masa/enderutilities/item/ItemHandyBag.java#L663) to get an ItemStack for a bag in the player's inventory.
- Cast to ItemModular
- Call [ItemModular.getSelectedModuleStack](https://github.com/maruohon/enderutilities/blob/master/src/main/java/fi/dy/masa/enderutilities/item/base/ItemModular.java#L43) to get the module
- Cast to ItemStackHandlerBasic
- Use the methods from [ItemStackHandlerBasic](https://github.com/maruohon/enderutilities/blob/master/src/main/java/fi/dy/masa/enderutilities/inventory/ItemStackHandlerBasic.java) to determine if the bag has the items needed, remove them, etc.

**Comment by MajorTuvok** [comment]
Is there a reason you know about, why they don't expose ItemHandler?

**Comment by MajorTuvok** [comment]
A note on your propsed way of retrieving it: this way we'd only get the first openable bag... We'd need to get all of them, especially for the copy-paste Gadget. Aka we'll just check for an openable bag whilst iterating over the Inventory ourselves (which is more efficient anyway)

**Comment by valarnin** [comment]
> Is there a reason you know about, why they don't expose the ItemHandler cap?

No clue. Maybe something to do with the way they handle the modules themselves, but I'm not really a mod dev.

> we'll just check for an openable bag whilst iterating over the Inventory ourselves

Sounds fine to me. I was just providing an example to make it easier to understand the code required, since I checked their source first to make sure it was possible. Technically you should be able to access all 4 modules for a given handy bag instead of just the active module as well if that were a path you wanted to go down. 

Realistically I'd write this myself and submit a PR but I've tried 3 times to get a working dev environment up for MC and failed each time. I can compile the mods but not debug, all attempts to launch MC from a dev environment fail and it's probably something with my setup (Gentoo linux).

**Comment by hnOsmium0001** [comment]
If you are using IntelliJ, here is the sequence that worked every time for me (Manjaro)
1. Open `build.gradle` using IDEA's `import project`
2. Open the `Gradle` tab, should be on the left tool bar
3. `forgegradle` > `setupDecompWorksapce`, wait
3. `forgegradle` > `genIntellijRuns`, wait
4. Import (refreshing button on Gradle tab`
5. `Minecraft Client` > Edit Configurations > set module to `BuildingGadgets.main`

**Comment by MajorTuvok** [comment]
This would be for 1.12,but the PR needs to be implemented for 1.13 first...

**Comment by hnOsmium0001** [comment]
How would you implement it if the mod don't even exist (yet)?

**Comment by MajorTuvok** [comment]
Ok, sorry...

**Comment by MajorTuvok** [comment]
I now I'm an idiot... :(

**Comment by MichaelHillcox** [comment]
Looking into this a bit, it would turn out that they do use IItemHandler but for some reason are using IItemHandlerModifiable which deters the use of said interface to mods. 

> /**
>   * Overrides the stack in the given slot. This method is used by the
>     * standard Forge helper methods and classes. It is not intended for
>     * general use by other mods, and the handler may throw an error if it
>     * is called unexpectedly.

Due to this reason, I'm going to close this and request you open an issue with the Ender Utils dev and request they follow the forge restrictions based on the class and move their systems over to IItemHandler. This will in turn allow the mod to work with ours.

**Comment by P3rf3ctXZer0** [comment]
Is it possible to add support for Project Storage? https://www.curseforge.com/minecraft/mc-mods/project-storage

**Comment by MajorTuvok** [comment]
Please open a new issue

**Comment by MichaelHillcox** [comment]
As we're coming to the final version of 1.12 I'm going to go ahead and close this issue. If the mod in question updates to 1.14 then please reopen the issue.
