### ISSUE TITLE
Paste structure in chunks, over several ticks

### ISSUE THREAD

**Issue by hnOsmium0001** [Direwolf20-MC/BuildingGadgets#307]
The current approach to pasting any structure is to spawn all build entities in one tick. However this causes a lot of lag, when both pasting and undoing.
I propose a way to gradually paste a structure larger than, say 4096 block, over several ticks, where in each tick we place down 512 blocks only.

**Comment by MajorTuvok** [comment]
The idea I was thinking about was to use a more variable approach. We divide the template in multiple chucks of a config determined max size according to the TenplateView's size estimate.

We'd then havs some general 'Ticking Executor' or something like that, taking some placement sequences and an estimated Size to run them. Note that the destruction Gadget would need to be interpreted as an enforcing PlacementSequence (of Air Blocks) as well.

Additionally we should try to allow for undo recording to happen at the same time, aka all it to happen not in one tick, which in large cases might very well take a lot of tps.

**Comment by MajorTuvok** [comment]
This can currently seen as a work in progress on the api branch and is going to come in once it get's merged. There are some issues with doing to many small placements resulting in mc being overwhelmed by Block updates, but we should be able to sort that out...
