### ISSUE TITLE
Corner selection mode for all gadgets except copypaste

### ISSUE THREAD

**Issue by Archilyte** [Direwolf20-MC/BuildingGadgets#308]
It would be cool if you could select corners a la RFTools builder for the construction, destruction and exchanging gadget. Construction & destruction is self explanatory, and for the exchanger, you could select the block you want to use, the block you want to replace, and the area, so that all block you chose that are in that area will get exchanged.

**Comment by MichaelHillcox** [comment]
I'd assume this is to avoid having to manual set a size each time you want to use the tools?

**Comment by MajorTuvok** [comment]
Problem is, that this would largely contradict the current design. The Gadgets are not meant to fill large areas.
In my opinion this would be rather suited for a shape-card to Template conversion.

**Comment by MajorTuvok** [comment]
It does match the destruction Gadget very well though.
