### ISSUE TITLE
bug report for inventory linking

### ISSUE THREAD

**Issue by mcintosh109** [Direwolf20-MC/BuildingGadgets#309]
Forge version - 14.23.5.2831
 Building Gadgets version -2.6.8

in the nether the linked inventory can be seen (the highlight)  after being liked to overworld 

location in nether -- https://imgur.com/a/FZ7Q1HN

Location in overworld and liked block/inventory -- https://imgur.com/a/oOAfwnj

build gadget is set to use cobblestone

can be replicated in sky factory 4

**Comment by MajorTuvok** [comment]
Ouch, thanks for the report

**Comment by MichaelHillcox** [comment]
Now that's interesting :)

**Comment by MajorTuvok** [comment]
I presume there's some kind of dimension check missing for the render?

**Comment by MichaelHillcox** [comment]
Most likely, I've not checked but that would be the most logical thing

**Comment by MichaelHillcox** [comment]
This has been fixed and will be released in version 2.7.0
