### ISSUE TITLE
Stairs don't rotate

### ISSUE THREAD

**Issue by thederpykrafter** [Direwolf20-MC/BuildingGadgets#31]
When using the building gadget to build in stairs mode the blocks place in the orientation of the original block used to choose what blocks are placed. And only works placing in the same direction of the original stairs block.

**Comment by thederpykrafter** [comment]
![15319579179671069720348](https://user-images.githubusercontent.com/25908683/42913672-25325920-8ac4-11e8-96a9-cfd21f728901.jpg)

**Comment by Direwolf20-MC** [comment]
Working as intended :).

**Comment by thederpykrafter** [comment]
It's a bit inconvenient to have to go back and place another stair block in the right direction select it with the building tool and then build the stairs(I know I'm a lazy builder) could you add a way to rotate the blocks before they are placed?

**Comment by Drullkus** [comment]
@Direwolf20-MC The Block class has a native `rotate()` method, you should check it out :)

**Comment by MajorTuvok** [comment]
I'd support mouse-wheel-rotation-support...

**Comment by Phylogeny** [comment]
Rotations/mirroring via keybind and radial menu implemented in d1de4638d6405fccf1492de8d658feb5b60067eb

**Comment by Phylogeny** [comment]
Released in v2.6.8
