### ISSUE TITLE
Fire correct PlaceEvent and BreakEvent when placing and breaking blocks

### ISSUE THREAD

**Issue by McJty** [Direwolf20-MC/BuildingGadgets#311]
It appears that the building and exchanging gadgets do not fire BreakEvent and PlaceEvent from Forge. Doing that would allow tools and protection mods to work properly.

Seems like the exchanging gadget does fire BreakEvent upon it's initial breaking but it doesn't fire PlaceEvent. Neither does the building gadget.

**Comment by McJty** [comment]
BTW, related to https://github.com/Direwolf20-MC/BuildingGadgets/issues/43 where it was apparently fixed for BreakEvent for the exchanging gadget

**Comment by MajorTuvok** [comment]
Ok, rhanks for the report

**Comment by MajorTuvok** [comment]
Interesting: I can't add it to both...

**Comment by McJty** [comment]
Why not? What do you mean exactly?

**Comment by MajorTuvok** [comment]
As you propably saw: If I try to add it to another milestone, github removes it from the previous one.

**Comment by McJty** [comment]
Just a question. Do you have a timing on this fix? Not having this ability kinda prevents me from working further on my big Ariente dungeon :-)

**Comment by MajorTuvok** [comment]
Sadly not. It depends on a) on our time to work on it and b) whether Dire or Phylogeny find Time to upload a new artifact. So it's very unpredictable - the **earliest** we might have a new version is in 2 weeks I'd say...
