### ISSUE TITLE
Feedback: Default Durability feels way too low.

### ISSUE THREAD

**Issue by katubug** [Direwolf20-MC/BuildingGadgets#313]
Hello! Firstly, thank you for this great mod and for the helpful videos and documentation.

I recognize that the initial vision for the mod was that the tools used energy and not durability, and that if you're configuring the tools at all, you may as well change their durability. That said, the default of 500 is far too low. Even tripling that is a little on the light side, in my opinion. Attempting to use the Copy-Paste Gadget to paste [this in](**url**) broke the gadget from full, and only partially pasted in the structure. Which wouldn't be so bad, except that when the gadget breaks, you can no longer use the undo function - so if you wanted to see how something looks, undo, and then reposition, you cannot.

Personally, I'll be bumping mine up to 5,000 per, in the hopes that that'll help. In any case, thank you very much for your time!

**Comment by MajorTuvok** [comment]
So I just went through the calculations:
Buildinggadget: 500000/50=10000 uses, has 500/1=500 with durability
Exchanger: 500000/100=5000 uses, has 500/2=250 with durability
Destruction: 1000000/200=5000 uses, has 500/4=125 with durability
CopPaste: 500000/50=10000 uses, has 500/1=500 with durability

=> I fully agree. We'll set the default values so that they are equal to the energy values.

**Comment by MajorTuvok** [comment]
As an FYI, we intended to remove them in 1.13 and instead provide a charging block. As a durability user what would you make of that? (So far you are the very first person, I hear of who uses durability)

**Comment by katubug** [comment]
Personally, I enjoy having the option of a building tool that doesn't require me to have a power gen setup (I'm not a tech person). I replaced Better Builder's wands with this and because that one is available so early-game, I wanted these to be, too.

Ultimately, if the decision is made to have them use energy only, then I respect that decision. I just prefer durability and enjoy having the option that fits my play style.

I would probably use the mod, regardless. Especially if you mean the gadgets wouldn't require a wireless power network to run, but ran on batteries, so to speak. I'd be fine with that.
