### ISSUE TITLE
[QUESTION] What is "[buildinggadgets]: Sending SyncedConfig to freshly" ?

### ISSUE THREAD

**Issue by wideblaze** [Direwolf20-MC/BuildingGadgets#315]
Why does my server show this as a user?

"[buildinggadgets]: Sending SyncedConfig to freshly"

http://prntscr.com/nyx41o

I'm running: BuildingGadgets-2.6.8

**Comment by MichaelHillcox** [comment]
Did this actually show on the clients screen?

**Comment by MajorTuvok** [comment]
This is a log message for debugging purposes, it does not hurt you.

**Comment by MajorTuvok** [comment]
For reference, it actually says `Sending SyncedConfig to freshly logged in Clients`...

**Comment by MajorTuvok** [comment]
I have to correct myself... You are seeing that as a user?!?

**Comment by MajorTuvok** [comment]
WTF?!?

**Comment by MajorTuvok** [comment]
I know for certain, that this is a Log.info message and has nothing to do with Players...

**Comment by MajorTuvok** [comment]
This is either some mod using logs to determine players, or some other thing determining players by parsing the log File. Whoever does that should not do that and is an idiot.

If you happen to find out who is being such an idiot, could you mention it, so that I can yell at that person?

**Comment by wideblaze** [comment]
I think the idiot is whoever made the server console web app for mcprohost. I assume it's parsing the log file for players.

thanks for the info!

**Comment by MajorTuvok** [comment]
You're welcome...
_(turing around and yelling: )_ 
**Shame on you mcprohost!**
