### ISSUE TITLE
Seared stone is invalid block

### ISSUE THREAD

**Issue by ecatherman** [Direwolf20-MC/BuildingGadgets#318]
* Forge version : 14.23.5.2836
* Building Gadgets version : 2.6.8
* Project Ozone 3 pack version :  3.0.40

I can guess that Seared stone is a tile entity (probably for the smeltery) but it doesn't really do anything.

![SearedStoneInvalid](https://user-images.githubusercontent.com/6530707/59227081-737c4e80-8ba2-11e9-936e-d5e2d55a8d7d.png)

**Comment by MajorTuvok** [comment]
If you know it's a TileEntity, why do you even open this issue for 1.12?

**Comment by MajorTuvok** [comment]
To make you feel a bit more comfortable, we are working on Tiles for 1.14

**Comment by ecatherman** [comment]
I am not sure it is. That is just a guess.

**Comment by MajorTuvok** [comment]
Ok, we'll verify that then. If it isn't then there's something wrong

**Comment by hnOsmium0001** [comment]
> I am not sure it is. That is just a guess.

A quick test would be try to use a piston on it.

**Comment by MichaelHillcox** [comment]
Or just press f3 haha

**Comment by MajorTuvok** [comment]
I always forget that's a thing

**Comment by ecatherman** [comment]
I am not sure what to look at in F3 debug screen, but a piston does move it.

**Comment by hnOsmium0001** [comment]
> I am not sure what to look at in F3 debug screen, but a piston does move it.

Almost forgot this: do you have Quark/Redstone++ installed and enabled (on by default) movable tile entities?
Quark supports movable tile entities by default, but some packs disable it because it causes crash on a lot of mods like RFTools.

**Comment by MichaelHillcox** [comment]
Screenshot f3 mode whilst look at the block :)

**Comment by ecatherman** [comment]
Quark is in the pack


![image](https://user-images.githubusercontent.com/6530707/59390690-06062480-8d40-11e9-9170-f3285deaa2ec.png)

**Comment by hnOsmium0001** [comment]
Why are we doing all this again?
Just do some quick lookup on Github and I found this: https://github.com/SlimeKnights/TinkersConstruct/blob/1.12/src/main/java/slimeknights/tconstruct/smeltery/block/BlockEnumSmeltery.java#L41-L45

Basically all seared components are tile entities. Including all variants of seared stone.

**Comment by MajorTuvok** [comment]
That would of course have been to easy... Because why would we do something that makes sense/is easy?
Well, I'm sorry then but it's invalid on intention.
