### ISSUE TITLE
Gadget's drop Items, when Dim with bound Inv is deleted

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#319]
A user reported this on Direcord:
- bound to a chest in an rftools dim
- delete said dim
- Gadget's will now drop Items instead of putting them into the player inventory
Notice that this happened on a dedicated Server - I don't know whether this can be reproduced using SP-mode. 

I presume he was using 2.6.8 but I didn't ask either.

**Comment by MajorTuvok** [comment]
I added the incompat label, because you normally don't create and then delete dimensions

**Comment by MichaelHillcox** [comment]
I'm not 100% sure on how worlds work but I've added in a check to ensure that the dimensions work actually exists before allowing a remoteInventory to continue to be linked to the players inventory. This should solve the issue. Please reopen if this continues after version 1.12.2-2.7.0 is released :)
