### ISSUE TITLE
Build to me is using gadgets range

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#325]

**Comment by MajorTuvok** [comment]
This is an easy fix: convert [this](https://github.com/Direwolf20-MC/BuildingGadgets/blob/8252103b0da12b9df4a015574fb7cab5f78892df/src/main/java/com/direwolf20/buildinggadgets/common/building/modes/BuildToMeMode.java#L29) to use the max range from the SyncedConfig instead of the Gadget's range

**Comment by MichaelHillcox** [comment]
Already done, this was for the changelog :P
