### ISSUE TITLE
Class Cast exception when opening material list 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Direwolf20-MC/BuildingGadgets#327]
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
* Forge version FML: MCP 9.42 Powered by Forge 14.23.5.2838 199
* Building Gadgets version BuildingGadgets-2.7.0.jar  
* *If the issue is a crash*; An external link to the crash report https://gist.github.com/P3rf3ctXZer0/66d01c9daadd8faed0733c43ba719ca9
* How to reproduce the issue Open material list
* A screenshot, if applicable

**Comment by P3rf3ctXZer0** [comment]
Why the hell does the template ask for forge version ... if people actually give you the crash log it is included.

**Comment by MajorTuvok** [comment]
Could you please provide the Informations instead of linking a gist

**Comment by MajorTuvok** [comment]
That might be true but you have to go through that crash log just to find it...
Furthermore I'd request the log, not only the crash log in order tk be able to see what you where doing

**Comment by P3rf3ctXZer0** [comment]
kay

**Comment by P3rf3ctXZer0** [comment]
[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3422179/latest.log)

**Comment by P3rf3ctXZer0** [comment]
I miss the days when it was right click left click ... this new system is very touchy.

**Comment by MajorTuvok** [comment]
I wonder how that happened: you were able to open the MaterialList, even though you had air in your hand (accorsing to the class cast exception)...

**Comment by P3rf3ctXZer0** [comment]
no it opens and crashes as in I never actually see the materials

**Comment by MajorTuvok** [comment]
Thanks for the log :). What do you mean with touchy?

**Comment by MajorTuvok** [comment]
It opens, yes... But according to the crash you opened it on an ItemStack with AIR as it's Item, which confuses me

**Comment by P3rf3ctXZer0** [comment]
You used to have 3 buttons - Anchor - Radial - and Distance.
The mode feels a way busier then before. It has 7 hotkeys and I cannot just look at blocks. Copy and and paste materials in my inventory.

Does the information "I shift left clicked a tinkers block" before this have any relevance?"

**Comment by P3rf3ctXZer0** [comment]
While holding building gadget?

**Comment by P3rf3ctXZer0** [comment]
I tried to build using the way I used to know.

**Comment by MajorTuvok** [comment]
Ok, I just found [something](https://github.com/Direwolf20-MC/BuildingGadgets/blob/f4a5871ce1f1f9b573492d1bcc191ad0fa884112/src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiProxy.java#L67) which should definitly not be like that: It checks for reference equality with `ItemStack#EMPTY`. Even though changing that to an `isEmpty()` check and validating `instanceof ITemplate` in this spot will fix this issue, it hints that at some point it is errornously called with illegal Data...

**Comment by MajorTuvok** [comment]
[This](https://github.com/Direwolf20-MC/BuildingGadgets/blob/f4a5871ce1f1f9b573492d1bcc191ad0fa884112/src/main/java/com/direwolf20/buildinggadgets/client/events/EventKeyInput.java#L59) should have the isEmpty check.

**Comment by MajorTuvok** [comment]
@P3rf3ctXZer0 am I correct that you attempted to open the MaterialList for something other then an `ITemplate` (Copy-Paste-Gadget or Template item)?

**Comment by MajorTuvok** [comment]
Add the oversight label, because this comes down to a missing `isEmpty()` check.

**Comment by P3rf3ctXZer0** [comment]
Yeah I tried opening it up while holding building gadget. I don't even what you are asking at this point - help item "Building gadget" and clicked open materials. I was trying to build a seared brick wall I held sneak and clicked a seared brick but it said "invalid stack isairempty" then I figured maybe I had to manually select the block and I clicked meterial list hotkey and bam crash! I hope this helps.

**Comment by P3rf3ctXZer0** [comment]
I had 128 seared bricks in my inventory too.

**Comment by P3rf3ctXZer0** [comment]
Tried this method and tutorial https://www.youtube.com/watch?v=JS1Xx_kwQQ0

**Comment by MajorTuvok** [comment]
The MaterialList is meant to show the Materials required to build a Template or something directly on the Copy/Paste. It does not work for the other Gadgets.
The materiallist hotkey doesn't select a block... Sadly the turotial you linked is badly outdated, I guess Dire is going to make one for 3.0.0 which is very similiar to 2.7.0

**Comment by P3rf3ctXZer0** [comment]
Well you can see why am I confused then?

**Comment by MajorTuvok** [comment]
Yep.

**Comment by MajorTuvok** [comment]
In order to select a block shift left or right click (I always mix the 2) a block.

**Comment by P3rf3ctXZer0** [comment]
I will wait till the version that does not crash me comes out ... I don't want my players complaining ... just let me know when that crash cannot happen anymore.

**Comment by MajorTuvok** [comment]
[Shift right click](https://github.com/Direwolf20-MC/BuildingGadgets/wiki/Building-Gadget) it is apperently. I linked you the wiki, even though it is quite incomplete, it says that :)

**Comment by P3rf3ctXZer0** [comment]
Something else that is relevant maybe is that server and client configs did not match.

**Comment by MajorTuvok** [comment]
That's not a Problem: as of 2.6.0 they are synced. The Server config overwrites the client config whilst being connected to said Server.

**Comment by MichaelHillcox** [comment]
So it needs a check? I'll have a look today. I'll fix it has push out a hotfix

**Comment by P3rf3ctXZer0** [comment]
mkay :D

**Comment by MichaelHillcox** [comment]
Updated and pending approval on curse forge. New version is 2.7.1
