### ISSUE TITLE
Bug 1.12.2 - Forge 14.23.5.2838 - BuildingGadgets-2.7.0 - Tinkers Seared Brick Is not a valid block?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Direwolf20-MC/BuildingGadgets#328]
![2019_07_23_09_03_38_Greenshot](https://user-images.githubusercontent.com/10351221/61718558-daa42b80-ad28-11e9-9f68-6b9b1227bf72.jpg)

Bug 1.12.2 - Forge 14.23.5.2838 - BuildingGadgets-2.7.0 - Tinkers Seared Brick Is not a valid block?

**Comment by MichaelHillcox** [comment]
All Tinkers blocks are TE apart from a few. Please search before posting issues as this has already been discussed.

**Comment by P3rf3ctXZer0** [comment]
What is is TE?

**Comment by MichaelHillcox** [comment]
TileEntitiy. As of mc1.12 our mod does not support any Tile Entities.

**Comment by P3rf3ctXZer0** [comment]
okay thank you :D
