### ISSUE TITLE
Support for Forge 1.12.2 Project Storage

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Direwolf20-MC/BuildingGadgets#331]
So this mode is called project storage and I have to say it is the best thing since toilet paper. It has two modes - survival where you can increase you inventory based on size upgrade items. I personally like unlimited space because you take no hit at all on performance and inventory management can be a pain. The reason I highly recommend support for this mod is the building gadgets could draw items from this vast pool of collected material and users could build massive structures quickly without dealing with inventory management. As a builder I would be eternally grateful. This mod is also 100 percent stable which for a mod this helpful is extremely rare.
 
https://www.curseforge.com/minecraft/mc-mods/project-storage

**Comment by P3rf3ctXZer0** [comment]
I actually don't know if it will be ported to 1.14.4 I will redact that statement for now.

**Comment by MajorTuvok** [comment]
I'm sorry, but we want to only support 1.12 with bug-fixes and focus on 1.14. If this mod exists in 1.14, feel free to reopen and change the title
