### ISSUE TITLE
[1.14.4] Construction Paste Recipe Serializer Breaks JEI

### ISSUE THREAD

**Issue by EmosewaPixel** [Direwolf20-MC/BuildingGadgets#333]
It's currently possible for certain implementations of crafting recipes serializers to break 1.14 JEI, such that it loads without errors, but no part of it shows up. The Construction Paste Recipe Serializer seems to be doing just that. I can't for sure say which part exactly is causing the issue. I'd suggest trying overriding getSerializer in the recipe class or making it not extend Shaped Recipe and copy everything over from it.

Forge version: 1.14.4 - 28.0.21
Building Gadgets version: 3.0.0
JEI version: 1.14.3-6.0.0.8 (it is compatible with 1.14.4)

**Comment by MichaelHillcox** [comment]
This would kinda infer that this is a JEI issue.

**Comment by MajorTuvok** [comment]
Not necessarily

**Comment by MichaelHillcox** [comment]
We'd need a crashlog or a normal log

**Comment by EmosewaPixel** [comment]
The fact it's fully breaking JEI is on JEI's side, but the fact it's causing the issue is on the mod's side.

**Comment by EmosewaPixel** [comment]
As mentioned, this issue gives no errors.

**Comment by MajorTuvok** [comment]
I'm currently trying to find out, what we are using that serializer for...

**Comment by MajorTuvok** [comment]
ok, so what we are using it for, is copying over paste that might have been present in the containers when upgrading them

**Comment by EmosewaPixel** [comment]
Ok, welp, this is awkward. It seems that something messed up with the Twitch launcher while I was going through all the mods in the pack checking what was causing the issue. It seems like at the end it isn't Building Gadgets' serializer causing the issue. Sorry for wasting your time.

**Comment by MajorTuvok** [comment]
Well I fixed it not returning the correct serializer anyway... Thanks for pointing that out @EmosewaPixel :)

**Comment by EmosewaPixel** [comment]
Ok, so, it turns outs it's a 3-way interaction. JEI only breaks when Building Gadgets is together with Fast Workbench. When it's JEI and only one of the 2 mods it doesn't happen. So, it must be some part of the recipe/serializer that Fast Workbench checks, but not JEI.

**Comment by EmosewaPixel** [comment]
Although it's possible setting the serializer fixed it, I'm going to re-open this until we're sure it did fix it.

**Comment by MajorTuvok** [comment]
Could you reference the related issues at jei and fast workbench?

**Comment by EmosewaPixel** [comment]
Well, I already made mezz aware of serializers possibly fully breaking JEI a few weeks ago (as I accidentally did that), but I will ask Shadows for what could possibly be causing the issue.

**Comment by MajorTuvok** [comment]
Thanks to shadows linking a forge issue, I noticed that I should have made that field an ObjectHolder, in order to allow replacement to happen...

**Comment by MajorTuvok** [comment]
We removed the serializer's - therefore this can no longer be an issue
