### ISSUE TITLE
Crash when looking at Xnet cable after selecting the cable with the building gadget

### ISSUE THREAD

**Issue by AdamEternal** [Direwolf20-MC/BuildingGadgets#334]
Forge version: forge-14.23.5.2838

Building Gadgets version: 2.7.1

External link to the crash report: https://pastebin.com/raw/9dU8XHfm

How to reproduce the issue: Hold a (charged?) building gadget. Shift-right-click an Xnet cable (connected to a powered Xnet network?).

Another note: I came to report a different bug, but it turns out that the modpack - SkyFactory 4 - didn't have a fully up-to-date version of Xnet or Building Gadgets. When I tried replicating that old bug with an up-to-date version of Building Gadgets (and Xnet, along with Cyclic for a creative battery and power cables and Chargers for its chargers to make my life easier), it was different.

In the old versions (Building Gadgets 2.6.8 and Xnet 1.7.6), it didn't crash. Rather, the issue I was looking at was that any Xnet cables that were placed using Building Gadgets didn't function.

I posted this issue to both Xnet and Building Gadgets' Github pages.

**Comment by MichaelHillcox** [comment]
https://github.com/McJtyMods/XNet/issues/360 (XNet issue)

I think this is likely on us but it's just as likely something is going wrong on their side. It looks like the render has been given an invalid state from the Xnet block.

**Comment by AdamEternal** [comment]
They were the connector cables.

**Comment by MichaelHillcox** [comment]
Not sure how to fix this, I'll talk to the team but it's missed the 2.7.4 release, I'll close for now and open back up when I come round to fix this again :+1:

**Comment by papadave66** [comment]
This also affected the client of mine . I am using 1.12.2 and BuildingGadgets-2.7.4 . And tring to fill network cable(default color) in server . and I can't enter the server even I remove the build tools in backpack.

**Comment by MajorTuvok** [comment]
Could you try with a 2.8.x version?

**Comment by MichaelHillcox** [comment]
I'm like 50% sure I wrapped this in a try catch so yeah, definitely try 2.8.1
