### ISSUE TITLE
ObjectHolder being applied after ColorHandler.Block event crashes game in some cases

### ISSUE THREAD

**Issue by Sunekaer** [Direwolf20-MC/BuildingGadgets#335]
* Forge version 1.14.4 28.0.24
* Building Gadgets version 3.0.0
* crash report https://paste.feed-the-beast.com/view/eaeb4d62
* How to reproduce the issue
Launch the game, doesn't happen every time.

**Comment by MajorTuvok** [comment]
I was about to update to Forge .24 - I guess I'll start experiencing it then -_-

**Comment by MajorTuvok** [comment]
Actually this is a Forge Bug: The line you are referencing can only throw a NPE if the event is null

**Comment by MajorTuvok** [comment]
What is kind of perculiar, is that this line references an ObjectHolder

**Comment by MajorTuvok** [comment]
So I tried starting the game 10 times in a row now and couldn't reproduce this crash. How often do you experience this? Does it even happen with only BuildingGadgets present?

**Comment by Sunekaer** [comment]
Current modlist: https://s1.sunekaer.com/files/modlist.html 
Happens like every 2second launch
ill test with only BuildingGadgets present?

**Comment by MajorTuvok** [comment]
I'd apreciate it, If you could test with only BuildingGadgets... I fail to reproduce this in dev... :(

**Comment by Sunekaer** [comment]
cant recreate with only BuildingGadgets, ill update the issue, when/if i find what mod causes it

**Comment by MajorTuvok** [comment]
Ok, thanks

**Comment by Sunekaer** [comment]
Torchmaster-2.0.0.3-alpha

**Comment by Sunekaer** [comment]
https://www.curseforge.com/minecraft/mc-mods/torchmaster/files/2751474
So if the issue is on your side or their idk

**Comment by MajorTuvok** [comment]
Errr... Ok... That's weird

**Comment by MajorTuvok** [comment]
Thanks

**Comment by Sunekaer** [comment]
Seems to be fixed by the new TorchMaster update

**Comment by MajorTuvok** [comment]
Ok, Thanks for the notice

**Comment by MajorTuvok** [comment]
I'll close it then
