### ISSUE TITLE
Server crash upon using Exchanging Gadget

### ISSUE THREAD

**Issue by GolldenFalcon** [Direwolf20-MC/BuildingGadgets#336]
* forge-1.14.4-28.0.21
* buildinggadgets-3.0.0
* https://pastebin.com/Phy17W0J
* Attempt to use the Exchanging Gadget to exchange blocks

**Comment by MichaelHillcox** [comment]
That's a fun one

**Comment by MajorTuvok** [comment]
I presume that swapping to loot_tables everywhere will fix that

**Comment by MajorTuvok** [comment]
You were running a dedicated Server, right?

**Comment by GolldenFalcon** [comment]
Yes, I'm running the server on my own PC.

**Comment by GolldenFalcon** [comment]
Updated client and server to forge-1.14.4-28.0.27 and the issue persists.

**Comment by MajorTuvok** [comment]
This is partially a Forge issue - The Method we are calling seemed to be safe to use until we replace it with LootContext's but apparently in 1.14.4 `Block#getItem` became ClientSide only...
