### ISSUE TITLE
Crash when deleting sand on the ground.

### ISSUE THREAD

**Issue by iansmith42** [Direwolf20-MC/BuildingGadgets#341]
forge-1.14.4-28.0.45
buildinggadgets-3.0.2

Repeatable crashing when trying to delete a block on the ground.  It does not crash when selecting a vertical surface or wall.  Running on single player mode.  Not sure if it's my specific settings, including them in a screenshot.

[crash-2019-08-09_08.20.33-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3486597/crash-2019-08-09_08.20.33-client.txt)

[crash-2019-08-09_08.54.10-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3486602/crash-2019-08-09_08.54.10-client.txt)

[crash-2019-08-09_09.33.51-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3486603/crash-2019-08-09_09.33.51-client.txt)

[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3486608/latest.log)

![2019-08-09_09 36 02](https://user-images.githubusercontent.com/44298052/62783151-cd59a180-ba89-11e9-92f1-32d75f60d36b.png)

**Comment by MajorTuvok** [comment]
Thanks for the Report, @MichaelHillcox already said that there are issues, if you spam the Destruction Gadget - might this be related?

**Comment by MichaelHillcox** [comment]
Somethings allowing null though, I'll have a look :D

**Comment by MajorTuvok** [comment]
It seems likely that the BlockData passed into initialiseData is null, as should be expected when destroying Blocks. But it saidly attempts to render this null Block.

**Comment by MajorTuvok** [comment]
Hmm, actually I think in this case we should just pass the current Block in case of destruction in there - this will also fail in case of the write and read Methods.

**Comment by MajorTuvok** [comment]
Definitly fixed in 3.1.0b/in-dev
