### ISSUE TITLE
NullPointerException on Initialization in 1.14.4

### ISSUE THREAD

**Issue by moomanfl** [Direwolf20-MC/BuildingGadgets#342]
I am having an issue with a NullPointerException causing a crash on game initialization. Building Gadgets is the only mod I have and the crash only occurs if it is in the mods folder. This was a fresh install of both Minecraft and Forge.

Minecraft 1.14.4
Forge 28.0.45
buildinggadgets-3.0.0.jar
Crash Log: [https://pastebin.com/qXT3LBek](url)
To reproduce, just place the mod in the mods folder and hit the play button.

**Comment by MajorTuvok** [comment]
Update to 3.0.2 first
