### ISSUE TITLE
Destruction Gadget in Connected Area mode clears at most one depth

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#344]
Dire reported this tonight on Discord - It works in normal mode, but for some reason connected area mode is active by default.

Used version: 2.7.2, I need to ask that...

**Comment by MajorTuvok** [comment]
I think the error [is here](https://github.com/Direwolf20-MC/BuildingGadgets/blob/f5893e70b4fc1368807eafa7ca9582b1214e556a/src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetDestruction.java#L272) I guess that just rewiriting this to 6 min/max variables will fix this.

Also I think the fuzzy Setting below is incorrect

**Comment by MichaelHillcox** [comment]
Spaghetti code everywhere. Should be a simple fix :)

**Comment by MajorTuvok** [comment]
Released in 2.7.3
