### ISSUE TITLE
Crash after deleting blocks with destruction gadget

### ISSUE THREAD

**Issue by ivohuisjes** [Direwolf20-MC/BuildingGadgets#345]
I installed the latest forge and latest buildinggadgets (no other mods) and deleted some blocks in my single player world

* Forge version: forge-1.14.4-28.0.45
* Building Gadgets version: buildinggadgets-3.0.2
* *If the issue is a crash*; An external link to the crash report: https://gist.github.com/ivohuisjes/5b658e41b57e8ccb0da71200329828d4
* How to reproduce the issue: delete some blocks
* A screenshot, if applicable n/a

**Comment by MajorTuvok** [comment]
This should have been closed already and is released
