### ISSUE TITLE
Another crash after deleting some netherrack

### ISSUE THREAD

**Issue by ivohuisjes** [Direwolf20-MC/BuildingGadgets#346]
I installed the latest forge and latest buildinggadgets (no other mods) and deleted some blocks in my single player world

* Forge version: forge-1.14.4-28.0.45
* Building Gadgets version: buildinggadgets-3.0.2
* *If the issue is a crash*; An external link to the crash report: https://gist.github.com/ivohuisjes/b9b52a2b866d8822acd4cb4b1b642f43
* How to reproduce the issue: delete some blocks with destruction gadget
* A screenshot, if applicable n/a

**Comment by ivohuisjes** [comment]
After this crash my world doesnt load anymore and get the crash:

java.lang.NullPointerException: Rendering Block Entity
	at com.direwolf20.buildinggadgets.client.renderer.EffectBlockTER.render(EffectBlockTER.java:44) ~[?:3.0.2] {}

**Comment by MajorTuvok** [comment]
Duplicate of #345

**Comment by MajorTuvok** [comment]
Why did you open this again?
