### ISSUE TITLE
[1.14.4] Crash on load after update to buildinggadgets-3.0.3.jar java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.builderWithExpectedSize

### ISSUE THREAD

**Issue by ProsperCraft** [Direwolf20-MC/BuildingGadgets#347]
* Forge version  28.0.55
* Building Gadgets version buildinggadgets-3.0.3
Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

![2019-08-21_07 12 00](https://user-images.githubusercontent.com/4427684/63435151-a719f700-c3e3-11e9-8523-890079f4ae6f.png)

Stacktrace-
https://gist.github.com/ProsperCraft/c82d51e8d40942537b7ccdb26b5320f4

Latest log-
[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3525471/latest.log)

Debug log-
[debug.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3525472/debug.log)

**Comment by MichaelHillcox** [comment]
Thanks for the bug report.

**Comment by MajorTuvok** [comment]
Say what?!?

**Comment by MajorTuvok** [comment]
I cannot reproduce this in our dev enviornment (using Forge .45)

**Comment by MajorTuvok** [comment]
This also doesn't make sense, because guava is a Forge provided lib - compiling against Forge just fine. I 'll verify now, that nothing changed in the most recent Forge version and file a bug to Forge otherwise

**Comment by MajorTuvok** [comment]
This issue is not caused by BuildingGadgets. It is either a Forge, installation (the library is missing!!!) or another mods issue.
It works perfectly fine for me using Forge .55.

**Comment by MajorTuvok** [comment]
Before we submit a Bug to Forge, could you try without all these other mods, or try to find out if someone is causing the library to go missing?

**Comment by ProsperCraft** [comment]
Reproduced with only forge .55 and Building Gadgets, on a different computer.

[debug.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3527437/debug.log)
[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3527438/latest.log)

When I was updating the pack this morning it may be worth noting that the prior version of Building Gadgets works fine, so I pushed the pack update with the downgraded version.

As a I final test I will see if I can reproduce it with only vanilla minecraft and Forge .55 and Building Gadgets bypassing the twitch launcher as it has been known to have library issues.

**Comment by ProsperCraft** [comment]
Reproduced without the Twitch launcher on a vanilla client with only Building Gadgets and forge .55

[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3527492/latest.log)
[debug.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3527493/debug.log)

**Comment by MajorTuvok** [comment]
I think that's an installer issue then, because it doesn't happen in dev enviornment.

**Comment by MajorTuvok** [comment]
Validated: this is a Forge issue, they download an older version of guava then the one used in Dev envoirnment: 
![image](https://user-images.githubusercontent.com/25031360/63505254-83ce7500-c4d3-11e9-91b1-74a52bd10631.png)
In Dev env. we have guava 25.1 or 25.0 but in production only 21.0 seems to be present. The Method I started calling for performance reasons in the 3.0.3 release was added in guava 23.0.

**Comment by Revvilo** [comment]
Is there a way to manually work around this whether using Twitch or not?

**Comment by MichaelHillcox** [comment]
Just use 3.0.2 for now

**Comment by MajorTuvok** [comment]
@Revvilo you could go into your minecraft dir and replace the guava 21 jar with the newer 25.1-jre jar - But I don't think it's worth the effort

**Comment by ProsperCraft** [comment]
It has nothing to do with Twitch, I reproduced it with forge on a vanilla install of mincraft.

**Comment by MajorTuvok** [comment]
We never said that it has anything to do with Twitch?!?

**Comment by MajorTuvok** [comment]
It is caused by Forge's mergetool exposing guava 25.1 to the dev enviornment, which made us use features which were added in guava 23.1. Sadly the installed Forge only has guava version 21 => crash

**Comment by MajorTuvok** [comment]
Released in 3.0.4
