### ISSUE TITLE
[question] Where would i start for adding Simple Storage Network support / capability. 1.12, 1.14

### ISSUE THREAD

**Issue by Lothrazar** [Direwolf20-MC/BuildingGadgets#348]
Im the mod dev of simple storage network and i want to allow it to pull or link to the network inventory in some way if thats possible

**Comment by MajorTuvok** [comment]
It is supported in 1.12 we haven't thought of supporting anything at all in 1.14 yet

**Comment by MichaelHillcox** [comment]
Effectively everything that is a tile entity and has an IItemHander is supported by the tools. An exception being where IItemHandlers are fakes for any reason. TE bags are a good example of this as they fake it for their privacy settings on the bag.

**Comment by MajorTuvok** [comment]
As I think this has been explained enough - closing. Feel free to reopen and ask questions
