### ISSUE TITLE
[Feature Request] CTM Support

### ISSUE THREAD

**Issue by samtrion** [Direwolf20-MC/BuildingGadgets#35]
Currently, CTM blocks are displayed in their standard textures. It would be great if the CTM support is expanded here so that the Connected Textures are displayed as well.

**Comment by Direwolf20-MC** [comment]
I have tried about a million things and just can't figure out how to make this work properly :). I got close, but it causes the blocks to render very darkly, and I don't like that part of it.

**Comment by samtrion** [comment]
Do not be discouraged by this.

**Comment by Direwolf20-MC** [comment]
I think this is good now!
