### ISSUE TITLE
Building gadgets version 2.7.3(latest 1.12 version) crash my game.

### ISSUE THREAD

**Issue by Mrthomas20121** [Direwolf20-MC/BuildingGadgets#350]
Forge version: 14.23.5.2838
Building gadgets : 2.7.3

im getting this crash when i try to start my modpack. building gadget is the latest mod i updated and every other mods are up to date.
https://paste.dimdev.org/edejimebog.mccrash

**Comment by TheFlipflop** [comment]
yep got the same problem after installing 2.7.3 into all the mods 3 lite modpack

**Comment by McJty** [comment]
Can confirm. Same problem here

**Comment by MichaelHillcox** [comment]
Hmm, that's just odd. It was tested. I'll test it my end and see what's going on. We've been having some gradle and build issues. Only one of us has been able to set up a 1.12 workspace recently

**Comment by MajorTuvok** [comment]
I put it into an empty workspace and I was ablw to run without Problems

**Comment by MajorTuvok** [comment]
So I kust read the log: for some reason it attempts to use an mapped Name!!! It was compiled using `gradle build` (in this weirdness that's my 1.12 workspace thoigh) so I honestly don't know how that happend. Someoneelse can try to recompile though?

**Comment by GhEppIO82** [comment]
same problem game crash initialization

**Comment by MajorTuvok** [comment]
I think I'm done with 1.12 - it no longer even creates a jar for me when I run `gradlew build`... 
[Sometimes it seems to be better not to update IntelluiJ]

**Comment by MajorTuvok** [comment]
I guess when I executed build it also didn't create a jar, which is why this mapped one is exported...

**Comment by LemADEC** [comment]
I suggest to remove or archive the buggy version from CurseForge so we're not tempted to use a version that won't boot.

**Comment by MajorTuvok** [comment]
Mike is going to fix it as soon as he can... I don't have access and Dire is outta town...

**Comment by MajorTuvok** [comment]
Again I'm sorry for that - I really didn't expect 1.12 to make these Problems (we already came to the conclusion that 1.14 needs to be tested in a non-Dev enviornment, but didn't expect that to be necessary for 1.12)

**Comment by MajorTuvok** [comment]
Mike updated the jar, it now runs properly

**Comment by MajorTuvok** [comment]
(the hotfix jar)

**Comment by GhEppIO82** [comment]
great so fast,i love it
