### ISSUE TITLE
Add Destruction Gadget Blacklist

### ISSUE THREAD

**Issue by Darkere** [Direwolf20-MC/BuildingGadgets#351]
The destruction gadget in connected area mode ignores the blacklist deleting tile entities and bedrock. 

Forge 2838
BG: 2.7.2

not sure if related (and fixed) with #344

**Comment by MajorTuvok** [comment]
Bedrock and Tiles are fixed now, I forgot about the blacklist thoigh

**Comment by MajorTuvok** [comment]
Th blacklist wasn't intended for the Destruction Gadget. It solely affects which Blocks can be selected/copied.

**Comment by MajorTuvok** [comment]
I don't think that adding a Blacklist for the Destruction Gadget in 1.14 would even be a good idea - you could use that for abusing the tool by just blacklisting the ores you want and then going mining with it

**Comment by MajorTuvok** [comment]
A question, to your comment: if it takes the Blacklist into account, then I'd flag that as a bug

**Comment by Darkere** [comment]
I don't see any problems in being able to "cheat" when I'm already editing configs. There are worse things I could do in there than mining with a destruction gadget.

But a blacklist would still be nice in any case where for whatever reason a block that shouldn't be voidable, is. Then Packmakers can work around it.

**Comment by MajorTuvok** [comment]
@Direwolf20-MC could you have a look at this?

**Comment by MajorTuvok** [comment]
Dire said this would be ok as a feature, but is low-priority

**Comment by MichaelHillcox** [comment]
So last I spoke to dire about this he's against it as it can turn the destruction gadget into a mining tool. I'll talk to him again today though.

**Comment by MajorTuvok** [comment]
I already added that to in-dev

**Comment by MajorTuvok** [comment]
I'll remove it if dire rejects it again...
Notice that this can only be modified by the Server owner and requires at least op permission (so that the reload command can be run) (it's as I said a Tag)

**Comment by MichaelHillcox** [comment]
Oh, okay, No I thought you where talking about an in-game black list. That's all good then.

**Comment by MajorTuvok** [comment]
Oh, just realised: this is already in 3.0.6a
