### ISSUE TITLE
Allow Placeholder Blocks to be loaded instead of missing Blocks

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#353]
Currently all unkown Blocks loaded by Template's will be ignored, but it might be that a user intends on Replacing these Blocks with something else, but isn't able to start the Pack they were saved in. (Even if he/she would be able to do that, replacing these can be tedious as long as we haven't implemented the Transaction Gui)

Adding Placeholder Blocks would solve this Problem by instead loading a Placeholder-`BlockState` (with some warning Texture and itself not being craftable, so that it wouldn't be build) and adding adding a `PlaceHolderTileEntityData` which only remembers the ResourceLocation of the Block or TileEntityData it's a Placeholder for. Because `BlockData` is identified by both `BlockState` and `ITileEntityData` every missing Block will be it's own Block and can later be replaced.

Replacements would happen via the Transaction Gui's (not yet implemented as of this writing) replace feature (`TemplateTransactions#replaceDataOperator(Map<BlockData, BlockData>)` in code), so that you'd select the the PlaceHolder's you want to replace and then specify what to replace them with.

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
