### ISSUE TITLE
1.14.4 New World crash.

### ISSUE THREAD

**Issue by Wissi** [Direwolf20-MC/BuildingGadgets#357]
Awesome mod. Thanks for your great work.

We're having this issue atm.

* Forge-28.0.55 (won't work with newest 28.0.81 either)
* buildinggadgets-3.0.4.jar
* *If the issue is a crash*; An external link to the [crash report](https://gist.github.com/Wissi/df2d22d1a7e5f1df45af0350d46ab6b1
)
* Create a new world. cleint crashes.

**Comment by MajorTuvok** [comment]
Duplicate of #355
