### ISSUE TITLE
Support for Dank Storage

### ISSUE THREAD

**Issue by Tfarcenim** [Direwolf20-MC/BuildingGadgets#358]
Allow the building gadget to pull from the dank storage to place items https://www.curseforge.com/minecraft/mc-mods/dank-storage

**Comment by MajorTuvok** [comment]
Could you maybe instead open an issue on their end to expose an ItemHandler?

**Comment by MajorTuvok** [comment]
[Or link their reasoning why the can'T do that]

**Comment by Tfarcenim** [comment]
I am the author, which one do you need, this? https://github.com/Tfarcenim/Dank-Storage/blob/master/src/main/java/com/tfar/dankstorage/block/DankBlock.java#L214

**Comment by MajorTuvok** [comment]
No, I'm requesting that you expose Forge's ItemHandler capability

**Comment by Tfarcenim** [comment]
I am lost, how would I do that? I already have one for the block, do I need one for the itemstack too?

**Comment by MajorTuvok** [comment]
Yes

**Comment by MajorTuvok** [comment]
You should notice us being able to link your blocks, if you already expose an ItemHandler for them.

**Comment by Tfarcenim** [comment]
is https://github.com/Tfarcenim/Dank-Storage/commit/dff7107ecc79ff304ef685bd2af6b7cdd7176857 enough for you guys?

**Comment by MajorTuvok** [comment]
So you are exposing your capability... That might be doable, but again, why don't you expose an item handler?

**Comment by MajorTuvok** [comment]
Yep I missed that you are exposing Forge'S IItemHandler, I'm sorry... I just saw a lot of code with your own cap and [missed this line](https://github.com/Tfarcenim/Dank-Storage/commit/dff7107ecc79ff304ef685bd2af6b7cdd7176857#diff-75dea213d84f9ef468e2204c6ae44574R47) which adds it to the Item,
If it doesn't work now, then that's a bug

**Comment by MajorTuvok** [comment]
Closing as this should work now. Feel free to reopen if it doesn't
