### ISSUE TITLE
Todo / QOL - Add block count next to radius

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#359]
Just a reminder for myself and an opportunity for anyone else to question me.

Simply add a `required block count` next to the radius either in the Gui or in the tooltip or both. Something like "Radius: 2 (9 Blocks)"

**Comment by MajorTuvok** [comment]
What does the Block count say? How many blocks are needed?

**Comment by MichaelHillcox** [comment]
How many blocks the radius is. So for 1 it would be 1 block, 2 would be 9 blocks, etc (that might be wrong)

**Comment by MajorTuvok** [comment]
<=> statement... :)

And you're correct, that's how it should be floor(range/2) is the radius of the wall modes. Building Mode of course can place regardless of the distance and columns will always require range many blocks.

**Comment by MichaelHillcox** [comment]
Fixed in 8ea03c650774d19a1ef13ac56a5123e894282d25
Release for 1.14.4 - 3.1.0
