### ISSUE TITLE
Crash on Server Startup [3.0.5]

### ISSUE THREAD

**Issue by KajesLorian** [Direwolf20-MC/BuildingGadgets#360]
Works fine Client side, but is crashing server.

* Forge version1.14.4-28.0.82
* Building Gadgets version 3.0.5
* https://pastebin.com/ZCysXi0K

**Comment by MajorTuvok** [comment]
Thanks for the report, though it really confuses me why the Registry is not available on the Server.

**Comment by MichaelHillcox** [comment]
Got to admit, I've not tested that, You are also on a newer version. I'll / @MajorTuvok  will check it out

**Comment by MajorTuvok** [comment]
@KajesLorian could you send the latest (and ideally debug) log? Because I've put some logs in there to show that it's called and I have aboslutly no idea why it wouldn't be called on the Server

**Comment by KajesLorian** [comment]
So I ran the server a few times without your mod, and was getting some strange crashes, and now the log for the last session with buildingGadgets is gone. If I upload the log.gz file to dropbox can you use that?

**Comment by MajorTuvok** [comment]
Not sure, I'd prefer if you gave me the latest.log or ideally the debug.log

**Comment by KajesLorian** [comment]
Latest.log: https://gist.github.com/KajesLorian/9f3170b6332815ff5e19471df9fb2322

debug.log: https://gist.github.com/KajesLorian/6ff193ff8991db681aae4ae0d6022362

Like I said though, I removed your mod, and was getting different crashes.

(Specifically, I removed your mod and the server worked, but I needed to change a config, so I changed it and started getting crashes. this log reflects those crashes. I suspect a problem with Forge, and am preparing a bug report there)

**Comment by MajorTuvok** [comment]
Something weird is going on: Forge doesn'T send us the NewRegistryEvent

**Comment by KajesLorian** [comment]
I agree. Everything, including your mod, works client-side.

**Comment by MajorTuvok** [comment]
Could you test with just BG on the Server?

**Comment by MajorTuvok** [comment]
It loads fine for me in Dev env. with Forge .76

**Comment by KajesLorian** [comment]
The server does work with just your mod Forge .82

I don't think this is a BuildingGadget problem

Link to Forge Bug report: https://www.minecraftforge.net/forum/topic/75511-forge-1144-28082-server-crashing-without-crash-report/

**Comment by MajorTuvok** [comment]
Closing then - you might want (need) to isolate the mod that causes the issue, even though that's a bit of work with that many mods

**Comment by MajorTuvok** [comment]
In the other issue @Wissi found the conflicting mods - I'm going to ask on the Forge Discord after my exam today and then submit either issues to Forge or these mods

**Comment by MajorTuvok** [comment]
I correct myself, I just noticed in the crash log, that BuildingGadgets is still in the constructing stage (together with some other mods), but already recieves ObjectHolder-Refreshes!

Forge is supposed to only refresh ObjectHolders of those mods that are currently recieving RegistryEvents (LOAD_REGISTRY stage). Therefore I'm going to report this to Forge

**Comment by MajorTuvok** [comment]
The most recent Forge version should fix this accordibg to cpw

**Comment by MajorTuvok** [comment]
(could someone try with 28.1.10?)

**Comment by MichaelHillcox** [comment]
Shall do
