### ISSUE TITLE
Charging station missing v2.7.3

### ISSUE THREAD

**Issue by chocom0nster** [Direwolf20-MC/BuildingGadgets#363]
Currently installed modlist below screenshot
![image](https://user-images.githubusercontent.com/51749577/64216366-95762c00-ce86-11e9-89d4-406007661145.png)

            
advskinmod-MC1.12.2-v1.8.2                    
animania-1.12.2-1.6.2                 
ATLCraftCandlesMod(MC1.12-Ver1.9)             
BasicNetherOres-1.12.2-1.0.4.0                
Baubles-1.12-1.5.2                            
betteranimalsplus-1.12.2-7.1.0                
betternether-0.1.8.3                          
BiomesOPlenty-1.12.2-7.0.1.2439-universal     
blue_skies-1.12.2-v1.1.2                      
BuildingGadgets-2.7.3                         
cc-tweaked-1.12.2-1.82.3                      
chiselsandbits-14.33                          
Chunk+Pregenerator+V1.12-2.1                  
CodeChickenLib-1.12.2-3.2.3.357-universal     
CoFHCore-1.12.2-4.6.3.27-universal            
CoFHWorld-1.12.2-1.3.1.7-universal            
conarm-1.12.2-1.2.4                           
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
CraftTweaker2-1.12-4.1.19                     
CTM-MC1.12.2-0.3.3.22                         
desktop                                       
DoggyTalents-1.12.2-1.15.1.4-universal        
dungeonmobs-5.8.3-MC1.12.2                    
DynamicLights-1.12.2                          
DynamicTrees-1.12.2-0.9.5                     
DynamicTreesBOP-1.12.2-1.4.1e                 
DynamicTreesTC-1.12.2-1.4.1e                  
endergetic-0.0.1                              
FastLeafDecay-v14                             
ForgeMultipart-1.12.2-2.6.2.83-universal      
gravestone-1.10.1                             
GrimoireOfGaia3-1.12.2-1.6.9.3                
InfernalMobs-1.12.2                           
InventoryTweaks-1.63                          
IvToolkit-1.3.3-1.12                          
jei_1.12.2-4.15.0.268                         
jetorches-1.12.2-2.1.0                        
journeymap-1.12.2-5.5.5                       
landlust-1.12.2-0.3.6                         
landmanager-1.12.2-1.3.1                      
LibraryEx-1.12.2-1.0.11                       
LootTweaker-1.12.2-0.0.10                     
lumen-Beta+0.4.1                              
Mantle-1.12-1.3.3.55                          
MCA-1.12.2-6.0.1-universal                    
MetalChests-v6.1.0+mc1.12.2                   
Metallurgy-4-Reforged-0.2.2                   
MoarSigns-1.12.2-6.0.0.11                     
morepaintings-paintings-1.12.2-5.0.1.2        
MrTJPCore-1.12.2-2.1.4.43-universal           
NetherEx-1.12.2-2.0.13                        
OptiFine_1.12.2_HD_U_E3                       
PrettyBeaches_1.12.2-1.0.4                    
ProjectRed-1.12.2-4.9.4.120-Base              
ProjectRed-1.12.2-4.9.4.120-compat            
ProjectRed-1.12.2-4.9.4.120-fabrication       
ProjectRed-1.12.2-4.9.4.120-integration       
ProjectRed-1.12.2-4.9.4.120-lighting          
ProjectRed-1.12.2-4.9.4.120-mechanical        
ProjectRed-1.12.2-4.9.4.120-world             
RecurrentComplex-1.4.8.2                      
RedstoneFlux-1.12-2.1.0.6-universal           
Rex's-Additional-Structures-1.12.x-(v.2.2.2)  
Rift-jitpack-d4cd7b00ba-1                     
RoguelikeDungeons-1.12.2-1.8.0                
Ruins-1.12.2                                  
SereneSeasons-1.12.2-1.2.17-universal         
simpleteleporters-1.12.2-3.0.2                
SpartanShields-1.12.2-1.5.4                   
speedyladders-1.1.3                           
TBone-v1.6.8+mc1.12.2                         
TConstruct-1.12.2-2.12.0.157                  
Thaumcraft-1.12.2-6.1.BETA26                  
theoneprobe-1.12-1.4.28                       
ThermalDynamics-1.12.2-2.5.5.21-universal     
ThermalExpansion-1.12.2-5.5.3.41-universal    
ThermalFoundation-1.12.2-2.6.2.26-universal   
thermallogistics-0.2-26                       
TinkersComplement-1.12.2-0.4.2                
twilightforest-1.12.2-3.9.984-universal       
UniDict-1.12.2-2.9.2                          
Useful+Interior+-+0.13.1+[1.12.2]             
WanionLib-1.12.2-2.2                          
Waystones_1.12.2-4.0.72                       
Welcome+To+The+Jungle-1.2005.1222             
worleycaves-1.5.0                             
[1.12]bspkrsCore-universal-7.6.0.1            
[1.12]TreeCapitator-client-1.43.0

**Comment by MichaelHillcox** [comment]
The charging station is only in 1.14 sorry :(
