### ISSUE TITLE
Offset for destruction- and building-gadget

### ISSUE THREAD

**Issue by bufu1337** [Direwolf20-MC/BuildingGadgets#365]
Hi direwolf,
It would be cool to define an offset for destruction gadget aswell as for the building gadget like an offset can be defined for the copy and paste tool.
Reason for this is f.e.: 
i wanna destroy a straight line with depth 16 but i wanna keep the first block i am aiming at.

Sorry if there is already a thread for this, at least i didnt find one

**Comment by MichaelHillcox** [comment]
I think it might be ideal to have an offset functionality for all of our tools. I'll definitely see what I can do. (Is this a request for 1.12 or 1.14?)

**Comment by bufu1337** [comment]
I still use 1.12 because i have a giant selection of mods and not all support 1.14
But of course it should be also for 1.14

PS: i am a fan of you youtube series, watching every video... you doing great :)

**Comment by MichaelHillcox** [comment]
I'll see about back porting the feature. I'm sure @Direworlf20-mc greatly appreciates your viewership :D

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
