### ISSUE TITLE
Invalid extended blockstate used in builder's overlay rendering

### ISSUE THREAD

**Issue by LemADEC** [Direwolf20-MC/BuildingGadgets#367]
* Forge version 14.23.5.2838
* Building Gadgets version 2.7.3
* WarpDrive version 1.12.2-1.5.8
* https://pastebin.com/W2aCiLNn
* How to reproduce the issue
Trying to use WarpDrive omnipanel causes a client crash.
Right before, Building gadget is trying to render said omnipanel by passing an invalid extended blockstate (one that wasn't initialized through calling getExtendedState()).

When rendering the item form, blockstate should be null.
When rendering the block form, blockstate comes from getExtendedState().
That's what forge/vanilla does to my understanding, I'm confused on why it would be different here?

**Comment by MajorTuvok** [comment]
I **presume** this happens, because we need to have a savable state - therefore the BlockProvider ignores the extended state...

This needs more investigation

**Comment by LemADEC** [comment]
For the record, there's also a crash because an invalid model renderer is used (one that expects simple baked models with no normals, incompatible with a pure baked model).

**Comment by MichaelHillcox** [comment]
I've added more failsafes since then. Please confirm if this still crashes you, closing till then :+1:
