### ISSUE TITLE
Crash when attempting to select a shulker box

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#368]
Pretty straight forward: A use on discord reported that 
> My game crashed after shift clicking with exchange on a shulker box

I think we found our first TE-issue

**Comment by HeuristicBishop** [comment]
I could not reproduce this crash.

Minecraft: 1.14.4
Forge: 28.1.79
Building Gadgets: 3.1.1b

If you can repro this bug let me know how. I'll take another look.

**Comment by MichaelHillcox** [comment]
Can not reproduce in 3.1.1b with an updated forge version. Closing
