### ISSUE TITLE
[Feature Request] Ability to use the building tool to place pipes, conduits etc.

### ISSUE THREAD

**Issue by PogoPogoPogo** [Direwolf20-MC/BuildingGadgets#37]
Loving it so far, it's making larger projects a breeze. Haven't found anything game breaking either so good job man. Just it seems that it is impossible to lay down long stretches of pipes, is that even at all possible? Keep up the good work, I'm sure this is going to be included as standard in my games from now on.

**Comment by Direwolf20-MC** [comment]
Currently all Tile Entities are disabled (Chests/furnaces/pipes, etc). I may allow them in the future.
