### ISSUE TITLE
add config options to modify each gadget individually 

### ISSUE THREAD

**Issue by flameface11** [Direwolf20-MC/BuildingGadgets#371]
i feel it would be a good idea to make it so you can edit the power requirements for one of the gadgets so something like the copy paste gadget isnt gated behind power (also make it use durability and break after a bit of use) for easy multiblock building for example astral sorcery

**Comment by MichaelHillcox** [comment]
The gating is to make the item less of a god item and more something you work towards using. Personally I'm against adding durability back. You can also already modify the power requirements of each tool from my knowledge. The cost per build is also configurable I think.

**Comment by MichaelHillcox** [comment]
All or nothing in reference to?

**Comment by MajorTuvok** [comment]
Just to point that out: you already can configure both max energy and max stored energy indicidually. However we specifically removed durability

**Comment by flameface11** [comment]
yes but i would like the copy paste gadget not to use power like not need it at all

**Comment by MajorTuvok** [comment]
And you can do that, it won't use duruability though

**Comment by flameface11** [comment]
mind telling me how?

**Comment by MajorTuvok** [comment]
By setting the used energy to 0?

**Comment by flameface11** [comment]
i tried that but it seems like it still needed atleast 1 rf to do the thing

**Comment by MajorTuvok** [comment]
As I'm rewriting it in #369 anyways there's no point in fixing it...
Once it's back in, I'd ask you if you could check whether that's still a thing...

**Comment by MajorTuvok** [comment]
This might be related to #373 - and might also be present in 1.12...a

**Comment by MichaelHillcox** [comment]
So as of dd48c7c3b25417746c310d6dde88295127635703 3.1.1b it is now possible to set the power to 0 in which will cause the canUse and performAction methods to always return true. It's as if you are in creative. This should solve your issue with power requirements. This has also been backported and released for 1.12
