### ISSUE TITLE
[1.14.4] [Copy Paste gadget] Hoppers

### ISSUE THREAD

**Issue by gabesmorais** [Direwolf20-MC/BuildingGadgets#372]
I tried pasting an automatic farm, but the hoppers were pasted facing the wrong side. They were copied facing the right side.
Similar thing happened to glass panes with exchange tool. Instead of placing the flat glass pane, it placed the cross-shaped glass pane on all the replaced ones.

**Comment by MichaelHillcox** [comment]
Darn! Thanks for the report. Could you by any chance let us know what version of the mod you're using and what version of forge you're using?

**Comment by MichaelHillcox** [comment]
Closing as this seems to already be fixed. It'll be either fixed in the next release or fixed already :D
