### ISSUE TITLE
Gadgets in inventory are used as a battery by other mods (eg: EnderIO dark armor)

### ISSUE THREAD

**Issue by CplPibald** [Direwolf20-MC/BuildingGadgets#373]
BuildingGadgets-2.7.2
SMP server running forge-1.12.2-14.23.5.2838

1) Charge building or exchange gadget to full.  (Optionally, use it a couple times to make sure it's "running")
2) Hold gadget in hand and walk around

Expected: Gadget only drains power when you click with it.
Actual: Gadget discharges simply by walking or looking around.

<s>As far as I can tell, the gadgets consume some power each time it renders the block outline that it would place.  This outline changes every time you move your cursor.  The result is that if you're not using the gadget, but simply moving from place to place, it is constantly draining itself.  I have observed that holding the gadget and looking or walking around drains a lot of power. </s>

According to some players on my server, it even drains this if you're not holding the gadget in your hand; merely having it in your inventory will discharge it, though I haven't personally confirmed this.

As a side-effect, the NBT updates to the item stack make the first-person player constantly raise and lower the gadget while walking.

**Comment by MajorTuvok** [comment]
I have to say, that I never moticed something like that occuring and therefore I'm kind of confused

**Comment by MichaelHillcox** [comment]
This is a really odd one, the only thing I can think it's that there is another mod drawing power from the items as I've never seen this issue and I would have noticed the items nbt updating. What other mods do you have?

**Comment by CplPibald** [comment]
Okay, I dug further into this and it's definitely a mod interaction bug.  Specifically, EnderIO dark armor is using the gadgets in inventory as a battery.  Same symptom - the gadget drains while walking around (assuming you're wearing the armor) - but totally different cause.  

I believe you can prevent this by making [`IEnergyStorage.extractEnergy()`](https://github.com/Direwolf20-MC/BuildingGadgets/blob/6a11e1d0f7f6c47dcd49c2f2e958bfa6aa43dd30/src/main/java/com/direwolf20/buildinggadgets/common/items/capability/ItemEnergyForge.java#L31) always return 0.

Sorry for the confusion.  That's what I get for investigating player issues at 2:30am.

**Comment by MajorTuvok** [comment]
I have to remind you that this would not be an Object manipulating it's internal values, but rather us either adding another capability just for this purpose or inserting casts everwhere  just to get access to it. Or even worse manipulate the nbt behind the scenes, complete ly bypassing the cap object!

I already agreed, that this piece of not nice code is required though - even though we already new that the Gadgets could be used as batteries, this resetting the animation all the Time is really annoying though
