### ISSUE TITLE
Effect block crashes renderer

### ISSUE THREAD

**Issue by sunstriker7** [Direwolf20-MC/BuildingGadgets#375]
client version 1.14.4
forge version 28.0.95
building gadgets version 3.0.5

client crashes fairly often when placing or undoing placements with the building gadget and exchanging gadget (others untested)

Crash report:
https://drive.google.com/file/d/1Of4pKfHRvLySxmuNFwS31WNP_7rwtO4X/view?usp=sharing

**Comment by MajorTuvok** [comment]
Fixed for 3.0.6a
