### ISSUE TITLE
[1.14.4] Server booting crash.

### ISSUE THREAD

**Issue by Gbergz** [Direwolf20-MC/BuildingGadgets#379]
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
* Forge version: 28.1.1
* Building Gadgets version: 3.0.5
* *If the issue is a crash*; [https://pastebin.com/5dkdWvcj](https://pastebin.com/5dkdWvcj)
* How to reproduce the issue: Start server, crash. It's a server with alot of other mods.
* A screenshot, if applicable: none.

**Comment by MajorTuvok** [comment]
This is a known Forge bug, see MinecraftForge/MinecraftForge#6148.

**Comment by MajorTuvok** [comment]
Duplicate of #360
