### ISSUE TITLE
Building gagdet crash

### ISSUE THREAD

**Issue by konkun1998** [Direwolf20-MC/BuildingGadgets#380]
Any attempt to use building gagdet causes game freeze and crash without crash log.
MC 1.14.4 (Forge 28.1.1)
BG 3.0.5

**Comment by konkun1998** [comment]
[crash-2019-09-16_15.15.01-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3616471/crash-2019-09-16_15.15.01-server.txt)

**Comment by MichaelHillcox** [comment]
Sorry but that's not our mod if that's the correct crash log

**Comment by MajorTuvok** [comment]
I can't even find us in the stacktrace... You need to report that to `ovh.com.tombstone`
