### ISSUE TITLE
Feature Request: move blocks tool

### ISSUE THREAD

**Issue by vakermit** [Direwolf20-MC/BuildingGadgets#381]
It would be nice to have a tool that mimics the WorldEdit //move command.
so you would identify an area like the copy-paste gadget does then move it X blocks in a direction

This is so useful when you built something but are off by one block or if you need to expand your base by moving out a wall

Love the mod and your channel!

Thank you for all that you do

**Comment by MajorTuvok** [comment]
Haha, that's kind of funny... :) 
I already want to implement that and we have discussed this on our discord quite a bit. I'd like to call it the "Cut and Paste Gadget"

**Comment by MajorTuvok** [comment]
Duplicate of #266
