### ISSUE TITLE
Energy tooltip shouldn't show if max energy config is set to 0

### ISSUE THREAD

**Issue by thephoenixlodge** [Direwolf20-MC/BuildingGadgets#383]
For thematic reasons, the pack I'm working on has energy use and energy capacity for the gadgets set to 0. However, the tooltip still shows "Energy: 0/0". Since this is useless information, it should really not be shown at all
I could've sworn that in the past that tooltip line did disappear, but at some point it showed up again.

**Comment by MichaelHillcox** [comment]
Not that we've ever setup but totally something I can solve

**Comment by MajorTuvok** [comment]
What Mc version are you talking about?

**Comment by MichaelHillcox** [comment]
I've got a minor update for 1.12 regardless so I'll implment it on both.

**Comment by MichaelHillcox** [comment]
Fixed for 1.14.4
Fixed 7a700c1b3cf645687b3de04f76b5f7ef97b7b5e5
Release for: 3.1.0

**Comment by thephoenixlodge** [comment]
Is this no longer slated to also be fixed on 1.12 then? I admittedly should have replied earlier, but since I am working with 1.12 currently, that's a little unfortunate.

**Comment by MajorTuvok** [comment]
It is in general very unlikely that we do anything for 1.12 as it is very tedious to get a dev env. using IntelliJ up and running for it... And only Mike is able to do it atm...

**Comment by MichaelHillcox** [comment]
I might back port it but I've been having issues with 1.12 myself. It's a pain in the a**

**Comment by thephoenixlodge** [comment]
Ok, understood

**Comment by MichaelHillcox** [comment]
Implemented into 1.12.2 - 2.7.4 https://github.com/Direwolf20-MC/BuildingGadgets/releases/tag/2.7.4-1.12.x

**Comment by thephoenixlodge** [comment]
Thanks. Hopefully it wasn't too much trouble getting the 1.12 dev environment to cooperate.
