### ISSUE TITLE
Crash when selecting Charred Stair (Mystical World) with Exchanging Gadget

### ISSUE THREAD

**Issue by katubug** [Direwolf20-MC/BuildingGadgets#385]
* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.2](http://enthusiasticraft.cf/modpack-update-1-7-2/#modlist)
* **Mod versions:** BuildingGadgets-2.7.3, MysticWorld-1.12.2-1.4.4, mysticallib-1.12.2-1.3.7

Hi! Was playing on my multiplayer server when I shift+right clicked Mystic World's Charred Stair block with the Exchanging Gadget. My screen went completely white, stalled for a while, and then produced this crash report: https://paste.dimdev.org/azixixinul.mccrash

A second attempt produced the same issue. I switched over to singleplayer to test it out. Vanilla stairs worked fine, Immersive Engineering Stairs worked fine, Mystical World stairs produced a crash. This happens in both creative and survival, if that matters.

Let me know if there's any other information I can provide! Thanks for your time. :)

**Comment by katubug** [comment]
Update: Okay, I just encountered the same crash when I was breaking the stairs with left click - without the Exchanging Gadget in my hand. I'll be reporting this to Mystic World as well.

**Comment by katubug** [comment]
Hoo boy, okay, new problem: now I'm crashing every time I try to log in to the server. If I had to guess, I'd assume it's a delayed reaction? I probably shift+clicked the gadget on the stairs too many times, and it added that to a queue of some kind, that doesn't process while I'm offline.

After a few tries, I seem to be okay now. So I'm guessing that's responsible for the second crash mentioned in my previous post.

**Comment by MajorTuvok** [comment]
II'm pretty sure that this is **not our fault**. Someone calls BufferBuilder.begin a second time!

**Comment by MajorTuvok** [comment]
Also, could you please post the latest or debug log? Crash logs don't have that much information besides the stacktrace...

**Comment by katubug** [comment]
I'm guessing, based on the response to the other thread, that this is unnecessary, but in the interest of full disclosure, here's my latest.log. My apologies for uploading it as a text file, but it was too long for pastebin *and* paste.ee.

[latestlog.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3663060/latestlog.txt)

**Comment by duely** [comment]
To clarify, this issue has been resolved as we no longer use baked models.

I think it has something to do with the fact that the baked models were rendered using BufferBuilder which happens to be how the Building Gadget overlay appears to be done, which would imply that there's some sort of nesting going on. 

Regardless, it shouldn't happen any more.

**Comment by MajorTuvok** [comment]
As this seems to be resolved I'll close it
