### ISSUE TITLE
Leaves placed will decay after update.

### ISSUE THREAD

**Issue by JJSax** [Direwolf20-MC/BuildingGadgets#386]
---------------------------------------------------------------------------
* Forge version - 14.23.5.2838
* Building Gadgets version - 2.7.3
* How to reproduce the issue -
1. copy  several player placed leaves adjacent to each other
2. paste said copy
3. break a single leaf block.
4. watch your paste crumble away

**Comment by MajorTuvok** [comment]
And I thought people liked realism :laughing::cry:
Not sure whether we'll fix it in 1.12, but we'll certainly try in 1.14. Thanks for the report :)

**Comment by MajorTuvok** [comment]
Have to check that in 1.14

**Comment by MichaelHillcox** [comment]
Implemented into 1.12.2 - 2.7.4 https://github.com/Direwolf20-MC/BuildingGadgets/releases/tag/2.7.4-1.12.x
