### ISSUE TITLE
Incorrect extraction behaviour of all Gadgets

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#387]
As can be seen [here](https://github.com/Direwolf20-MC/BuildingGadgets/blob/9b9770994a6caf43fea24171b5503d8551b6117e/src/main/java/com/direwolf20/buildinggadgets/common/tools/InventoryManipulation.java#L143) InventoryManipulation modifies on purpose the stack returned by `getStackInSlot`. This however is forbidden by the contract of that Method and is supposed to cause exceptions if anyone detects this modification.
Furthermore this Method will fail if the first Stack found in the player inventory has fewer Items, then should be extracted - it will fail even though the remaining stacks may have the required Items! Notice that this case can never happen with our current usages, as we never request more then one Item at once. This may however cause future bugs.

**Comment by MajorTuvok** [comment]
I haven't checked, but there might be similiar errors in the other Methods

**Comment by MichaelHillcox** [comment]
Plz explain :P I don't think it's a huge issue so I'll close here but we can talk more in discord about it.
