### ISSUE TITLE
Bugs regarding 1.14 (master and 1.14-in-dev)

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#389]
Currently running the old (before we really got involved) mod (2.6.0) against our newest 1.14-in-dev branch. This is a list of issues / bugs that I'd like to have resolved before release.

### 3.0.5 (+ in-dev):
- [x] Connected surface will not validate if a block is within a wall or not. Needs to be able to do so. Either all the time or on by default.
- [x] Whilst the builder will validate if a block can be placed in the specific location, the exchanger fails to do so. This means you can take the top half of a plant for example (Only valid placement is on top of the same plant) and place it on the ground.
- [x] Exchanger shouldn't be able to place torches as it allows for instant mining of blocks when the auto-placement of the torch is on an in-valid location. 
- [x] Stop torches popping off their block when having the block exchanged (Fixed by ignoring torches for the exchanger)
- [x] Charging station doesn't switch texture when active
- [x] Charging station needs a burn icon or something to show it takes burnables
- [x] Charging station needs the energy number to be under the word Energy and to have it comma formatted :+1: 
- [x] Construction Blocks no longer simulate the hardness of the other blocfk and have shovels as their tool class
- [x] You can select a construction block (after being placed by the gadget) and it'll render a standard construction block. The old versions select the current construction block but with the block data that it's pretending to be so you can place more of them. If this is a 1.14 issue then just disable selecting it with a messaging telling you a construction block and not a normal block
- [x] Builds available blocks in the order in which they appear, not sorted closest to furthest: https://i.imgur.com/9hsB7bY.png (compared to 1.12 https://i.imgur.com/EEkc4aM.png)
- [ ] You can build when the selection is inside of you allowing you to kill yourself (this is a result of  making effect Blocks TileEntities - previously when they were Entities, they pushed you out)
- [x] Charging station do not show black overlay when in their GUI's.
- [ ] Template Manager and Charging station do not support JEI. Todo: found out why.
- [x] Charging station should keep it's charge when broken
- [x] Exchanger shouldn't replace blocks which aren't visible to the player. We need to be careful to support the edge case of half blocks etc which would make the face partial visible.
- [ ] Replace Destruction gadget gui completely and make it more user friendly and move it off of shift right click. Currently I'm thinking about rendering a 3d outline that the player can move their mouse over and drag to increase and decrease the vector they wish to change. This would also auto cap meaning players don't need to do math in their head for it haha.
- [ ] Remove all gadgets shift right-click functionality and push it all onto a button on the main `g` menu.

### in-dev:
- [x] Tool Mode status text missing space between "prefix:suffix" should be "prefix: suffix"
- [x] This weird undo behaviour https://streamable.com/t7sji not sure what is causing that but it's not like how it should be. It would seem the tile / render doesn't know what it should be for a while... On reflection, I think it's because of the new enum on the Tile. It first renders a blank redness then pauses and renders the block properly. 
- [x] Copy and paste text on the modes is in all caps? Seems angry, should calm it down a bit.
- [x] message.gadget.areareset doesn't exist for Copy area clearing
- [x] Gadgets all: Energy should always be in the same place on the tool tip. Current Building and Copy paste is on different lines to the rest. Should either be at the very top or at the very bottom. (possibly also 3.0.5)
- [x] Crash on undo when using construction paste: https://pastebin.com/4j2AAJVp (Cannot reproduce, I added code, that will prevent this crash, but it should not have happened in the first place as it indicates that one tried to insert an ItemStack of Items.AIR)
- [x] Console spam on start up https://i.imgur.com/2quKHNZ.png regarding item-serializer (Fixed with new Worlds)
- [x] Blocks show as unbuild-able even when you have a full construction paste container: https://i.imgur.com/iYltqKP.png (I fail to reproduce this, I calculated how much paste I needed for these blocks and always to the same result... If you could send me the paste that makes Problems, I'll try again)
- [x] Missing slot images? likely the old template manager code: https://i.imgur.com/psy07wz.png (Cannot be reproduced, try cleaning your caches+re-running genIntellijRuns and then doing a full build)
- [x] Undo doesn't put torches back in the inventory. (Cannot reproduce)
- [x] Missing i18n on size failure on destruction gadget https://i.imgur.com/brCUerY.png
- [ ] This is a really old bug... When shift right-click you can bypass area size checks by setting an area without already having an area selected. This shouldn't happen. Although the cords mode is logically useful, I think we should disable it / add clearer text to show if you're in cords mode or not and if you're not then the inputs should be disabled. We should also fix the size check bypass(different for in-dev)
- [x] Copy mode has no clear way of showing if the first selection was successful. Can we either show a highlight around the first block or just build that block as the first and last block so the render shows? or just something in status to say "Pos 1 set"

**Comment by MichaelHillcox** [comment]
Note: I will also be marking these off as we go towards stable but some of them are defiantly @MajorTuvok issues and others are just port and changes issues which I can clean up pretty nicely.

**Comment by MajorTuvok** [comment]
As a note: Here are a few issues which have nothig to do with me and are already present in 3.0.5.

**Comment by MichaelHillcox** [comment]
If the are bugs they need to be sorted. I'm happy to merge before that but they all need sorting and a good amount of them come from the in-dev branch. if they're not then edit and make a new section for 3.0.5 and put them there for me :P

**Comment by MajorTuvok** [comment]
> Console spam on start up https://i.imgur.com/2quKHNZ.png regarding item-serializer
This is due to me doing changes with that world. It no longer happens if you create a new world and place and copy stuff there

**Comment by MichaelHillcox** [comment]
If it's solved please add a commit id next to the issue and check it off :D

**Comment by MajorTuvok** [comment]
I don't know when that happened, sorry. I tested it know, and can reproduce it only with a world which contains things from previous world saves.
I'll just add the last commit that touched it.
