### ISSUE TITLE
[Feature Request] Build to me Rectangle

### ISSUE THREAD

**Issue by Jkosio23** [Direwolf20-MC/BuildingGadgets#39]
Basically, build to me, but it combines both of the current types of build to me, you make a rectangle based on the corner you're at and the corner you're looking at.

**Comment by Direwolf20-MC** [comment]
This can currently be accomplished with 4 mouse clicks :). Its a neat idea, but I'm trying to avoid too many modes, so don't want to have modes that duplicate existing functionality.  To Do this:

Place a block at the opposite corner, BuildToMe off the 2 faces of the block you can see, then BuildToMe off the ends of the new rows that are created.

**Comment by Jkosio23** [comment]
Oh! I meant a filled in rectangle, not a rectangle's outline.

**Comment by Direwolf20-MC** [comment]
Ahh well thats pretty much a horizontal wall then :).
