### ISSUE TITLE
[1.14] Multiple issues with the Charging Station

### ISSUE THREAD

**Issue by Darkere** [Direwolf20-MC/BuildingGadgets#390]
Building Gadgets 3.0.5
forge : 28.1.44

**Comment by MichaelHillcox** [comment]
We know, sorry, it has been fixed! We're really close to another release. I'd suggest you `/give` it to yourself. Soon we promise!

**Comment by Darkere** [comment]
Ah is the charging station fixed too? Losing power and tooltips are rendering behind JEI.

**Comment by MichaelHillcox** [comment]
We've not done any integration with other mods yet so I'm unsure of JEI related issues. Whats this about a charging station losing power when unloaded?

**Comment by Darkere** [comment]
For the JEI issue, there is a method call that is missing in the GUI that darkens the background behind the GUI. It was something like renderBackgroundLayer in 1.12. 

will double check the powerloss issue.

**Comment by MichaelHillcox** [comment]
I'll check it out :D

**Comment by Darkere** [comment]
So Yeah, Charging Station doesn't save it's power. Closing and reopening the world has it at 0rf.

**Comment by MichaelHillcox** [comment]
Really?! Alright, I'll add not to the notes thanks.

**Comment by Darkere** [comment]
Shift Clicking items into it also doesn't work.

**Comment by MajorTuvok** [comment]
The latger might be fixed... There were several container issues, cause by not applying the windowId on the Server (all of them had something to do with the Items vanisvhing again, or geting dupe Items into the armor slots)

**Comment by MajorTuvok** [comment]
Well I jist looked back at the code and saving etc. seems to be ok. It might be however, that the energy isn't synced to the client properlyso that the gui thinks it's 0,even though the Server has an value for it

**Comment by Darkere** [comment]
In that case, inserting an item for charging would resync the values though right? That is not the happening.

**Comment by MajorTuvok** [comment]
Saving was fixed in [this commit](fc67cde007f4e32fcfb546590cad1af00296ffdd)
