### ISSUE TITLE
Add tapemeasure like C&B

### ISSUE THREAD

**Issue by MichaelHillcox** [Direwolf20-MC/BuildingGadgets#391]
Nuff said. Just like C&B for our mod :D 

Todo: add full spec for implementation

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534

**Comment by Rensik** [comment]
Suggestion: instead of adding a whole new tool, add Height, Width and Length counts to Selected Blocks count by the Copy Gadget.

**Comment by MajorTuvok** [comment]
@Rensik you can already read the dimension from the paste...

**Comment by MichaelHillcox** [comment]
I think he means in world on the paste render
