### ISSUE TITLE
Copy Paste gadget will not select an area if that area contains blocks from Magneticraft

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Direwolf20-MC/BuildingGadgets#398]
When selecting a region that contains only vanilla blocks, the mod works normally. The cuboid can be expanded at will with no issue.

If you attempt to expand the selected region into an area that contains Magneticraft blocks, nothing will happen. The region will not change, as if I didn't right click at all. 

It should be noted that every block I tried from the mod had this issue, including machine blocks, copper ore and limestone blocks. These are not tile entities.

This creates an error in console, which can be found at the very bottom of the latest.log file below.

* Latest.log file: https://gist.github.com/TheDeviantCrafter/bfb9b12c483da871a575ae3e8da22aa1
* Forge version: 14.23.5.2838
* Building Gadgets version: 2.7.3
* How to reproduce the issue: 

1. Right click a block, then shift right click it again to create a 1x1x1 region.
2. Place a vanilla block next to it.
3. Right click the vanilla block. It will expand to become a 1x1x2 region.
4. Right click the first block to turn it back into a 1x1x1 region.
5. Break the vanilla block, and replace it with a Magneticraft block.
6. Right click on the Magneticraft block. The region will not change, staying as a 1x1x1 region.

* A screenshot, if applicable: 

https://imgur.com/a/cMkE1iS

**Comment by MichaelHillcox** [comment]
We don't actually support tile entities in 1.12. are you sure it happens with non tile entities?

**Comment by MajorTuvok** [comment]
@TheDeviantCrafter your log seems to be incomplete: I can only read all the errors other mods had during startup - but it ends somewhere whilst railcraft is initing their models and doesn't even get to the point where a world is opened

**Comment by MajorTuvok** [comment]
Sorry but something is wrong with githubs mobile interface - it randomly closed my keyboard whilst I was editing resulting in my click being registered for the close button

**Comment by TheDeviantCrafter** [comment]
I used TellMe to confirm that the blocks I was testing are no tile entities.

I'll redo the test and upload a working latest.log file in a few hours. Not sure what happened there.

**Comment by TheDeviantCrafter** [comment]
Looks like the log I uploaded is working fine, it just got truncated because it's huge. You need to click "view the full file" at the top to see the entire thing.

Just in case, here's another latest.log where I tested the same bug:
https://gist.github.com/TheDeviantCrafter/6b5edf0c73c925ed7315592f69444337

And the file itself:
[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/3802011/latest.log)

**Comment by MajorTuvok** [comment]
Ah, ok. Sorry... I'm dumb

**Comment by MajorTuvok** [comment]
My mobile can't view it though... Need to get to my Laptop XD

**Comment by MajorTuvok** [comment]
Magneticraft is throwing exceptions...

**Comment by MajorTuvok** [comment]
To be precise Magneticcraft errors because of [this](https://github.com/Direwolf20-MC/BuildingGadgets/blob/9b9770994a6caf43fea24171b5503d8551b6117e/src/main/java/com/direwolf20/buildinggadgets/common/tools/InventoryManipulation.java#L384) line. They complain about us passing null here - I'd need 1.12 source to be sure but I'm pretty sure that we don't have a sensible value to pass down to this...
@MichaelHillcox I think we need to catch exceptions from this Method as I remember us doing in other places...

**Comment by azaghal** [comment]
For what it's worth, I ran into the same issue, but only with the building gadget itself when doing the shift-right click to select block to build with (might be easier to reproduce).

**Comment by MichaelHillcox** [comment]
Thanks for letting us know. 1.12 will get a final update but we're not sure on when yet. Thus why this issue is still open. I'll be sure to mention the issue when I fix it :D
