### ISSUE TITLE
Stuck placeholder blocks

### ISSUE THREAD

**Issue by purpleposeidon** [Direwolf20-MC/BuildingGadgets#4]
I have an Extra Utilities mechanical user replacing blocks. The system is chunkloaded. Sometimes I login to find placeholder blocks just hanging around doing nothing. Fortunately they are breakable. It might be caused by a server restart during a swap? But I do not know.

**Comment by Direwolf20-MC** [comment]
Caused by a server restart / chunk unload '/ world exit. Now resolved (Thanks Fuj1n):
https://github.com/Direwolf20-MC/BuildingGadgets/commit/d43f381287b612a033decc0b9ad2c1effedc63bf
