### ISSUE TITLE
[1.14.4] Early exchanging gadget ItemStack tooltip instantiation causes crash with BlockData serialisation with 10+ mods installed

### ISSUE THREAD

**Issue by duely** [Direwolf20-MC/BuildingGadgets#400]
Forge: 28.1.79
Building Gadgets: 3.1.1b
Crash report: [Here](https://gist.github.com/duely/67826bf261bc999e2ad7ea0af2f83daa)
Screenshot: inapplicable

This is a bit of a crazy one that I've had difficulty replicating. Having *Building Gadgets* (latest version), as well as the latest version of al132's *Techemistry* (and associated library mods) along with the latest version of *Random Patches*, plus the top 10 or so mods on Twitch, causes the above crash, implying [that your serializer is getting null at some point on this line](https://github.com/Direwolf20-MC/BuildingGadgets/blob/master/src/main/java/com/direwolf20/buildinggadgets/common/building/BlockData.java#L154).

Line in question:

```java
tag.putString(NBTKeys.KEY_SERIALIZER, tileData.getSerializer().getRegistryName().toString())
```

Either tileData (which is unlikely as the constructor requires nonnull), the result of getSerializer, or the result of that serializer's registry name (more likely that it hasn't been registered yet) are null. Given that this is taking place during the item tooltip function (func_82840_a), I'm assuming that Random Patches' classloading is causing this to load earlier than expected -- potentially before the expected registrations.

Regardless of either of the versions of Techemistry or Random Patches, however, it might be wise to program defensively in this case and check for multiple nulls, potentially serializing nothing, especially as this only seems to occur when a specific combination of mods trigger (or trigger classloading) first, and only during the searchtree creation on the client, which I believe is specifically limited to the creative tab.

Thus, it would presumably not affect actual exchanging gadgets.

**Comment by MajorTuvok** [comment]
I presume that this might be the result of some race condition - if populateSearchTreManager is called before we got the RegistryEvent then this would happen... Or if someone instatiates our Items before we got all RegistryEvents.

**Comment by MajorTuvok** [comment]
Could you send me the logs, so I can check? (We need to update our Issue-Template, because logs are much more intresting and informative then crash reports...)

**Comment by MajorTuvok** [comment]
Though in my opinion the solution is not to check whether it is null, but rather ensure that it is never null. I never liked it that Forge allows it's registry names to be null sometimes.

**Comment by MajorTuvok** [comment]
Could you check with this  [jar](https://github.com/Direwolf20-MC/BuildingGadgets/files/3801341/buildinggadgets-3.1.1b.zip) (need to change the file ending back from zip to jar, because github doesn't like jar's)?

**Comment by duely** [comment]
I'll check it out but I definitely think that will solve the issue. 

Have you looked into DeferredRegistry<T> and RegistryObject<T>? It's a slightly more complex system but it automatically generates suppliers that are then automatically registered, allowing for static initialization of anything that has a Forge registry. I mostly based the code in MysticalWorld on [Tropicraft's system](https://github.com/Tropicraft/Tropicraft/blob/1.14/src/main/java/net/tropicraft/core/common/block/TropicraftBlocks.java). [My library for it in MysticalLib](https://github.com/MysticMods/MysticalLib/blob/1.14/src/main/java/epicsquid/mysticallib/registry/ModRegistry.java) is still fresh, [here's an example of it](https://github.com/MysticMods/MysticalWorld/blob/1.14/src/main/java/epicsquid/mysticalworld/init/ModBlocks.java).

I'm not sure if it would precisely resolve the issue in this case, but at the very you'll be able to tell if the serializer is being accessed *before* the actual registry event for the serializer.

(Just beware that it's better to do EntityTypes statically.)

Upon testing, there's now another error that appears to be shifting back to an optional failing, so ... I think it's fixed!

**Comment by MajorTuvok** [comment]
We know about that, but Forge added that the evening after Mike rewrote our registration System and already having other more important things todo, it went really low on our todo list.

**Comment by MichaelHillcox** [comment]
I'll actually be moving is over two `DeferredRegistry` in the coming days :+1:

**Comment by MajorTuvok** [comment]
Ah, ok nice :)
