### ISSUE TITLE
Broken Images in the Wiki

### ISSUE THREAD

**Issue by Tetha** [Direwolf20-MC/BuildingGadgets#403]
Good Morning,

I'm using no issue template, because this is neither a functional issue with the mod, nor a feature request. Instead I noticed a couple of broken images on your wiki page, primarily the pages "Home", and "Destruction Gadget". 

As fas as I can see there are two groups of issues here:

 - Commit 18de7d6167d947ed4d7fbc173410029c718aff6b modified the texture names in the src/main/resources/assets folder. These are referenced by the Home-Page of the wiki and these are consequently broken. Sadly, github doesn't have a simple way to do pull requests on a wiki page, so I've attached a [patch](https://github.com/Direwolf20-MC/BuildingGadgets/files/3828337/home-md-image-fixes.diff.txt) to the Home-File that fixes these images, at least in my editor. The file has the extension "diff.txt" because apparently diff-files are a very strange thing to attach to a github issue.

- There are a few images referenced from the `.github/wiki` folder and the links should be correct. It seems like the merge commit f61b6ab812a32ac83288a4e14f10fcdc0d3fa1a0 has deleted it - the folder is there in commit 9b977099 and gone in a8764060. With a  modern git, this could be recovered using:

> git restore --source=9b977099  --staged --worktree -- ".github/wiki"

This stages the .github/wiki directory ready for a recovery commit. 

After that, the images in the wiki should all be working again.

Cheers, 
tetha

**Comment by MajorTuvok** [comment]
@MichaelHillcox  is this a case for your gitbook? I'm going to fix these manually, but would be quite interested, whether this would be a case to be solved via gitbook.

**Comment by MajorTuvok** [comment]
Fixed - I corrected the links on the wiki page...

**Comment by MichaelHillcox** [comment]
This is actually solved on the gitbooks. I've not set the domain up yet so I've not linked it.
