### ISSUE TITLE
Building Gadgets Charging Station CRASH

### ISSUE THREAD

**Issue by ItzTwoost** [Direwolf20-MC/BuildingGadgets#405]
When I place the charging station down it crashes my game.
Why?

---- Minecraft Crash Report ----
// My bad.

Time: 11/10/19 12:15 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeHooks.getBurnTime(Lnet/minecraft/item/ItemStack;)I
	at com.direwolf20.buildinggadgets.common.tiles.ChargingStationTileEntity.initBurn(ChargingStationTileEntity.java:326) ~[?:3.1.1b] {}
	at com.direwolf20.buildinggadgets.common.tiles.ChargingStationTileEntity.tryBurn(ChargingStationTileEntity.java:308) ~[?:3.1.1b] {}
	at com.direwolf20.buildinggadgets.common.tiles.ChargingStationTileEntity.func_73660_a(ChargingStationTileEntity.java:271) ~[?:3.1.1b] {}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.direwolf20.buildinggadgets.common.tiles.ChargingStationTileEntity.initBurn(ChargingStationTileEntity.java:326)
	at com.direwolf20.buildinggadgets.common.tiles.ChargingStationTileEntity.tryBurn(ChargingStationTileEntity.java:308)
	at com.direwolf20.buildinggadgets.common.tiles.ChargingStationTileEntity.func_73660_a(ChargingStationTileEntity.java:271)

-- Block entity being ticked --
Details:
	Name: buildinggadgets:charging_station_tile // com.direwolf20.buildinggadgets.common.tiles.ChargingStationTileEntity
	Block: Block{buildinggadgets:charging_station}[facing=west,lit=false]
	Block location: World: (-345,64,-403), Chunk: (at 7,4,13 in -22,-26; contains blocks -352,0,-416 to -337,255,-401), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Block: Block{buildinggadgets:charging_station}[facing=west,lit=false]
	Block location: World: (-345,64,-403), Chunk: (at 7,4,13 in -22,-26; contains blocks -352,0,-416 to -337,255,-401), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:621)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['ItzTwoost'/216, l='Village', x=-346.74, y=63.94, z=-403.63]]
	Chunk stats: ServerChunkCache: 2167
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Village
	Level seed: 8048637594413913139
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-240,68,-206), Chunk: (at 0,4,2 in -15,-13; contains blocks -240,0,-208 to -225,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 11718 game time, 11718 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 88686 (now: false), thunder time: 101452 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 703441296 bytes (670 MB) / 3493855232 bytes (3332 MB) up to 6524764160 bytes (6222 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7000m -Xms256m -XX:PermSize=256m
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		[1.14.4] SecurityCraft v1.8.14.jar SecurityCraft {securitycraft@v1.8.14 DONE}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		BetterCaves-1.14.4-1.0.1.jar YUNG's Better Caves {bettercaves@1.14.4-1.0.1 DONE}
		BiomesOPlenty-1.14.4-9.0.0.257-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.256 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		caelus-FORGE-1.14.4-1.0.1.jar Caelus API {caelus@FORGE-1.14.4-1.0.1 DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		colytra-FORGE-1.14.4-2.0.jar Colytra {colytra@FORGE-1.14.4-2.0 DONE}
		compressed_items-1.14.4-1.1.jar Compressed Items {compressed_items@1.14.4-1.1 DONE}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 DONE}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a DONE}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 DONE}
		DefaultOptions_1.14.4-10.2.6.jar Default Options {defaultoptions@10.2.6 DONE}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 DONE}
		embellishcraft-1.14.4-1.3.1.jar EmbellishCraft {embellishcraft@1.14.4-1.3.1 DONE}
		EnchantmentDescriptions-1.14.4-1.3.8.jar EnchantmentDescriptions {enchdesc@1.3.8 DONE}
		extragolems-9.0.4.jar Extra Golems {golems@9.0.4 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 DONE}
		glassential-forge-1.14.4-1.1.1.jar Glassential {glassential@1.1.1 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		jei-1.14.4-6.0.0.24.jar Just Enough Items {jei@6.0.0.24 DONE}
		metalbarrels-1.4.jar Metal Barrels {metalbarrels@1.4 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		Modpack Configuration Checker-1.14.x-v1.7.1.jar Modpack Config Checker {concheckrmd@1.7.1 DONE}
		MouseTweaks-2.12-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.12 DONE}
		mysticallib-1.14.4-1.6.0.jar Mystical Lib {mysticallib@1.14.4-1.6.0 DONE}
		Neat 1.5-19.jar Neat {neat@1.5-19 DONE}
		PrettyBeaches_1.14.4-3.0.7.jar Pretty Beaches {prettybeaches@3.0.7 DONE}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 DONE}
		Rays Dongles-1.14.4-2.0.4d.jar Ray's Dongles {slurpiesdongles@2.0.4d DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		traverse-1.14.4-2.0.0.jar Traverse {traverse@1.14.4-2.0.0 DONE}
		upsizer-mc1.14.4-5.0b2.jar Upsizer {upsizer@5.0.0b2 DONE}
		VanillaTweaks-1.14.4.1.5.10.jar VanillaTweaks {vanillatweaks@1.14.4.1.5.10 DONE}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 DONE}
		Aquaculture-1.14.4-2.0.2.jar Aquaculture 2 {aquaculture@1.14.4-2.0.2 DONE}
		forge-1.14.4-28.1.0-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['ItzTwoost'/216, l='Village', x=-346.74, y=63.94, z=-403.63]]
	Data Packs: mod:buildinggadgets, vanilla, mod:voxelmap, mod:vanillatweaks, mod:upsizer, mod:traverse, mod:theoneprobe, mod:swingthroughgrass, mod:slurpiesdongles, mod:securitycraft, mod:randomthings, mod:prettybeaches, mod:neat, mod:mysticallib, mod:mousetweaks, mod:modnametooltip, mod:metalbarrels, mod:jei, mod:harvest, mod:golems, mod:glassential, mod:forge, mod:fastleafdecay, mod:enchdesc, mod:embellishcraft, mod:ding, mod:defaultoptions, mod:cyclic, mod:cosmeticarmorreworked, mod:controlling, mod:concheckrmd, mod:compressed_items, mod:colytra, mod:clumps, mod:caelus, mod:biomesoplenty, mod:bettercaves, mod:arl, mod:aquaculture, mod:appleskin
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.5.0 - Build 23.20.16.4973
	OpenGlRenderer: Intel(R) HD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by MajorTuvok** [comment]
Could you try updating your Forge version? It says that you're referencing Forge 28.1.0 - which is kind of old compared to the current latest which is 89 if I remember correctly. 

As well as actually doing what I suggest...
Like **not dumping the exception message into the description**? Just use something like

**Comment by ItzTwoost** [comment]
I want to use optifine with 1.14.4 mods though.

**Comment by MajorTuvok** [comment]
@MichaelHillcox it might actually have produced when you introduced the Item burn time check as this Method seems to not exist in the recommended build. Should we add a hard requirement for the version in which this was added to Forge instead of only 28.1.0?

**Comment by MajorTuvok** [comment]
@ItzTwoost and?
Optifine is a kind of killer for a lot of things... It might even work if you remove Optifine...

**Comment by ItzTwoost** [comment]
????? Im 14, I don't understand most of the things you're saying.

**Comment by MajorTuvok** [comment]
Why does the fact that you want to use Optifine make you use this old Forge version?

And also Optifine is kind of annoying for mods and has a tendency to break mod renders...

**Comment by MajorTuvok** [comment]
(proposed solution update to latest Forge... We might add a requirement to a newer Forge version in the next release)

**Comment by MichaelHillcox** [comment]
Yeah, update your forge. Use this link: https://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.87/forge-1.14.4-28.1.87-installer.jar

**Comment by MajorTuvok** [comment]
Btw @ItzTwoost take a look at #406... That's a really good bug report...
