### ISSUE TITLE
additional keybinds dont work

### ISSUE THREAD

**Issue by redgoblin88** [Direwolf20-MC/BuildingGadgets#406]
* minecraft version
1.14

* Forge version
28.1.56

* Building Gadgets version
3.0.6a

* *If the issue is a crash*; An external link to the crash report

* How to reproduce the issue
by having a key, additional to your mouse and keyboard (for example, in the clip i made my mouse has two extra programmable thumb buttons) the gadget wont work, but note that vanilla is unaffected UNLESS gadgets is also set to it

* A screenshot, if applicable
how about a clip? https://imgur.com/a/yczhlCT

**Comment by MajorTuvok** [comment]
Notice that there is both a newer Forge and buildinggadgets version...
Could you verify with latest Forge and BG 3.1.1b?

**Comment by redgoblin88** [comment]
nope this still persists in forge 28.1.56 and building gadgets 3.1.1b

**Comment by MichaelHillcox** [comment]
I'll check the code but it might be an MC / forge issue... Let me check

**Comment by MichaelHillcox** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets/blob/cb752c7170c8fc550c4593420c966a81438ab4e7/src/main/java/com/direwolf20/buildinggadgets/client/gui/ModeRadialMenu.java#L441

From the looks of it we're handling the check correctly. I'll investigate

**Comment by MajorTuvok** [comment]
Could you verify with latest (>=.87) in case that was already fixed by Forge?
(Sorry, just want to make sure)

**Comment by MajorTuvok** [comment]
Could you maybe also add your latest.log (for example via a gist) for the record?
[it might also possibly contain extra information then the GL Error you send on Discord though that's rather unlikely in this case]

**Comment by redgoblin88** [comment]
here you go
https://pastebin.com/DGLXP6jx

interestingly i pressed the button THREE times with the default "g" and nothing happens, but when i change it to my custom button ("button 5" but i have no clue what keycode that will be) it throws the "GL" errors

so the GL errors are when i press with my additional key and not the "normal" key

**Comment by redgoblin88** [comment]
what i have found from a quick google is that keycode 4 (which appears what the GL is catching on) is a null value, but my mouse uses its 2 additional buttons for null values

**Comment by MajorTuvok** [comment]
@MichaelHillcox pointed out on Discord that there is a different approach we should be able to take - similiar to how chisels and bits did it in 1.12. Instead of relying on key Events we'd actively query the keybinding's pressed state.

I'm unsure whether this wouldn't just mask some underlying Forge/Vanilla bug, but is definitly something we can try out.

**Comment by MichaelHillcox** [comment]
We thank you for your issue report, unfortunatly we no longer support this version of Minecraft / Our mod. I've added your issue to a collection of issues that the community is welcome to create pull requests for. Hopefully your issue is resolved in time 👍 Master list: #535
