### ISSUE TITLE
Pulling from a Tile Entity shows insufficient blocks

### ISSUE THREAD

**Issue by Tfarcenim** [Direwolf20-MC/BuildingGadgets#407]
forge: 28.1.20
building gadgets 3.1.1b

Issue: Binding a building gadget to any Tile Entity and then using it to build will show insufficient blocks even if the te has enough blocks.  Right clicking will still place the blocks however

The following screenshots are in a dev environment with only Dank Storage (mod being worked on), Building Gadgets, and JEI
![image](https://user-images.githubusercontent.com/44327798/68734626-f322a500-05a8-11ea-931c-b8420cde07aa.png)
![image](https://user-images.githubusercontent.com/44327798/68734660-151c2780-05a9-11ea-81b3-c60ed8db1739.png)

**Comment by MajorTuvok** [comment]
Could you verify with latest Forge?
Thanks for the report

**Comment by Tfarcenim** [comment]
![2019-11-13_01-46-54](https://user-images.githubusercontent.com/44327798/68739738-895dc780-05b7-11ea-8845-c31a81b49e1c.gif)
same thing in 28.1.90

**Comment by MajorTuvok** [comment]
I presume that all three Gadgets which perform building are affected?

I think I also know why, but I don't have the time to explain it right now.

**Comment by Tfarcenim** [comment]
exchanging is affected as well, copy and paste doesn't seem to bind to TEs at all.

**Comment by MichaelHillcox** [comment]
I’ve noted this in our master list, this is a known issue

**Comment by MichaelHillcox** [comment]
Fixed :D Will release later. (Leaving open as I know it's an issue on 1.16 as well. 😢)

**Comment by MichaelHillcox** [comment]
Fixed will release soon :D
