### ISSUE TITLE
compatibility with Cubic chunks 

### ISSUE THREAD

**Issue by OresKa2** [Direwolf20-MC/BuildingGadgets#409]
Cubic Chunks is a mod that breaks the game up in 16³ cubes and with those cubes it allows for virtually unlimited dept and height.
The problem is that your copy and paste gadget can’t paste below Y=0 and with CC (Cubic Chunks) you can build there.
It would be great if you could add compatibility for this, maybe with some check if CC present allow paste below Y=0
These are some links to find CC:

Github:
https://github.com/OpenCubicChunks/CubicChunks

discord:
https://discord.gg/rq7YNK Barteks2X is the mod dev

**Comment by MichaelHillcox** [comment]
I'll look into it :)

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
