### ISSUE TITLE
Wired behaviour when server/client configs not in sync

### ISSUE THREAD

**Issue by SirFlip** [Direwolf20-MC/BuildingGadgets#41]
When you have different settings for "poweredByFE" on the server and the client.

Especially when server is in "vanilla mode" and client is in "rf mode" it kinda works but it looks like this after the first usage:
![2018-07-26_12 03 07](https://user-images.githubusercontent.com/6735323/43256595-7a8d3d5e-90cd-11e8-85aa-989df70bae57.png)

The other way round it works better (no missing block). but you also can't see how much charge is left.

Forge: 1.12.2-14.23.4.2739
Version: 1.6.1

**Comment by MajorTuvok** [comment]
(@see my pull request, that's why I synced the server-side config to the client...)

**Comment by SirFlip** [comment]
I just got another idea which just got into my mind I want to let you know of and is kind of related to this.
I use your mod as an early game tool in a sky-block world. (you get it pretty much for free at the beginning) So you don't have to run backwards shifting all the time ;). But there is no Power available this early. On the other hand Power-usage as balance would be nice for later when you are more advanced in the pack.

The tools use RF when they got charge and when they are out of charge they start to use up their durability. If its out of durability and charge you have to repair it or charge it up to use it again.

When one likes to only use only one method they could set the maximum durability/RF-capacity to zero.

What do think of this idea?

**Comment by Phylogeny** [comment]
I do know that the gadget model/texture will break when it has damage > 0 and max damage <=0. You can replicate that in single player by allowing a tool to take damage, then setting the durability config to <= 0 and reloading.

As for your suggestion, SirFlip; I like it, but one issue is how the durability bar should be displayed. I suppose it could represent the power level when it's greater than 0, and the item damage when the power is 0, but that could be confusing as to which one it's displaying. Perhaps some kind of icon overlay could render over the item when in an inventory to clearly indicate what the bar represents.

**Comment by SirFlip** [comment]
I thought of a visualisation like in EnderIO the DarkTools. With the durability bar and the blue charge bar above. So you can see from the colour of the bar wich mode is active.

**Comment by Phylogeny** [comment]
I just looked at some images of what you're referring to, and yeah, that would work great.

**Comment by MajorTuvok** [comment]
This should be resolved now

**Comment by hnOsmium0001** [comment]
@MajorTuvok I don't think this is fixed yet, from the latest commit today.
When I re-enabled powered gadgets, old gadgets with a damage value will have a missing texture.

![2019-02-07_16 56 10](https://user-images.githubusercontent.com/36975818/52452867-b5648d80-2af9-11e9-9cb4-96de9c2630d1.png)

**Comment by MajorTuvok** [comment]
wtf? Then this has some other source, as the poweredByFE setting is definitly synced.

**Comment by MajorTuvok** [comment]
Moment, how were you able to re-enable poweredByFE, which is @RequireWorldRestart?

**Comment by MajorTuvok** [comment]
For me this happens, as soon as I set the config of previously damagable Gadgets to 0... And I also can't set it back - I guess this bug results from returning 0 from getMaxDamage whilst the ItemStack already has some damage, which as you might expect confuses MC a little bit. As soon as one enters a damage value, above what was previously as damage on the stack, it works again.

**Comment by MajorTuvok** [comment]
As soon as you re-enable poweredByFE the same happens again - you have a 0 damage value on an stack with an higher damage value, because getMaxDamage now returns 0.

**Comment by MajorTuvok** [comment]
Notice however, that this is completly independant of the Config sync and should therefore gain it's own issue and this one can be closed-

**Comment by Phylogeny** [comment]
I don't see a way of fixing that without checking each tick for held/inventory items (and all the slots of the currently open GUI), just to reset the damage of any broken stacks one might ever encounter. And that's certainly not worth doing.

**Comment by MajorTuvok** [comment]
We might consider adding a note to use that once they've got durability in their worlds, they should not switch to FE...

**Comment by MajorTuvok** [comment]
Is it worth opening an "won't fix" issue for reference?

**Comment by Phylogeny** [comment]
Yeah, that's probably best.

**Comment by hnOsmium0001** [comment]
I think there's a way to make minecraft use the texture for meta=0 for other "unkown" meta values, but this is probably not worth it since 1.13 removes meta values and store damage in nbt instead.

**Comment by Phylogeny** [comment]
Fixed in v2.6.2
