### ISSUE TITLE
Futurepack vs Building gadgets crash issue 

### ISSUE THREAD

**Issue by darkrahmir** [Direwolf20-MC/BuildingGadgets#412]
So I use builder gadgets to do a good amount of my building. and when I used the building tool on a black metal slab it crashed my game and corrupted my world.

 Forge version:  forge-14.23.5.2847
Building Gadgets version: 	BuildingGadgets-2.7.4
If the issue is a crash*; An external link to the crash report
[crash-2019-11-19_20.28.25-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/3866862/crash-2019-11-19_20.28.25-client.txt)

How to reproduce the issue: use the building gadget on a futurepack mod black metal slab

**Comment by MajorTuvok** [comment]
Seems to be similiar to #354

**Comment by MichaelHillcox** [comment]
Simple fix for now to get in your world, load the world and as it's loading spam a different number key to the one your gadget is in. Then bin the gadget and give yourself a new one. I'll add a try catch around the area of code but ideally I'd like to fix it properly

**Comment by darkrahmir** [comment]
I just removed building gadgets then the world started i then reinstalled it 

Here is a link to the issue i opened on the futurepack github
https://github.com/mcenderdragon/Futurepack-API/issues/589

**Comment by MajorTuvok** [comment]
I answered to mc ender dragom how to fix it properly
