### ISSUE TITLE
Building Gadget CTD 1.14

### ISSUE THREAD

**Issue by Flatts3000** [Direwolf20-MC/BuildingGadgets#420]
The crash occurred while using build to me mode on the Building Gadget building with gravel in creative. I was clicking quickly whenever it happened.

MC Version: 1.14
BG Version: 3.0.5
crashlog: https://pastebin.com/s7c8FHEK

**Comment by MichaelHillcox** [comment]
Looks like you're on an old version of the mod. Can you update and let us know if the issue persists.
