### ISSUE TITLE
[Suggestion] Circular walls based on diameter or radius 

### ISSUE THREAD

**Issue by MikeHollisJr** [Direwolf20-MC/BuildingGadgets#421]
Add Horizontal wall shape Circle
Add Vertical wall shape Circle 
Add Build to me shape Circle

**Comment by MichaelHillcox** [comment]
We'll likely add some level of shapes but at the moment we're unsure. We'd likely opt for a `surface` mode approach instead of adding 3 modes like you've sugggested. I can understand the want for this though.

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
