### ISSUE TITLE
Log spam from gadget

### ISSUE THREAD

**Issue by Trinsdar** [Direwolf20-MC/BuildingGadgets#423]
* Forge version: 14.23.5.2847
* Building Gadgets version: 2.7.4
* Log(Partial since what I linked is only what really matters): https://gist.github.com/Trinsdar/a19327dd125789b04c13eaf158de475b

**Comment by xGarionx** [comment]
Can confirm the issue, makes tracking of actual problems really difficult

**Comment by Uimori** [comment]
Not sure if this will help anyone. But we ran into this problem as well.

The direct cause was an Exchanging Gadget was left in an Energetic Infuser from Thermal Expansion (specifically a Hardened one with the Augment: Flux Linkage Concentrator).

Did not test it with any other charges as we were just glad to be rid of the spam!

**Comment by MajorTuvok** [comment]
We already found the issue guys...

**Comment by MajorTuvok** [comment]
See #324... I unfortunatly still can't manage issues, which is why I haven't been answering this and closing it in favor if the older one...
