### ISSUE TITLE
Crash at startup FTB Revelelations with Dire

### ISSUE THREAD

**Issue by Zang518** [Direwolf20-MC/BuildingGadgets#424]
* Forge version: 14.23.5.2846
* Building Gadgets: 2.7.4 and 2.7.3
* *If the issue is a crash*; https://pastebin.com/y3sKPS05
* Am following DireWolf in the FTB Revelations 3.21 series and added building gadgets just like DireWolf and the game crashes at startup. If I remove building gadgets, the pack loads up fine. I read that 1.12 version updates will slow down or stop but hoping there might be a quick fix.

Thanks.

**Comment by MajorTuvok** [comment]
Interesting, this is a compat problem with mekanism...
In particular mekanism tells us, that a "dexonstructpr recipe" is registered in the wrong loading phase - you could try up or downgrading the mekanism version to see whether that helps.

**Comment by Zang518** [comment]
Sorry I've been away. Will try that and report back

**Comment by Zang518** [comment]
Updated Mekanism to the latest version as of 12/27/19 and MC no longer crashes.
