### ISSUE TITLE
Suggestion: Gap Fill Mode?

### ISSUE THREAD

**Issue by ChaosExAnima** [Direwolf20-MC/BuildingGadgets#428]
Hi there! I'm wondering if it may make sense to create a "fill mode", where Building Gadgets fills gaps with a selected block _behind_ the block you're looking at. This would be useful if say you build a structure but want to eliminate gaps that mobs could spawn in. The range selector could control how wide of an area you fill is.

Hope I'm making sense? I don't actually play MC a lot, but I watch Dire constantly fill blocks left by his Dire Wire made me think of this. :)

**Comment by MajorTuvok** [comment]
This should already be possible by deactivating "place atop". Just remove the block you're looking at and perform a placement without "place atop" on the block behind it - or if you don't want to change that setting remove another block and leave it active...

I actually don't see why you'd need another mode for that?

**Comment by MajorTuvok** [comment]
I presume that it's faster for Dire to manually fill in a few blocks, then to switch to BG and select a matching block.

**Comment by MichaelHillcox** [comment]
This can be achieved anyway as described above. Thanks for the suggestion though ❤️
