### ISSUE TITLE
Modifying block model to support 3D model json

### ISSUE THREAD

**Issue by PhantomSmithy** [Direwolf20-MC/BuildingGadgets#429]
I had emailed Direwolf about this earlier and he asked that I drop it in the GitHub so he can look into it.

Essentially I am working on a resource pack for the mod in its 1.14.4 state, that would setup 3D models for some of the block elements in the mod. I have run into an issue where Minecraft will cull the faces of the adjacent blocks as it assumes it's touching another 16x16 block.

I was told by another model maker that the mod itself needed to be coded to ignore adjacent models and not to cull those faces. Their exact words were "to change the culling properties of those blocks".

I've attached a rough model just to show what the issue is.

![2020-02-02_18 04 40](https://user-images.githubusercontent.com/60587183/73617655-a0c0b580-45e6-11ea-9116-5abe55d03fd2.png)

If you have any questions I can reply with an answer to the best of my ability. Thank you.

**Comment by MichaelHillcox** [comment]
Hi, this seems more like a you issue :P as you're trying to turn a non-culling block into a culling block. It would be illogical for us to change this as our block does not have culling nor does it require it. We're always looking for texture changes though and I like what you're working on. Please feel free to fork the mod and submit your changes to the mod 👍

**Comment by MichaelHillcox** [comment]
Closing this but we're still completely open for you to make a PR adding propsing your new models to the mod to become the mods offical ones as they look really nice. :+1:
