### ISSUE TITLE
Copy and Paste tool, not copying right information

### ISSUE THREAD

**Issue by BrandonGamesYT** [Direwolf20-MC/BuildingGadgets#430]
Just trying to create a copy of something with the copy and paste tool on a server i played in 1.14.4 a while back that i wanted to move to a different server i am now playing on but the copy of the code is copying like this 

`{
  "header": {
    "version": "2-beta",
    "mc_version": "1.14.4",
    "bounding_box": {
      "min_x": 0,
      "min_y": 0,
      "min_z": 0,
      "max_x": 0,
      "max_y": 0,
      "max_z": 0
    },
    "material_list": {
      "root_type": "buildinggadgets:entries",
      "root_entry": []
    }
  },
  "body": "H4sIAAAAAAAAAONiYOBkYElJLElkAAFOBuaC/GIwk4uBLSM1MSW1CMhIyi/NSylmZmDJzcyLBElCmBEwZmJFFIIZiWBGINSCFYAs4CpOLcpMzMmsSi2CCAEAbCuw1YMAAAA\u003d"
}`

And not actually copying as the structure I am trying to copy
went back and watched the spotlight video to see if i was doing it right and it seems to be so. 
Thanks for any help!

**Comment by MajorTuvok** [comment]
Avvording to the header you've copied a single block region... 
I wonder, does the following help:
`{ "body": "H4sIAAAAAAAAAONiYOBkYElJLElkAAFOBuaC/GIwk4uBLSM1MSW1CMhIyi/NSylmZmDJzcyLBElCmBEwZmJFFIIZiWBGINSCFYAs4CpOLcpMzMmsSi2CCAEAbCuw1YMAAAA\u003d" }`
(It should not, but worth a try)
Also does it work within the world, aka after copying are you able to paste in?

**Comment by BrandonGamesYT** [comment]
Tried both of those things and doesnt work either way no

**Comment by hvdklauw** [comment]
Yeah, any chance for a fix? 

Thought it was a format change in 1.14 I couldn't copy a 1.12 paste, but it just crashes the game right now.
https://www.reddit.com/r/9x9/comments/g823pb/meta_enigmatica_4_starter_big_base_world_save

**Comment by MajorTuvok** [comment]
Could you give us a stacktrace?

**Comment by hvdklauw** [comment]
Weird, it worked for a while before I got it to crash.

[debug.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/4535155/debug.log)
[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets/files/4535156/latest.log)

**Comment by MajorTuvok** [comment]
Hmm, need to look at that from my laptop (my mobile is having trouble viewing the file, so that I'm only see parts) - but I did see some other mods recipe reload listener in the stacktrace...

**Comment by MichaelHillcox** [comment]
We thank you for your issue report, unfortunatly we no longer support this version of Minecraft / Our mod. I've added your issue to a collection of issues that the community is welcome to create pull requests for. Hopefully your issue is resolved in time 👍 Master list: #535
