### ISSUE TITLE
Suggestion: Exchanging Gadget With Stairs

### ISSUE THREAD

**Issue by theboo** [Direwolf20-MC/BuildingGadgets#431]
A suggestion would be to make it so when using the exchanging gadget on stairs, the newly placed stairs are orientated the same way as the previous stairs. Currently there is no way to exchange upside down stairs. Or at least give the ability to flip blocks, mirror and rotate will not allow you to flip stairs upside down.

**Comment by MajorTuvok** [comment]
How do you define 'previous' stairs? Are you maybe talking about keeping properties of the blocks which were present, before they were exchanged? Aka you're talking about replacing stairs with other stairs...?

If so, why can't you select upside down stairs and exchange afterwards?

**Comment by theboo** [comment]
ah, and i am an idiot... i just needed to select upside down stairs... closing, thanks
