### ISSUE TITLE
[1.12] Block duplication bug with Exchanging Gadget and slabs

### ISSUE THREAD

**Issue by dh458** [Direwolf20-MC/BuildingGadgets#432]
----------------------------------------------------------------------------
Version Information:
* Forge Version 14.23.5.2847 (1.12.2)
* Building Gadgets version 2.7.4

The Exchanging Gadget can be used to duplicate blocks in just a few easy steps:
1. Shift + right click a block consisting of two slabs on top of each other to select it. (In this example, I picked two stone slabs stacked together into one block space.)
2. In the player inventory, put one slab into a slot towards the left and bottom, and any number of slabs into the slots to the right.
3. Point at a block with the exchanging gadget and right click it. 
The targeted blocks remain in the world but are also duplicated to the player's inventory (or spit out into the world if the inventory is full.) The number of slabs available in the player inventory remains the same, and the exchanging gadget's available power decreases. 

Tested with modpacks "Enigmatica 2 Expert" and "SkyFactory 4". Also tested with a trimmed down modpack consisting of Actually Additions, Building Gadgets, and JEI.

You only really need two slots in the inventory - a left slot with one slab and a right slot with the rest.
![Before](https://user-images.githubusercontent.com/4950495/74580629-41628e00-4f74-11ea-9cf0-3113db2a22be.png)

Slabs do not disappear from the player inventory during the block exchange, but the picked blocks act as if they were mined anyway. (Fuzzy mode used in this screenshot for effect.) 
![During](https://user-images.githubusercontent.com/4950495/74580636-48899c00-4f74-11ea-8f15-e20581239628.png)

Bonus shot after a little clicking with a full inventory.
![BonusShot_AfterFullInventory](https://user-images.githubusercontent.com/4950495/74580638-4b848c80-4f74-11ea-9947-dfdfafc4a84f.png)

Silk touch on the exchanging gadget does get applied to ores and bookshelves.
The dupe bug works on crafting tables, pistons, and anvils, but not enchanting tables or glass.

Certain modpacks have blocks that do not get duplicated: 
The osmium block from Mekanism gets removed from the world and added to the player inventory without the slabs being exchanged. (Osmium ore can be duplicated, though.) Environment Tech litherite blocks and Tinkers Construct seared blocks can't be duplicated either.

**Comment by MichaelHillcox** [comment]
Christ, I'll see if I can fix that : )
