### ISSUE TITLE
Allow additional Features via Upgrades

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#433]
Abstract: 
As @MichaelHillcox is already extracting common features from Buildinggadgets and MiningGadgets into some GadgetsCore or similiar mod, I'd like to discuss moving some features onto upgrades instead of enchants or additional GUI Elements, as well as adding entirly new features only via upgrades.

Suggestion: 
At the moment we keep adding more and more GUI elements to the ModeRadialMenu, which are rarely used all together. Instead we could enable the specific additions by installing and uninstalling the upgrades via the upgrade block which is currently only in mining gadgets. If on-the-fly modifications are needed, we could add some 'settings'-like button in the Radial Menu, which would then link to a GUI listing all installed upgrades and their options. 
Either way we would no longer keep filling the RadialMenu with more and more buttons/toggels and could add things like an energy use/capacity upgrade or move the enchanting to upgrades too. As an additional benefit, both mods would now work more similiar.

Implementation:
Move the upgrade block and upgrade base, as well as upgrades which are present in both mods to the GadgetsCore, as well as some UbgradableItem base class. To add the settings menu, one could for example do by enumerating all installed upgrades and giving each upgrade the ability to render it's own settings.

**Comment by MichaelHillcox** [comment]
So this ended up getting a no from Dire so I'm going to close it for now but we can revisit this issue.
