### ISSUE TITLE
Building Gadgets Stopped Working / Errors in Logs

### ISSUE THREAD

**Issue by Xanarios** [Direwolf20-MC/BuildingGadgets#435]
Forge version: 14.23.5.2847
Building Gadgets version 2.8.0
Logs: https://pastebin.com/LZifEx7i or as attached, [latest.log.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/4228915/latest.log.txt)

Error Snippet:
`[00:00:57] [Client thread/WARN]: Failed to load texture: buildinggadgets:textures/gui/setting/undo_colored.png
java.io.FileNotFoundException: buildinggadgets:textures/gui/setting/undo_colored.png`

The latest release (2.8.0) stopped working after a while; attempts to use the exchange gadget or the building gadget, with the appropriate materials and RF in inventory, results in failure and warnings / errors in the logs.  No blocks are placed or exchanged.  It is unclear what lead to this failure state, as it was working OK for a number of exchanges prior to these warnings.

Loading the same world in 2.7.4 does not cause the problem.

**Comment by MajorTuvok** [comment]
Could you test, whether this occurs with only BuildingGadgets installed, or if not, with what mod it is conflicting?

What Blocks were you working with?

**Comment by MichaelHillcox** [comment]
This is a well known issues I'll log it for memory's sake regardless. It's due to a bad bit of code from an old developer

**Comment by MichaelHillcox** [comment]
So, I don't know about this one, the texture issues have existed since the new Gui, I'll see if I can pull in a different branches fixes for this.

I have no clue why the tool would stop working? Did the render go red? I need more details please

**Comment by Xanarios** [comment]
It basically stopped placing blocks.  Say for the building gadget, the ghost preview of the placement of a column would render but when right clicking nothing would occur.  No blocks would be removed from inventory, nothing would render into the world, and no blocks would be placed.

I've got some free time today to try to isolate and repeat the issue.

**Comment by Xanarios** [comment]
It looks like the issue is tied back to being unable to pull from the dank/null.  I was able to recreate the behavior with a minimal modset {JEI 4.15.0.291, Dank Null 1.7.89, Building Gadgets 2.8.0, p455w0rd's Library 2.3.161} w/ Building Gadgets configured to "Powered by Forge Energy"=false

Starting with a fresh world:

1.  Spawn in dank/null and assorted Blocks.  Fill accordingly.
2.  Spawn in building gadget(s).
3.  Attempt to build or exchange w/ blocks found only in dank/null inventory.  Ghost preview is grey, indicating that the build or replacement has enough items and power.  Expected behavior would be to pull from the dank/null inventory.  Nothing happens and configuration of dank/null (extract or placement behavior) in inventory has no impact.  Attempting to build with a block that is not in the player inventory or the dank/null results in a red preview and no action, as expected.
4.  Take out several blocks from the dank/null and place them in player inventory.  Building gadgets pull from inventory first and now work as expected.  Once the player inventory is depleted, the gadget reverts to behavior in step 3, as if there is no block available for placement, even with the dank/null full.

Building Gadgets 2.7.4 pulls from the dank/null in this situation as expected.

**Comment by MichaelHillcox** [comment]
This is my fault although, my implementation is a 1:1 replica of the old so I'll have to figure this one out. Thanks for the report and the extra info

**Comment by MichaelHillcox** [comment]
Related to #437
