### ISSUE TITLE
Building gadget no longer works with dank null

### ISSUE THREAD

**Issue by donnymoonshine** [Direwolf20-MC/BuildingGadgets#437]
Forge version 1.12.2-14.23.5.2847
Building gadgets version 2.8.0
 
Don’t think screen shot is necessary for this one pretty self explanatory the building gadgets cannot pull from the dank null any long after the inventory fix I’m guessing

**Comment by MajorTuvok** [comment]
Missing calls of extractFromInventory on the handlers return by findInvContainers [here](https://github.com/Direwolf20-MC/BuildingGadgets/blob/c27326c664c3de9249c6acf32867430a4bec0696/src/main/java/com/direwolf20/buildinggadgets/common/tools/InventoryManipulation.java#L121)... @MichaelHillcox you should also revist where else the remote Inv should also be scanned...

**Comment by MichaelHillcox** [comment]
I'll get to this.

**Comment by MichaelHillcox** [comment]
Right, I see the issue https://github.com/Direwolf20-MC/BuildingGadgets/commit/58cf3a6ef097c6c5d172037623df0c9632a31427#diff-42bdbabf11231ae7cfc5fca82bfb5ba7L132 I must have missed this part, I'll sort it out when I'm home. I've got a small bucket list of things I'd like to fix so I'll push and update this afternoon.
