### ISSUE TITLE
copy past gadget includes unneeded astral lights and pasted them as black blocks

### ISSUE THREAD

**Issue by donnymoonshine** [Direwolf20-MC/BuildingGadgets#438]
Forge version 1.12.2-14.23.5.2847
Building gadgets version 2.8.0
Copy paste gadgets take astral sorcery spectral lights and try and paste black construction paste blocks where they were 
![56C4DB52-545D-4716-AA18-F0CF0EF43C00](https://user-images.githubusercontent.com/58052413/75011538-8475a300-5445-11ea-806d-44c07b2dcd0a.jpeg)
![C5FA5059-2AD8-4779-81C5-7CD29E58148E](https://user-images.githubusercontent.com/58052413/75011569-922b2880-5445-11ea-82c8-497976506784.jpeg)
![FEB94235-90C4-4011-B6AD-CE71259A0391](https://user-images.githubusercontent.com/58052413/75011595-a3743500-5445-11ea-8a14-c866eee13cb0.jpeg)

One image shows the lights I’m referring too the other shows them as construction paste

**Comment by MajorTuvok** [comment]
I think this is an old issue... I presume we need to whitelist some part of the blockstate to make them work

**Comment by MichaelHillcox** [comment]
Yeah, that would make sense, I'll add them to a whitelist / make a whitelist to support them.

**Comment by MichaelHillcox** [comment]
I've add it to our default blacklist as the block has some weird properites regardless of anything else. It only works on newly generated configs (😢) so you'll need to find the `blacklist` section of your config and add this line `"astralsorcery:blockflarelight"`. The mod already supports this so you don't have to wait for me to release `2.8.1`
