### ISSUE TITLE
Crash in Forge 28.2.1 (1.14.4)

### ISSUE THREAD

**Issue by Rensik** [Direwolf20-MC/BuildingGadgets#439]
* Forge version

Forge 28.2.1

* Building Gadgets version

buildinggadgets-3.1.1b

* *If the issue is a crash*; An external link to the crash report

https://paste.gg/p/anonymous/5d1db838dbe6436e995a79ef61d8a5ca

* How to reproduce the issue

Load Minecraft.

**Comment by MajorTuvok** [comment]
Am I wrong, or is this an outdated Forge version?

**Comment by MajorTuvok** [comment]
Just verified, that this is not the bug I thought it was...
Could you please provide the latest.log instead of the crash log as well as testing it without other mods involved?

**Comment by Rensik** [comment]
latest.log
https://paste.gg/p/anonymous/88ba172cf12e4b589415c045d3a726ed

Loads without other mods just fine.

**Comment by Rensik** [comment]
Found the conflicting mod: betterTotem1.0-1.14.4

**Comment by MajorTuvok** [comment]
Thanks @Rensik I sadly don't know why this is conflifting eith BG, but Ibguess @MichaelHillcox cannfind that out?

**Comment by Rensik** [comment]
It was also conflicting with Shadows of Fire's mod Apotheosis. He posted, "Then it would be a bug in that mod, likely for invoking getSubItems before registry phase has ended." Probably not something Building Gadgets can do something about.

**Comment by MichaelHillcox** [comment]
My only thought is that we're not in that forge version. I may push a forge bump to see if that resolves these issues

**Comment by MajorTuvok** [comment]
> for invoking getSubItems before registry phase has ended
If someone indeed does this, then I know why it crashes... We could maybe add another null check to resolve this, but we kind of rely on our registries to be created before someone invokes Mc's SearchTreeManager...

**Comment by MichaelHillcox** [comment]
Closing this. Please confirm if it's still an issue in the later releases of 1.14 :+1:
