### ISSUE TITLE
Per layer(s) Copy-Paste Gadget

### ISSUE THREAD

**Issue by SirXudes** [Direwolf20-MC/BuildingGadgets#440]
I would love a feature like the Schematica mod but then with the gadget for pasting layer-layer instead of all of it at once. My server can't handle a a 23x21x23 structure from NuclearCraft (pretty mod heavy pack) and I think it would be nice to be able to do like 5 layers at a time or something.

**Comment by MajorTuvok** [comment]
This is already in 3.1.0 an won't be backported to the 1.12 versions (to the latter - I'm right @MichaelHillcox)

**Comment by MichaelHillcox** [comment]
Yeah, this won't be coming back to 1.12 as 1.12 is no longer a Forge supported versions. All activity on 1.12 will be simple patches to clean up some bad code left behind that is causing issues.
