### ISSUE TITLE
New gadget: cut and replace gadget!

### ISSUE THREAD

**Issue by aleZZ1994** [Direwolf20-MC/BuildingGadgets#442]
Hello :) I'm literally happy with this mod because it's very easy to use and very helpful but the only flaw is that there is no possibility to cut and move a selected part. I think It's very helpful so I hope to be implemented soon. Thank you for the attention. Bye :)

**Comment by MajorTuvok** [comment]
We already planned that last year, and some time ago someone else requested this - we just did not get to it...
Sorry...

**Comment by MajorTuvok** [comment]
Duplicate of #381
