### ISSUE TITLE
Allow MaterialList to be pinned 

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#444]
3 days ago some users on Discord pointed out that it's hard to remember, which Items are needed for a paste which has many different Items. They therefore suggested to add a `Todo List` similiar to how it seems [possible in Satisfactory](https://satisfactory.gamepedia.com/To_Do_List). I thought that in order to achieve this, if we want to, we could "pin" the MaterialList somewhere on the Screen's GameOverlay. We just need to cache the list in some static var as long as it is visible and render from the GameOverlayEvent...

**Comment by MichaelHillcox** [comment]
This is a great idea for 1.15 and maybe even 1.14 but will have to see about the back port haha

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
