### ISSUE TITLE
Allow User mined blocks to directly flow into the build

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#445]
Alongside #444 it was also suggested to allow someone to mine remaining blocks with a MiningGadget and directly put them into a copy paste build.

Whilst this seems achievable, I personally think that this would be too much effort for too little gain.

**Comment by MichaelHillcox** [comment]
I don't think this is worth the time.

**Comment by MajorTuvok** [comment]
Good, now that 2 out of 3 people agree, I guess we can safely close this unless Dire specifically wants to implement this
