### ISSUE TITLE
Implement a Combined Gadget like the Akashic Tome

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#446]
It was suggested on Discord, to allow a Gadget which holds the other Gadgets and then let's the user use one Gadget or cycle through them - just like the Akashic Tome. The only name proposal that was given was the "Go-Go-Gadget" which I personally don't like - need to find a name for this.

**Comment by MichaelHillcox** [comment]
We'll need dires approval for something like this

**Comment by MajorTuvok** [comment]
Other Name suggestions were "Akashic Gadget", "Omni-Gadget" and "AIOG". @Direwolf20-MC what do you think about this in General?

**Comment by MichaelHillcox** [comment]
I think it avoid the point of the gadgets being separate. I'm also unsure as to how you'd select each one and make it simple and smooth enough to counter just switching it in the inventory. Like I said, we need dires approval. I'm not against it but I feel like it's feature stacking.

**Comment by MajorTuvok** [comment]
In my opinion it doesn't contradict the Gadgets being seperate. The Akashic tome just functions as a container for other tomes, of which one might be selected. If we do the same, this would allow people to avoid
1. Using multiple inventory slots to have all gadgets ready
2. Avoid searching where they put Gadget b), when Gadget a) is in chest x

A potential interface could allow cycling through the Gadgets with some keybind or shift click and then all other operations are just delegated through to it.

**Comment by MichaelHillcox** [comment]
Closed as dire has declined.
