### ISSUE TITLE
Curve-/SurfaceGadget

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#447]
# Idea
A user on Discord suggested to add a Gadget for creating curves similiar to how one can do that in some Graphics Programs like Adobe Photoshop/Illustrator. An example of the underlying [bezier curves](https://en.wikipedia.org/wiki/Bézier_curve) at work can be seen [here](https://www.jasondavies.com/animated-bezier/). 
## Implementation
As implementing them is really easy using [de-Casteljau's Algorithm](https://en.wikipedia.org/wiki/De_Casteljau%27s_algorithm), I'd suggest going one step further and allow people to build Bezier Surfaces. The evaluation of them is just the intuitive way, for a 2D set of control points, first evaluate the bezier curves for "all first dimensions" and then evaluate the second dimension by using the first dimension bezier curves as control points.
The interesting part would be mapping the curve points onto 3d blocks - a good and simple start would be to adapt interval bisection/binary search, stopping when an already known position is found. Whilst this would not guarantee to find all blocks, which are touched by the surface, it would guarantee to find all blocks which are touched by substantial amount of it and also guarantee to generate a connected surface. 
## Interface
The tricky part would propably be finding a intuitve way to select the control points - we could for example go via having a selection mode and a build mode. In selection mode you can add new "control blocks" to the current section by (shift) clicking them and cycle through selections (which would be highlighted in the render) via shift/ctrl+scroll wheel. To add a new section use ctrl+click on a first block and then add more to the section. In the future we might possibly add a gui to view the selections.
# Advantages
I think the advantages of this are obvious. Building large, curved surfaces or even just curves could help people a lot.

**Comment by MichaelHillcox** [comment]
This can't be a new gadget as it would fall under "Adding a gadget that only slightly does something different from the it's counter part". Although, if we could find a way of making this work for the Building Gadget then I'd love to see how this would be implemented.

**Comment by MajorTuvok** [comment]
To sum up a discussion on github. @MichaelHillcox had the nice idea of adding a gui to the building gadget for configuring the curves. First of all we'd differ between planar curves, 3d curves and  surfaces. The latter would be formed in a range×range×range grid, whilst the firat would of course be formed in a range×range grid. On the right hand side of this UI would be an editable list with the control points, a setting for the to 3d distance metric and possible weights. 

I'd also like to use Bezier-B-Spline curves instead of traditional Bezier curves, as the possibilty of choosing the interpolation degree gives users more control about how close the curve matches itself to thw control points.

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
