### ISSUE TITLE
Feature Request - Cutting for C/PG and BG

### ISSUE THREAD

**Issue by Tahakk** [Direwolf20-MC/BuildingGadgets#449]
**DESCRIPTION**
This function would allow to do cleanup of area before it build in it so that you don't have to spend time to figuring out if your build fits in the place of your choosing.
Cleaning the while area (voiding the blocks) from start (x1, y1, z1) to the end (x2, y2, z2) or just at the exact place where the blocks are going to be build, I'll let that on the guys implementing it.

**AFFECTED GADGETS**
[Building Gadget](https://github.com/Direwolf20-MC/BuildingGadgets/wiki/Building-Gadget)
[Copy Paste Gadget](https://github.com/Direwolf20-MC/BuildingGadgets/wiki/Copy-Paste-Gadget)
[Destruction Gadget](https://github.com/Direwolf20-MC/BuildingGadgets/wiki/Destruction-Gadget)**\***

*\*depends on implementation*

**IMPLEMENTATION**
1. New button in the GUI for Cutout
2. Automatic function while holding Destruction Gadget in the offhand
3. Automatic function when DG is in your inventory suggested by @MajorTuvok after some discussion

Looking forward to discuss this and fine-tuning this feature request

**Comment by MajorTuvok** [comment]
> Automatic function while holding Destruction Gadget in the offhand
> New button in the GUI for Cutout
I'm pretty sure that we can't do it with only one of the being the case, but rather need both to be active at the same time. There is a certain risk of someone having the destruction Gadget in their hand and then wanting to finish their build...

**Comment by Tahakk** [comment]
I was thinking it as 1. **or** 2.

**Comment by MajorTuvok** [comment]
> I was thinking it as 1. OR 2.

And I think it would be best to do 1 and 2 or if Dire allows this, just 1.

Notice that for the copy paste Gadget it is normally an intended feature, not to void the area, as this allows you to build the part for which you have the blocks now, and come back later when you have the rest.

**Comment by MajorTuvok** [comment]
> Automatic function when DG is in your inventory suggested by @MajorTuvok after some discussion
To make this automatic function a bit more specific: it should only activate when the cutout mode is selected as an option on the gadget.

**Comment by MajorTuvok** [comment]
Also to make it more consistent with how it looks to a user: I think we should go for the void everything in the area option and not only where the build blocks are. Aka "you apply the destruction Gadget before you build", just in one click, instead of 2.

**Comment by MichaelHillcox** [comment]
I’ll talk with dire and see what he think about this. I’m thinking 1 and 2 are likely the most logical.

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
