### ISSUE TITLE
[Request] Single block mode

### ISSUE THREAD

**Issue by scribbler957** [Direwolf20-MC/BuildingGadgets#45]
I've noticed I frequently switch to the 1 block length to touch something up, rather than cycle all the way through the options, I'd like a single block mode.
Thank you.

PS Get Morvelaira Little Tiles or Masilis Doors so she can put in some decent doors. ;) Thanks for the fun.

**Comment by Direwolf20-MC** [comment]
I’ve honestly considered this. Just haven’t been able to decide if it’s a good idea or not. Let me think on it some more. Too many modes might be annoying

**Comment by SirFlip** [comment]
Or maybe also an GUI to select the range

**Comment by MajorTuvok** [comment]
Using a gui to select the range would be overdone in my eyes - in stead of just changing it (which happens quite often to me) you'd always have to open that and then select.
Also it would become more difficult to adjust the range based on how big you want it to be cause you'd have to reopen it for every change...

**Comment by Direwolf20-MC** [comment]
I considered this, but several modes allow for 'single block' placing, such as vert column, horizontal column, and build to me. I'm gonna close this for now but if I change my mind I'll re-open.

**Comment by scribbler957** [comment]
I was actually thinking of the exchanger, but the shift-to-reverse functionality usually does well enough.
Thanks for considering and thanks for the mod.
