### ISSUE TITLE
[1.15.2] Text in buttons in template manager invisible when items in JEI are behind

### ISSUE THREAD

**Issue by 016Nojr** [Direwolf20-MC/BuildingGadgets#456]
![BG](https://user-images.githubusercontent.com/8192699/77832951-f4103980-7139-11ea-8efd-37c6103dc6fa.jpg)

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/77869437-22dcfb80-7271-11ea-8fc5-fe8ea74953e4.png)
What is this? 1.15 support Botania?

**Comment by MichaelHillcox** [comment]
> ![image](https://user-images.githubusercontent.com/10114685/77869437-22dcfb80-7271-11ea-8fc5-fe8ea74953e4.png)
> What is this? 1.15 support Botania?

Yes

**Comment by EnterFor** [comment]
> > ![图片](https://user-images.githubusercontent.com/10114685/77869437-22dcfb80-7271-11ea-8fc5-fe8ea74953e4.png)
> > 这是什么？1.15支持波塔尼亚？
> 
> 是

Where can I download it? Curseforge didn't find

**Comment by MichaelHillcox** [comment]
It might still only be in ForgeCraft as the reported found it on the ForgeCraft server
