### ISSUE TITLE
[1.15.2] Impossible to use gadgets in survival mode

### ISSUE THREAD

**Issue by ChabaudieMaxime** [Direwolf20-MC/BuildingGadgets#459]
Forge version : 31.1.30
Building Gadgets version : 3.3.4

It's impossible to use any gadget in survival, they have a "energy" mode and a energy bar but there is no item that can fill it and no "charge station".

**Comment by MichaelHillcox** [comment]
You're meant to use it with other mods but if you don't have other mods or don't want other mods and you don't care for the power requirement then go into the config and set the max energy (I think) to 0 and it'll no longer use power

**Comment by ChabaudieMaxime** [comment]
Config files are empty, what is the correct syntax for this ?

**Comment by MichaelHillcox** [comment]
You playing on single player? if you are, then you need to go into your wold folder/serverconfig/buildinggadgets-server.toml (if I recall correctly)

**Comment by ChabaudieMaxime** [comment]
No in multiplayer but I find it in my server config files, thank you ! (It could be interesting to indicate with which mods the energy is suitable)
