### ISSUE TITLE
exchanging gadget 

### ISSUE THREAD

**Issue by gamingwithpeter25** [Direwolf20-MC/BuildingGadgets#460]
i have found something wrong with the exchanging gadget i sometimes get the block.buildinggadget.effect_block.name it picks the temporary block and makes it a solid block and you have to break the temporary block and put the block you want to change it to in its place

**Comment by MichaelHillcox** [comment]
Hmm, intresting. Is this on 1.15? and could you follow the template next time as it greatly speeds up the fixing process.

* Forge version
* Building Gadgets version
* *If the issue is a crash*; An external link to the crash report
* How to reproduce the issue
* A screenshot, if applicable

**Comment by gamingwithpeter25** [comment]
Minecraft 1.15.2
forge version 31.1.30
version - buildinggadgets-3.3.4
Does not make the game crush
shift-right click half way though the charging of the block to get the temporary block
creative mode and in survival mode
![creative mode](https://user-images.githubusercontent.com/31567250/78257512-d94f1380-74f1-11ea-8b89-238751e6345b.png)
![Survival mode](https://user-images.githubusercontent.com/31567250/78258295-ed474500-74f2-11ea-95e6-a6fa2a8d61d0.png)

**Comment by MichaelHillcox** [comment]
I swear I fixed that! alright, thanks. I'll see if I can reproduce that

**Comment by gamingwithpeter25** [comment]
your welcome :)
