### ISSUE TITLE
[1.15.2]Client crash

### ISSUE THREAD

**Issue by EnterFor** [Direwolf20-MC/BuildingGadgets#464]
After deleting this template, please provide the following information:
* Forge version:31.1.35
* Building Gadgets version:1.15.2 latest
* *If the issue is a crash*
[crash-2020-04-04_16.55.32-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/4431039/crash-2020-04-04_16.55.32-client.txt)

* How to reproduce the issue:When I searched for '存储' with JEI, the client crashed and the server remained intact.

**Comment by MajorTuvok** [comment]
Notice that we have no clue what these chinese, japanese, whatever symbols mean

**Comment by MajorTuvok** [comment]
Nor have we a way to type them in

**Comment by EnterFor** [comment]
This may not be your problem, but I don't know why there are Building Gadgets..
https://github.com/FifouBE/EconomyInc/issues/16

**Comment by MajorTuvok** [comment]
Whilst this might be correct, it may happen that we release another version and from that point on it is unclear which version was meant. Also it is easier to find out in the future what this was about, when one knows ghe verwion number.

**Comment by EnterFor** [comment]
I see what you mean.
I'm sorry, it's my fault

**Comment by MajorTuvok** [comment]
Also I believe that this can be closed temporarily, as the dev of FifouBE pointed out, that his block would still be a WIP. This can always be reopened if it appears unfixable on his end.

**Comment by EnterFor** [comment]
When I updated EconomyInc 1.6.7, it still crashed.
I tried to delete BuildingGadgets and the crash went away.
This is the latest crash report: https://gist.github.com/EnterFor/045cbc70f17f04a35f05d692c0500895

**Comment by MajorTuvok** [comment]
Which doesn't change the fact that they don't seem to hand our renderer our tile...
I'll take a look at what workaround I can see

**Comment by MajorTuvok** [comment]
To be honest: in this line is the class initialisation... 
So to me the only cast which matches the exception that happens here is when someone should pass our tile to the render Method. Therfore this is not our: EconomyInc seems to do an unchecked cast here, which does not succeed propably because **they are passing the wrong tile to our render Method**.

**Comment by MajorTuvok** [comment]
Therefore this is not a BG Problem and can be closed

**Comment by MajorTuvok** [comment]
@MichaelHillcox

**Comment by EnterFor** [comment]
Thanks

**Comment by MajorTuvok** [comment]
Actually block bills does something else then I thought and I can see nothing obviously wrong with any of our or FifouBe's  renderer code

**Comment by MichaelHillcox** [comment]
My first guess towards this without looking at any code would be the collection method or how our render block is setup.

**Comment by FifouBE** [comment]
I updated my github, with the latest version 1.6.7. If you see anything wrong with the render code please let me know, I doubled checked and saw nothing wrong. My guess is on the inventory renderer that is not rendering and maybe causing the problem.

**Comment by MajorTuvok** [comment]
@MichaelHillcox it fails already when attempting to pass the Tile into our render Method. For some reason mc associates our renderer with this BlockBills tile entity, when it is rendered in an inventory. And I see nothing obviously wrong with our registration, which would lead to our type overwriting this other one. Which is why I believe the issue must be elsewhere, possibly even in Forge. But only debughing can prove that.

**Comment by MajorTuvok** [comment]
> My guess is on the inventory renderer that is not rendering and maybe causing the problem.
@FifouBE what do you mean with that?

**Comment by FifouBE** [comment]
The method I use is returning true, which means that mc couldn't render properly the item in the inventory, so oit might me that who is causing the crash. I'm trying to contact EnterFor to see with a temporary fix of disabling the inventory render line, if it's resolve the crash with your rendering process.
