### ISSUE TITLE
Connected texture mod

### ISSUE THREAD

**Issue by Biciklee** [Direwolf20-MC/BuildingGadgets#467]
* forge-31.1.46
* buildinggadgets-3.3.4.jar
* Use building gadget in surface mode

![2020-04-17_14 25 03](https://user-images.githubusercontent.com/44593422/79569388-c9b9f800-80b7-11ea-8bb0-aefd57fc4c44.png)
![2020-04-17_14 25 08](https://user-images.githubusercontent.com/44593422/79569400-cf174280-80b7-11ea-9d63-641985df3a41.png)

When surface mode is in use the CTM isn't working properly. Basically the fuzzy mode is always on.

**Comment by MichaelHillcox** [comment]
This is on the todo list :+1: I rewrite the mode list but didn't implement this feature just yet. Sorry

**Comment by Biciklee** [comment]
It's all good, thanks for the quick answer tho.

**Comment by MichaelHillcox** [comment]
No worries, thanks for the report though, it'll remind me to do it :D

**Comment by Biciklee** [comment]
When should we expect the change? Not to be hasty, just curious. :D

**Comment by MichaelHillcox** [comment]
Within the next week or so, I have a few updates to push out regarding modes so it shouldn't be too long

**Comment by Biciklee** [comment]
Thanks :D

**Comment by MichaelHillcox** [comment]
Fixed for 1.15, releasing soon.

**Comment by MichaelHillcox** [comment]
Fixed, will be released soon
