### ISSUE TITLE
(Suggestion) Chiseling blocks

### ISSUE THREAD

**Issue by mtjohnson47** [Direwolf20-MC/BuildingGadgets#468]
I'd like to suggest, if you have a chisel in your inventory, that the copy-paste gadget be able to chisel blocks to the right variant.  Been playing Astral Sorcery a lot lately.

Similar feature:  If you have a bit bag with the right bits, it can chisels&bits the blocks needed.

**Comment by MajorTuvok** [comment]
This has been suggested before and I'm pretty sure it has been shut down. Let me take a look...

**Comment by MajorTuvok** [comment]
Duplicate of #109. This has been shut down by Dire himself and therefore should be closed.
