### ISSUE TITLE
Feature Request: Make a Mode like Builder Wand

### ISSUE THREAD

**Issue by alpal01** [Direwolf20-MC/BuildingGadgets#47]
Can you make a mode for the building gadget to act like the functionality of "Better Builder Wands"?

**Comment by Direwolf20-MC** [comment]
I left this open this long to think about whether I want to do this, but I'm going to pass. Builders wands work fine :)

**Comment by Phylogeny** [comment]
Duplicate of #87. Released in v2.6.2 as `Surface Mode`
