### ISSUE TITLE
Undoing with Copy Paste Gadget gives me a different block than was placed

### ISSUE THREAD

**Issue by Lispetsketches** [Direwolf20-MC/BuildingGadgets#474]
Forge Version - 14.23.5.2847
Building Gadgets Version - 2.8.2

Issue reproduced here; https://www.youtube.com/watch?v=sXUi4ujkV_c

This is the copy/paste for the structure; https://pastebin.com/Mh1c6BPt

**Comment by MajorTuvok** [comment]
Thanks for the report

**Comment by MichaelHillcox** [comment]
The team have tried to get this to happen again but we can't seem to do it. Can you explain further as to what the issue is in detail and how to do it so we can try and debug this on our end?

**Comment by MichaelHillcox** [comment]
We thank you for your issue report, unfortunatly we no longer support this version of Minecraft / Our mod. I've added your issue to a collection of issues that the community is welcome to create pull requests for. Hopefully your issue is resolved in time 👍 Master list: #535
