### ISSUE TITLE
Crash when binding Copy/Paste to Refined Storage

### ISSUE THREAD

**Issue by P1ckl3s** [Direwolf20-MC/BuildingGadgets#476]
[crash-2020-05-11_02.31.33-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/4608103/crash-2020-05-11_02.31.33-client.txt)

Crash log attached. Playing MC Eternal v1.3.5.2 with Refined Storage v1.6.16 added. Vanilla Fix crash screen says it's a conflict between Refined Storage and Building Gadgets.

**Comment by MajorTuvok** [comment]
Could you also add the bg version and the latest log?

**Comment by MajorTuvok** [comment]
Looks like the player was null [here](https://github.com/Direwolf20-MC/BuildingGadgets/blob/d3259bf4e8cbdc449f490141a8eb39e936655f7f/src/main/java/com/direwolf20/buildinggadgets/common/integration/mods/RefinedStorage.java#L31)...

**Comment by MajorTuvok** [comment]
And it is not null [here](https://github.com/Direwolf20-MC/BuildingGadgets/blob/d3259bf4e8cbdc449f490141a8eb39e936655f7f/src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java#L285), as implied by the `.isSneaking()` check.
I just went through all Methods in between and the player is just outright passed through. As the other argument is also non-null, I believe this to be an RefinedStorage bug.

**Comment by MichaelHillcox** [comment]
Can confirm, this is a Refined Storage bug. Please report to them at https://github.com/refinedmods/refinedstorage
