### ISSUE TITLE
[3.3.5] Placement preview vertical offset incorrect

### ISSUE THREAD

**Issue by xenoflot** [Direwolf20-MC/BuildingGadgets#479]
Heyo,

Playing All the Mods 5-1.25a.
* Forge version 31.2.0
* Building Gadgets 3.3.5

Just made a gadget and I've found that the placement preview in the default BuildtoMe is 1 2/3 blocks too low, as illustrated here: https://i.imgur.com/1mGNvHd.png

I'm not using any shaders or resource packs, just the ones that come default with ATM5. I don't know why it's purple. It's white now but it's been purple for most of the time I've been playing with it!

**Comment by MichaelHillcox** [comment]
I don't have a clue but I can pretty safely say that this is because of another mod. There are so many things wrong here.

**Comment by xenoflot** [comment]
OK, Thanks. I'll xpost to the ATM5 wiki.

**Comment by xenoflot** [comment]
@MichaelHillcox Looks like it was caused by a bug in Vazkii's Neat. Fixed in 1.6-22
