### ISSUE TITLE
[Feature Request] Infinite blocks/energy in creative mode

### ISSUE THREAD

**Issue by bl4ckscor3** [Direwolf20-MC/BuildingGadgets#48]
It would be ideal if both gadgets would not need any blocks in the inventory or any energy (if enabled) to work, should the player be in creative mode. This would make building in creative just as easy as in survival mode.

**Comment by Direwolf20-MC** [comment]
Fixed! - https://github.com/Direwolf20-MC/BuildingGadgets/commit/33e6daaf58e3e5f313bc85586ba3cf9b9175c695
