### ISSUE TITLE
"Invalid block" when selecting hempcrete with the exchanging gadget.

### ISSUE THREAD

**Issue by kafeinnet** [Direwolf20-MC/BuildingGadgets#480]
Hi,

I'm using forge-14.23.5.2847 and BuildingGadgets 2.8.2 (MC Eternal modpack). I just found that the exchanging gadget does not work with Immersive Engineering (v0.12-92) hempcrete blocks. A message saying "Invalid block" appears on selecting hempcrete with the gadget.

Just so you know, the Cyclic (1.19.18) standard exchange scepter works (but it's not as powerful as this mod :)).

![2020-05-22_12 20 26](https://user-images.githubusercontent.com/4932189/82658365-24022780-9c27-11ea-8d43-be221ae7ea43.png)
![2020-05-22_12 22 28](https://user-images.githubusercontent.com/4932189/82658372-28c6db80-9c27-11ea-8d32-d4dfef5b5140.png)

Cdlt,
--
\fab

**Comment by kafeinnet** [comment]
Aaaand I reply to myself, that's a slab issue. It works perfectly with full blocks. *derp*

**Comment by MajorTuvok** [comment]
Immersive slabs are tiles. This is correct behaviour.

**Comment by MajorTuvok** [comment]
Immersive slabs are tiles. This is correct behaviour.

**Comment by MajorTuvok** [comment]
Compare #443
