### ISSUE TITLE
Charging tools 1.15.2

### ISSUE THREAD

**Issue by Simulakra** [Direwolf20-MC/BuildingGadgets#481]
I couldn't find this info on anywhere.

I'm using these;

- Minecraft 1.15.2,
- buildinggadgets-3.3.5.jar
- Forge 31.1.0

Just vanilla, nothing more...

How can I charge my tools? 

There is not any charger block or tool block. Can I edit config to "not use energy" thing?

Should I need to download any mod for this? Because I don't want to download anything else...

**Comment by MajorTuvok** [comment]
The Charging Station has been deliberatly seperated out of building gadgets. You can download it as ChargingGadgets as I believe...

**Comment by MajorTuvok** [comment]
@MichaelHillcox am I right?

**Comment by MichaelHillcox** [comment]
Charging stations is not out yet unfortunatly. We intended to have it released at the same time as the 1.15 release but my and dire got busy and haven't had time to test it yet... I'm hoping it will be released soon. On the upside RFTools has a great options for changing and 1.15 already has some good charging / power based. Tools. You also have the option to just disable power by modifying the server config and setting the maxPower to 0 :D

**Comment by Simulakra** [comment]
@MichaelHillcox 

> "You also have the option to just disable power by modifying the server config and setting the maxPower to 0"

How? :D 

I can use that, but I couldn't find it on any wiki or readme...

**Comment by MichaelHillcox** [comment]
Singleplayer: Go into your world folder, find the serverconfigs folder, then look for buildinggadgets-server.toml and edit the maxPower on each of the gadgets, this is done by changing the maxPower to 0.

On a server you run / own / have access to server config for: Go to the configs folder and edit the buildinggadgets-server.toml the same as the above.
