### ISSUE TITLE
Add Chisel support for the copy/paste gadget

### ISSUE THREAD

**Issue by BLucky-gh** [Direwolf20-MC/BuildingGadgets#482]
It would be really convenient if the copy/paste gadget could convert the chiseled variants of blocks if there was a chisel in the player's inventory. There are mods that can do that already so I suppose it's not impossible.

**Comment by MichaelHillcox** [comment]
This has been turned down a few times, I think it would be very much scope creaping. In the future, I intend on having an api for modders to provide extra functionality to each of the tools build methods. This likely won't happen any time soon. You also have the problem of even if I was to implement this, how would the gagdet know what to chisel the block to? I'd basically have to build half of the Chisel code into our mod which wouldn't be ideal nor would it happen.

**Comment by BLucky-gh** [comment]
Thanks for explaining
