### ISSUE TITLE
[1.15.2] Charger is missing.

### ISSUE THREAD

**Issue by brianSites** [Direwolf20-MC/BuildingGadgets#485]
The charger used to charge the gadgets were missing. Sorry if you are currently adding that but I see no other way to use the mod in survival without the charger. Can you suggest another mod that adds something to charge my gadgets?

**Comment by MichaelHillcox** [comment]
#481 

https://github.com/Direwolf20-MC/BuildingGadgets/issues/481#issuecomment-633286925

Basically, it's on it's way, if you don't want to add another mod then disable the power requirements in the buildinggadgets-server.toml
