### ISSUE TITLE
Copy Paste gadget not working 1.14.4

### ISSUE THREAD

**Issue by MorbiusProductions** [Direwolf20-MC/BuildingGadgets#486]
Forge version: 28.1.0
Building Gadgets version: 3.1.1b
I'm trying to use the copy paste gadget and it copies fine but when I switch to paste the object shows as red blocks and when I right click it says Template Build and builds nothing. I have sufficient blocks in my inventory. Also, I have MaxEnergy set to 0.

![2020-06-05_17 27 29](https://user-images.githubusercontent.com/12752595/83931598-6ad93c80-a752-11ea-9eb2-befaf44a110b.png)

**Comment by MajorTuvok** [comment]
> Also, I have MaxEnergy set to 0.
Pretty sure that this is the problem (bug). 
Also I think that 1.14 is no longer supported, though 1.15 is. Could you verify, whether this happens in 1.15?

**Comment by MajorTuvok** [comment]
@MorbiusProductions you might want to try setting the energy usage to 0.

**Comment by MichaelHillcox** [comment]
1.14 is still supported, I just hate working on that code :P

**Comment by MorbiusProductions** [comment]
Ya, setting energy usage to 0 fixed it. What's funny is that the building gadget worked. Didn't try destruction or exchange.

**Comment by MichaelHillcox** [comment]
Hmmm, Fun. I'll take a look at this one, likely a mess up in the "ignore power when no max power" part of the logic.

**Comment by moshner** [comment]
We are experiencing this bug as well. We tried the energy usage to 0 fix but it crashed the server. 

Of note, we are on 1.15.2.

**Comment by MichaelHillcox** [comment]
Can you please attach a crash report :D

**Comment by moshner** [comment]
Sorry it has taken so long. I'll get my admin to replicate it and post the crash logs soon.

**Comment by moshner** [comment]
I've been told there wasn't a crash log generated. "It was just a hang"

**Comment by MichaelHillcox** [comment]
Hmm, able to see if any errors were in the latest.log?

**Comment by moshner** [comment]
Not that he could find. It literally stopped starting up.

**Comment by MichaelHillcox** [comment]
Starting up? that's super weird. Have you tried to use it since?

**Comment by moshner** [comment]
We have not. It's a shared server so we focused on stability first. I've just been using the paste feature as a template to manually build with.

**Comment by MichaelHillcox** [comment]
Hmm, would you be able to spin up a test server to see if you can reproduce the issue?

**Comment by moshner** [comment]
We can try, yes. It might be a bit.

**Comment by moshner** [comment]
Okay, we re-enabled the suggested fix and now everything is working! I guess the crash was related to something else. We've updated our pack a couple of times with other bug fixes so maybe that fixed it. Regardless, thank you for your time and attention.

**Comment by MichaelHillcox** [comment]
Awesome, glad you've got it all sorted. I'll close this issue but feel free to re-open it or make a new issue if you have an issue again regarding this feature :D
