### ISSUE TITLE
Maybe it sometimes voids blocks in a mechanical user?

### ISSUE THREAD

**Issue by purpleposeidon** [Direwolf20-MC/BuildingGadgets#5]
I had a mechanical user with a gadget, and an inventory full of smoothstone. I accidentally allowed it to hit the floor, but I think it voided the blocks? I'd need to double check; it usually does the right thing.

**Comment by Direwolf20-MC** [comment]
Can you clarify and possibly figure out exact steps to reproduce? :)

**Comment by purpleposeidon** [comment]
1. Place a mechanical user on top of a platform made of smoothstone, facing down.
2. Configure it: Redstone on, Upper left slot only.
3. Exchanging gadget: swapping out block planks; mode wall; range 3.
4. Put the gadget in the top-left slot, and fill the rest of the slots with 64 planks each.
5. Install a button, push it.
6. The swap happens, and 9 planks get consumed. But where does the cobble go?

It's actually not voided. There's a secret buffer in the mechanical user. A mechanical user with a buffer will try to empty the buffer when activated, and will block until it can do so.

**Comment by Direwolf20-MC** [comment]
So is this a bug with my mod, or Tema's? :)
