### ISSUE TITLE
[Feature request] chisels and bits mode.

### ISSUE THREAD

**Issue by RiftomeR** [Direwolf20-MC/BuildingGadgets#50]
Allow building and replacing gadgets to be switched into c&b mode. In this mode they will work with chiseled bits like with blocks in normal mode.

**Comment by McJty** [comment]
Note: while possible (Chisel & Bits has an API which would allow doing this) and a VERY nice feature to have this is a rather big job though

**Comment by Direwolf20-MC** [comment]
It’s a neat idea but I would be very lost trying to figure out how :). I’ll Pass for now. Consider it way in the future maybe.
