### ISSUE TITLE
Template manager UI unclear

### ISSUE THREAD

**Issue by hvdklauw** [Direwolf20-MC/BuildingGadgets#500]
As discussed on discord: the template manager UI is unclear that the copy/paste works for the template and not the gadget.

My suggestion would be to disable the Copy button when there is no template (maybe a tooltip explaining why) and disable the Paste button when there is no paper.

The load and save buttons should similarly only be enabled when they can be used.

Also the messages appearing in chat when pressing the buttons should maybe be shown in the interface, because chat is hard to read with the whole overlay.

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
