### ISSUE TITLE
[1.12.2] Dupe bug with BiomesOPlenty

### ISSUE THREAD

**Issue by Basedgod199** [Direwolf20-MC/BuildingGadgets#503]
Forge version: 14.23.5.2847
 Building Gadgets version: 2.8.3
BiomesOPlenty version: 7.0.1.2441

Pretty simple really, all you need is any BiomesOPlenty ore and a Building Gadget. Then select the ore with the Building Gadget and place it in the world. Then undo it. It will give you back the blocks you placed while also dropping the blocks in the world, giving you twice the amount you placed.

**Comment by MichaelHillcox** [comment]
Hmm, I can look into that one, I don't have a plan on updating 1.12 again for a while.... But I can look at it

**Comment by MichaelHillcox** [comment]
We thank you for your issue report, unfortunatly we no longer support this version of Minecraft / Our mod. I've added your issue to a collection of issues that the community is welcome to create pull requests for. Hopefully your issue is resolved in time 👍 Master list: #535
