### ISSUE TITLE
Suggestion - Paste Gadget Anchor

### ISSUE THREAD

**Issue by Lithorn** [Direwolf20-MC/BuildingGadgets#505]
Seems that when anchor is set, if the original point is occupied then it will unset the anchor. Any possible way to set a perm lock on the anchor so that, if its occupied it just won't paste anything until the anchor points are all free?

**Comment by MajorTuvok** [comment]
Why do you want it to paste nothing when an anchor is set? As I see it, you could just come back at a later date to finish the build process and to me there's nothing wrong with that behaviour.

**Comment by Lithorn** [comment]
More for automations sake but that may not be what you intend it for. A lot easier to use something like this tool than a mass of pistons or other larger mods is all.

**Comment by MajorTuvok** [comment]
Thanks for the explanation. @MichaelHillcox what do you think? The Copy-Paste-GUI is not so full that a lock anchor button would be too much (though I guess we'll do that in the rewrite, right?)

**Comment by MichaelHillcox** [comment]
To keep things tidy, we now have master list of feature requests, we thank you for your suggestion and we will use this issue for future reference. Closing in preference for https://github.com/Direwolf20-MC/BuildingGadgets/issues/534
