### ISSUE TITLE
Paste Gadget cannot clear settings

### ISSUE THREAD

**Issue by Lithorn** [Direwolf20-MC/BuildingGadgets#506]
In the modpack Compact Claustriphobia, the paste gadgets are a one compact machine use only. To help understand what I mean, when you make the paste gadget you will be tied to the compact machine you use it in. If I make machine 12, and use the first copy in 12, that gadget is forever tied to 12. Trying to use it anywhere else will result in "Area too big". Trying to right click to clear the settings results in "Area too big". Trying to reset in the machine its tied too, does nothing. 

I'm unable to clear the settings and use the gadget elsewhere, I must create a new one for each machine I plan to use it in. 

Compact Machines 1.12.2, 3.0.18-b278
Building Gadgets 2.8.3
Modpack - Compact Claustriphobia - 1.3.4

I am making this aware to the modpack author too, as I don't know where the issue is from so its best to report to both.

**Comment by MajorTuvok** [comment]
What is that? Could you please describe what you're doing (especially define the word use, as there is more then one mode)?
This sounds like a user error or a bug on compact machines side (which I really could not imagine how something like that would happen - only the undo checks the dim, the remainder really doesn't care)...

**Comment by MajorTuvok** [comment]
I could imagine the message being misleading, when attempting to copy unloaded blocks, but in that case, select in the overworld, what you want to copy and you're good again.

**Comment by MichaelHillcox** [comment]
Sounds to me like it's trying to extend the dimension. This is 100% on us for not giving a clear message about dimensions or sizes but I'm pretty sure if you shift right click in the air you can use the clear button unless major broke it haha

**Comment by MajorTuvok** [comment]
@MichaelHillcox it is 1.12: 2.8.3...

**Comment by MichaelHillcox** [comment]
Then the clear button should work :)

**Comment by Lithorn** [comment]
Clear button dosen't work. Still get the message "Area too big". What im doing is, I brought a paste gadget that had some data already in it to another compact machine. When I tried to clear it to reuse it I got that "Area too big" message. If I go back to the machine I used it in first, it works but even once cleared can't be used out of that machine.

**Comment by MichaelHillcox** [comment]
Right, well that's intresting, you are on an older version but this seems like a bug we should fix. Typically we're trying to move away from 1.12 as it's becoming harder and hander to develop for. I'll check out your bug in my dev env and keep you posted. (a note: youc an open the shift right click gui by holding G (gadget settings button) and clicking on the icon with the pencil in it. This will open that shift right click gui allowing you to press the clear button)

**Comment by MichaelHillcox** [comment]
We thank you for your issue report, unfortunatly we no longer support this version of Minecraft / Our mod. I've added your issue to a collection of issues that the community is welcome to create pull requests for. Hopefully your issue is resolved in time 👍 Master list: #535
