### ISSUE TITLE
Undo not compatible with dropt

### ISSUE THREAD

**Issue by misterplus** [Direwolf20-MC/BuildingGadgets#509]
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
* Forge version 14.23.5.2847
* Building Gadgets version 2.8.4
* *If the issue is a crash*; An external link to the crash report
* How to reproduce the issue
1.Replace a block's drop with dropt (a mod that lets you reconfigure block drops)
2.Place a block whose drops have been changed with a gadget
3.Undo that placement
4.Not only you get the block back in your inventory, the newly replaced drops would also drop.
* A screenshot, if applicable

**Comment by MichaelHillcox** [comment]
Could you pastebin your Dropt config so I can test this as I don't personally know how dropt works but I can definitely see if I can fix this.

**Comment by MajorTuvok** [comment]
Is there maybe an event we're supposed to be listening/firing?

**Comment by MichaelHillcox** [comment]
`ForgeEventFactory.onItemPickup `

**Comment by misterplus** [comment]
Yeah after some tinkering I figured out a way to make this work with undo,

**Comment by misterplus** [comment]
Yeah after some tinkering I figured out a way to make this work with dropt, so here's the original script: (the ones that are on the bottom, the ore ones)
https://paste.ubuntu.com/p/GRJ5YjVgnb/
This is the script that works:
https://paste.ubuntu.com/p/XKyxYdQrtN/
I'm sorry for submitting an issue kind of early and without through testing, if there's anything you guys can do to make this easier (make the scripting not too messy just to play around undo), that'd be great. If not you can close this. Again, I'm sorry for my impatience.

**Comment by MichaelHillcox** [comment]
Can definitely take a look

**Comment by MajorTuvok** [comment]
You could contact the people of dropt, as they now better then we do how it works...

**Comment by misterplus** [comment]
Yeah, fair enough. I'll do that then. Sorry for the inconvenience.

**Comment by MichaelHillcox** [comment]
No worries, feel free to reference our issue #509 in the issue for Dropt so we can track it 👍

**Comment by codetaylor** [comment]
Hi, I'm the author of Dropt. If you have time, can you please link the code that is responsible for the undo behavior? It would save me considerable time rooting around in your codebase.

Chances are the undo operation is triggering a `HarvestDropsEvent` as that's what Dropt hooks at `@SubscribeEvent(priority = EventPriority.LOWEST)`.

**Comment by MichaelHillcox** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets/blob/1.12.x/src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetBuilding.java#L193-L237

**Comment by MichaelHillcox** [comment]
Should be the main bits you're intrested in. Its likely that we're not handling something correctly

**Comment by codetaylor** [comment]
Thank you. I'll dig into it when I have time.

**Comment by MichaelHillcox** [comment]
No worries, if it's us then we'll push out a patch to fix it, we're not doing much with 1.12 anymore but as this looks to be a mod used in packs, it's likely a good idea we patch it :+1:

**Comment by MichaelHillcox** [comment]
We thank you for your issue report, unfortunatly we no longer support this version of Minecraft / Our mod. I've added your issue to a collection of issues that the community is welcome to create pull requests for. Hopefully your issue is resolved in time :+1: Master list: https://github.com/Direwolf20-MC/BuildingGadgets/issues/535
