### ISSUE TITLE
Using the GUI (coordinates) when copying does not copies the new highlighted area

### ISSUE THREAD

**Issue by winsrp** [Direwolf20-MC/BuildingGadgets#515]
* Forge version [1.16.1...99]
* Building Gadgets version ->3.5.1
* How to reproduce the issue -> copy an area, modify coordinates with the GUI option, try to paste area... pasted area preview and actual paste are not the modified area with coordinates

**Comment by MichaelHillcox** [comment]
Fixed, will be released soon 👍
