### ISSUE TITLE
Template saved with "Copy X" name regardless of the name given on template manager

### ISSUE THREAD

**Issue by winsrp** [Direwolf20-MC/BuildingGadgets#516]
Forge version [1.16.1...99]
Building Gadgets version ->3.5.1
How to reproduce the issue -> Copy an area, open your template manager, put your copy/paste gadget on the template manager, put some paper, name the template "test 1" or something I used "Restaurant" hit the save button, new template has "Copy 1" as name instead of what ever you put

**Comment by MajorTuvok** [comment]
Hmm, thanks for the report

**Comment by MichaelHillcox** [comment]
Fixed, will be released soon :+1:
