### ISSUE TITLE
Older Template formats error message is incorrect

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#517]
BG version: 3.2.0
Forge Version: some 1.14 version, I don't know which exactly

When attempting to paste a Template **into** the Template Manager from clipboard which has an older version, an erroneous error message is shown. It says "Failed to paste Template to Clipboard", even though someone tries to paste from the Clipboard. Furthermore an older format error message should be shown.
Related video: https://youtu.be/B6ACtNk5WMM

**Comment by MajorTuvok** [comment]
This made finding out that multiple people attempted to paste 1.12 Templates into 1.14 a real hassle... - _-

**Comment by MichaelHillcox** [comment]
Fixed will be released soon
