### ISSUE TITLE
[Feature Request] Improve the integration with /dank/null

### ISSUE THREAD

**Issue by bbf** [Direwolf20-MC/BuildingGadgets#52]
Hi Direwolf20,

Thank you so much for building gadgets, it is a very welcome addition to Minecraft.
I'm wondering if you could improve it even further by implementing these 3 features in the integration with /dank/null.

1) Respect the "Extraction Mode", and avoid removing blocks that are configured to keep an amount, just like its dock.
2) Invert your retrieval logic so you remove items first from the inventory, and than from the /dank/null.
3) Allow the exchanger to deposit items directly on the /dank/null. This might be trickier since I'm not sure how /dank/null intercepts item collection.

Best Regards,

**Comment by Direwolf20-MC** [comment]
I talked to the author of dank/null about most of these when i first implemented it :). 

1) He said thats more meant to be used with the dock, so I didn't implement that. I might consider it, but it'd probably be low on the to-do list. 
2) This is a personal preference for me. I'd rather it pull from dank/null first, then inventory. But maybe I"ll make this a config option (No promises)
3) That should work once dank/null updates. Its a bug on his end (Well not really a bug, but he has to change the way he does things).
