### ISSUE TITLE
Building gadget crashing server with undo error 

### ISSUE THREAD

**Issue by BUFFALOMC** [Direwolf20-MC/BuildingGadgets#521]
After deleting this template, please provide the following information:
* Forge version   32.0.61
* Building Gadgets version    downloaded for 1.16.1 server straight from twitch 
* *If the issue is a crash*; An external link to the crash report     Console of server said Building gadgets failed to undo even though i was not undoing the first two times the third time i didnt even have the building gadget in my hand 
* How to reproduce the issue     install building gadgets on 1.16.1 server and play for 10 minutes 
* A screenshot, if applicable  console was already cleared of error from another player starting the server 
This may not help but hopefully it does help to find the issue if there is one im sure you will find and fix love your mods man

**Comment by MajorTuvok** [comment]
> An external link to the crash report
Even if the console was cleared, the log was not until the server shut down after another restart. Could you please provide it or recreate the crash. 
> install building gadgets on 1.16.1 server and play for 10 minutes
State what you/someone else did, if you don't know it, close the issue. Your message states it has something to do with undoing, but without at least the informatio which Gadget attempted to undo, how is someone supposed to re-create this?!? We'd have to basically test the whole mod through! 😠

**Comment by MajorTuvok** [comment]
Also the screenshot does not refer to some server console (The trace log is much more informative then a single screenshot), but rather to a screen shot of the situation. For example a screenshot of stairs rotating the wrong way around etc.

**Comment by MajorTuvok** [comment]
> Building Gadgets version downloaded for 1.16.1 server straight from twitch
When referencing this issue in the future it will likely be very difficult (and annoying) to reverse engineer the version. Therefore could you also provide the exact version?

**Comment by BUFFALOMC** [comment]
> > Building Gadgets version downloaded for 1.16.1 server straight from twitch
> 
> When referencing this issue in the future it will likely be very difficult (and annoying) to reverse engineer the version. Therefore could you also provide the exact version?

I believe it is 3.5.1.jar

**Comment by BUFFALOMC** [comment]
> > Building Gadgets version downloaded for 1.16.1 server straight from twitch
> 
> When referencing this issue in the future it will likely be very difficult (and annoying) to reverse engineer the version. Therefore could you also provide the exact version?

we were not even using the building gadgets at the time of the second or third crash im trying to replicate this in solo world since both building gadgets and charging gadgets were removed from the server (not my server so i cant make them put it back on)

**Comment by BUFFALOMC** [comment]
> > An external link to the crash report
> 
> Even if the console was cleared, the log was not until the server shut down after another restart. Could you please provide it or recreate the crash.
> 
> > install building gadgets on 1.16.1 server and play for 10 minutes
> 
> State what you/someone else did, if you don't know it, close the issue. Your message states it has something to do with undoing, but without at least the information which Gadget attempted to undo, how is someone supposed to re-create this?!? We'd have to basically test the whole mod through! 😠

Can you tell me where to find a crash report if i know how to find it i will and post it if i can get it to happen on single player if i cant i will see if i can get it added to the server for a little while to test and get the crash report If i can find it for a mcprohosting server as well. I only posted because it happened 3 times in a row and i thought this might be helpful was not sure what all i needed to post and didnt have everything that i needed because after the third time the server crashed and "performed safe shut down" the server owner just uninstalled it and started it back up before i could get anything or look up how to. sorry but i am working on getting it all now and replicating the issue now because if it is a bug i would like it found because these mods are the best i love dw20 and his mods so i was just trying to help

**Comment by BUFFALOMC** [comment]
> Also the screenshot does not refer to some server console (The trace log is much more informative than a single console screenshot), but rather to a screenshot of the situation. For example a screenshot of stairs rotating the wrong way around etc.

[crash-2020-08-30_14.59.21-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/5147393/crash-2020-08-30_14.59.21-server.txt)

![crash from console](https://user-images.githubusercontent.com/70446944/91668487-b772b080-ead2-11ea-84a1-235dfc190cad.PNG)
![crash from console2](https://user-images.githubusercontent.com/70446944/91668489-b9d50a80-ead2-11ea-87b3-d71c8ebe41ab.PNG)

mods installed 
ai-improvements 0.3.0
amb0.1.1
appleskin-mc1.014
autoreglib 1.6-42
bambooeverything 1.0.0
bettertitlescreen 1.10.0
bookshelf 6.0.2
Buildinggadgets3.5.1
caelus-forge2.0-beta5
charginggadgets 1.1.1
clienttweaks5.0.0 
collective 1.35
controlling 7.0.0.2
cookingforblockheads 9.0.0
craftingtweaks 12.0.4
crafttweaker 7.0.0.6
curioofundying forge 4.0
curios forge 3.0-beta3
curioselytra-forge 3.0
decorative blocks7a
easyelytrato 1.3
farmingforblockheads 7.0.1
fastleafdecay v23
fasworkbench 4.1.1
fpsreducer 1.16
getinthebucketmod 3.0.1
ironshulkerboxes 5.0.1
jei 7.0.0.6
heitweaker 1.0.1.2
mcw doors 1.0.0
mixinbootstrap 1.0.3
modnametooltip 1.14.0
morevanillalib 1.2.8
mousetweaks 2.13
netherprtalfix 7.0.0
oneplayersleeping 0.0.3
phc2foodcore 1.0.1
placebo 4.0.1
preview_optifine_1.16.1_HD_U_G2_pre4
Quark-r2.2-255
randompatches1.21.2.1
toastcontrol 4.0.0
trashslot 12.0.1
valhelsia_stuctures 16.0.1
vanillahammers 2.1.1
waystones 7.0.2
xaros_minimap_20.16.0.1_forge_1.16.1.jar
xaerosworldmap_1.7.4_Forge_1.16.1.jar


HOPE THIS HELPS TO RESOLVE! If you need anything else feel free to let me know and i will try to find it/post it

the file below is why i said had something to do with undo and the unadulterated version of that is linked above!

![Inkedcrash from console_LI](https://user-images.githubusercontent.com/70446944/91668793-091c3a80-ead5-11ea-9b7a-ec26db41f074.jpg)

**Comment by MajorTuvok** [comment]
Hui, a NoSuchMethodError...
Thanks for the crash report :)

**Comment by MichaelHillcox** [comment]
Update forge.

**Comment by BUFFALOMC** [comment]
> Update forge.

Does this mean this issue is found and fixed?

**Comment by BUFFALOMC** [comment]
> Hui, a NoSuchMethodError...
> Thanks for the crash report :)

did that help find what you were looking for it is doing the same thing on server as i posted from my single player

**Comment by MichaelHillcox** [comment]
It means it's likely an incompatabiltiy between the version of forge you're running and the version I've built against

**Comment by MajorTuvok** [comment]
Aka you're almost certainly using a Forge version in which this Method is not available. It will work if you update Forge.

**Comment by BUFFALOMC** [comment]
so the building gadgets wont work on that version of forge? sorry im not very good with programming more physical IT then programming 


> It means it's likely an incompatabiltiy between the version of forge you're running and the version I've built against

**Comment by MichaelHillcox** [comment]
Essentially yes. You'll need to update forge on your end and have the server people update it on theirs. .61 is pretty out of date. we're on .108 now and I've built against .107

**Comment by BUFFALOMC** [comment]
> Aka you're almost certainly using a Forge version in which this Method is not available. It will work if you update Forge.

but cant that break some of the other mods as well then it would be some other mod thats broke right? Before installing bg it was working fine but as its a server i would be hesitant to update forge as i dont know how to without starting the world over

**Comment by BUFFALOMC** [comment]
ill try it on solo world then see if it works with the other mods THANK YOU FOR YOUR HELP!

**Comment by BUFFALOMC** [comment]
> Essentially yes. You'll need to update forge on your end and have the server people update it on theirs. .61 is pretty out of date. we're on .108 now and I've built against .107

Also at the time we set up server that was the highest version of forge mcprohosting offered

**Comment by MajorTuvok** [comment]
> did that help find what you were looking for it is doing the same thing on server as i posted from my single player
Yes. If a User has a crash, the worst thing that can happen to a programmer is being told by someone to fix it, without being able to know anything about what was going on. In case of programs logs exactly fulfill this purpose - even though we can't write as much logs as I'd like to without the other mods logs no longer being readable. This is why we also want a description what people did...
