### ISSUE TITLE
Building fences gives 'connected' version

### ISSUE THREAD

**Issue by JonSar-GitHub** [Direwolf20-MC/BuildingGadgets#522]
Forge 32.0.108
Building Gadgets 3.5.1 on Minecraft 1.15.1
No Crash
Build a 9x9 fenced area using the building gadget
Screenshot attached - fence is built as if there's a block on the side and the 'connected' version of the fence appears. 

![javaw_RyCsoVkMey](https://user-images.githubusercontent.com/68348444/91646922-70da7300-ea4c-11ea-959a-5418b0554d5e.png)
![javaw_5ljUMH9qby](https://user-images.githubusercontent.com/68348444/91646937-aaab7980-ea4c-11ea-8b03-bca3ddbaae12.png)

**Comment by MajorTuvok** [comment]
Thanks for the report...
I think this is related to #520
