### ISSUE TITLE
Unable to pull a building gadget out of a Dank Null Once placed inside.   (1.12.2)   (Mod interaction)

### ISSUE THREAD

**Issue by hyperjoe** [Direwolf20-MC/BuildingGadgets#523]
Using these two mods among a 178 mod self-created modpack:

Building Gadgets 2.8.4.
DankNull-1.12.2-1.7.101

I put my building gadget in my dank null (Mk VI), but was unable to pull it out using my mouse, or right clicking or change the extraction method (Extract all but 1)  

Unfortunately I just tested this issue with a pack that had just these mods in (plus Dank Null's library mod)  and it worked fine.  So there's another mod interaction at play.   If I figure out which one, I'll report it again.

**Comment by MichaelHillcox** [comment]
Unfortunatly for that level of mods it would take us too long to track down who is messing up in this instance. As it works in isolations between the two mods you can safely assume that it's neither us nor Dank nulls. If you are able to find out who is causing it then please do let us know as we may be able to address it from our end but other than that, I can't be much help, sorry.

**Comment by MichaelHillcox** [comment]
We thank you for your issue report, unfortunatly we no longer support this version of Minecraft / Our mod. I've added your issue to a collection of issues that the community is welcome to create pull requests for. Hopefully your issue is resolved in time 👍 Master list: #535
