### ISSUE TITLE
Dup bug

### ISSUE THREAD

**Issue by JWC5556** [Direwolf20-MC/BuildingGadgets#525]
Forge version 31.2.36
Building Gadgets version 3.4.0
Minecraft 1.15.2

Using the building gadget i was using Horizontal wall mode to remove some hanging water. I pasted blocks in to remove water then undid the past and it gave back double. It was gonging into a alchemical bag from project E  Version ProjectE-1.15.2-PE1.0.4.jar. with a black hole ring. i thought it was a mistake until it did it with iron ore also.

**Comment by hvdklauw** [comment]
Confirmed, that specific interaction is indeed happening

**Comment by hvdklauw** [comment]
Ok, this is also a dupe bug with Simply Backpacks with autopickup enabled

**Comment by hvdklauw** [comment]
Exchanging gadget is weird too with auto pickup, for instance when I replace 25 blocks I get 26 of the replaced items in my bag

**Comment by hvdklauw** [comment]
Oh, it's not 100% the same: 
- ProjectE alchemical bag with black hole band: Double what you expect
- Simply Backpacks with auto pickup: 1 extra of what you expect

Both for building and exchanging.

**Comment by MichaelHillcox** [comment]
Fixed :+1: will be released soon.
