### ISSUE TITLE
Placing Glass Panes and other similar blocks causes blocks to be placed with improper state on empty sides

### ISSUE THREAD

**Issue by mross5013** [Direwolf20-MC/BuildingGadgets#526]
Running on Minecraft version 1.15.2, Mining Gadgets has been updated to the latest version.

Running Q-Tech Modpack

* Forge Version 31.2.31
* Building Gadgets version 3.3.5

* How to reproduce the issue: Using the exchanging gadget, replace existing object with Glass panes. The glass panes will place with all sides showing as if connected to adjacent blocks. 

* Video Clip of Iskall85 having blank sides of glass panes show as connected instead of flat. [https://clips.twitch.tv/CheerfulClearJayBrainSlug](https://clips.twitch.tv/CheerfulClearJayBrainSlug)

* What needs to be fixed: Need to check state of each side of the glass pane object and set meta data for sides with air to be not connected. 

Additional testing: Tested with Iron bars as well and the iron bars show the issue as well.

**Comment by hvdklauw** [comment]
Ok, tried this and it actually depends on what you picked as the source block

A glass pane connected on 4 sides gives me panes connected at 4 sides (even if there is nothing there)
A single glass pane on it's own as source gives me glass panes that connects perfectly.

Building gadget does the same thing, depending on the source it is connected or in it's default state and then it's fine.

**Comment by hvdklauw** [comment]
Also a I think this is the same issue as #522
