### ISSUE TITLE
Server Freezeing when using any gadget

### ISSUE THREAD

**Issue by MikeDonaghy** [Direwolf20-MC/BuildingGadgets#528]
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
Forge version: 14.23.5.2847
Building Gadgets version: 2.8.4
I am playing on enigmatica 2 expert mode

when using any gadget the entire server freezes and the server is spammed with the text below I really like this mod any solution would be great 
![image](https://user-images.githubusercontent.com/39144000/92290813-8388f800-eee3-11ea-9498-da5af47ed26d.png)

**Comment by MichaelHillcox** [comment]
Is the gadget bound to an ME / RS system?

**Comment by MikeDonaghy** [comment]
idk probably Ill try unbounding it

**Comment by MikeDonaghy** [comment]
that did not fix it. the issue has been happening since i first made one in this pack

**Comment by MichaelHillcox** [comment]
Please submit a full log of the issue you're having

**Comment by MikeDonaghy** [comment]
ok one minute

**Comment by MikeDonaghy** [comment]
[2020-09-04-1.log.gz](https://github.com/Direwolf20-MC/BuildingGadgets/files/5177298/2020-09-04-1.log.gz)

**Comment by MichaelHillcox** [comment]
Likely the wrong log as it's got almost nothing in it par from a server start up

**Comment by MikeDonaghy** [comment]
[latest.zip](https://github.com/Direwolf20-MC/BuildingGadgets/files/5177304/latest.zip)
yeah my bad its this

**Comment by MichaelHillcox** [comment]
What gives you the impression that this is due to our mod?

**Comment by MikeDonaghy** [comment]
its also just me on the server

**Comment by MikeDonaghy** [comment]
i guess it could be something interacting poorly with building gadgets

**Comment by MichaelHillcox** [comment]
The error looks to be more like a hardware issue. I'm honestly not sure as I use our mod on a 1.12 server still and have not had these issues... Try emptying your inventory par from our gadget and see if it still happens.

**Comment by MikeDonaghy** [comment]
ok

**Comment by MikeDonaghy** [comment]
it may be a bit I had to restart the server

**Comment by MikeDonaghy** [comment]
seemed to fix it could it be my dank null?

**Comment by MichaelHillcox** [comment]
Is that the thing that starts to cause the issues?

**Comment by MikeDonaghy** [comment]
![image](https://user-images.githubusercontent.com/39144000/92291538-3ad33e00-eee7-11ea-89d2-9aa365553684.png)
idk these are the items I had on me

**Comment by MikeDonaghy** [comment]
only one i know of that has interaction with building gadgets is the dank null

**Comment by MichaelHillcox** [comment]
Could be one of the bags, dank null, I'd recommend trying to figure out which one of those might be causing it

**Comment by MikeDonaghy** [comment]
thats what im doing now

**Comment by MikeDonaghy** [comment]
all the items are back in my inventory and its working so I don't know what caused it or fixed it but it's working now

**Comment by MikeDonaghy** [comment]
thanks I guess

**Comment by MichaelHillcox** [comment]
How strange, open this again if the issue comes back

**Comment by MikeDonaghy** [comment]
ok
