### ISSUE TITLE
1.12 Exchanging gadget doesn't place blocks in /dank/null

### ISSUE THREAD

**Issue by jdratlif** [Direwolf20-MC/BuildingGadgets#529]
When you use the exchanging gadget with a dank null, the blocks do not go back into your dank null. Unless I'm misremembering, this used to be the case.

This is a short 1 min video demonstrating the problem:
http://www.technoplaza.net/temp/dank-null-exchanging-gadget.mp4

MC Version 1.12.2
Forge 14.23.5.2854
Building Gadgets 2.8.4
Dank Null 1.7.101 (also tested on 1.7.91 -- the most recent release non-beta)

I created a test pack with just these mods (and JEI) to make sure it wasn't another mod interfering.

Thanks.

**Comment by jdratlif** [comment]
I was checking to make sure I wasn't imagining this feature, and it worked with Building Gadgets 2.7.4, which is the version I would have been playing with when I remembered this feature. 2.8.0 didn't work at all, and 2.8.1 exhibits the same problem.

So something seems to have changed in 2.8.0 that broke the dank null integration. 2.7.4 works with both the current dank null beta and the most recent stable release.

**Comment by MichaelHillcox** [comment]
We thank you for your issue report, unfortunatly we no longer support this version of Minecraft / Our mod. I've added your issue to a collection of issues that the community is welcome to create pull requests for. Hopefully your issue is resolved in time 👍 Master list: #535
