### ISSUE TITLE
Exchanging Gadget ToolMode 'Change-Cycle' display's BuildingGadget in the corners

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#53]
So, I've been updating my PR just now (I therefore have you're current code...) and when testing whether it still runs, I noticed that the Exchanging Gadget display's Building Gadgets instead of exchanging gagdets for each tool Mode. Sry if this is intended and the issue therefore unessecary...
![2018-08-01_10 12 51](https://user-images.githubusercontent.com/25031360/43509695-a517f92e-9573-11e8-9c8a-600cb626602e.png)

As you can see in the Picture there is the ExchangingGadget displayed in the middle, but the 4 corners, containing the toolModes do not - they show a BuildingGadget...

**Comment by Direwolf20-MC** [comment]
Thank you :) Rorax is working on some art for those corners so it’ll get fixed soon.
