### ISSUE TITLE
Tile Enities Display Incorrectly in Copy-Paste Gadget Tooltip

### ISSUE THREAD

**Issue by WenXin20** [Direwolf20-MC/BuildingGadgets#533]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Building Gadgets v`

In the tooltip of the copy-paste gadget, tile entities are not displaying correctly and look inverted.
Also, the tooltip is cutoff by the top of the screen, and in the template manager, the block preview list can be cutoff on the left side.

How to reproduce the issue: 
1. Copy a structure containing a chest or a head
2. View the tooltip

Screenshot:
![2020-10-22_00 11 10](https://user-images.githubusercontent.com/12000593/96831927-86906700-1403-11eb-8f21-7f38b1bfda17.png)

**Comment by MichaelHillcox** [comment]
Intresting... The cut off isn't really something we can fix unless we just stop showing some items after X amount. Can you confirm if this inverted look still happens on the material screen? (Press M on the copy paste gadget being in your hand) (You also can't trust either screen as both don't take in account for internal inventories nor linked ones)

**Comment by WenXin20** [comment]
Ok that makes sense, Is it possible to make it so you can scroll in the template manager material list instead?

I'll see if I can try out the material screen later today or tomorrow.

**Comment by MichaelHillcox** [comment]
Making the tooltip scroll would be a lot of work for little reward when we have the Material screen for more specific information :D

**Comment by WenXin20** [comment]
Oh, I see. I haven't had a chance to check the material screen yet, so I don't know what's on it. :D 
I might be able to check it later today.

**Comment by MichaelHillcox** [comment]
Fixed, will release the layering issue fix sometime soon :D

**Comment by WenXin20** [comment]
Thanks!

**Comment by MichaelHillcox** [comment]
This issue has been closed by one of our team with an attached reply: 
          
> "Thanks stfwi"

 If you feel this has been done incorrectly then please mention @MichaelHillcox.

**Comment by hvdklauw** [comment]
Wrong issue, my bad :D
