### ISSUE TITLE
Crash w/ Lord of the Rings Mod

### ISSUE THREAD

**Issue by WenXin20** [Direwolf20-MC/BuildingGadgets#536]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Building Gadgets v3.4.0`
[`Lord of the Rings v2.3`](https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed)

If a Copy-paste Gadget tries to place a schematic containing Drystone (crafted with 4 cobblestone) from the Lord of the Rings mod, the game will crash, most likely due to the connected textures the mod uses.
[Crash Report](https://gist.github.com/WenXin20/97e2f86cd3ab0ffe8a483fc841dbeb85)

**Comment by MichaelHillcox** [comment]
Looks to be a closed source mod and thus I can't debug it properly. Looks to be an incompatability issue, just avoid using those blocks. They seem to be doing some hacky things with the block rendering.
