### ISSUE TITLE
Double Slabs Mod Place Incorrectly

### ISSUE THREAD

**Issue by WenXin20** [Direwolf20-MC/BuildingGadgets#537]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Building Gadgets v3.4.0`
[`Double Slabs v2.11.8`](https://www.curseforge.com/minecraft/mc-mods/double-slabs)

If a copy-paste gadget contains double slabs when the mod double slabs is installed, the slabs will not be displayed in the material list, the preview will display the double slabs with missing textures, and will then place double slabs with missing textures, which has the potential to crash the game, as it is an invalid block.

**Comment by MichaelHillcox** [comment]
Looks like they’re all handed via tile entities so this would be the same issue as #538 so I’ll close this one in preference for the other one, thanks for the report and I’ll keep your other issue updated on progress
