### ISSUE TITLE
[Question] Destruction Gadget

### ISSUE THREAD

**Issue by MonfGeiger** [Direwolf20-MC/BuildingGadgets#539]
Got a question about this gadget. Can I set this gadget to only void liquids, or will it only void everything highlighted and not single out anything?

**Comment by hvdklauw** [comment]
Ohh, I love the idea of a liquid only voiding mode!

**Comment by MonfGeiger** [comment]
so I tried to make it only target liquids, but.....I guess that just wont happen. the destruction gadget is indiscriminate in what it erases, fitting as its name implies.  Well, maybe in a future update, that might happen one day, eh?

**Comment by MichaelHillcox** [comment]
Re-opened, I like the idea, I'll add it soon
