### ISSUE TITLE
[1.15.2] Visual glitch when using the paste feature

### ISSUE THREAD

**Issue by elienaimg** [Direwolf20-MC/BuildingGadgets#540]
* Forge 31.2.36
* buildinggadgets-3.4.1.jar
* Using OptiFine_1.15.2_HD_U_G1_pre30

It's just the visual glitch.

![2020-11-08_09 55 08](https://user-images.githubusercontent.com/71791383/98466505-d1a1cc80-21ae-11eb-8a68-aa6be03f51ab.png)
![2020-11-08_09 53 25](https://user-images.githubusercontent.com/71791383/98466515-d6668080-21ae-11eb-80e4-d10ea5644433.png)
![2020-11-08_09 52 46](https://user-images.githubusercontent.com/71791383/98466519-d8c8da80-21ae-11eb-9469-5d8a70e4cf63.png)

I was looking at the banners issue and Idk if the copy/paste tool is supposed to save contents from chests... If it isn't its fine but otherwise isn't working for me...

**Comment by MichaelHillcox** [comment]
What?

**Comment by elienaimg** [comment]
I'm still editing. I posted it by accident.

**Comment by MichaelHillcox** [comment]
Does removing optifine fix this?

**Comment by elienaimg** [comment]
I'll test it now...

**Comment by elienaimg** [comment]
Completely disabling shaders fixes it.  Using optifine's internal shaders or any other brings it back.

**Comment by MichaelHillcox** [comment]
It's a optifine issue then, I can't fix this unfortunately

**Comment by elienaimg** [comment]
I see... I decided to do some building this morning and I've decide to test out the building tool.  I noticed that there is no visual glitch with it.  but if I use the copy/paste tool on the same blocks I just built the glitch is there..  
![2020-11-09_07 18 38](https://user-images.githubusercontent.com/71791383/98543197-daf36d80-2270-11eb-90ca-245c94c29ed1.png)
![2020-11-09_07 18 49](https://user-images.githubusercontent.com/71791383/98543216-e21a7b80-2270-11eb-979e-21f688c9fe76.png)
![2020-11-09_07 27 36](https://user-images.githubusercontent.com/71791383/98543270-f9596900-2270-11eb-96e9-780ece122140.png)

**Comment by MichaelHillcox** [comment]
I'll have a look into it.

**Comment by dkambersky** [comment]
FWIW this is still going on, whenever one turns on shaders through optifine. Possibly related / same class of bug in here - 
https://github.com/refinedmods/refinedstorage/issues/2919
https://github.com/sp614x/optifine/issues/5448
https://github.com/Melonslise/Subterranean-Wilderness/issues/32

These seem a little different but there might be some useful info in there. Looks to have been a quick fix in RS/ST at least.

**Comment by JenyaRostov** [comment]
is a fix to this problem possible? sorry for bumping such an old issue, but i really want to use building gadgets with shaders
