### ISSUE TITLE
fix the glitch

### ISSUE THREAD

**Issue by loonywolf** [Direwolf20-MC/BuildingGadgets#542]
works and all version  just reset optifine to default and poof the glitch is gone (same problem just reset it and it works again not sure if its fast render or something  else but a reset  brings it back )

Lwolf

**Comment by The-Code-Monkey** [comment]
@loonywolf can you explain the glitch in any way you've said how to get around it but you haven't actually told us what is happening. If you can tell us that plus the version of gadgets and if you think optifine is the issue what version of that you are using thanks

**Comment by MichaelHillcox** [comment]
Closing until more info is provided
