### ISSUE TITLE
just a little idee 

### ISSUE THREAD

**Issue by loonywolf** [Direwolf20-MC/BuildingGadgets#543]
maybe please just when moving your build around with the menu z y x please let it  remember were last i excepted and work from there 

Bit of a pain when you reopen the  fine tune menu and your build springs back to the  reset point for when you  started :) 

drives me crazy :) Aka check the name and I'm not far off :) Boo ha ha ha 
 ps great  mod saves me hours of build time and  very useful in creative  fast build all my weird contraptions 

LW

**Comment by MichaelHillcox** [comment]
I might just add this to the rewrite but i like the idea :)
