### ISSUE TITLE
Construction paste blocks do not retain their shape upon reploading them

### ISSUE THREAD

**Issue by Centauren** [Direwolf20-MC/BuildingGadgets#544]
![image](https://user-images.githubusercontent.com/74191484/98605743-efa52500-22b3-11eb-863d-f3e436531bbc.png)
Example of the issue

![image](https://user-images.githubusercontent.com/74191484/98605795-03e92200-22b4-11eb-9944-36176394451d.png)
Minecraft and forge versions

![image](https://user-images.githubusercontent.com/74191484/98605825-12cfd480-22b4-11eb-9862-d0283aae813c.png)
The copy of building gadgets our custom mod pack is using

**Comment by hvdklauw** [comment]
Can confirm with current master.
Paste some blocks that you don't have.

F3+I gives me this:
```/setblock -71 42 118 buildinggadgets:construction_block[ambient_occlusion=false,bright=false,neighbor_brightness=false]{state_actual:{data:{},serializer:"buildinggadgets:dummy_serializer",state:{Name:"minecraft:cobblestone"}},state:{data:{},serializer:"buildinggadgets:dummy_serializer",state:{Name:"minecraft:cobblestone"}}}
```

Exit the world and rejoin it, now F3+I gives:
```/setblock -71 42 118 buildinggadgets:construction_block[ambient_occlusion=false,bright=false,neighbor_brightness=false]{}```

So the state is lost.

**Comment by MichaelHillcox** [comment]
This has been fixed, will be released soon :+1:
