### ISSUE TITLE
[1.16.3] Overlay Glitch

### ISSUE THREAD

**Issue by lulabyte** [Direwolf20-MC/BuildingGadgets#545]
Hello! When using the Building Gadget to place blocks from inventory, I get this wonky overlay:

We are running quite a few mods so I wonder if it could be a conflict.

![2020-11-09_21 52 05](https://user-images.githubusercontent.com/70821058/98633317-0197bf80-22d6-11eb-90b5-bb6f20385e15.png)
y:

**Comment by hvdklauw** [comment]
Which version of the mod/minecraft? What mods?

**Comment by lulabyte** [comment]
Minecraft 1.16.3
Forge 34.1.4.2
Building Gadget 3.7.2

Let me get the list of mods here...

**Comment by lulabyte** [comment]
Mods in our custom modpack:

AdChimneys-1.16.3-6.0.3.0-build.0025.jar
AdHooks-1.16.3-6.1.1.0-build.0017.jar
AdLods-1.16.3-4.1.1.0-build.0026.jar
Apotheosis-1.16.3-4.4.1.jar
Aquaculture-1.16.3-2.1.5.jar
AttributeFix-1.16.3-8.0.1.jar
AutoRegLib-1.6-46.jar
BedBenefits-1.16.3-3.0.1.jar
BiomesOPlenty-1.16.3-12.0.0.417-universal.jar
BloodMagic-1.16.3-3.0.0-1.jar
Bookshelf-1.16.3-8.7.20.jar
Botania-1.16.3-409.jar
BotanyPots-1.16.3-5.1.14.jar
CTM-MC1.16.1-1.1.1.5.jar
ClientTweaks_1.16.3-5.2.0.jar
ConfigurableCane-1.16.3-2.0.0.jar
Controlling-7.0.0.9.jar
CookingForBlockheads_1.16.3-9.2.2.jar
CosmeticArmorReworked-1.16.3-v1.jar
Craftable+Saddles+[1.16.3]-1.3.jar
Cucumber-1.16.3-4.1.3.jar
Cyclic-1.16.3-0.8.3.jar
DarkPaintings-1.16.3-4.0.2.jar
DarkUtilities-1.16.3-6.0.3.jar
DoggyTalents-1.16.3-2.0.1.0.jar
DungeonCrawl-1.16.3-2.1.1.jar
EnchantmentDescriptions-1.16.3-5.0.6.jar
FallingTree-Forge-1.16.3-2.5.0.jar
FarmersDelight-1.16.3-0.2.3.jar
ForgeEndertech-1.16.3-7.0.6.0-build.0024.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
Inspirations-1.16.3-1.2.1.24.jar
JustEnoughResources-1.16.3-0.12.0.100.jar
Lollipop-1.16.3-3.2.2.jar
Ma-Enchants-1.16.3-3.5.0.jar
Mantle-1.16.3-1.6.40.jar
MysticalAgradditions-1.16.3-4.1.0.jar
MysticalAgriculture-1.16.3-4.1.1.jar
NaturesCompass-1.16.3-1.8.5.jar
NetherPortalFix_1.16.3-7.2.1.jar
PackingTape-1.16.3-0.10.0.jar
Patchouli-1.16.2-47.jar
Placebo-1.16.3-4.3.3.jar
Powah-1.16.3-2.3.4.jar
Quark-r2.4-274.jar
RandomTP-MC1.16-4.1.2.jar
RefinedRelocation_1.16.3-8.2.0.jar
RingOfAttraction-1.16.4-1.2.8.jar
Runelic-1.16.3-5.0.1.jar
SBM-BoneTorch-1.16.4-0.0.1.jar
SaveYourPets-1.16.2-1.0.0.4.jar
ServerTabInfo-1.16.3-1.3.3.jar
SilentGear-1.16.3-2.3.3+168.jar
SilentGems-1.16.3-3.7.3+106.jar
SilentLib-1.16.3-4.9.0+63.jar
SimpleDivingGear-5.0.3+mc+1.16.3.jar
SimplyJetpacks2-1.16.3-2.6.3.0.jar
SoundFilters-0.14_for_1.16.2.jar
StorageDrawers-1.16.3-8.2.1.jar
Uncrafted-1.16-4.0.0pre1.jar
Waystones_1.16.3-7.3.1.jar
[1.16.2][Forge]+RPG-HUD-3.8.2.jar
[1.16.3]+SecurityCraft+v1.8.20.1.jar
aiotbotania-1.16.2-1.3.2.jar
angelring-1.16.3-1.3.3.jar
appliedenergistics2-8.1.0-beta.2.jar
archers_paradox-1.16.3-1.0.0.jar
bambooeverything-1.16.3-forge-1.0.0.jar
buildinggadgets-3.7.2.jar
carryon-1.16.3-1.15.1.7.jar
chiselsandbits-0.2.2-ALPHA.jar
cofh_core-1.16.3-1.0.4.jar
collective-1.16.3-1.53.jar
comforts-forge-1.16.3-4.0.0.1.jar
corpse-1.16.3-1.0.6.jar
creeperconfetti-3.4.jar
curios-forge-1.16.3-4.0.2.0.jar
cyclepaintings_1.16.3-1.4.jar
decorative_blocks-1.16.2-1.1.jar
dungeons-plus-1.16.3-1.0.3.jar
elevatorid-1.16.3-1.7.6.jar
embellishcraft-1.16.3-3.2.0.0.jar
enchantedbookredesign-3.1a.jar
extlights-3.1.jar
fairylights-4.0.0-1.16.3.jar
fakeblocks-1.16.3-1.0.1.jar
fishtraps-0.1.2.jar
ftb-gui-library-1603.1.1.25.jar
furniture-7.0.0-pre19-1.16.3.jar
gemsplusplus-1.16.3-V1.8.0.jar
guardvillagers-1.16.3-1.1.5.jar
horsestandstill-1.16.3-1.0.1.jar
invtweaks-1.16.2-1.0.0.jar
ironchest-1.16.3-11.2.6.jar
ironcoals-3.1.2.jar
jei-1.16.3-7.6.0.51.jar
lootbagmod-1.16.3-1.6.2.jar
mahoutsukai-1.16.3-v1.25.2.jar
mapperbase-1.16.3-2.2.0.0.jar
mcpaint-1.6.2.jar
mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar
mcw-windows-1.0.2-mc1.16.3.jar
mcws-roofs-1.16.3-v2.0.0.jar
mermaidtail-1.4.jar
metalbarrels-3.3a.jar
minecolonies-0.13.420-ALPHA-universal.jar
multibeds-1.16-1.7.4.jar
neoncraft-2.1.jar
pamhc2crops-1.16.3-1.0.1.jar
pamhc2foodcore-1.16.3-1.0.0.jar
potionofbees-1.16.3-1.1.0.1.jar
quickhomes-1.16.2-1.2.6.jar
randomloot-2.1.7.jar
randompatches-1.16.2-1.22.1.2.jar
refinedstorage-1.9.7.jar
repurposed_structures-1.16.3-2.2.11.jar
ropebridge-1.16.1-2.0.jar
shetiphiancore-1.16-3.8.4.jar
simplefarming-1.16.3-1.3.5.jar
sit-1.16.2-v1.3.jar
structure-gel-api-1.16.3-1.4.2.jar
structurize-0.13.96-ALPHA-universal.jar
torchmaster-2.3.4-alpha.jar
u_team_core-1.16.3-3.1.12.185.jar
useful_backpacks-1.16.3-1.11.6.84.jar
valhelsia_structures-16.0.5.jar
worldedit-forge-mc1.16.3-7.2.0-rc2-dist.jar

**Comment by MichaelHillcox** [comment]
So strange, what mode and range was that using and out of curiosity, what cords are you at in game?

**Comment by lulabyte** [comment]
Creative mode and it's all ranges with the building (and I think destruction) gadget as well. It's all coords, no matter where I'm at.

Going to check now and see if it happens in survival mode and with the destruction gadget.

**Comment by MichaelHillcox** [comment]
It's definitely another mod doing it but no clue which one

**Comment by lulabyte** [comment]
Yeah I'm sure it is. It happens in survival mode and with the destruction gadget. I can kind of "read" the glitch and it's still usable, it's just tricky. No optifine or anything like that, but yeah I'm sure it's a mod conflict. If I ever narrow it down I'll let you know.

**Comment by hvdklauw** [comment]
I remember enigmatica 5 having a similar glitch, but minecolonies and mining gadgets had the same glitch then. But no clue how it was solved. I'll see if I can find the issue.

**Comment by hvdklauw** [comment]
https://github.com/NillerMedDild/Enigmatica5/issues/312

It was a mod called Neat, but I don't see it in your modlist

**Comment by MichaelHillcox** [comment]
See if you can reproduce this on a newer version of the mod. This is a strange one. Re-open / comment if you can still do it
