### ISSUE TITLE
Copying modded blocks

### ISSUE THREAD

**Issue by Zarbon44** [Direwolf20-MC/BuildingGadgets#546]
The mod is phenomenal, and really helps with making vertical farms of mine, but i have to manually place any block from a mod (Such as IC2). Is it possible to allow any block to be copied? That would be a great feature.

**Comment by MichaelHillcox** [comment]
Game version, mod versions, thanks :)

**Comment by Zarbon44** [comment]
> 
> 
> Game version, mod versions, thanks :)

1.12.2 
2.0.8
Dont tell me its possible now, i havent played mine in a while,

**Comment by MichaelHillcox** [comment]
Wow, that's a really old version, you should update to the latest BG for 1.12 at the very least but no, 1.12 version of BG doesn't support TileEntities but 1.14+ sort of does. It won't be backported either as it requires a big rewrite, sorry about that.
