### ISSUE TITLE
Render crash in GadgetUtils.getAnchor(GadgetUtils.java:116) when placing tool in hand

### ISSUE THREAD

**Issue by wjrogers** [Direwolf20-MC/BuildingGadgets#55]
As soon as I select the Building Gadget in my hotbar, the client crashes:
https://pastebin.com/PwwXmnQz

**Comment by Direwolf20-MC** [comment]
Hi should be fixed in latest version. :)

**Comment by Direwolf20-MC** [comment]
Weird :). I’ll see if I can figure out the cause! Thanks :)

**Comment by Direwolf20-MC** [comment]
Fixed in 2.0

https://github.com/Direwolf20-MC/BuildingGadgets/commit/f1faedaf5551d9bd2fafbb4c429a10420d7b0f2a

**Comment by comp500** [comment]
If anyone finds this crash and can't get back into their game (and can't update the version of building gadgets, like the dw20 pack where it is at version 1.6.2), I have made a jar with just this fix applied. You only need to install it on the client.
[BuildingGadgets-1.6.2-patched.jar.zip](https://github.com/Direwolf20-MC/BuildingGadgets/files/2518900/BuildingGadgets-1.6.2-patched.jar.zip)
