### ISSUE TITLE
[1.16.4] Gadgets not returning isRepairable as false

### ISSUE THREAD

**Issue by kwpugh** [Direwolf20-MC/BuildingGadgets#552]
Forge:  1.16.4 - 35.1.0
Building Gadgets:  3.7.2

I have an item called Ring of Repair from my Gobber mod that scans player inventory and repairs items that are a) repairable and b) damaged.

The ring gets caught on building gadgets.  I think this is because you have the following commented out:

`    /*@Override
    public boolean isRepairable() {
        return false;
    }*/`

in the AbstractGadgets.java class.

If the gadgets are not repairable with material, can you re-enable this feature please?   There may be more going on that I'm not seeing, but you know your code and will now more.

For some reason, this causes ALL items in the player inventory to not be repaired.   The intent is not to allow my ring to repair the gadgets, since they are powered, but to prevent the gadgets from stopping the ring of repair in repairing other items in the players inventory.

This is my core util that handles the repair work:  https://github.com/kwpugh/gobber/blob/1.16.4/src/main/java/com/kwpugh/gobber2/util/RepairTickUtil.java

Thank you.

Regards.

**Comment by hvdklauw** [comment]
The isRepairable method probably shouldn't be implemented (Item already does that) but the damage is used for the energy levels and uses some deprecated methods, so we'll need to have a look at the correct way to handle that, but looking at it settings the canRepair property to false should probably fix this.
