### ISSUE TITLE
[1.16.4] Allow linking of Building Gadget to an Inventory

### ISSUE THREAD

**Issue by MacAttack-UK** [Direwolf20-MC/BuildingGadgets#559]
In the 1.12.x version we were able to Shift+R/Click an inventory such as a chest or 'Storage Drawers' Controller so that it could pull the blocks from it without having them in your inventory.

Would it be possible to add this function back into the 1.16.x version maybe with a config option to enable/disable?

**Comment by MichaelHillcox** [comment]
This already is in the mod :) it got changed to control + shift + right click now

**Comment by MacAttack-UK** [comment]
Excellent, thank you for your time.
