### ISSUE TITLE
Bug/Feature? Proper Rotation

### ISSUE THREAD

**Issue by desagas** [Direwolf20-MC/BuildingGadgets#568]
* Forge version ..13
* Building Gadgets version 3.7.2

* Using the exchanger, the exchanger does not respect the orientation of the original copied block. So, if any log is selected to exchange with, for example, it will only exchange a block with the up down varient, ignoring the south/north and east/west variants entirely. This is the same for stairs, and any other block that has rotation/orientation data.

![2020-12-22_23 23 12](https://user-images.githubusercontent.com/8404632/102966425-16f33280-44ad-11eb-8272-aa47209f7b46.png)
![2020-12-22_23 25 16](https://user-images.githubusercontent.com/8404632/102966426-178bc900-44ad-11eb-8aa3-0b97cbf0c57f.png)

**Comment by hvdklauw** [comment]
This was fixed in 3.7.3, please update!

**Comment by MichaelHillcox** [comment]
This issue has been closed by one of our team with an attached reply: 
          
> "already fixed in 3.7.2"

 If you feel this has been done incorrectly then please mention @MichaelHillcox.

**Comment by desagas** [comment]
Ah, I apologize, I often leave curse open, and sometimes it will not re-sync its site information, which is why I may not have seen the update.
