### ISSUE TITLE
When placing the construction block minecraft crashes

### ISSUE THREAD

**Issue by greencrab312** [Direwolf20-MC/BuildingGadgets#569]
**Forge version**
I tried on 35.1.13 and 35.1.4 the game crashed both times

**Building Gadgets version**
- 3.7.3 (building gadgets)
- There was no crash when I used forge: 35.1.4 (forge) & 3.7.2 (building gadgets)

crash report: https://pastebin.com/72LFpiFp

**How to reproduce the issue**
Place a construction block
or load a world with a construction block already placed in it.

https://user-images.githubusercontent.com/76529328/103047633-211f3a80-455a-11eb-9924-1b96c587ba03.mov

**Comment by MichaelHillcox** [comment]
Yeah, that's likely expected as you're not meant to place them by hand, I think you want the construction paste which is used with the gadgets to build that contrustion block so it takes the shape of any other block. I'll look into this as it shouldn't crash but yeah.
