### ISSUE TITLE
Placing glass panes (build to me) not connecting properly

### ISSUE THREAD

**Issue by CaribouJohn** [Direwolf20-MC/BuildingGadgets#570]
* Forge version = 35.1.13
* Building Gadgets version = 3.7.2
* Not a crash :) and not a serious bug
* Build to me with window panes (vanilla) (see screenshot)
![image](https://user-images.githubusercontent.com/6026956/103171259-b49a8900-4842-11eb-8668-dd31484ef10c.png)

At the bottom right I placed the lowest pane to reference, and the one above I broke the block next to it and replaced it to see if it updated properly which it did. 

The other panes are as created by the building gadget - no big deal but thought it might be something that could be fixed.

**Comment by hvdklauw** [comment]
Please update to 3.7.3 this was fixed in that version!

**Comment by MichaelHillcox** [comment]
This issue has been closed by one of our team with an attached reply: 
          
> "Fixed in 3.7.3"

 If you feel this has been done incorrectly then please mention @MichaelHillcox.

**Comment by CaribouJohn** [comment]
Thx :)
