### ISSUE TITLE
Allow whitelisting blocks with NBT data

### ISSUE THREAD

**Issue by TrevorBagels** [Direwolf20-MC/BuildingGadgets#571]
It'd be nice if we could use the building gadget to place things like fluxducts and itemducts from thermal expansion, and an ideal way to do this would probably be a whitelist somewhere in the config.

**Comment by hvdklauw** [comment]
Those aren't implemented in 1.16 yet are they? 

I agree that it would be nice if they worked, but I doubt we'll be adding a feature like that to 1.12.

For 1.16 they might just work once implemented, depending on how they do it, but can't say anythin about it right now.

**Comment by MichaelHillcox** [comment]
I don't plan adding this for 1.12 as 1.12 is only bug fixes and from what I know this will just work on 1.14+ once TE and TD updates.
