### ISSUE TITLE
Exchanging Gadget and Spawners

### ISSUE THREAD

**Issue by RyanP1991** [Direwolf20-MC/BuildingGadgets#584]
While playing on the Direwolf20 pack, it seems to be that an exchanging gadget when copying a spawner will copy a spawner and when pasting will turn it in to a pig spawner at only just an energy cost.

Pack Version: 1.2.0
Forge Version:
Building Gadget version: 3.7.3

![2021-01-10_20 02 20](https://user-images.githubusercontent.com/8337825/104134006-041ea000-537f-11eb-8552-48fec93fc1d8.png)

**Comment by MichaelHillcox** [comment]
Thanks! I'll get this sorted, must have missed it in the block blacklist

**Comment by hvdklauw** [comment]
Yeah, looking at spawners: they have no tag, and apotheosis for instance replaces spawners with their own version, so it's not so simple to add to the blacklist

**Comment by MajorTuvok** [comment]
Spawners not having a Tag is I think an oversight of Forge, because there are quite a few mods adding spawner like behaviour.
