### ISSUE TITLE
Feature Request: Building Gadget Contiguous Mode

### ISSUE THREAD

**Issue by cobbkris** [Direwolf20-MC/BuildingGadgets#585]
It would be nice to have a contiguous mode at least in the surface or horizontal wall.  Here is a visual representation:
(S=Sand | G=Gravel)
Green is where a new block is placed.
Red is left alone.
![image](https://user-images.githubusercontent.com/34900042/104225381-51008600-5414-11eb-8cdf-e43109899d53.png)

**Comment by MichaelHillcox** [comment]
Isn’t that just connected area mode?

**Comment by cobbkris** [comment]
My bad, yes it is.  Not sure mine wasn't turned on.
