### ISSUE TITLE
How to select block type used by the Building Gadget?

### ISSUE THREAD

**Issue by khdhhde21** [Direwolf20-MC/BuildingGadgets#586]
I just started using this mod. Watched the youtube video. Still can't figure out how to select the block type that is used for all the new structures created by the Building Gadget.

**Comment by TinusJ** [comment]
Hi @khdhhde21, i believe you press 'LSHIFT' and Right Click with your mouse on the block type you want to select

**Comment by khdhhde21** [comment]
Thank you @TinusJ so much! Could you please share a link to that documentation page?

**Comment by MichaelHillcox** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets/wiki although it's a bit out of date

**Comment by khdhhde21** [comment]
Sorry, but it looks like a different page.

**Comment by MichaelHillcox** [comment]
I mean, I wrote both so.... if you want me to be super specific: https://github.com/Direwolf20-MC/BuildingGadgets/wiki/Building-Gadget

**Comment by khdhhde21** [comment]
Thank you! This is a really nice mod. I wouldn't attempt building anything serious without it.
