### ISSUE TITLE
[Feature Request] Allow construction paste to be created using Create

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#588]
Create offers a pulverizer/macerator like structure and via bulk washing (compare Dire's Create Spotlight Part 2, around 27mins) something that might be a nice replacement for placing the blocks next to water.

To be honest I'm not that familiar with how construction paste is created, I just remember that the default method involves having to place somw block next to water which after getting converted has to be mined. Both of these processes sound like something that could nicely be automated using create and the fact, that create can process stacks at a time (and can create clay) would propably make it a lot easier for people to get their hands on construction paste.

**Comment by hvdklauw** [comment]
Create has good datapack support, I wonder if we can add a datapack to buildinggadget that will add a recipes to create

**Comment by hvdklauw** [comment]
https://github.com/Creators-of-Create/Create/blob/mc1.15/dev/src/main/resources/data/create/recipes/compat/quark/splashing/iron_plate_rusting.json

This is an example from create itself where it basically has datapack support added to add a recipe if quark is loaded, I think we can flip that around and add a thing in building gadgets that adds a recipe if create is loaded.
