### ISSUE TITLE
[Feature Request] Structure/Mode API

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#59]
It would be really appreciated if you could add an API (as mentioned in #58) allowing to add Modes to Building/Exchanging Gadgets. 

Benefits:
- People would be able to allow auto-build of whole structures (which might come in handy with f. e. Astral Sorcery altars, etc.)
- If anyone comes around with a mode of which you think is too much, they will now be capable of adding it themselves (if they truly want it so much)
- A system for all the new modes which might eventually come up, would solve your not yet (but in the forseeable future) existing mode-overflow problem

A proposal for this (If you want to I could write the code for it, but I presume you'd rather write something similiar yourself... :) ):
- For the mode system I'd propse being able to cycle through pages (f. e. with the Mouse Wheel) grouped by owning mod (and a max number of some kind (8?) though ot would certainly look more nicely, if in the case of additional pages, modes of one mod would be evenly divded amongst it's pages)
- For the API in itself, maybe IBuildingMode and IExhangingMode interfaces with a Method build (passed in coordinate list, lookVec and whatnot). One could then register them to the Building/Exchanging-Registry (Could be a ForgeRegistry? (Buildingmodes should be singletons after all)) and instead of hardcoding this giant if/else you'd then delegate through to the respective build Method in order to retrieve your coordinates. Of course Building/Exchanging Modes would require localization Methods amongst other things...

**Comment by Direwolf20-MC** [comment]
This is pretty much covered by the copy/paste tool. Also, planned, is a template system to store copied structures.

**Comment by MajorTuvok** [comment]
:)

I forgot to close it myself after you showed that preview... 
Sry for the extra work...

**Comment by Direwolf20-MC** [comment]
No worries :).  Copy paste tool has been a feature planned since I first had the idea. I just didn’t want to spoil the feature ;)
