### ISSUE TITLE
exchanging logs in one orientation for one in another orientation doesn't work.

### ISSUE THREAD

**Issue by hvdklauw** [Direwolf20-MC/BuildingGadgets#591]
Notice this today when doing some building and Haas to basically rotate some logs, thought the exchanging gadget would help, but it simply didn't work. Had to first exchange it with another block and then exchange it with logs with the right orientation.

**Comment by MajorTuvok** [comment]
@MichaelHillcox I told you, that you should check the blockstates, not just the block!
