### ISSUE TITLE
Client Crash On Paste of schematic!

### ISSUE THREAD

**Issue by Grant-K** [Direwolf20-MC/BuildingGadgets#595]
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
* Forge version 35.1.36
* Building Gadgets version 3.7.3
* *If the issue is a crash*; An external link to the crash report https://pastebin.com/xqNTn6H3
 I attempted to use this schematic (https://pastebin.com/dTSMamRy) while only having construction paste available to build with and upon building it crashes the client

**Comment by MichaelHillcox** [comment]
Fixed in 1.16.5 #569 not sure why it happened in this instance though, likely an edge case this should have covered.
