### ISSUE TITLE
Building Gadget/Destruction Gadget showing no preview of blocks being placed or destroyed

### ISSUE THREAD

**Issue by 3XZACT** [Direwolf20-MC/BuildingGadgets#596]
As above no preview or overlay being shown even though it is on. Attached are 2 short clips of showing now overlay with blocks that should be destroyed, and the other being no overlay with building gadget.

I am playing the latest version of FTB Direwolf20 1.16.

I have restarted the game, tried different worlds uninstall and reinstall the mod into the modpack and every time coming across the same frustrating result.

Now I am fairly new to trying to trouble shoot and also this mod so i could be missing something very basic here as well.

https://user-images.githubusercontent.com/42225521/105309199-04d1f480-5c11-11eb-8880-99eee97a203c.mp4

https://user-images.githubusercontent.com/42225521/105309260-07cce500-5c11-11eb-8ce2-b63a0902324f.mp4

**Comment by MajorTuvok** [comment]
Could you try to reproduce this without other mods installed? Is optifine or another similiar mod present?

**Comment by MichaelHillcox** [comment]
Part of #609 it's Fabulous graphics causing issues
