### ISSUE TITLE
BOP leaves can only be swapped once?

### ISSUE THREAD

**Issue by purpleposeidon** [Direwolf20-MC/BuildingGadgets#6]
I grew a Pam tree, and wanted to replace its vanilla leaves with BOP ones. First I replaced a single leaf block above the fruit, to check that the fruit didn't pop off. (It doesn't.) Later I came back to replace the leaves on the entire tree, but the gadget was refusing to swap the BOP leaves with any block.

**Comment by Direwolf20-MC** [comment]
I want to say this is fixed, but there are edge cases where it may not work. I think they are exclusively acacia and dark oak?  https://github.com/Direwolf20-MC/BuildingGadgets/commit/2eee25bb7c30f0436097ca722ee8d6744364438c
