### ISSUE TITLE
Rftool storage controller has crafting bug

### ISSUE THREAD

**Issue by wain99** [Direwolf20-MC/BuildingGadgets#600]
forge version 1.16 (35.1.36) via ftp launcher
The last update of the pack 
the storage controller wont craft certain items such as the crafting table and a diamond sword. I don't know all of them just these two.
how to recreate it?
 just place storage controller place any kind of storage (I placed a modular storage with 4tire upgrade with needed items) put the wood planks in and try to craft a crafting table.
![123](https://user-images.githubusercontent.com/78321071/106396501-bcd97b80-6421-11eb-9031-71fce4db5b70.PNG)

**Comment by MichaelHillcox** [comment]
What does this have to do with BG?

**Comment by McJty** [comment]
I didn't know building gadgets caused bugs in my mods already :-)
Anyway, I'm already aware of this bug so no need to report it for me

**Comment by MichaelHillcox** [comment]
> I didn't know building gadgets caused bugs in my mods already :-)
Anything is possible with building gadgets
