### ISSUE TITLE
Paste is too large for BG in SF4

### ISSUE THREAD

**Issue by TbagTheGreat** [Direwolf20-MC/BuildingGadgets#603]
**IMPORTANT:** Before continuing, please ensure that Building Gadgets (and any other mods involved) is updated to the latest available version
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
* Forge version
* Building Gadgets version
* *If the issue is a crash*; An external link to the crash report
* How to reproduce the issue
* A screenshot, if applicable

**Comment by MajorTuvok** [comment]
@TbagTheGreat this is missing a description

**Comment by MichaelHillcox** [comment]
Closing until more info is added
