### ISSUE TITLE
Rendering crash with Construction Blocks

### ISSUE THREAD

**Issue by DenimRed** [Direwolf20-MC/BuildingGadgets#608]
Affected Versions: 
- Building Gadets **3.7.3**
- Forge **35.1.4** and above
- Minecraft **1.16.4**

Crash Report: https://pastebin.com/TSSm4n1S

---
It's caused by a [missing null check in `ConstructionBlockTileEntity#getModelData` regarding the nullable `blockState` object](https://github.com/Direwolf20-MC/BuildingGadgets/blob/180ead3b2bd07e3b51a60c4dcda37be9e48ee26f/src/main/java/com/direwolf20/buildinggadgets/common/tileentities/ConstructionBlockTileEntity.java#L34).

Reproducible by simply placing down a Construction Block.

**Comment by hvdklauw** [comment]
Yeah, you are not supposed to have those blocks to place them. You make the powder, it turns into dense blocks when placed and those give you construction paste to use when you don't have the right blocks. The tool places the construction blocks with the correct data.

**Comment by DenimRed** [comment]
Ah okay, that makes sense thank you. (I don't use the mod much myself, I'm just a member of a modpack.)
I think it would be good to have a failsafe though, just to prevent the block from possibly breaking worlds in the event of an issue or if someone accidentally places it directly.
It may also be good to remove its item as well to avoid confusion, but that's something else to consider.

**Comment by hvdklauw** [comment]
Totally agree, it shouldn't crash!

**Comment by MichaelHillcox** [comment]
Oh, fixed this, it was part of #569 closing for now :D
