### ISSUE TITLE
blue concrete causes crashes

### ISSUE THREAD

**Issue by XCOYoshi** [Direwolf20-MC/BuildingGadgets#610]
---------------------------------------------------------------------------
After deleting this template, please provide the following information:
* Forge version : 35.1.37
* Building Gadgets version buildinggadgets-1.16.4-3.7.3.jar 
* *If the issue is a crash*; An external link to the crash report 
[crash-2021-02-05_20.57.04-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/5934957/crash-2021-02-05_20.57.04-server.txt)

* Building blue concrete

**Comment by MichaelHillcox** [comment]
> [crash-2021-02-05_22.10.28-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/5935364/crash-2021-02-05_22.10.28-client.txt)
> client crasch with ender pouch

Please create a new issue with more details for this crash

**Comment by MichaelHillcox** [comment]
>     * Building blue concrete

Please provide more information on how this crash happened

**Comment by XCOYoshi** [comment]
the crasche hapend wenn 2 peopel tryt to built a blue concret wall with build to me Function

**Comment by MichaelHillcox** [comment]
Patched the crash at least, please provide more detail if you wish to have the root cause of the crash fixed. I can't really understand what you're saying here.
> the crasche hapend wenn 2 peopel tryt to built a blue concret wall with build to me Function
