### ISSUE TITLE
Building Gadget crasching client wenn puting away into a Inventory or wenn using the Exchange gadget

### ISSUE THREAD

**Issue by XCOYoshi** [Direwolf20-MC/BuildingGadgets#611]
----------------------------------------------------------------------------
After deleting this template, please provide the following information:
 Forge version  : 35.1.37
Building Gadgets version buildinggadgets-1.16.4-3.7.3.jar

[crash-2021-02-05_22.10.28-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/5936797/crash-2021-02-05_22.10.28-client.txt)
[crash-2021-02-06_12.00.50-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/5936798/crash-2021-02-06_12.00.50-client.txt)

Schift Rigtclicking a Stonbrick or trying to move the gadget in the inventory

Cant make a screnschot becouse i cant conect back into the server becfouse my game kepps crasching

**Comment by MichaelHillcox** [comment]
Use an NBT editor for you players inventory to remove the gadget, or whilst joining, spam a button that isn't a gadget. I'll look into this issue. It could be a mod incompatibility issue.

**Comment by XCOYoshi** [comment]
ok thanks

**Comment by MichaelHillcox** [comment]
Looks like this is an issue on Industrial foregoing's mod, it also looks to be fixed so I'll close this, update your IF mod :D
