### ISSUE TITLE
Crash on copying of a template into the copy-paste tool

### ISSUE THREAD

**Issue by Raphpat** [Direwolf20-MC/BuildingGadgets#613]
**Building Gadgets version**
3.7.3

**Forge version**
36.0.10

**Do you have optifine installed?**
No

**Modpack (with version), if applicable**
Enigmatica 6, v 0.3.13

**If the issue is a crash; An external link to the crash report**
[Link to crash report](https://pastebin.com/vtYhLHy1)

**If it's copy paste gadget related, the actual template that is causing the issue would be appreciated.**
[Link to template](https://pastebin.com/scYgz1Vt)

**Screenshot of the crash**
[Link to screenshot](https://imgur.com/a/6emHklz)

**How to reproduce the issue**
- Place a piece of paper in the bottom slot of the template manager
- Import the template from clipboard with "Paste" button into the paper
- Click "Load" button with copy-paste gadget in the top slot of the template manager
- Crash

**Anything to add**
I got it working again the next day. The template had been imported into the copy paste gadget. I then used it a bit (used another template) then went back to load the original template in the tool and crashed again.

**Comment by MichaelHillcox** [comment]
Hmm, I can't reproduce this error... It might be a mod incompatibility. I'm not using your mod pack but if you could load up a standard forge instance with just BG installed and see if you can reproduce the issue, that would be super helpful

**Comment by Raphpat** [comment]
I can't reproduce it anymore either... Both in the modpack and in the standard forge instance with just BG.

**Comment by MichaelHillcox** [comment]
Well let's home it's fixed, if not, reopen this issue
