### ISSUE TITLE
EnderChests + Building Gadget = Not Happy

### ISSUE THREAD

**Issue by drunkripper** [Direwolf20-MC/BuildingGadgets#614]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Building Gadgets version**
Found in Modpack Version

**Forge version**
Found in Modpack Version

**Do you have optifine installed?**
Found in Modpack Version

**Modpack (with version), if applicable**
Direwolf20 1.16.5 1.6.1

**If the issue is a crash; An external link to the crash report**
https://pastebin.com/zq2ayniD

**How to reproduce the issue**
Building Gadget To Me Enderchests cause crash loop on world load.
*Please provide use with a step by step description*
Tried to place ender chests with building gadget. Game Crashed

**Comment by MajorTuvok** [comment]
> Forge version
> Found in Modpack Version

Please be aware that you did not provide the Forge version, but instead only the mc version and the version of the direwol30 pack. Could you please include the Forge version?

**Comment by MajorTuvok** [comment]
> Do you have optifine installed?
> Found in Modpack Version

Furthermore could you please answer this question? And try without optifine if the answer is yes?

**Comment by MajorTuvok** [comment]
> Building Gadget To Me Enderchests cause crash loop on world load.
I'm sorry but a crash loop is an impossible thing - if it crashes the loop ends and if the exception is caught, it doesn't crash (though it does spam the log)... What do you mean with that? You can no longer load the world?

**Comment by MajorTuvok** [comment]
> Building Gadgets version
> Found in Modpack Version

This is missing too, btw... I guess you are on 3.7.3 (latest)?

**Comment by MajorTuvok** [comment]
Using the crash log I just spent on my mobile 15min extracting the following information:
Forge version: 36.0.14
BG: 1.16.4-3.7.3
Ender Storage: EnderStorage-1.16.4-2.7.1.166
Optifine does not seem to be present.

@drunkripper please provide this information in the future!
