### ISSUE TITLE
[1.16] Cannot paste in survival with energy disabled

### ISSUE THREAD

**Issue by 3l3m01** [Direwolf20-MC/BuildingGadgets#617]
I have building gadgets installed on my server, with my custom modpack. I play with no energy ("Maximum Energy" set to 0).  All gadgets work fine, except the copy-paste gadget. It simply refuses to paste anything if energy is disabled. All other gadgets work fine, it works in creative, or if I re-enable energy, I have all items in my inventory (everything is green on the material list).

Building Gadgets version:3.8.0
Forge version:36.0.42
Do you have optifine installed? No

Way to reproduce:
Set "Maximum Energy" = 0 under [Gadgets."Copy-Paste Gadget"] in the buildinggadgets-server.toml file.
Craft a copy-paste gadget in survival.
Copy any block 
Try to paste it.

**Comment by MichaelHillcox** [comment]
Hmm, strange, I'll look into it

**Comment by NillerMedDild** [comment]
Can confirm that this is happening in `buildinggadgets-1.16.5-3.8.0` still, with `Forge-1.16.5-36.1.16`

**Comment by SkyRaax** [comment]
Can also confirm.

For the fix:
"Energy Cost" for the "Copy-Paste Gadget tool" to "0"

**Comment by MichaelHillcox** [comment]
feat-request: make the gadgets easier to disable power

**Comment by NillerMedDild** [comment]
Or just update the config comment 😄 this is what it looks like:
```toml
#Energy Cost & Durability of the Copy-Paste Gadget
[Gadgets."Copy-Paste Gadget"]
	#The max energy of the Gadget, set to 0 to disable energy usage
	#Range: > 0
	"Maximum Energy" = 0
	#The Gadget's Energy cost per Operation
	#Range: > 0
	"Energy Cost" = 50
```

It's correct that setting `"Maximum Energy" = 0` disables energy usage for the other gadgets, just not the copy-paste gadget.

**Comment by MichaelHillcox** [comment]
Of course but this is a constant issue with a pretty easy solution, make it simpler :P haha

**Comment by 4rz0** [comment]
I can confirm this issue with version 3.8.2 and forge 36.2.20.

**Comment by NielsPilgaard** [comment]
Thank you ❤️
