### ISSUE TITLE
[1.16.5] Placing Pane In The Glass Glass creates noninteractive space

### ISSUE THREAD

**Issue by NillerMedDild** [Direwolf20-MC/BuildingGadgets#622]
**Building Gadgets version**
- buildinggadgets-1.16.5-3.8.0

**Forge version**
- Forge-1.16.5-36.0.46

**Do you have optifine installed?**
- No

**Modpack (with version), if applicable**
- Enigmatica 6 v0.4.3 in-dev

**How to reproduce the issue**
- Attempt to place `Glass pane (edge aligned)` from the mod Pane in the Glass with a Building Gadget
- Observe the bug

**A screenshot, if applicable**
Screenshot of the affected Pane selected in Building Gadget in build-to-me mode.
![billede](https://user-images.githubusercontent.com/21295394/111379673-ae7ab280-86a3-11eb-9cbe-66564c0c5da2.png)

Normal Glass Panes for comparison
![billede](https://user-images.githubusercontent.com/21295394/111379755-c81bfa00-86a3-11eb-93cc-4b930f0fff57.png)

**Anything else we should know?**
Reported to Pane in the Glass here: https://github.com/MongoTheElder/PITG/issues/19

**Comment by MajorTuvok** [comment]
You say observe the bug - as I can't see anything on the image (it's too dark for my mobile, do might as well be that), I assume that a ghost block is created?

**Comment by MichaelHillcox** [comment]
Looks like non connected glass? We're going to need more info about the 'bug' part please

**Comment by telemenar** [comment]
I’ve not tested it myself but having followed the bug on the Enigmatica 6 side. When you paste the block it results in a ghost block that is non-interactable. Block ends up in some sort of invalid state.

**Comment by NillerMedDild** [comment]
The Pane in the Glass dev says it's a bug on his part: https://github.com/MongoTheElder/PITG/issues/19#issuecomment-801308218
