### ISSUE TITLE
Blueprint tool?

### ISSUE THREAD

**Issue by pokermanx** [Direwolf20-MC/BuildingGadgets#623]
.blueprint tool reader, building like copy&paste. Last one can have a save button. Structurize has similar working login, tho required minecolonies.

**Comment by MichaelHillcox** [comment]
So you want us to work with blueprints? Are .blueprints even a thing anymore?

**Comment by pokermanx** [comment]
You tell me. Its a feature request. Call me retarded and close it if its stupid lol

**Comment by MichaelHillcox** [comment]
It's your feature request, provide more information or I can't help you. I can't even consider your recommendation without proper info

**Comment by pokermanx** [comment]
Well, say I have a build in SP I would really want to transfer to a server. How do I do that without a 3d party world editor? Build it block by block. Why was I talking about .blueprint ext? It is used in structurize to scan-save-paste an area. So having the functionality of copy&paste tool, instead of holding it in a buffer (pure guess, haven`t looked into sources) add an option to save it permanently for later use.

**Comment by MichaelHillcox** [comment]
You can already do this. Read the docs / wiki. The TL;DR is use the template manager, copy the area with the copy paste gadget, put in the template manager, click copy and it'll be in your clipboard.

**Comment by pokermanx** [comment]
I am retarded
