### ISSUE TITLE
Building Gadgets menu doesn't work

### ISSUE THREAD

**Issue by Jonathany25** [Direwolf20-MC/BuildingGadgets#636]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

buildinggadgets-1.16.5-3.8.0

Forge - 36.1.16(1.16.5)

No optifine, also doesn't work with optifine.

Seaopolis-B5.5

When trying to open the menu, it flashes then closes again. Most of the times it doesn't even open. I have checked the keys and there are no conflicts.

**Comment by MichaelHillcox** [comment]
I'll assume you've bound it to a mouse button or something other than default?

**Comment by Jonathany25** [comment]
Yes I have. Is that a problem?

**Comment by MichaelHillcox** [comment]
Yeah, if it's a non-standard keyboard button, it'll likely not work as minecraft handles custom key buttons really oddly.
