### ISSUE TITLE
when i try to paste terracota it crashes the game

### ISSUE THREAD

**Issue by ollietron** [Direwolf20-MC/BuildingGadgets#640]
### Building Gadgets version

3.8.0

### Minecraft Version

1.16.5

### Modpack & Version

seaopolis 1.5

### Do you have optifine installed?

No

### Describe the issue

when I try to paste terracotta it crashes the game

### Steps to reproduce

copy blue terracotta with copy-paste tool
select paste

### Expected behaviour

it to not crash

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
I can't believe that I spent time on the issue template and yet you still managed to avoid adding crash logs for a issue related to crashing...

Please add crash logs

**Comment by MichaelHillcox** [comment]
Can not reproduce
