### ISSUE TITLE
Crash to desktop issue

### ISSUE THREAD

**Issue by Cfgaar** [Direwolf20-MC/BuildingGadgets#646]
### Building Gadgets version

3.8.0

### Minecraft Version

1.16.5

### Forge Version

36.1.0

### Do you have optifine installed?

No

### Describe the issue

Game crashes to desktop and is unable to be loaded back in without admin assistance

### Steps to reproduce

No idea.

### Expected behaviour

Not crashing.

### Log files

https://paste.ee/p/6H6fV
https://paste.ee/p/fzozu

### Additional information

Dynamic trees community referred me to this post when I asked them for help. 
https://github.com/ferreusveritas/DynamicTrees/issues/546#issuecomment-846352936

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Odd, I'll look into it

**Comment by Fireztonez** [comment]
I don't know if this is the cause of your crashes, but your forge version is very old (You are using the first forge version released for 1.16.5), today many mods require a newer forge version to be able to function. I possibly suggest you try updating forge to the latest recommended version, i.e. up to version 36.2.0.

**Comment by Cfgaar** [comment]
Understood. I think the server version would have to be updated as well.
Just picked the one multimc recommended.
I'll look into the process.

**Comment by Cfgaar** [comment]
It might be. Killed the server for inactivity.
If it goes up again soon with the same issues, I'll let you know.
