### ISSUE TITLE
Crash to desktop on paste preview/placement

### ISSUE THREAD

**Issue by DarkWolfe5** [Direwolf20-MC/BuildingGadgets#648]
### Building Gadgets version

3.8.0

### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Modpack & Version

Seaopolis 5.3

### Do you have optifine installed?

Yes

### Describe the issue

Crash to desktop in Paste mode of Copy-Paste gadget with larger structure ready to copy. 

### Steps to reproduce

1. When in game, select a large area of blocks, ex: the starter sphere.
2. Switch to paste mode
3. Watch the game crash!

### Expected behaviour

NOT to crash, but to show the structure to be pasted.

### Log files

https://pastebin.com/tMBgeHRC

### Additional information

This happened to me before, but I was on a seriously under-powered computer (integrated CPU graphics), so I thought it was my lack of a GPU.
I managed to save the structure to a blueprint and stored it away for the future.

Brand new computer w/ RTX 3060 16GB  and I got the same issue.
Today I loaded the blueprint and as soon as I selected the copy-paste gadget, the screen froze then crashed a few seconds later w/o even seeing the build preview.

Tried it w/o optifine. Got as far as a foggy purgatory. I could see the copy-paste gadget in my hand, then crash to desktop: https://pastebin.com/FLbK39mD

### Information

- [X] I have provided as much information as possible

**Comment by MajorTuvok** [comment]
The issue originates from blockcarpentry mod.pianomanu.blockcarpentry.util.BlockColorHandler.getColor(BlockColorHandler.java:91)
and is somehow related to how the color is retrieved, haven't looked into the code though.
Could you please verify this without Optifine being installed?

**Comment by DarkWolfe5** [comment]
Hehe, all good. I have the save backed up just in case you'd like to try it out yourself as well.
Blueprint should be in a chest tucked in the corner of my storage drawers and big window in the wooden room.
(It's not a big base, and kinda haphazard)
Let me know if you need any help finding it.

https://1drv.ms/u/s!AvBipfvhCM9jixKIAaoZxks-cI1c?e=5pbFKT
