### ISSUE TITLE
Update 1.17

### ISSUE THREAD

**Issue by LR146** [Direwolf20-MC/BuildingGadgets#666]
My server is version 1.17. I regret that I cannot use the MOD you made. I really need this MOD, because my players and I love your plug-in very much. I hope to update to support 1.17. For this we sponsored you 5 U.S. dollars as your motivation

**Comment by MichaelHillcox** [comment]
I'll release the 1.17 version sometime this week I guess?

**Comment by MichaelHillcox** [comment]
Released <3
