### ISSUE TITLE
Transparent Quark/Chisel blocks using building gadgets 

### ISSUE THREAD

**Issue by Keikekshi** [Direwolf20-MC/BuildingGadgets#667]
### Building Gadgets version

buildinggadgets-1.16.5-3.8.2

### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Modpack & Version

Ragnamod VI (Beta 6.0.25)  - 1.16.5

### Do you have optifine installed?

No

### Describe the issue

Using the building gadgets to place modded blocks the blocks are textured transparent until interacted with 

### Steps to reproduce

1 Equip building gadgets tool
2 Try to place modded blocks with the tool (chisel I.E)

### Expected behaviour

Block not being transparent

### Screenshots

![java_Bbegn95iBv](https://user-images.githubusercontent.com/95539473/144716622-86efc65f-a429-43e3-a99f-11baa54b6a2b.jpg)

### Additional information

Some fixes are changing dimensions, DC/RC, hitting them.

Also if I use the tool too fast, some modded blocks are invisible(not loaded?) and impossible to interact with. Fixed with the usual fixes from above. 
Example : 
![java_4o0uIxbUJM](https://user-images.githubusercontent.com/95539473/144716744-66a6517f-1c91-4773-8be3-81efc5bb9b98.png)
 
 
 There could be another rendering mod in the pack, but I'm not aware of it. I just downloaded it and it's incompatible with optifine.
 
 Thank you

### Information

- [X] I have provided as much information as possible

**Comment by The-Code-Monkey** [comment]
Were there any specific blocks this was happening with in the modpack or was it doing it with all of them??

**Comment by Keikekshi** [comment]
Mostly quark and chisel it seems. I tried a bunch of random blocks from different mods. So far only those two mods.
![java_jXzClcJ9Cv](https://user-images.githubusercontent.com/95539473/144717690-5940843d-c0ff-4ef5-b332-de49578ced1a.png)

I will try to find other blocks from other mods that are affected by this issue.

**Comment by The-Code-Monkey** [comment]
Ok the specifics mean someone can test it with those mods in isolation to see if it's that mod that causes it or like you said there might be another rendering mod at work.

**Comment by Keikekshi** [comment]
Good news.
In total isolation it's fine. 
Tried with the same mod version as ragnamod 6
The issue only applies to Quark/Chisel in Ragnamod 6, I wonder what causes it.

![GDLauncher_0CqgtmgTyP](https://user-images.githubusercontent.com/95539473/144718117-53cd7dea-80a6-4bca-995f-67296fdadd19.png)

**Comment by Keikekshi** [comment]
No issues in singleplayer.

**Comment by Keikekshi** [comment]
I tried two things
1 - Hosting a server in isolation to see if I can replicate the issue in multiplayer too.
2 - Hosting a new map on Ragnamod 6 to see if the issue persist.

Results :

- Isolated mods -
No issues. Both SP & MP. Unable to replicate.

- Ragnamod 6 -
SP : No issues.
MP : The issue persist. Replicated.

I will try to go on their discord to see if anyone figured out the mod that conflict with that specific interaction, hopefully bringing back good information. (You might not care, if that is the case you should close this thread. Thank you for your time and help <3 )

**Comment by Keikekshi** [comment]
Seems like the bug has been in the modpack for a while (August at least). It also affect construction wands, but even worse, they're entirely invisible instead of transparent, and you get the typical bug where you get stuck in them and rolled back. (Only Quark & Chisel blocks once again.)

If you have any idea about what could possibly cause this. I will gladly try it out. Thank you.

Their discord doesn't allow new users to discuss anything, so it'll take a while until I'm given access it seems. And I doubt they found a fix if it's still up to this day, but I'll try anyway.

I don't know if I should close this thread (I'm new to github) since it seems it's not Direwolf's mod that causes it, but at the same time I'd like to narrow it down to what causes it for awareness/potential fixes.

**Comment by Keikekshi** [comment]
I am closing this since it's caused by conflicting mods, sadly I couldn't find any fix.
I haven't tried everything but tried a lot, nothing worked on my end MP-wise..
