### ISSUE TITLE
Stair replacement

### ISSUE THREAD

**Issue by Thiana** [Direwolf20-MC/BuildingGadgets#67]
With BuildingGadgets v1.6.2 replacing stairs doesn't work correctly (rotation). The following two images demonstrate the problem.

![2018-08-22_13 10 44](https://user-images.githubusercontent.com/405832/44479028-63907f80-a60d-11e8-8b19-bb39a766f49a.png)

![2018-08-22_13 10 53](https://user-images.githubusercontent.com/405832/44479032-65f2d980-a60d-11e8-8497-c858817e3614.png)

This is a common problem with replacers but I'm hoping since your mod specializes in building tools that it can be done correctly (via staying with the placed rotation or a toggle to lock/unlock rotation matching). 

Thanks.

**Comment by MajorTuvok** [comment]
@see #31...

**Comment by Thiana** [comment]
It's not the same issue as #31. That issue is about placing *new* blocks, not replacing existing blocks which have a known rotation.

**Comment by kfish610** [comment]
Are these construction paste stairs?

**Comment by Thiana** [comment]
No, just standard stone/netherbrick stairs.

**Comment by Direwolf20-MC** [comment]
This is intended. I don't want to copy the rotation of the block you're replacing and apply it to the block you're replacing it with.  I do see the use case for it though....I'll consider having some kind of toggle (Like fuzzy mode) but for now, no promises.

**Comment by Phylogeny** [comment]
Rotations/mirroring via keybind and radial menu implemented in d1de4638d6405fccf1492de8d658feb5b60067eb

**Comment by Phylogeny** [comment]
Released in v2.6.8
