### ISSUE TITLE
Building Gadgets causing server crash with Latest Dynmap installed.

### ISSUE THREAD

**Issue by BonaireDreams** [Direwolf20-MC/BuildingGadgets#670]
### Building Gadgets version

3.10.1-build3+mc1.18

### Minecraft Version

1.18.1

### Forge Version

39.0.8

### Modpack & Version

Custom

### Do you have optifine installed?

No

### Describe the issue

Server crashes with Building Gadgets & Dynmap

### Steps to reproduce

Latest version of dynmap 3.3-beta-4 which has the most complete set of fixes for 1.18 crashes with building gadgets. 
Issue has been reported to Mike Primm author of dynmap who found it's caused by Building Gadgets mixin. He's putting a bandaid into Dynmap to ignore teh error but it will cause some inaccurate light attenuations in dynmap.

Here is the info I have from my conversation with him. Pastebin of actual crash attached as well.

> mikeprimm — 01/14/2022
That's being caused by another mods mixin - don't expect me to be able to fix that
mikeprimm — 01/14/2022
BUT I think I can wrap the offending call in a catch to just ignore the error (it's used for the lighting fix, so the blocks where the mod in question has broken block state logic - which is the root problem - will just not get accurate light attenuation when we're generating lighting vs using MCs lighting)

> OK found it with just the buildinggadgets mod (no other block additions):
> 
> [18:45:48] [Server thread/WARN]: [Dynmap] Exception while checking lighting data for block state: buildinggadgets:construction_block[ambient_occlusion=true,bright=true,neighbor_brightness=true]
> [18:45:48] [Server thread/WARN]: [Dynmap] Exception while checking lighting data for block state: buildinggadgets:construction_block[ambient_occlusion=true,bright=true,neighbor_brightness=false]
> [18:45:48] [Server thread/WARN]: [Dynmap] Exception while checking lighting data for block state: buildinggadgets:construction_block[ambient_occlusion=true,bright=false,neighbor_brightness=true]

### Expected behaviour

No crash on server startup

### Log files

https://pastebin.com/EGvw3cVh

### Information

- [X] I have provided as much information as possible

**Comment by ProjectET** [comment]
building gadgets does not use mixin

**Comment by BonaireDreams** [comment]
Perhaps its not mixin that was early on in the conversation.
 Crashlog does seem to indicate somethings not happy with building gadgets
 Description: Exception in server tick loop
 
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60815_()" because "mimic" is null
	at com.direwolf20.buildinggadgets.common.blocks.ConstructionBlock.m_7952_(ConstructionBlock.java:208) ~[buildinggadgets-3.10.1-build.3+mc1.18.jar%2350!:3.10.1-build.3+mc1.18] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60768_(BlockBehaviour.java:482) ~[server-1.18.1-20211210.034407-srg.jar%23140!:?]

**Comment by MichaelHillcox** [comment]
Odd, I'll look into it

**Comment by MajorTuvok** [comment]
Did you try removing the performance mods that are present in this instance?

**Comment by MajorTuvok** [comment]
For example: mod:fpsreducer or mod:betterfpsdist might also influence this render issue...

**Comment by BonaireDreams** [comment]
MikePrimm, author of dynmap tested it with just dynmap and BuildingGadgets, no other mods present. He has implemented a work around in dynmap to prevent the crash and its just logging the blockstate and passing it to the console as an error instead of it crashing the server. So dynmap works again. Just thought it might be good to get to the root of the issue. I'm no coder so don't fully understand all the references, but in the issue I had opened on dynmaps Github Mike stated:

> Older version [of dynmap] worked because I didn't look up lighting passthrough behavior before, because I hadn't needed to work around the fact the upgraded chunk lighting on 1.18 is completely FUBAR, and I got tired of all the complaints about broken lighting data :)

So I guess it has something to do with the fact that newer dynmap checks the lighting passthrough behavior on blocks, and something about building gadgets blockstate is not playing nicely. It does seem odd that it's catching the construction blocks which are not even left in the world after the actual blocks have been placed.

My pack currently has 107 mods with a quite a few that render blocks in the world (Immersive Engineering, Quark, Mystical Agriculture, Storage Drawers, refined Storage, RF Tools) and none of the others have the error with dynmap. 

Hope the additional info helps. As I said no longer critical since Mike applied a bandaid to dynmap to ignore the broken block state logic errors from building Gadgets.

**Comment by MichaelHillcox** [comment]
Releasing soon
