### ISSUE TITLE
Copy Paste Across Worlds Doesnt Work

### ISSUE THREAD

**Issue by joblessme1** [Direwolf20-MC/BuildingGadgets#671]
### Building Gadgets version

3.10.1

### Minecraft Version

1.18.1

### Forge Version

39.0.10

### Modpack & Version

Custom Mod Pack

### Do you have optifine installed?

Yes

### Describe the issue

Essentially, I am trying to copy a build from a creative world to a survival one. Ive copied the build and then pasted the schematics onto a doc. Then I change to my survival world and then try pasting it onto the Copy-Paste Gadget but I run into an error there where it says 'Paste Failed, MC Version (1.12.x) is not supported. Please use only templates that were build for (1.18.1) -> ()

### Steps to reproduce

1. Copy build in one world. 
2. Copy the schematic from the Copy Paste gadget to a document.
3. Exit the world and open another world.
4. Copy the schematic from the document
5. Place the Copy Paste Gadget in the Template Manager and press 'Paste'
6. The error code will pop up in the chat saying: Paste Failed, MC Version (1.12.x) is not supported. Please use only templates that were build for (1.18.1) -> ()

### Expected behaviour

Its technically supposed to paste.

### Screenshots

![2022-01-20_15 16 46](https://user-images.githubusercontent.com/70889934/150314352-7867f499-28bc-45b4-8303-327aa7941a73.png)

### Information

- [X] I have provided as much information as possible

**Comment by ProjectET** [comment]
You have only copied the material list from the copy paste gadget, though the message should probably be clearer. To get the actual schematic, you must use the Template Manager and click the copy button when you have the copy paste gadget in the second slot

**Comment by ProjectET** [comment]
for example, this is the material list acquired from using the copy paste gadget
`{
  "version": "2.1.0",
  "mc_version": "1.17.1",
  "name": "",
  "author": "Player784",
  "bounding_box": {
    "min_x": 0,
    "min_y": 0,
    "min_z": 0,
    "max_x": 5,
    "max_y": 5,
    "max_z": 6
  },
  "material_list": {
    "root_type": "buildinggadgets:entries",
    "root_entry": [
      {
        "count": 100,
        "item": {
          "item": "minecraft:dirt"
        }
      },
      {
        "count": 1,
        "item": {
          "item": "minecraft:grass"
        }
      },
      {
        "count": 42,
        "item": {
          "item": "minecraft:grass_block"
        }
      },
      {
        "count": 24,
        "item": {
          "item": "minecraft:gravel"
        }
      },
      {
        "count": 70,
        "item": {
          "item": "minecraft:stone"
        }
      }
    ]
  }
}`

And this is the schematic after copying by using the template manager
`{
  "header": {
    "version": "2.1.0",
    "mc_version": "1.17.1",
    "name": "",
    "author": "Player784",
    "bounding_box": {
      "min_x": 0,
      "min_y": 0,
      "min_z": 0,
      "max_x": 5,
      "max_y": 5,
      "max_z": 6
    },
    "material_list": {
      "root_type": "buildinggadgets:entries",
      "root_entry": [
        {
          "count": 100,
          "item": {
            "item": "minecraft:dirt"
          }
        },
        {
          "count": 1,
          "item": {
            "item": "minecraft:grass"
          }
        },
        {
          "count": 42,
          "item": {
            "item": "minecraft:grass_block"
          }
        },
        {
          "count": 24,
          "item": {
            "item": "minecraft:gravel"
          }
        },
        {
          "count": 70,
          "item": {
            "item": "minecraft:stone"
          }
        }
      ]
    }
  },
  "body": "H4sIAAAAAAAA/52WzW7TQBRGv3vnTpRmAWzY8xBIoD4E6rLtpnIbk1rkp7IdoLwz78DYc6KUXUGKfKbjb+z5TmM5K+lCsW7GZiUpr+pYSauh7btm2/1q+3JCK+VhbMZ2qfjS7Fq92XX79qFvvo6X664fp8ArV747r9z0zfd2+4q1K62u+sNT249dOyzL5P7w41n5a7MdWp0u/P6vCw/D3f328PDtH3b29nyBYTzs2/9bOt97spqeDkOU7O9pQZYWE2OmlStWOjSoma5s5GGCbuShTjknBx0alNfrRiIHHRpUqrkUlR6ch2LecqVync/zx6Z+mX6Zfpl+mX55PlhlwATdyEMxn508TNCdPNTMckjkYYIODSrVfERlgh7koJgvvTO9M5sLege9g95B76B30DvoHfSueWhQnC+9g95B76B3TJs3KOZL76B30DvoHfQOesfsKSoDpiAPDSpqxZRrzqFB5bqPPG8msalUD+Xj0KBgNvIwQYcGBYuPmncuwt8ODYrzOVUGTNChQcHio+Zhgg4NKupNckY+TNChQWX2r6oiYIIODQpmIw8TdGhQsPhx/NQ8dGhQM2c/jh/Hj+PH8eP4cfw4fhw/jh/Hj+PH8eP4cfw4fhw/jh/Hj+HH8GPc3PBj+DH8GH4MP4Yfw4/hx3iejOfJ8GP4MfwYfgw/hh/Dj+HH8GP4MfwYfgw/hh/Dj+HH8GP4MfwYfgw/hh/Dz+nhPX9pdf4nnTYjmI08TNChQRZOfsT3R/gRfoQf4Uf4EX6EH+FH+DltRfgRfoQf4Uf4ITDPTn6EH+FH+BF+hJ/yUl48ts267ZdaNMfx8dDr4mrbPLf9p88fy8n7w3G/Hkq38rK+oWYZXp+Gzc/bMlrU4U0tNw2vT8Nufzvvrbz199Nbf3rLv/hhsJz2rw/3x2677vabTbPetONwuT7uds93L34//AE4mr5TdAkAAA\u003d\u003d"
}`

**Comment by joblessme1** [comment]
I am so sorry for the trouble. Please dont tell my parents about this.

**Comment by MichaelHillcox** [comment]
Lmao
