### ISSUE TITLE
Crash when placing blocks with gadget 

### ISSUE THREAD

**Issue by StrangeThistle** [Direwolf20-MC/BuildingGadgets#672]
### Building Gadgets version

3.10.1-build.3+mc1.18

### Minecraft Version

1.18.1

### Forge Version

39.0.57

### Modpack & Version

custom

### Do you have optifine installed?

No

### Describe the issue

exception ticking world crash when placing blocks with building gadget

### Steps to reproduce

update forge to latest version, load game, get gadget, use gadget to place block, CRASH! This happens even when the 3 Gadgets mods are the only ones installed in the pack.

### Expected behaviour

expected block to be placed without crashing game

### Log files

https://pastebin.com/B0v7NbR6 (crash report)
https://pastebin.com/rSj0ZMCA (latest.log)

### Additional information

similar crash happens when placing a charging station in the world (reported)

### Information

- [X] I have provided as much information as possible

**Comment by Soaryn** [comment]
Dear Mikey, and by proxy, Dire. This bug MAY be causing building gadgets to be unusable AND may have inadvertently killed Forgecraft... woops... 

If more info is needed. See Player for details. on crashlog from server.

Please fix :D

**Comment by FuuNoKamiOka** [comment]
Came here to say the same thing that's already being said. Did a pastebin just in case. https://pastebin.com/6UdSv6p3

**Comment by aAndrew3030** [comment]
Needs updated to forge .59

**Comment by MichaelHillcox** [comment]
Fixed: releasing soon :+1:
