### ISSUE TITLE
Building gadgets failed to load properly

### ISSUE THREAD

**Issue by KaoticMando** [Direwolf20-MC/BuildingGadgets#679]
### Building Gadgets version

3.10.0

### Minecraft Version

1.18.2

### Forge Version

40.0.12

### Do you have optifine installed?

Yes

### Describe the issue

Game fails to load on start up

### Steps to reproduce

1. Start MC
2. Crashes

### Expected behaviour

I expected the game to load and I would be able to use the mod in singleplayer

### Screenshots

![2022-03-08_20 13 39](https://user-images.githubusercontent.com/86382884/157372807-5983cde3-b192-4bbd-9273-aca018a7f7d5.png)

### Log files

https://paste-bin.xyz/42232

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
It's not released yet...
