### ISSUE TITLE
9x9 Tool - Ideas

### ISSUE THREAD

**Issue by AnthonyFuller** [Direwolf20-MC/BuildingGadgets#68]
Turn it into a clone tool. With either upgradeable area with a crafting recipe or like the exhanger/building gadget with that range tool. Or intergrate a clone tool with the building gadget as it would make more sense than having a 9x9 tool on the building gadget.

Thanks for reading, Anthony.

**Comment by Direwolf20-MC** [comment]
Good idea :)
