### ISSUE TITLE
Spelling mistake - Wiki Binding page

### ISSUE THREAD

**Issue by HunterMikkelsen** [Direwolf20-MC/BuildingGadgets#683]
There is a spelling mistake in the wiki on the Binding page: https://github.com/Direwolf20-MC/BuildingGadgets/wiki/Binding

In Support section:
That's it... Sorry... Please make a PR if you want us to support your mod. We are actively working on re-adding support for AE2 and **Refinded** storage.

Change to: 
That's it... Sorry... Please make a PR if you want us to support your mod. We are actively working on re-adding support for AE2 and Refined storage.

**Comment by HunterMikkelsen** [comment]
I'm new to github issues & stuff so any assistance is appreciated <3

**Comment by MichaelHillcox** [comment]
Fixed, thanks for letting me know :+1:
