### ISSUE TITLE
[Crash 1.18.2] BGrender crash

### ISSUE THREAD

**Issue by itsdinkd** [Direwolf20-MC/BuildingGadgets#689]
### Building Gadgets version

1.0.21

### Minecraft Version

1.18.2

### Forge Version

Fabric: 0.13.3 / API 51.1

### Modpack & Version

AQM2 1.0b

### Do you have optifine installed?

No

### Describe the issue

Didnt make any movements for 20 seconds and went into inventory waited 20 seconds and crashed

### Steps to reproduce

Not sure really..
1. Rain and Lightning weather
2. Open inventory
3. Chill for a minute or two
4. crash?

### Expected behaviour

not to crash

### Log files

https://gist.github.com/itsdinkd/30035e499c974c4dde4fe46ad88e04e9

### Additional information
![image](https://user-images.githubusercontent.com/35115304/166615568-8fb34a6a-7866-4695-abf7-5d41a882c3c7.png)

**Comment by ProjectET** [comment]
wrong repo report here: https://github.com/St-ructure-Mods/BuildingGadgets-Fabric
