### ISSUE TITLE
Crash 1.19

### ISSUE THREAD

**Issue by castilio20** [Direwolf20-MC/BuildingGadgets#698]
### Building Gadgets version

3.14.0

### Minecraft Version

1.19

### Forge Version

1.19-forge-41.0.45

### Modpack & Version

no

### Do you have optifine installed?

No

### Describe the issue

crash with just the mod

### Steps to reproduce

install the mod

### Expected behaviour

work

### Log files

https://pastebin.com/qSUQv4kC - log
https://pastebin.com/pbc9CNt0 - crash

### Information

- [X] I have provided as much information as possible

**Comment by ac287846** [comment]
I am experiencing the same.
Narrowed down a collection of mods to this one causing problems.

Error: "The game crashed whilst rendering overlay"
Building Gadgets version - 3.14.0
Minecraft Version - 1.19
Forge Version - 1.19-forge-41.0.45

**Comment by MichaelHillcox** [comment]
I'll look into it :)

**Comment by Jessie6321** [comment]
Same. 

Error pop up says:
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Exit Code: -1

[crash-2022-06-24_18.05.33-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/8981709/crash-2022-06-24_18.05.33-client.txt)

**Comment by MichaelHillcox** [comment]
Should be fixed as of 3.14.1 on curseforge soon :D

**Comment by Archesr** [comment]
It loads now :D thank you.
