### ISSUE TITLE
copy past wont pull from danknull

### ISSUE THREAD

**Issue by jackyboy1992** [Direwolf20-MC/BuildingGadgets#703]
### Building Gadgets version

1.0.22

### Minecraft Version

1.18.2

### Modpack & Version

all of fabric 5 1.3.1

### Do you have optifine installed?

No

### Describe the issue

copy and past gadget wont will from danknull

### Steps to reproduce

copy a build can past while blocks are in my inventory but if they are in the danknull it wont work

### Expected behaviour

be able to past if i have the blocks in the dank null

### Information

- [X] I have provided as much information as possible

**Comment by ProjectET** [comment]
Wrong repository, report here https://github.com/St-ructure-Mods/BuildingGadgets-Fabric

**Comment by jackyboy1992** [comment]
ah ok thanks

**Comment by ProjectET** [comment]
please close the issue thank you
