### ISSUE TITLE
crashes when loading

### ISSUE THREAD

**Issue by VerserVarlin** [Direwolf20-MC/BuildingGadgets#705]
### Building Gadgets version

3.14.2 build 11

### Minecraft Version

1.19

### Forge Version

41.0.100

### Modpack & Version

na

### Do you have optifine installed?

No

### Describe the issue

i get this crash report when i launch the game

### Steps to reproduce

using curseforge i download the mod and launch the game

### Expected behaviour

the game not to crash

### Log files

https://pastebin.com/nebMhFix

### Information

- [X] I have provided as much information as possible

**Comment by ProsperCraft** [comment]
Same issue here, Forge made breaking changes.

**Comment by MichaelHillcox** [comment]
Working on an update atm

**Comment by wildkurt** [comment]
This keeps crashing. 
Windows 11
Minecraft 1.19
Forge 41.1.0

Log File: https://pastebin.com/vZYRxM3C

**Comment by MichaelHillcox** [comment]
You're running the 1.19.1 version on 1.19
