### ISSUE TITLE
MacOS / Linux support

### ISSUE THREAD

**Issue by mystery-z** [Direwolf20-MC/BuildingGadgets#710]
Any future plans?

**Comment by MichaelHillcox** [comment]
?

**Comment by mystery-z** [comment]
Sorry, my question wasn't clear...

Are there are any plans to support MacOS / Linux? Are there any existing ways to get this working on MacOS / Linux?

**Comment by ProjectET** [comment]
I dont see how this wouldnt work on mac or linux considering its in java
