### ISSUE TITLE
Unable to start a fresh copy and paste on an existing tool.

### ISSUE THREAD

**Issue by Wynnefox** [Direwolf20-MC/BuildingGadgets#714]
### Building Gadgets version

3.13.0

### Minecraft Version

1.18.2

### Forge Version

40.1.69

### Modpack & Version

Direwolf20 1.18 v1.9.1

### Do you have optifine installed?

No

### Describe the issue

Unable to start a fresh copy and paste due to chuck loading error when using a previous C&P tool. I must craft a new one

### Steps to reproduce

1. set gadget to copy mode. 
2. right click to start copy point
3. get error, "...reform a copy which would have 9210 unloaded chunks. if you want to copy nonetheless please use forceloadc..."

### Expected behaviour

A new copy and paste to begin overwriting the old one.

### Screenshots

![image](https://user-images.githubusercontent.com/115366804/194719228-a74e5f87-4b18-4a63-ad2d-211b9fa1a50e.png)

### Information

- [X] I have provided as much information as possible

**Comment by DoctorMage** [comment]
just reset the copied information inside should be a keybind to clear or sneak clicking air iirc

**Comment by Wynnefox** [comment]
> just reset the copied information inside should be a keybind to clear or sneak clicking air iirc

Holy smokes, thank you. That sneak click the air worked.
