### ISSUE TITLE
Maximum Range setting doesn't work.

### ISSUE THREAD

**Issue by RedstoneGamer123** [Direwolf20-MC/BuildingGadgets#719]
### Building Gadgets version

3.13.0

### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

 Server config has max range for gadgets set to 16, in-game tho in the setting wheel on the building gadget it resets to 15 after opening it and changing it to 16.

### Steps to reproduce

1. Change Max Range in server config.
2. Try to change gadget range to 16
3. Open again to see it say 15

### Expected behaviour

To stay 16 and work with that range

### Additional information

I am doing this in my custom modpack on a dedicated server.
I have not tested in an isolated environment nor in single player.

### Information

- [X] I have provided as much information as possible

**Comment by ThePetePandaPablo** [comment]
same issue
