### ISSUE TITLE
Blacklist tags have no affect

### ISSUE THREAD

**Issue by dannydjdk** [Direwolf20-MC/BuildingGadgets#724]
### Building Gadgets version

3.16.1-build.15

### Minecraft Version

1.19.2

### Forge Version

43.2.0

### Do you have optifine installed?

No

### Describe the issue

Adding blocks to the blacklist tags does not prevent the exchange gadget from exchanging them.

### Steps to reproduce

1. Create a data pack
2. Add a blacklist tag file under buildinggadgets/tags/blocks/blacklist/generic.json  (or exchanging.json depending on desired result).
3. Add a block to the values array in the json file.
4. Look at the block in game with F3 debugging enabled to verify that the #buildinggadgets:blacklist/generic is listed among the blocks tags.
5. Attempt to interact with the block using the exchange gadget and find that it is not restricted

### Expected behaviour

Attempting to exchange a blacklisted block should fail.

### Information

- [X] I have provided as much information as possible

**Comment by Raidobw2** [comment]
I noticed the same thing too, but in 1.18.2 instead. Doors for example are blacklisted by default in the mod but I'm able to copy paste them. This fix might need to be backported to 1.18.2 as well, if possible

![doors](https://user-images.githubusercontent.com/17010632/214739353-4290c461-8d4a-4735-9ef4-3801358a9b44.gif)
