### ISSUE TITLE
The Exchanger will exchange hidden blocks

### ISSUE THREAD

**Issue by Laventry** [Direwolf20-MC/BuildingGadgets#73]
When using the exchanger around Thaumcrafts Arcane Lamps, it will swap the hidden light sources with whatever block you are currently trying to swap in the area. I'm not sure if you are able to make it ignore specific tiles but just letting you know that it grabs them. thanks

**Comment by Drullkus** [comment]
Dire: I think there’s a way to test if the block is equivalent to air, rather than testing if Blocks.AIR

**Comment by KingLemming** [comment]
Yeah, there definitely is.

**Comment by Direwolf20-MC** [comment]
Cool thanks guys I’ll look into it!

**Comment by Direwolf20-MC** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets/commit/4058caef7e3a7ae7b6a4cfb983f26370997ec76c
This should resolve that, thanks!
