### ISSUE TITLE
CRASH when searching in JEI or Toms Storage Terminal the letter "str"

### ISSUE THREAD

**Issue by SugarDaddii** [Direwolf20-MC/BuildingGadgets#737]
### Building Gadgets version

3.16.2

### Minecraft Version

1.19.2

### Forge Version

43.2.11

### Do you have optifine installed?

No

### Describe the issue

When iam searching something with the letter S T R game will crash

### Steps to reproduce

1.Open JEI 
2. search for something like Stripped 
3. After entering the letter str the game crashed
4. only do tr without the s it will not crash

### Expected behaviour

Game dont crash

### Log files

https://pastebin.com/UiVSrJxR

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Please update to BG 3.17.0 as this should now be fixed

**Comment by MichaelHillcox** [comment]
Sorry, my mistake, that's for 1.19.3... I'm pushing a fix out for 1.19.2 now :D
