### ISSUE TITLE
(1.12.2) poof! crashes

### ISSUE THREAD

**Issue by Migmag789** [Direwolf20-MC/BuildingGadgets#74]
Hey Direwolf20 ! I love your mod. Now I use it everytime I play somewhere. But... it crash. I was playing my modpack, and the mod crashed. I was in a server, I crashed, but the server did nothing. I guess that's a client side problem... Please, fix it and thank you for your awesome mod !
Forge : 14.23.4.2757
Building Gadgets : 1.6.2
(for the modpack I'm using Beyond the skies 1.6.1)

Good job ! :D

**Comment by Tahakk** [comment]
It is nice that you report a crash, just include crashlog mate

**Comment by Migmag789** [comment]
https://paste.dimdev.org/kufefifahe.mccrash Oops sorry I forgot to add it... ;(

**Comment by Tahakk** [comment]
This looks much like #66, take a look at that please if there is solution for you

**Comment by Direwolf20-MC** [comment]
Should be fixed in 2.0 :)

**Comment by Phylogeny** [comment]
Duplicate of #55
