### ISSUE TITLE
Construction paste causing crashloop

### ISSUE THREAD

**Issue by Odgug** [Direwolf20-MC/BuildingGadgets#743]
### Building Gadgets version

3.16.2

### Minecraft Version

1.19.2

### Forge Version

43.2.14

### Modpack & Version

Create: Steam n' Rails Server modpack

### Do you have optifine installed?

No

### Describe the issue

Construction paste can still copy tile entities that are fluid based (cauldrons, create mod fluid tanks etc), putting that down seems to work fine but eventually entered the server into a crash loop

### Steps to reproduce

Use a copy paste gadget to copy a fluid tank or any other fluid related tile entity
Have construction paste in ur inventory
paste that tile entity
Wait a bit (i got no clue why it happend with delayed activation but it was 100% that block)
World enters into a crash loop

### Expected behaviour

The construction paste shouldn't copy the fluid holding block

### Log files

    Name: buildinggadgets:construction_tile // com.direwolf20.buildinggadgets.common.tileentities.ConstructionBlockTileEntity
    Block: Block{create:fluid_tank}[bottom=false,shape=plain,top=false]
    Block location: World: (-19,47,-32), Section: (at 13,15,0 in -2,2,-2; chunk contains blocks -32,-64,-32 to -17,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
    Block: Block{buildinggadgets:construction_block}[ambient_occlusion=false,bright=true,neighbor_brightness=false]
    Block location: World: (-19,47,-32), Section: (at 13,15,0 in -2,2,-2; chunk contains blocks -32,-64,-32 to -17,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Sorry for the **very** delayed response. If this is still an issue for you, please could you attach full logs. Completely understandable if you no longer have this kinda stuff
