### ISSUE TITLE
Incompatibility with Building Gadgets and Connectedness (maybe)

### ISSUE THREAD

**Issue by Carrielzada** [Direwolf20-MC/BuildingGadgets#746]
### Building Gadgets version

3.16.2 build 22

### Minecraft Version

1.19.2

### Forge Version

43.2.21

### Modpack & Version

Personal modpack - soon in curseforge

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

When in creative mode, when I click on Building Gadgets tab my game crashes

### Steps to reproduce

1. Open MC
2. Go in creative mode
3. Click on Building Gadgets tab
4. Game crashes

### Expected behaviour

I expected test items of the mod, before open my server

### Screenshots

the modpack have not enough crashes installed, he allows players to back to tittle although have to re run the pack...
and shows some info when crash happens, like in the print bellow.

![image](https://github.com/Direwolf20-MC/BuildingGadgets/assets/82341321/b2d9ac87-b118-4768-aba8-86c4def7d9e4)

### Log files

https://bytebin.lucko.me/BXx57VdDwS

### Additional information

I looked into other bigger packs like Prominence I  [FORGE] 
And that modpack have both mods, Building Gadgets and Connectedness, and it works, so I guess that's not the problem, maybe the problem is a render issue with other render mod. 

### Information

- [X] I have provided as much information as possible

**Comment by Carrielzada** [comment]
I guess its Oculus causing the crash, I try to enter a second time to fix, and every entity (including me) was invisible.
Do not rendered my hand, or the items in my hotbar.

And if I insist and try to open my inventory the game instantly crash. but now its a new error message from the not enogh crashes:

![image](https://github.com/Direwolf20-MC/BuildingGadgets/assets/82341321/53781d9c-0b82-48a9-b388-1d65d52979fe)

i will let the crashlog here, but i think the building gadgets was working fine: https://bytebin.lucko.me/LUK0Vxf0XG

**Comment by RipleyHyena** [comment]
Same issue but rendering in JEI search. There's an open PR that may fix this?

**Comment by MichaelHillcox** [comment]
This should be fixed in 3.16.3 :+1:
