### ISSUE TITLE
Building Gadget's Range Config doesn't work

### ISSUE THREAD

**Issue by NostalgicInc** [Direwolf20-MC/BuildingGadgets#748]
### Building Gadgets version

3.8.3

### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Modpack & Version

Enigmatica 6 1.8.0

### Do you have optifine installed?

No

### Describe the issue

I've been trying to change the maximum range of the building gadget devices.

### Steps to reproduce

1. Change Minecraft Client's defaultconfig for building gadgets to a range of 31.
 - This lets the client adjust the slider further.
2. Change Minecraft Server's serverconfig file for building gadgets to a range of 31.
3. Start Client and Server
4. Join Server from Client
5. Compare range of 15 to range 31 with exchanging gadget.

### Expected behaviour

The Range of the Exchanging Gadget should increase past 15 when the slider is past 15, and when the server and client allow for it.

### Screenshots

![2023-08-13_11 10 24](https://github.com/Direwolf20-MC/BuildingGadgets/assets/44733294/f5271e6d-b5cb-40ba-852e-1a3646c44081)
![2023-08-13_11 10 34](https://github.com/Direwolf20-MC/BuildingGadgets/assets/44733294/a1f9995c-56d0-4258-9856-8ed2bb06b493)
![2023-08-13_11 10 29](https://github.com/Direwolf20-MC/BuildingGadgets/assets/44733294/4f66d914-d8f9-41c0-b8c6-8d1946cd042f)
![2023-08-13_11 10 31](https://github.com/Direwolf20-MC/BuildingGadgets/assets/44733294/5fe02792-68b8-4440-bf07-ec9300e2b2c8)

### Information

- [x] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Sorry for the delayed response... And I mean... like a year later... Sorry about that.

My assumption is this is a client vs server desync. Does it actually work on the larger area if you use the gadget?
