### ISSUE TITLE
Was told I would have to send this here.

### ISSUE THREAD

**Issue by EloXShadow** [Direwolf20-MC/BuildingGadgets#751]
**Building Gadgets Version**
1.19.2
**Describe the bug**
No clue what causes this bug but every time i load into my server, I crash immediately.
**To Reproduce**
Load into the world
**Expected behavior**
I expected to load into my server and just mess around and then I crashed.
**Screenshots**
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/146122362/cf41188e-3f51-4c12-a30b-609f154995f9)
**Log Files** 
Crash logs are extremely important in helping me figure out how I DireDerped.
[crash-2023-09-26_13.08.03-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12730422/crash-2023-09-26_13.08.03-client.txt)

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by MichaelHillcox** [comment]
This should be fixed as of 3.16.3 :+1:
