### ISSUE TITLE
BuildingGadgets Data

### ISSUE THREAD

**Issue by Keiko403** [Direwolf20-MC/BuildingGadgets#758]
Firstly apologies for raising this as an issue/feature request when it isn't.

I have an idea I want to do, I'd like to combine 3 of my hobbies....minecraft, raspberry Pi/coding, 3D modelling/printing.
As a Pi can be used as a HID I want to (just for the fun and learning) recreate an actual building gadget to use as a HID when playing modded, totally unnecessary I know but I think it'll be fun. I can do everything I need to code wise, modelling wise etc but is there any files saved anywhere which stores the data such as currently selected block in the exchanging gadget or the range, fuzzy mode true/false, grid. I'm sure you get the idea. Or is it all just stored in memory, not in an actual file?

**Comment by MichaelHillcox** [comment]
Sorry, I was meant to get back to you sooner. Basically all the data from the items settings is stored in memory. Technically it lives in the player data file which in NBT but this won't be updated instantly as saving is deferred (This is a minecraft system). You could make your own companion mod which would stream the gadgets settings to a Pi via WS or something like that.

Hope this helps.
