### ISSUE TITLE
Crash with JEI 1.19.2

### ISSUE THREAD

**Issue by Enterprise12nx01** [Direwolf20-MC/BuildingGadgets#759]
**Building Gadgets Version**
buildinggadgets-3.16.2-build.22+mc1.19.2.jar

**Describe the bug**
Using JEI the log mentions building gadets, just scrolling through the pages, it crashes
"java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60815_()" because "mimic" is null
	at com.direwolf20.buildinggadgets.common.blocks.ConstructionBlock.m_7952_"

I have tried this with and without embeddium

**To Reproduce**
Steps to reproduce the behavior: Install "Industrial Age The Turning" modpack latest alpha for 1.19.2
scroll through jei

**Expected behavior**
No crash using JEI

**Screenshots**

**Log Files** 
[Crash logs are extremely important in helping me figure out how I DireDerped.]
https://pastes.io/iosprcebw7

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by MichaelHillcox** [comment]
Please update building gadgets to 3.17.0 as this hsould already be fixed
