### ISSUE TITLE
[Suggestion] The copy/paste tooltip should show the total number of blocks used.

### ISSUE THREAD

**Issue by rwtema** [Direwolf20-MC/BuildingGadgets#76]
If I'm intending to use pure construction paste, I add up each of the block counts manually to see how many are needed.

**Comment by Direwolf20-MC** [comment]
I planned on adding a paste tooltip that shows how much paste you need (basically it’d be total blocks minus missing block count). Would that work?

**Comment by Direwolf20-MC** [comment]
Resolved: https://github.com/Direwolf20-MC/BuildingGadgets/commit/9cf4bfee95511255fc70ac29ce6ab7ba656113ef
