### ISSUE TITLE
One-time use Copy Paste Gadget

### ISSUE THREAD

**Issue by AnAnonymousUsername** [Direwolf20-MC/BuildingGadgets#761]
I would love to be able to have a one-time use Copy Paste Gadget that can be pre-filled with a template, with an option to have it not require blocks in inventory to paste. After pasting, the Copy Paste Gadget should break, so it can't be used again. This would be useful for SMP shops, where you could sell pre-built structures. It would also be useful as quest rewards where you want to give a player a structure, without giving them a Copy Paste Gadget to use later. Maybe the survival crafting could require a Copy Paste Gadget and a Destruction Gadget be used together to prevent item dups.

**Comment by AnAnonymousUsername** [comment]
I see this is a duplicate of #498

**Comment by TheDeviantCrafter** [comment]
The capsules mod might be better for your use case.
