### ISSUE TITLE
Dedicated Server crash from undoing with a gadget

### ISSUE THREAD

**Issue by CrystalSpore** [Direwolf20-MC/BuildingGadgets#762]
### Building Gadgets version

3.16.2-build.22+mc1.19.2

### Minecraft Version

1.19.2

### Forge Version

43.2.14

### Modpack & Version

Enigmatica 9 - 1.18 (+ extra mods)

### Do you have optifine installed?

No

### Describe the issue

When undoing with a gadget quickly after placing a block, causes the server to crash

### Steps to reproduce

1. place block(s) with gadget
2. before block place animation finishes, undo
3. server crashes

### Expected behaviour

Not have the server crash

### Log files

Crash report:
https://pastebin.com/B47fjpyz

Log file:
https://pastebin.com/9J8vub2H

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
This looks like a very strange edge-case. Are you able to replicate this?

(Also, sorry for the very slow reply)

**Comment by CrystalENVT** [comment]
Sorry for my long delayed reply. We've had this happen a couple of times, but I'll try to recreate the situation again soon.
