### ISSUE TITLE
Exchanger trying to copy block state.

### ISSUE THREAD

**Issue by og-wilbury** [Direwolf20-MC/BuildingGadgets#77]
Copied redstone lamp, exchanger seem to be trying to look for a "on" lamp in my inventory.

Redstone torches will place in an "off" state if that's what's been copied (though no "off" torch is in inventory).

**Comment by Direwolf20-MC** [comment]
This should fix that specific case, and maybe a few others. The conversion of Blockstate->block->Item is a really tricky one in minecraft. In this example, Lit and UnLit lamps are not the same block with different blockstates, but two totally different blocks all together (Same with torches).  

https://github.com/Direwolf20-MC/BuildingGadgets/commit/9a5257eefa12cf06625aff3ff6c66c486283aa87
