### ISSUE TITLE
Server Config File not created or found

### ISSUE THREAD

**Issue by Shadder-1-5** [Direwolf20-MC/BuildingGadgets#770]
### Building Gadgets version

3.84

### Minecraft Version

1.16.5

### Forge Version

36.2..34

### Modpack & Version

Pixelmon modified

### Do you have optifine installed?

I have other rendering based mods installed

### Describe the issue

Cannot find building gadgets config file on server

### Steps to reproduce

1. Install Building Gadget mod on server
2. Install Building Gadget mod on Client
3. Use Gadgets successfully, useable on multiplayer forge server
4. Attempt to change server config to make gadgets use 0 rf
5. Cant find building gadget config in server files, Config either never generated or hidden. Although the items still work, just cant find config

### Expected behaviour

Find config, change config settings

### Screenshots

![image](https://github.com/user-attachments/assets/e56d8bea-2da2-472b-852c-82d9292bbbb9)

### Additional information

Have removed and reinstalled the mod, no config file generated

Rubidium 

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
We no longer support 1.16. 

For your issue specifically, make sure you check the world/serverconfigs/Config file
