### ISSUE TITLE
invalied JSON failed copy/paste

### ISSUE THREAD

**Issue by thv000** [Direwolf20-MC/BuildingGadgets#773]
### Building Gadgets version

2,8,4

### Minecraft Version

1.12.2

### Forge Version

14.23.5.2858

### Modpack & Version

Dungeons Dragons and Space Shuttles-8.0_R1

### Do you have optifine installed?

No

### Describe the issue

There could be some in modpack by default im not aware of

### Steps to reproduce

1. Open Mc
2. get gadget 
3. copy code from web
4. paste code in the template 
5. get error

### Expected behaviour

I expected everything to run smoothly

### Additional information

The code is from a build called "1.12 Steampunk Fantancy Manor" . Creator: Howester84. Website: Airtable

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
1.12 is no longer supported
