### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by lonevox** [Direwolf20-MC/BuildingGadgets#774]
Could this be uploaded to Modrinth? It is one of the only mods in my pack that isn't on Modrinth so an upload there would be awesome! If a Modrinth release isn't planned, is it okay to distribute your jars in my pack?

**Comment by MichaelHillcox** [comment]
We don't have plans to release this mod on Modrinth. You're more than welcome to redistribute the mod as part of your pack as our mod is licenced under MIT and thus automatically provides redistribution permission
