### ISSUE TITLE
Crash when trying to use exchanging gadget with AE2s Vibrant Quartz Glass.

### ISSUE THREAD

**Issue by NJM1564** [Direwolf20-MC/BuildingGadgets#78]
[crash-2018-09-04_22.17.22-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/2350991/crash-2018-09-04_22.17.22-client.txt)

Logging back in I get an instant crash and this log.

[crash-2018-09-04_22.43.25-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/2351028/crash-2018-09-04_22.43.25-client.txt)

Edit: looks like the issue might be with thaumcraft's infusion crafting checking items around it for adjusting instability and the glass. Will redirect but report.

**Comment by Direwolf20-MC** [comment]
Looks like you think its a thaumcraft issue? If so I'll close for now, but feel free to reopen (With more info, like mod version, and exactly what you did to cause it) if it turns out its on my end :)
