### ISSUE TITLE
TileEntity support

### ISSUE THREAD

**Issue by loordgek** [Direwolf20-MC/BuildingGadgets#79]
hi am atm watching https://youtu.be/RJgTpn961uY (love it)
and you are talking about support for TileEntitys (chisel and bits)
maybe this helps https://github.com/BuildCraft/BuildCraftAPI/tree/8.0.x/api/buildcraft/api/schematics

https://discord.gg/v4geqgA buildcraft discord link maybe they can help you 

offtopic https://minecraft.curseforge.com/projects/edx-multipart pipe and torch in 1 place

**Comment by Direwolf20-MC** [comment]
Its too complex at this time, but I'll consider it in the future as a whitelist only :)

**Comment by Phylogeny** [comment]
Would you consider special-casing Chisels & Bits blocks? Algo's API makes it effortless to get an IBitAccess from an in-world block, and use it to create an item stack. As well as the other way around. Rotating them is easy too. As long as you could handle storing an item  stack (or an IBitAccess directly), it would work fine.

**Comment by MajorTuvok** [comment]
As my Forge PR (https://github.com/MinecraftForge/MinecraftForge/pull/5167) is going to add Tagging to Forge Registries, I added an TileEntityType tag called allow_copy, which allows modders to specify TileEntities which my be copied by copy tools...
Should I open an reminder Issue?
