### ISSUE TITLE
Terrain clearing mechanic

### ISSUE THREAD

**Issue by MajorTuvok** [Direwolf20-MC/BuildingGadgets#81]
As by Forgecraft2 S12E28 (about 23:20) you said that you wanted to add an terrain clearing mechanic...
Cause I think that would be reeeeaaally useful I just wanted to post a reminder here ;)

I have an propably not so smart idea for an clearing heuristic:
If the block has an ore Dictionary entry, void it and drop it otherwise - dirt and stone aren't oredictionaried, are they? (can't look it up at the moment...)
(I guess there are some obvious flaws I'm missing in this balancing thing again... Sry)

**Comment by Phylogeny** [comment]
Sadly, things like dirt, grass, sand, etc, are in the ore dictionary.

**Comment by Direwolf20-MC** [comment]
The mechanic would likely void everything except tile entities of course. It’s on my todo list :)
