### ISSUE TITLE
[Feature Request] Copy & Paste Tool Templates

### ISSUE THREAD

**Issue by robert-r** [Direwolf20-MC/BuildingGadgets#84]
This mod is quickly becoming one of my favourites! I really like the new copy & paste tool, and had an idea for making it more versatile: introducing writable template cards. Now this might make things a bit more complicated, but I think the idea is worth exploring.

Basically you would craft a bunch of empty templates, and "write" your structures to them using the copy & paste tool in copy mode. Perhaps to make things easier you can also add a name to a written template? You can then insert a written template into the tool and paste copies of it. This mechanism would allow you to make snapshots of common building features and swap between them rapidly as needed without referencing the source each time.

What do you think? Will something like this be feasible?

**Comment by Direwolf20-MC** [comment]
Today is your lucky day :). 
https://imgur.com/a/tX5adJ1

I have more work to do, but yes, coming soon!

**Comment by robert-r** [comment]
Nice! :) 👍
