### ISSUE TITLE
Building Mode: Same Material

### ISSUE THREAD

**Issue by pneumaticLance** [Direwolf20-MC/BuildingGadgets#87]
Can we have a mode for the building gadgets that behave similarly to Chisel and Bits's 'Same Material' placing style? In a sense, kinda like Builder's Wand, but instead of being forced to place the exact same material(e.g. cobble on cobble) as the target, the building gadget places the block that you have shift-right-clicked before instead(e.g. wood on cobble).

**Comment by Direwolf20-MC** [comment]
I’d rather not add that feature. You can just shift click the block you’re building off can’t you?

**Comment by Phylogeny** [comment]
The C&B 'Same Martial' mode he's referring to only effects the bit type(s) you interacted with. In your case, that would mean that the exchanger only replaces blocks of the same type as the one you click on with the one the exchanger is set to. It's very useful.

**Comment by Phylogeny** [comment]
Right now the exchanger only replaces as per C&B's 'same material' mode, and the builder doesn't place as per it. It would be nice if both gadgets had both modes: 'replace same blocks in area' and 'replace all blocks in area' for the exchanger; and 'place on same blocks' for the builder.

The builder's 'place on same blocks' could check all blocks in the plane of the face clicked, and only add blocks if the position offset in the opposite direction to the face clicked contains the same block as the one clicked.

**Comment by Direwolf20-MC** [comment]
Hrm I see what you're asking for. I'll consider this addition, not 100% sure either way if I want to add it just yet :).

**Comment by hnOsmium0001** [comment]
@Direwolf20-MC 
If I would make a PR, do you prefer a separate gadget or a mode of the existing building gadget?

**Comment by pneumaticLance** [comment]
A mode of the existing building gadget would be lovely. It will help reduce the clutter on hotbar.

**Comment by Phylogeny** [comment]
I'm having a go at implementing this.

**Comment by hnOsmium0001** [comment]
@Phylogeny Sorry didn't see that

**Comment by Phylogeny** [comment]
Released in v2.6.2
