### ISSUE TITLE
Crash loop - crafted Building Gadget from RS system and tried to place it on hotbar

### ISSUE THREAD

**Issue by jlbrewer** [Direwolf20-MC/BuildingGadgets#89]
[crash-2018-09-16_20.53.57-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets/files/2387181/crash-2018-09-16_20.53.57-client.txt)

Playing on a multiplayer server with DW Pack 2.3.0

Made the building gadget in an RS crafting grid. Crash occurred when I tried to click the gadget into my hotbar. Crashed again with the same error immediately upon trying to log in again. Have to wait for the admin to come on and roll my player data back from backups.

**Comment by Direwolf20-MC** [comment]
This should be fixed in 2.0. I’ll get the pack updated ASAP
