### ISSUE TITLE
[Request/Bug?] Having FE off and durability set to 0 should make the gadgets free to operate.

### ISSUE THREAD

**Issue by Birgliss** [Direwolf20-MC/BuildingGadgets#90]
I add "Bug?" because I assume that was the intent of letting 0 being in the valid range, but currently, when those are the settings, the gadgets do nothing.
Forge version: most recent as of 9/22/18, version 2760
Modlist (though issue persists without):
![image](https://user-images.githubusercontent.com/20749209/45914086-e0319c00-be0d-11e8-897a-7fa8606f267c.png)
Configs: 
![image](https://user-images.githubusercontent.com/20749209/45914153-ed9b5600-be0e-11e8-874d-1aae4dd3e963.png)

shown behavior: 
https://gfycat.com/KaleidoscopicScalyCutworm

**Comment by Phylogeny** [comment]
Pull request #82 implements this. Dire just hasn't implemented it himself yet.

**Comment by Birgliss** [comment]
maybe a github issue will get it implemented faster? ehe :p 

thank you, though.

**Comment by Direwolf20-MC** [comment]
I’ll add it! :). P.s I’ll implement some of those pull requests when I can.

**Comment by Direwolf20-MC** [comment]
https://github.com/Direwolf20-MC/BuildingGadgets/commit/e8b387847cd3007b81a11abc4c79ebd25d43cb0d

Added :)
