### ISSUE TITLE
i am working on TileEntity support

### ISSUE THREAD

**Issue by loordgek** [Direwolf20-MC/BuildingGadgets#91]
the only tile i support atm is the flowerpot, 
i dont have a undo state and does not render

https://github.com/loordgek/BuildingGadgets/commit/a71d361da4c7c872836969a0f0e5bbe7333ad842

forgot to add the files to the commit oops
https://github.com/loordgek/BuildingGadgets/commit/aafe2fefa1406854a48d863085f208a322564eac

if you want to play w/ it
[BuildingGadgets-2.2.1.jar.zip](https://github.com/Direwolf20-MC/BuildingGadgets/files/2412364/BuildingGadgets-2.2.1.jar.zip)

**Comment by loordgek** [comment]
hope you like it

**Comment by loordgek** [comment]
yes you need a separate class for each TileEntity but hat is not a problem because the only TileEntitys that should be supported are the tile from Chisel and bits and other fancy TileEntitys like https://minecraft.curseforge.com/projects/architecturecraft-elytradev

**Comment by Direwolf20-MC** [comment]
Thanks I appreciate that but I'd rather not implement tile entities in such a way that a separate class is needed for each tile entity we want to support.

**Comment by loordgek** [comment]
why dont you want separate class for each tile entity ??

**Comment by HellFirePvP** [comment]
Cause it's a huge amount of work to implement correctly in the first place AND a massive amount of work to maintain and update as other mods get new updates.
