### ISSUE TITLE
[Feature Request] Direct to Cloud Link Paste 

### ISSUE THREAD

**Issue by sonolumin** [Direwolf20-MC/BuildingGadgets#92]
[Feature Request]

**Goal**
_To facilitate an easier user experience for sharing structures via the copy/paste tool._ 

**Feature**
Add support for the copy/paste tool to send json text directly to a free cloud hosted text repository. Then allow users to copy and past the links as well as the raw json. 
Possible hosts– [https://gist.github.com/](https://gist.github.com/) or [https://pastebin.com/](https://pastebin.com/)

**Comment by UnRealDinnerbone** [comment]
I think it would allow for easier sharing instead of having to copy the while long json, that would just have to copy a same url

**Comment by Direwolf20-MC** [comment]
That’s true but suddenly the mod requires an internet connection to function fully. :/

**Comment by MajorTuvok** [comment]
Not necessarily Dire, you don't need to connect to said Services in Singleplayer.
If the Socket creation fails, then the user just can't do it...

Still I agree that this would be way too much effort for too little gain - where's the Problem with copy/pasting to one's own Provider of choice: just open a new browser window and you're ready to go...

**Comment by Direwolf20-MC** [comment]
Agreed. Gonna close :)
