### ISSUE TITLE
Feature Request: Clearing Gadget

### ISSUE THREAD

**Issue by delta2k** [Direwolf20-MC/BuildingGadgets#97]
i used to use meecreeps for clearing area's. but i would love the see a gadget thats able to clear areas and make them flat. with options to drop the blocks/items and silk touch option. but also use ftb claim land protection. so u can't clear other people land. would be a cool gadget

**Comment by Direwolf20-MC** [comment]
If I implement this (I’ve considered it) it would void the drops from an area. I wouldn’t want it used for mining.

**Comment by Direwolf20-MC** [comment]
Void area tool implemented :)
