### ISSUE TITLE
Suggestion: "Partial" Mode for Copy/Paste

### ISSUE THREAD

**Issue by LazerusKI** [Direwolf20-MC/BuildingGadgets#98]
Havnt seen (or even missed) that in your spotlight, so if it is already a thing, just ignore this.

So, assuming it is impossible to paste a structure because you cant have all the blocks at once, lets say due to inventory space.
Would it be possible to add a mode that pastes everything that you currently have, so you can paste the structure piece by piece?

**Comment by Direwolf20-MC** [comment]
Yes it already does this :). It’ll place whatever it can.
